### ISSUE TITLE
[HW] Pradnya Pethe

### ISSUE THREAD

**Issue by pethepradnya** [datastaxdevs/workshop-introduction-to-nosql#10]
Name: Pradnya Pethe
Email: pethe.pradnya@gmail.com
Linkedin Profile: https://www.linkedin.com/in/pradnya-pethe-9382b514/

[](url)
![Capture1](https://user-images.githubusercontent.com/52218526/117191470-99222a80-adae-11eb-94a9-81a156501f54.PNG)

**Comment by pethepradnya** [comment]
![image](https://user-images.githubusercontent.com/52218526/117201263-75fd7800-adba-11eb-99ad-0f9e73e85f5b.png)

![image](https://user-images.githubusercontent.com/52218526/117201631-dbe9ff80-adba-11eb-920e-2e8741c5abb2.png)

![image](https://user-images.githubusercontent.com/52218526/117201801-118ee880-adbb-11eb-95b9-fa62bc90e4d8.png)
![image](https://user-images.githubusercontent.com/52218526/117201997-4f8c0c80-adbb-11eb-8c47-f52e312a8b69.png)

![image](https://user-images.githubusercontent.com/52218526/117202138-79453380-adbb-11eb-967c-fd7b99a281b2.png)

**Comment by pethepradnya** [comment]
![image](https://user-images.githubusercontent.com/52218526/117208442-21122f80-adc3-11eb-9477-9e31ed85c909.png)
![image](https://user-images.githubusercontent.com/52218526/117208872-a1d12b80-adc3-11eb-9e05-eb91d4327052.png)

**Comment by SonicDMG** [comment]
Hi there Pradnya. Thank you for your submission. Please provide a screenshot of your completed "try-it-out" scenario as per homework step 2.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

**Comment by HadesArchitect** [comment]
Ping Pradnya! Please complete the homework as David explained in his comment: at the moment you are missing a screenshot

**Comment by pethepradnya** [comment]
Hi, I will follow the link : https://www.datastax.com/try-it-out 
and submit the screenshot soon. Sorry for replying late.

**Comment by pethepradnya** [comment]
![try-it-out-screenshot-1](https://user-images.githubusercontent.com/52218526/118529708-d1602c00-b711-11eb-96ea-fb97d7444796.PNG)
![try-it-out-screenshot-2](https://user-images.githubusercontent.com/52218526/118529710-d1f8c280-b711-11eb-86b4-9002cc3d206e.JPG)
![try-it-out-screenshot-3](https://user-images.githubusercontent.com/52218526/118529711-d2915900-b711-11eb-828f-4030edbc061d.JPG)
![try-it-out-screenshot-4](https://user-images.githubusercontent.com/52218526/118529713-d2915900-b711-11eb-9e73-36e2753e737a.JPG)
![try-it-out-screenshot-5](https://user-images.githubusercontent.com/52218526/118529715-d2915900-b711-11eb-8784-e89722a162bc.JPG)
![try-it-out-screenshot-6](https://user-images.githubusercontent.com/52218526/118529718-d2915900-b711-11eb-9379-7ab6aceb8695.JPG)
![try-it-out-screenshot-7](https://user-images.githubusercontent.com/52218526/118529720-d329ef80-b711-11eb-9c04-00a40aff45f0.JPG)
![try-it-out-screenshot-8](https://user-images.githubusercontent.com/52218526/118529722-d329ef80-b711-11eb-924c-e14483f47965.JPG)

**Comment by HadesArchitect** [comment]
Great job! Issuing the badge!

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/-MFQYS2fST-CE-SnDsizHw?identity__email=pethe.pradnya%40gmail.com
