### ISSUE TITLE
[HW] <workshop-introduction-to-nosql>

### ISSUE THREAD

**Issue by Nikhil5480** [datastaxdevs/workshop-introduction-to-nosql#100]
**Name:** <Nikhil kamani>
**Email:** <nikhilsai690@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/nikhil-kamani-a285b715a/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Screenshot 2021-06-03 035541](https://user-images.githubusercontent.com/53121431/120559990-a23eff80-c41f-11eb-904d-d5a7f363f83b.png)

![Screenshot 2021-06-03 025551](https://user-images.githubusercontent.com/53121431/120603202-62046f00-c469-11eb-8aae-cf29c639017d.png)

![Screenshot 2021-06-03 021343](https://user-images.githubusercontent.com/53121431/120603187-5f097e80-c469-11eb-9339-dc606148516c.png)

-- images removed by team --

**Comment by SonicDMG** [comment]
Everything looks good Nikhil, thank you. Here's your badge -> https://api.badgr.io/public/assertions/CIMyhm8NSLOzW0dXvD3A2w?identity__email=nikhilsai690%40gmail.com. I also went and removed some images that included your Astra key. I highly suggest to delete the token from the AstraUI to be safe.

**Comment by Nikhil5480** [comment]
Thank you datastaxdevs.
Yes, I'll make it sure.
