### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by teethulcer** [datastaxdevs/workshop-introduction-to-nosql#101]
**Name:** <José Diogo Moura>
**Email:** <snuff0990@gmail.com>
**Linkedin Profile:** <LINK>

-----------------------------------------
![nosql1](https://user-images.githubusercontent.com/85260751/120560013-ef0fdf80-c3f9-11eb-9a1f-5246418fd5ea.png)
![nosql1-2](https://user-images.githubusercontent.com/85260751/120560017-efa87600-c3f9-11eb-99bb-fca0434ba1ae.png)
![nosql1-3](https://user-images.githubusercontent.com/85260751/120560019-efa87600-c3f9-11eb-9a2c-f74a69352385.png)

**Comment by SonicDMG** [comment]
Looks great José, thank you. Here's your badge -> https://api.badgr.io/public/assertions/Ckd6Xzh-Syav8Raxg3piFw?identity__email=snuff0990%40gmail.com
