### ISSUE TITLE
Try It Out: Cassandra Query Language (CQL)

### ISSUE THREAD

**Issue by vigneshj6** [datastaxdevs/workshop-introduction-to-nosql#103]
**Name:** Vigneshwaran Jothi
**Email:** vigneshj6@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/vigneshwaran-jothi/

Attach the homework screenshots below:
----------------------------------------

![image](https://user-images.githubusercontent.com/14002798/120577500-0a9ed880-c442-11eb-98b9-92eb35abe9a3.png)

**Comment by SonicDMG** [comment]
Hi there Vigneshwaran. Thank you for your submission. I see step 2, but not step 1 from the homework. Please provide a screenshot from either completion of step IV or V.
1. Complete the practice steps of this workshop as explained below, steps I-IV are mandatory, step V is optional. Take screenshots of the last completed step from either step IV or V. NOTE: When taking screenshots ensure NOT to copy your Astra key!

**Comment by HadesArchitect** [comment]
Hey **Vigneshwaran Jothi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/_BYsnh8yQ92koJwS0qNWXw
