### ISSUE TITLE
[HW] No Sql assignment

### ISSUE THREAD

**Issue by Ange12007** [datastaxdevs/workshop-introduction-to-nosql#104]
**Name:** Angel Aloysius
**Email:** angelaloysius123@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/angelaloysius/

Attach the homework screenshots below:
-----------------------------------------

Try Out Scenario
![image](https://user-images.githubusercontent.com/68355107/120592664-7742b480-c3fb-11eb-9ad7-964ca63ed648.png)

Step II
![image](https://user-images.githubusercontent.com/68355107/120589521-35633f80-c3f6-11eb-8529-0b4733492629.png)

Step III
![image](https://user-images.githubusercontent.com/68355107/120591160-ed91e780-c3f8-11eb-9af2-4f3080134f07.png)

Step IV
![image](https://user-images.githubusercontent.com/68355107/120592151-9a209900-c3fa-11eb-9eca-72f79e9fb072.png)

**Comment by Ange12007** [comment]
Done

**Comment by SonicDMG** [comment]
Nice job Angel, thank you. Here's your badge -> https://api.badgr.io/public/assertions/Hxysq61hScqEx7ViIZIMWw?identity__email=angelaloysius123%40gmail.com
