### ISSUE TITLE
[HW] Introduction to nosql

### ISSUE THREAD

**Issue by VinodKumarKP** [datastaxdevs/workshop-introduction-to-nosql#105]
**Name:** Vinod Kumar KP
**Email:** vinodkumar.kp.1985@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/vinod-kumar-k-p/

Attach the homework screenshots below:
-----------------------------------------

Step 2:
![image](https://user-images.githubusercontent.com/31899217/120589558-457b1f00-c3f6-11eb-9ac3-49003d83d2df.png)

Step 3:
![image](https://user-images.githubusercontent.com/31899217/120591052-bcb1b280-c3f8-11eb-8a18-d83dfbeba1bc.png)

Step 4:
![image](https://user-images.githubusercontent.com/31899217/120591796-ffc05580-c3f9-11eb-92a5-9cda309064dd.png)

TryOut:
![image](https://user-images.githubusercontent.com/31899217/120592362-fa173f80-c3fa-11eb-95d3-9e3fdbd588cd.png)

**Comment by VinodKumarKP** [comment]
Completed

**Comment by SonicDMG** [comment]
Looks good Vinod, thank you. Here's your badge -> https://api.badgr.io/public/assertions/RVyZdRI7TW-Hdk4tkthO6g?identity__email=vinodkumar.kp.1985%40gmail.com
