### ISSUE TITLE
Introduction to NoSQL Alejandro Lazaro

### ISSUE THREAD

**Issue by alazarog7** [datastaxdevs/workshop-introduction-to-nosql#106]
**Name:** Alejandro Lazaro Gutierrez
**Email:** a.lazaro.g7@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------
1.
![image](https://user-images.githubusercontent.com/14830175/120579558-ba018e00-c3f5-11eb-8c7f-294ef97717de.png)

![image](https://user-images.githubusercontent.com/14830175/120579845-2e3c3180-c3f6-11eb-84fb-ab8704440309.png)
2.
2a
![image](https://user-images.githubusercontent.com/14830175/120579998-63e11a80-c3f6-11eb-9e4f-5cf8cb0edf0a.png)
2b
![image](https://user-images.githubusercontent.com/14830175/120580150-a86cb600-c3f6-11eb-9536-08f3d96ff187.png)
2c
![image](https://user-images.githubusercontent.com/14830175/120580291-ed90e800-c3f6-11eb-871f-dca2a055fd0b.png)
2d
![image](https://user-images.githubusercontent.com/14830175/120580471-42ccf980-c3f7-11eb-893a-ce2359221172.png)
![image](https://user-images.githubusercontent.com/14830175/120580515-524c4280-c3f7-11eb-995d-c1edbee67bc1.png)
![image](https://user-images.githubusercontent.com/14830175/120580563-67c16c80-c3f7-11eb-9699-a03b622c6732.png)
![image](https://user-images.githubusercontent.com/14830175/120580612-7b6cd300-c3f7-11eb-82f7-fbaf55b5e120.png)
3
3a
![image](https://user-images.githubusercontent.com/14830175/120582097-e919fe80-c3f9-11eb-9d8e-088ea7bfd383.png)
3b
![image](https://user-images.githubusercontent.com/14830175/120588850-e6250b00-c405-11eb-9fb0-29c21ea2213f.png)
3c
![image](https://user-images.githubusercontent.com/14830175/120589153-69466100-c406-11eb-8f51-82849bc1fbb6.png)
3d
![image](https://user-images.githubusercontent.com/14830175/120589310-a6125800-c406-11eb-92cb-7bf0d2f05f6f.png)
3e
![image](https://user-images.githubusercontent.com/14830175/120589481-e8d43000-c406-11eb-9151-f819a0527488.png)
3f
![image](https://user-images.githubusercontent.com/14830175/120589657-2f298f00-c407-11eb-9f6a-1c30761cb776.png)
3g
![image](https://user-images.githubusercontent.com/14830175/120589915-a52df600-c407-11eb-86a5-0f28ad86df85.png)
4
4b
![image](https://user-images.githubusercontent.com/14830175/120590159-140b4f00-c408-11eb-932e-964b832c68c4.png)
![image](https://user-images.githubusercontent.com/14830175/120590218-31d8b400-c408-11eb-85fe-dc7856715232.png)
4c
![image](https://user-images.githubusercontent.com/14830175/120590363-68163380-c408-11eb-890b-3f07e99db28f.png)
![image](https://user-images.githubusercontent.com/14830175/120590412-795f4000-c408-11eb-8c64-b6358a8e773c.png)
![image](https://user-images.githubusercontent.com/14830175/120590529-a90e4800-c408-11eb-9e08-d5cf058f6f09.png)

![image](https://user-images.githubusercontent.com/14830175/120591310-f0e19f00-c409-11eb-8ddc-d6189e2d9a87.png)

**Comment by SonicDMG** [comment]
Very well documented Alejandro, thank you. Here's your badge -> https://api.badgr.io/public/assertions/Iai_fL_GS06OEgYHsR0tdQ?identity__email=a.lazaro.g7%40gmail.com
