### ISSUE TITLE
[HW] Amandeep Singh Ahuja

### ISSUE THREAD

**Issue by AmanAhuja5616** [datastaxdevs/workshop-introduction-to-nosql#108]
**Name:** Amandeep Singh Ahuja
**Email:** aman.ahuja5616@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/amandeep-singh-ahuja-00627249/

Attach the homework screenshots below:
-----------------------------------------

![DatastaxAstra_ScenarioComplete](https://user-images.githubusercontent.com/85133735/120601621-cfaf9b80-c467-11eb-8b00-bfc83a7b7591.PNG)
![DatastaxAstra_4](https://user-images.githubusercontent.com/85133735/120601626-d1795f00-c467-11eb-9269-5af1a86cfd60.PNG)

**Comment by SonicDMG** [comment]
Looks great Amandeep, thank you. Here's your badge -> https://api.badgr.io/public/assertions/vjozPvCrTgaF9x-iFBdOBg?identity__email=aman.ahuja5616%40gmail.com
