### ISSUE TITLE
[HW] <Shiva Farkade>

### ISSUE THREAD

**Issue by shivafarkade1889** [datastaxdevs/workshop-introduction-to-nosql#11]
**Name:** <Shiva Farkade>
**Email:** <shivafarkade@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/shiva-farkade/>

Attach the homework screenshots below:
-----------------------------------------

<
-- images removed by team --

**Comment by shivafarkade1889** [comment]
Adding the Home Work 5

**Comment by shivafarkade1889** [comment]
![image](https://user-images.githubusercontent.com/68903482/118023332-10415b00-b37b-11eb-95ec-f4e35f0305fb.png)
![image](https://user-images.githubusercontent.com/68903482/118023372-1afbf000-b37b-11eb-8794-15e4c1f2a44e.png)
![image](https://user-images.githubusercontent.com/68903482/118023403-22bb9480-b37b-11eb-9c21-41d69c540b14.png)

**Comment by SonicDMG** [comment]
Looks good, thank you Shiva.

**Comment by shivafarkade1889** [comment]
Not received the Badge yet

**Comment by SonicDMG** [comment]
Badges will be issued tomorrow. Please note this is not an automated process. We have to grade all of these and then process  the badges in a batch so it can take a couple days to get them out.

**Comment by shivafarkade1889** [comment]
Thanks David. Sorry for hurry.

**Comment by SonicDMG** [comment]
No worries at all. We totally understand wanting to get credit for your work.

**Comment by HadesArchitect** [comment]
Here we go: https://api.badgr.io/public/assertions/xan95IVrRjCd_02iqD2sGg?identity__email=shivafarkade%40gmail.com

**Comment by shivafarkade1889** [comment]
Thanks Aleks
