### ISSUE TITLE
[HW] Venkata Mani Kumar

### ISSUE THREAD

**Issue by venkatamanikumar** [datastaxdevs/workshop-introduction-to-nosql#110]
**Name:** Venkata Mani Kumar
**Email:** mvmk.venkat@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/venkatamanikumar/

Attach the homework screenshots below:
-----------------------------------------

![Step4](https://user-images.githubusercontent.com/83075550/120618446-b82cde80-c478-11eb-87e7-0bd5ffaba024.PNG)
![Completed Scenario](https://user-images.githubusercontent.com/83075550/120618477-bd8a2900-c478-11eb-9659-5819e98c9d63.JPG)

**Comment by SonicDMG** [comment]
Awesome Venkata, looks good, thank you. Here's your badge -> https://api.badgr.io/public/assertions/zqrrzJS9TNa2Xa6I4xk2Zg?identity__email=mvmk.venkat%40gmail.com
