### ISSUE TITLE
[HW] Matyas Meszaros

### ISSUE THREAD

**Issue by mathi931** [datastaxdevs/workshop-introduction-to-nosql#111]
**Name:**  Matyas Meszaros
**Email:**  mesi.mathi@gmail.com
**Linkedin Profile:**  https://www.linkedin.com/in/meszi93/

Attach the homework screenshots below:
-----------------------------------------

![stepIV](https://user-images.githubusercontent.com/51709088/120621668-60817980-c45e-11eb-9a68-2e6bb17b6cb8.png)
![scenario](https://user-images.githubusercontent.com/51709088/120621677-624b3d00-c45e-11eb-9aba-b3baba6caa65.png)

**Comment by SonicDMG** [comment]
Looks great Matyas, thank you. Here's your badge -> https://api.badgr.io/public/assertions/IW2GlyZzSKCWjFAdjGCgoA?identity__email=mesi.mathi%40gmail.com

**Comment by mathi931** [comment]
amazing thanks a lot, it was pretty nice guys, I learned a lot of new stuff
