### ISSUE TITLE
[HW] <Carlos Wilker>

### ISSUE THREAD

**Issue by CarlosWilk** [datastaxdevs/workshop-introduction-to-nosql#112]
**Name:** <Carlos Wilker R. da Silva Paulino>
**Email:** <carloswilkersp@hotmail.com>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------
![chrome_2021-06-03_10-21-05](https://user-images.githubusercontent.com/85285378/120623049-44c6a500-c457-11eb-9614-0e11573a3130.png)
![2021-06-03_10-16-06](https://user-images.githubusercontent.com/85285378/120623090-4d1ee000-c457-11eb-8b68-11971c91a235.png)
![2021-06-03_10-20-18](https://user-images.githubusercontent.com/85285378/120623096-4e500d00-c457-11eb-8eb7-93bd4954ac74.png)
![chrome_2021-06-03_10-16-49](https://user-images.githubusercontent.com/85285378/120623099-4e500d00-c457-11eb-9d23-545be8fb9c15.png)
![chrome_2021-06-03_10-18-22](https://user-images.githubusercontent.com/85285378/120623100-4ee8a380-c457-11eb-8c24-4384f097e676.png)
![chrome_2021-06-03_10-18-54](https://user-images.githubusercontent.com/85285378/120623101-4ee8a380-c457-11eb-8dd0-1f84cf5c0d16.png)
![chrome_2021-06-03_10-20-48](https://user-images.githubusercontent.com/85285378/120623102-4f813a00-c457-11eb-8937-e4ce55565071.png)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Hi Carlos, thank you for your submission. I see the try-it-out scenario, but not a screen from the either the end of steps IV or V from the github readme. Note step 1 from the homework section.
1. Complete the practice steps of this workshop as explained below, steps I-IV are mandatory, step V is optional. Take screenshots of the last completed step from either step IV or V. NOTE: When taking screenshots ensure NOT to copy your Astra key!
https://github.com/datastaxdevs/workshop-introduction-to-nosql#partitipation-certificate--homework

**Comment by CarlosWilk** [comment]
Sorry, I forgot it.

![chrome_2021-06-04_10-56-16](https://user-images.githubusercontent.com/85285378/120785097-b4569600-c524-11eb-9442-2175cb5e6e3c.png)
![chrome_2021-06-04_10-57-06](https://user-images.githubusercontent.com/85285378/120785104-b587c300-c524-11eb-9eef-f0752bf7a9ca.png)
![chrome_2021-06-04_10-57-49](https://user-images.githubusercontent.com/85285378/120785105-b587c300-c524-11eb-85ba-a89ba5df05cf.png)
![ShareX_2021-06-04_10-54-49](https://user-images.githubusercontent.com/85285378/120785108-b6205980-c524-11eb-81bd-31fccca6a891.png)

**Comment by SonicDMG** [comment]
Awesome Carlos, thank you. Here's your badge -> https://api.badgr.io/public/assertions/NvjmwzdURkq0oyLJaBDowg?identity__email=carloswilkersp%40hotmail.com
