### ISSUE TITLE
[HW] <Sabarish Susiraj>

### ISSUE THREAD

**Issue by Sabarishsusiraj** [datastaxdevs/workshop-introduction-to-nosql#113]
**Name:** Sabarish Susiraj
**Email:** <sabarishsusiraj21@gmail.com>
**Linkedin Profile:** https://www.linkedin.com/in/sabarish-susiraj-474305171 

Attach the homework screenshots below:
----------
![IMG_20210603_145524](https://user-images.githubusercontent.com/85276825/120622232-4060b300-c47c-11eb-8475-2efabcad6219.jpg)
![IMG_20210603_145408](https://user-images.githubusercontent.com/85276825/120622253-45256700-c47c-11eb-9d83-44c7e406cb7a.jpg)

-------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks good Sabarish, thank you. Here's your badge -> https://api.badgr.io/public/assertions/rX_RWjOHR1SfwnnyPYmF5Q?identity__email=sabarishsusiraj21%40gmail.com
