### ISSUE TITLE
[HW] Simon Priet

### ISSUE THREAD

**Issue by Khosmon** [datastaxdevs/workshop-introduction-to-nosql#116]
**Name:** Simon Priet
**Email:** Simon.priet@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/simonpriet/

# Attach the homework screenshots below:

(Please note my Astra key has been revoked for security)

![Screenshot_2021-06-02 Dashboard — DataStax Astra (Step I)](https://user-images.githubusercontent.com/54704417/120531406-e3fb8600-c3de-11eb-9960-e2dcd51b97b6.png)
*DataStax Astra (Step I)*

![Screenshot_2021-06-02 Manage Database — DataStax Astra (Step II)](https://user-images.githubusercontent.com/54704417/120531916-6f751700-c3df-11eb-9a98-db1f7029060d.png)
*DataStax Astra (Step II)*

![Screenshot_2021-06-02 Swagger UI (cropped, Step III)](https://user-images.githubusercontent.com/54704417/120532372-e8746e80-c3df-11eb-980a-ba9a8a977ce9.png)
*Swagger UI (cropped, Step III)*

![Screenshot_2021-06-02 Manage Database — DataStax Astra (Step IV)](https://user-images.githubusercontent.com/54704417/120532417-f1fdd680-c3df-11eb-9db5-becec7aa2caa.png)
*DataStax Astra (Step IV)*

![image](https://user-images.githubusercontent.com/54704417/120635378-b2c99700-c46c-11eb-8a5c-ac171b6edf4b.png)
*DataStax Studio Graph Workshop (Step V)*

![Screenshot_2021-06-03 Try It Out (Scenario)](https://user-images.githubusercontent.com/54704417/120624361-ea324680-c460-11eb-9d13-ad516a9667ab.png)
*Try It Out (Scenario)*

**Comment by SonicDMG** [comment]
Nice job Simon, thanks for the submission. Here's your key -> https://api.badgr.io/public/assertions/5bBaBwK8THmZR4rreQwM7A?identity__email=simon.priet%40gmail.com

**Comment by Simon-Priet** [comment]
Hi !

Thank you @SonicDMG for you work and the badge :D
