### ISSUE TITLE
[HW] Anna Scimone

### ISSUE THREAD

**Issue by scimone** [datastaxdevs/workshop-introduction-to-nosql#117]
**Name:** Anna Scimone
**Email:** anna_scimone@live.de
**Linkedin Profile:** https://www.linkedin.com/in/anna-scimone/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![2021-06-03 13_27_35-Greenshot](https://user-images.githubusercontent.com/56034784/120638144-10abae00-c470-11eb-8582-fc836ca9448a.jpg)
![2021-06-03 13_29_45-Greenshot](https://user-images.githubusercontent.com/56034784/120638146-11444480-c470-11eb-9a99-2d1cdf68a9cd.jpg)

**Comment by SonicDMG** [comment]
Great job Anna, thank you. Here's your badge -> https://api.badgr.io/public/assertions/a9HNEouIR1SYXPTjLHBV2g?identity__email=anna_scimone%40live.de
