### ISSUE TITLE
[HW] Tam Truong

### ISSUE THREAD

**Issue by truongthanhtam212** [datastaxdevs/workshop-introduction-to-nosql#118]
**Name:** Tam Truong
**Email:** truongthanhtam212@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/truongthanhtam212/
Attach the homework screenshots below:
-----------------------------------------

<img width="1280" alt="nosql1" src="https://user-images.githubusercontent.com/83177704/120639633-3ccc2c80-c47a-11eb-90d4-9c99d672b37b.png">
<img width="1273" alt="nosql2" src="https://user-images.githubusercontent.com/83177704/120639649-405fb380-c47a-11eb-95e0-98c389c21aeb.png">
<img width="1271" alt="nosql3" src="https://user-images.githubusercontent.com/83177704/120639659-435aa400-c47a-11eb-8b2d-ca679b224398.png">
<img width="1274" alt="nosql4" src="https://user-images.githubusercontent.com/83177704/120639667-46ee2b00-c47a-11eb-8c87-cdf83c05675f.png">

**Comment by SonicDMG** [comment]
Looks great Tam, thank you. Here's your badge -> https://api.badgr.io/public/assertions/EuQ5cMfITnSj246tYyPf7Q?identity__email=truongthanhtam212%40gmail.com

**Comment by truongthanhtam212** [comment]
@SonicDMG Thank you, David!
