### ISSUE TITLE
[HW] <Introduction to NoSQL>

### ISSUE THREAD

**Issue by Rafi55555** [datastaxdevs/workshop-introduction-to-nosql#119]
**Name:** <Rafał Żurek>
**Email:** <rafzurek@wp.pl>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<
![1](https://user-images.githubusercontent.com/85263624/120655049-8c165b00-c482-11eb-868c-789b62f5a699.jpg)
![2](https://user-images.githubusercontent.com/85263624/120655076-933d6900-c482-11eb-9f27-5a9870ea91c8.jpg)

SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks good Rafał, thank you. Here's your badge -> https://api.badgr.io/public/assertions/q8fFhAVFQwOgMk_lwn5IMQ?identity__email=rafzurek%40wp.pl
