### ISSUE TITLE
[HW] <Manikandan R>

### ISSUE THREAD

**Issue by maniram477** [datastaxdevs/workshop-introduction-to-nosql#12]
**Name:** Manikandan R
**Email:** maniram477@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/maniram477

Attach the homework screenshots below:
-----------------------------------------
![nosql_screenshot1](https://user-images.githubusercontent.com/8090429/117276032-4616a900-ae7c-11eb-8527-eb2835118222.png)

![Screenshot from 2021-05-06 15-01-28](https://user-images.githubusercontent.com/8090429/117276042-47e06c80-ae7c-11eb-92b4-9b4845a76d78.png)

**Comment by maniram477** [comment]
![Screenshot from 2021-06-01 08-53-11](https://user-images.githubusercontent.com/8090429/120262322-29249880-c2b7-11eb-8e66-487f904b3bb2.png)

**Comment by SonicDMG** [comment]
No worries at all regarding time. Thank you so much for your submission and I'm sorry to hear about your unfortunate event. Awesome job following through. Here you go -> https://api.badgr.io/public/assertions/iD8gXregSjeFjYI2pzy7jA?identity__email=maniram477%40gmail.com
