### ISSUE TITLE
[HW] <ANKUR DEY>

### ISSUE THREAD

**Issue by AnkurDey20** [datastaxdevs/workshop-introduction-to-nosql#120]
**Name:** Ankur Dey
**Email:** deyankur2000@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ankurdey20/

Attach the homework screenshots below:
-----------------------------------------

![ss1](https://user-images.githubusercontent.com/80063726/120654913-c2ae9e80-c49f-11eb-83d5-6dff3c53d9b9.png)
![ss2](https://user-images.githubusercontent.com/80063726/120654954-cb9f7000-c49f-11eb-80a4-e5323a0face1.png)

**Comment by SonicDMG** [comment]
Great work Ankur, thank you. Here's your badge -> https://api.badgr.io/public/assertions/SjgY3q21R9WbCJQh7pb3Sw?identity__email=deyankur2000%40gmail.com
