### ISSUE TITLE
[HW] <ASWIN KUMAR BHATTA>

### ISSUE THREAD

**Issue by bHatTa-03** [datastaxdevs/workshop-introduction-to-nosql#121]
**Name:** <Aswin Kumar Bhatta>
**Email:** <akbhatta3067@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/aswin-bhatta-720389204
![Create a table with GraphQL](https://user-images.githubusercontent.com/65768023/120659867-65691c00-c4a4-11eb-857f-f3a82a8497c5.png)
![POPULATE THE TABLE](https://user-images.githubusercontent.com/65768023/120659876-6732df80-c4a4-11eb-8a6e-ab1bf3924508.png)
![select key,p0,p1,text_value from col1](https://user-images.githubusercontent.com/65768023/120659878-67cb7600-c4a4-11eb-9630-53644a49b8b2.png)
![select key,p0,p1,text_value,dbl_value from col1](https://user-images.githubusercontent.com/65768023/120659880-68640c80-c4a4-11eb-8b07-19522d2b30fb.png)

>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
This looks like a duplicate of https://github.com/datastaxdevs/workshop-introduction-to-nosql/issues/123
