### ISSUE TITLE
[HW] K S A R AMBEDKAR

### ISSUE THREAD

**Issue by ambedkar1985** [datastaxdevs/workshop-introduction-to-nosql#122]
**Name:** K S A R AMBEDKAR
**Email:** ambedkar1985@gmail.com
**Linkedin Profile:** http://www.linkedin.com/in/ambedkar1985@gmail.com/

Attach the homework screenshots below:
[N-1.pdf](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/6592338/N-1.pdf)
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks great K S A R, thank you very much. Here's your badge -> https://api.badgr.io/public/assertions/It4dZli7QReqO3r-E-t9Jw?identity__email=ambedkar1985%40gmail.com
