### ISSUE TITLE
[HW] <ASWIN KUMAR BHATTA>

### ISSUE THREAD

**Issue by bHatTa-03** [datastaxdevs/workshop-introduction-to-nosql#123]
**Name:** <Aswin Kumar Bhatta>
**Email:** <akbhatta3067@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/aswin-bhatta-720389204>
![Create a table with GraphQL](https://user-images.githubusercontent.com/65768023/120662014-6a2ecf80-c4a6-11eb-98b0-5fbf1479727e.png)
![POPULATE THE TABLE](https://user-images.githubusercontent.com/65768023/120662022-6bf89300-c4a6-11eb-9238-87461b5c9c95.png)
![select key,p0,p1,text_value from col1](https://user-images.githubusercontent.com/65768023/120662024-6c912980-c4a6-11eb-98a0-8b8309c896f2.png)
![select key,p0,p1,text_value,dbl_value from col1](https://user-images.githubusercontent.com/65768023/120662030-6d29c000-c4a6-11eb-9c8f-4cc2a6bac38f.png)
![Try it Out](https://user-images.githubusercontent.com/65768023/120662032-6d29c000-c4a6-11eb-8ede-1d6c0fa74632.png)
![try it out-2](https://user-images.githubusercontent.com/65768023/120662037-6dc25680-c4a6-11eb-9192-544d200ef0e2.png)
![try it out-3](https://user-images.githubusercontent.com/65768023/120662040-6e5aed00-c4a6-11eb-94d5-84f52f50f544.png)

>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Really nice work Aswin, thank you. Here's your badge -> https://api.badgr.io/public/assertions/JJxtVlOLSXe0IxLeCODZJg?identity__email=akbhatta3067%40gmail.com
