### ISSUE TITLE
[HW] AtufaShireen

### ISSUE THREAD

**Issue by AtufaShireen** [datastaxdevs/workshop-introduction-to-nosql#124]
Name: Atufa Shireen
Email: atufashireen@gmail.com
Linkedin Profile: https://www.linkedin.com/in/atufa-shireen-526a2117b/

homework screenshots are below:
-----------------------------------------

![Screenshot (17)](https://user-images.githubusercontent.com/49982114/120672886-54260c80-c4b0-11eb-9bba-51e20b55bc7b.png)

-- image removed by team --
![NoSqlLastStep](https://user-images.githubusercontent.com/49982114/120672946-6142fb80-c4b0-11eb-9cdc-d9177cd1497d.png)
![Screenshot (16)](https://user-images.githubusercontent.com/49982114/120672964-656f1900-c4b0-11eb-9bb3-2e954ff1790c.png)
![Screenshot (15)](https://user-images.githubusercontent.com/49982114/120672979-67d17300-c4b0-11eb-9bf0-3365be19abb4.png)

**Comment by AtufaShireen** [comment]
Really Enjoyed this introductory Workshop...

**Comment by SonicDMG** [comment]
Looks great Atufa, thank you. Here's your badge -> https://api.badgr.io/public/assertions/hidm7aT4Rsy6mMy_lnu7uQ?identity__email=atufashireen%40gmail.com

**Comment by SonicDMG** [comment]
I also removed an image because it contained your key. I suggest to delete the token from the AstraUI to be safe.
