### ISSUE TITLE
[HW] <Niranjana Rao Prabakararao>

### ISSUE THREAD

**Issue by NiranjanaRao-P** [datastaxdevs/workshop-introduction-to-nosql#125]
**Name:** <Niranjana Rao Prabakararao>
**Email:** <niran21@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/niranjana-rao-prabakararao/>

Attach the homework screenshots below:
-----------------------------------------

<
![Document_DB_Niranjana](https://user-images.githubusercontent.com/75638383/120681314-dca8ab00-c4b8-11eb-95e8-72f39e5afff8.png)
![KV_DB_Niranjana](https://user-images.githubusercontent.com/75638383/120681317-de726e80-c4b8-11eb-8da4-92222722a501.png)
![KV_DB_Niranjana2](https://user-images.githubusercontent.com/75638383/120681321-df0b0500-c4b8-11eb-9e32-16c31304d51f.png)
![Scenario_Niranjana](https://user-images.githubusercontent.com/75638383/120681362-e9c59a00-c4b8-11eb-814b-709d52173ef4.png)
>

**Comment by SonicDMG** [comment]
Nice job Niranjana, thank you. Here's your badge -> https://api.badgr.io/public/assertions/nnO77IwzTOupgiM_1MGLDw?identity__email=niran21%40gmail.com

**Comment by NiranjanaRao-P** [comment]
Hi David,

The session was a good introduction as promised. Thank you for the workshop
and the badge.

Kindly help me by guiding me on how to update the badge in my LinkedIn
profile.

Thanks and Regards,
Niranjana Rao Prabakararao
+1-510-925-3179
***@***.***

**Comment by SonicDMG** [comment]
Of course Niranjan. If you go to your LinkedIn profile page, click the + icon in the "Featured" section you can paste in your badge link to display your badge.
![Screen Shot 2021-06-03 at 1 49 26 PM](https://user-images.githubusercontent.com/23346205/120689968-ae07e180-c472-11eb-8f16-373ecbbf4f95.png)

I added one to my page as an example.

**Comment by NiranjanaRao-P** [comment]
Thank you very much David!

Regards,
Niranjana Rao Prabakararao
+1-510-925-3179
***@***.***
