### ISSUE TITLE
[HW] Augustia Babu

### ISSUE THREAD

**Issue by augubabu** [datastaxdevs/workshop-introduction-to-nosql#126]
**Name:** Augustia Babu
**Email:** <augubabuaugu@gmail.com>
**Linkedin Profile:** linkedin.com/in/augu-babu-4131a5101

Attach the homework screenshots below:
-----------------------------------------

![scenario completed](https://user-images.githubusercontent.com/85178831/120685912-07e1c900-c4be-11eb-92d2-d830da6ae1d5.PNG)
![Step IV](https://user-images.githubusercontent.com/85178831/120685916-09ab8c80-c4be-11eb-9ebd-7de6c7b29fb3.PNG)

**Comment by SonicDMG** [comment]
Awesome Augustia, looks good. Here's your badge -> https://api.badgr.io/public/assertions/JuhM2FeXQAK05MTXcd3LXg?identity__email=augubabuaugu%40gmail.com
