### ISSUE TITLE
[HW] Sanskar

### ISSUE THREAD

**Issue by Sanskar1903** [datastaxdevs/workshop-introduction-to-nosql#127]
**Name:** SANSKAR
**Email:** <ssanskar0300@gmail.com>
**Linkedin Profile:** linkedin.com/in/sanskar-sharma-03181b1bb

Attach the homework screenshots below:
-----------------------------------------
![ss1](https://user-images.githubusercontent.com/81019699/120688838-1978a000-c4c1-11eb-8aed-491565cc7705.png)
![ss2](https://user-images.githubusercontent.com/81019699/120688851-1aa9cd00-c4c1-11eb-8a21-6b0413774595.png)
![ss3](https://user-images.githubusercontent.com/81019699/120688854-1b426380-c4c1-11eb-9af6-1be2991f0cc1.png)
-- image removed by team --
![ss4(2)](https://user-images.githubusercontent.com/81019699/120688860-1c739080-c4c1-11eb-96d6-359529bce5e2.png)
![tryiton](https://user-images.githubusercontent.com/81019699/120688867-1da4bd80-c4c1-11eb-8f4c-d42a760acaff.png)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks great Sanskar, thank you. Here's your badge -> https://api.badgr.io/public/assertions/D4AZ3q-oSVKimGsOl4Q43Q?identity__email=ssanskar0300%40gmail.com
