### ISSUE TITLE
[HW] <Shrinithi S>

### ISSUE THREAD

**Issue by Shri-s123** [datastaxdevs/workshop-introduction-to-nosql#128]
**Name:** <Shrinithi S>
**Email:** <Shrishan0123@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/shrinithi-s-a86a79163/>

Attach the homework screenshots below:
-----------------------------------------
[NoSQL HW.docx](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/6593808/NoSQL.HW.docx)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks good Shrinithi, thank you. Here's your badge -> https://api.badgr.io/public/assertions/umohGTquQZuve1-JG-qPwA?identity__email=shrishan0123%40gmail.com
