### ISSUE TITLE
[HW] Akash Kumar

### ISSUE THREAD

**Issue by akash9767** [datastaxdevs/workshop-introduction-to-nosql#129]
**Name:** Akash Kumar
**Email:** akashkumarit5@gmail.com
**Linkedin Profile:**  https://www.linkedin.com/in/akash-kumar-65a22899

Attach the homework screenshots below:
-----------------------------------------
2a ![image](https://user-images.githubusercontent.com/85246591/120700714-9ca0f280-c4cf-11eb-9dd5-8706546ccf69.png)
2b ![image](https://user-images.githubusercontent.com/85246591/120700889-db36ad00-c4cf-11eb-8537-d14b12a33027.png)
2c ![image](https://user-images.githubusercontent.com/85246591/120701293-4c766000-c4d0-11eb-8eaf-6654e1201abe.png)
2d ![image](https://user-images.githubusercontent.com/85246591/120701706-d1617980-c4d0-11eb-8f05-bab494b344d6.png)
3a ![image](https://user-images.githubusercontent.com/85246591/120702069-46cd4a00-c4d1-11eb-80d4-f3a7d58b461a.png)
3c ![image](https://user-images.githubusercontent.com/85246591/120703551-14245100-c4d3-11eb-8aa9-a5227aaa8a73.png)
3d ![image](https://user-images.githubusercontent.com/85246591/120703759-564d9280-c4d3-11eb-8214-61ef441878a7.png)
3e ![image](https://user-images.githubusercontent.com/85246591/120703904-885ef480-c4d3-11eb-8fce-2de727fc2414.png)
3f 
![image](https://user-images.githubusercontent.com/85246591/120704218-f7d4e400-c4d3-11eb-9b6d-77884c7bdea6.png)
3g 
![image](https://user-images.githubusercontent.com/85246591/120704737-9a8d6280-c4d4-11eb-912b-a579da9562bc.png)
4b 
![image](https://user-images.githubusercontent.com/85246591/120705677-c0ffcd80-c4d5-11eb-9fcf-7ca44aab2879.png)
![image](https://user-images.githubusercontent.com/85246591/120705710-cbba6280-c4d5-11eb-8202-01aca8303e91.png)

4c 
![image](https://user-images.githubusercontent.com/85246591/120706240-7894df80-c4d6-11eb-9f15-a1ee5ae3c6c6.png)
![image](https://user-images.githubusercontent.com/85246591/120706493-cb6e9700-c4d6-11eb-8909-d5e5a9a70586.png)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Very nice submission Akash. The only thing I am missing is the completed screen from step 2 of the homework.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please provide that screen as well.

**Comment by akash9767** [comment]
![image](https://user-images.githubusercontent.com/85246591/120900684-cc790300-c653-11eb-88b7-f045e0e1f11a.png)

**Comment by akash9767** [comment]
Hi David,
The same has been done. Please check.

**Comment by SonicDMG** [comment]
Looks good Akash, thank your for following up. Here you go -> https://api.badgr.io/public/assertions/95z-LNVlQLag7DdjtAWnEg?identity__email=akashkumarit5%40gmail.com
