### ISSUE TITLE
Megha Swami

### ISSUE THREAD

**Issue by megha3004** [datastaxdevs/workshop-introduction-to-nosql#13]
**Name:** <NAME>Megha Swami
**Email:** <email> meghaswami30@gmail.com
**Linkedin Profile:** <LINK> https://www.linkedin.com/in/megha-swami-25b254b8/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
-- images removed by team --

**Comment by SonicDMG** [comment]
Hi there Megha. I don't see anything in the document you attached. You mind resubmitting please or just paste the images directly into the issue here.

**Comment by HadesArchitect** [comment]
@SonicDMG I can open the doc and I see the step II there:

![image](https://user-images.githubusercontent.com/1742301/118503255-c239a800-b72a-11eb-8722-52440501dbd7.png)

@megha3004 We still need screenshots for the step I please :)

**Comment by megha3004** [comment]
I have sent a document

**Comment by SonicDMG** [comment]
Ok, looks good. Thank you Megha, here you go. https://api.badgr.io/public/assertions/HoqTN9xzQKu21x5WiHaErw?identity__email=meghaswami30%40gmail.com

**Comment by megha3004** [comment]
Thank you!
