### ISSUE TITLE
[HW] Marcin Czernicki

### ISSUE THREAD

**Issue by Niodor** [datastaxdevs/workshop-introduction-to-nosql#130]
**Name:** Marcin Czernicki
**Email:** czermar@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/marcin-czernicki-34a53a93/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![1](https://user-images.githubusercontent.com/22057799/120708970-8e95a680-c4bc-11eb-833d-2dd8136a26b1.JPG)
![2](https://user-images.githubusercontent.com/22057799/120708980-92292d80-c4bc-11eb-83dc-8c3696265079.JPG)

**Comment by SonicDMG** [comment]
Perfect Marcin, looks good, thank you. Here's your badge -> https://api.badgr.io/public/assertions/q1Qd0UlLQ_mwBkDLsSCPiw?identity__email=czermar%40gmail.com
