### ISSUE TITLE
[HW] Abeezer Golwala

### ISSUE THREAD

**Issue by Abeezer-Golwala** [datastaxdevs/workshop-introduction-to-nosql#131]
Name: Abeezer Golwala
Email: abeezergolwala98@gmail.com 
LinkedIn Profile: https://www.linkedin.com/in/abeezer-golwala/

Attach the homework screenshots below:
-----------------------------------------
1. Create Astra Instance
![step1](https://user-images.githubusercontent.com/72350213/120693520-bab62500-c4c6-11eb-80e6-836459b17db9.png)
2. Tabular databases
![image](https://user-images.githubusercontent.com/72350213/120695298-de7a6a80-c4c8-11eb-86eb-9840f4bd944e.png)
![image](https://user-images.githubusercontent.com/72350213/120695448-05d13780-c4c9-11eb-9521-472e36cd0663.png)
![image](https://user-images.githubusercontent.com/72350213/120695709-5183e100-c4c9-11eb-82fd-b90964be75d2.png)
3. Document Databases
![image](https://user-images.githubusercontent.com/72350213/120696153-d5d66400-c4c9-11eb-8c52-ec8f62bd077e.png)
3d. Create a new document :
![image](https://user-images.githubusercontent.com/72350213/120701806-f2c26580-c4d0-11eb-9b46-2ede9bd7c9e5.png)
![image](https://user-images.githubusercontent.com/72350213/120702814-22be3880-c4d2-11eb-91d0-e85f1c1fa45c.png)
3g Search document from a where clause :
![image](https://user-images.githubusercontent.com/72350213/120703005-6153f300-c4d2-11eb-8c07-c47aa7dc4103.png)
4. KeyValue Databases
![image](https://user-images.githubusercontent.com/72350213/120704233-fc010180-c4d3-11eb-9937-9a64ad39db60.png)
![image](https://user-images.githubusercontent.com/72350213/120704878-c0b30280-c4d4-11eb-8671-6371c5b8650b.png)
![image](https://user-images.githubusercontent.com/72350213/120705080-f9eb7280-c4d4-11eb-947e-f39b193bd435.png)

Try out
![image](https://user-images.githubusercontent.com/72350213/120716183-4b9af980-c4e3-11eb-97dd-c5ec5f3e5782.png)

**Comment by SonicDMG** [comment]
Looks great Abeezer, thank you. Here's your badge -> https://api.badgr.io/public/assertions/Fuo4s29wRjylG5uv4Skhcg?identity__email=abeezergolwala98%40gmail.com
