### ISSUE TITLE
[HW] <Michael Lau>

### ISSUE THREAD

**Issue by mlaucs** [datastaxdevs/workshop-introduction-to-nosql#133]
**Name:** <Michael Lau>
**Email:** <mlaucse@gmail.com>
**Linkedin Profile:** <linkedin.com/in/michaellau-cs>

Attach the homework screenshots below:
-----------------------------------------
![Screenshot (529)](https://user-images.githubusercontent.com/65942318/120754478-94da5180-c4c1-11eb-9f28-488cccba23b3.png)
![Screenshot (528)](https://user-images.githubusercontent.com/65942318/120754637-cd7a2b00-c4c1-11eb-8371-995996716820.png)
![Screenshot (544)](https://user-images.githubusercontent.com/65942318/120754830-0914f500-c4c2-11eb-906e-e21d8046ab2e.png)

**Comment by SonicDMG** [comment]
Awesome job Michael, thank you. Here's your badge -> https://api.badgr.io/public/assertions/o42h9Z3wT9GK2JDgDKqenQ?identity__email=mlaucse%40gmail.com
