### ISSUE TITLE
[HW] <Shahana>

### ISSUE THREAD

**Issue by Shahana0214** [datastaxdevs/workshop-introduction-to-nosql#134]
**Name:** <SHAHANA>
**Email:** <ahmedshahana@gmail.com
![Screenshot (369)](https://user-images.githubusercontent.com/85240991/120763040-782b3180-c534-11eb-8ff3-0318f35c760e.png)
![Screenshot (370)](https://user-images.githubusercontent.com/85240991/120763049-79f4f500-c534-11eb-8490-02bd138c7539.png)
![Screenshot (371)](https://user-images.githubusercontent.com/85240991/120763053-7a8d8b80-c534-11eb-9ea8-059d1c569ace.png)
![Screenshot (372)](https://user-images.githubusercontent.com/85240991/120763056-7b262200-c534-11eb-893c-7df7b1cfde34.png)
![Screenshot (374)](https://user-images.githubusercontent.com/85240991/120763060-7b262200-c534-11eb-870d-a97126d5e248.png)
![Screenshot (375)](https://user-images.githubusercontent.com/85240991/120763061-7bbeb880-c534-11eb-9be2-0de89aa9725a.png)
![Screenshot (376)](https://user-images.githubusercontent.com/85240991/120763062-7c574f00-c534-11eb-8fdf-6c3d7c02f6ff.png)
![Screenshot (377)](https://user-images.githubusercontent.com/85240991/120763064-7c574f00-c534-11eb-8b38-ed74c1b05489.png)
![Screenshot (373)](https://user-images.githubusercontent.com/85240991/120763109-8711e400-c534-11eb-9bc1-994c64d91efb.png)
![120662014-6a2ecf80-c4a6-11eb-98b0-5fbf1479727e](https://user-images.githubusercontent.com/85240991/120763320-ba547300-c534-11eb-8d48-9e5c6d104c95.png)
![120662022-6bf89300-c4a6-11eb-9238-87461b5c9c95](https://user-images.githubusercontent.com/85240991/120763333-bc1e3680-c534-11eb-8b40-d9866b5e1dcf.png)
![120685912-07e1c900-c4be-11eb-92d2-d830da6ae1d5](https://user-images.githubusercontent.com/85240991/120763336-bc1e3680-c534-11eb-88a2-de57d3213fd4.png)

>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Nice job Shahana, thank you. What name should I use for your badge?

**Comment by Shahana0214** [comment]
Shahana Ahmed

**Comment by Shahana0214** [comment]
Please issue me the badge

**Comment by SonicDMG** [comment]
Here you go Shahana -> https://api.badgr.io/public/assertions/1ZScVC_LQcyEsKOZEE6Qfg?identity__email=ahmedshahana%40gmail.com
