### ISSUE TITLE
HW_Aashish_Kumar

### ISSUE THREAD

**Issue by aashish72it** [datastaxdevs/workshop-introduction-to-nosql#135]
**Name:** Aashish Kumar
**Email:** aashish72.it@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/aashish-kumar-75810949

Attach the homework screenshots below:
-----------------------------------------

**1. Create Astra Instance:**

![image](https://user-images.githubusercontent.com/85340192/120777737-3b1a6b80-c543-11eb-8f2e-305e09ea3e66.png)

**2. Create Database and Keyspace and create table videos and users_by_city to check working of partition, filter & tracing .**

![image](https://user-images.githubusercontent.com/85340192/120777975-787ef900-c543-11eb-90f3-34579f6d76bc.png)

![image](https://user-images.githubusercontent.com/85340192/120778460-f9d68b80-c543-11eb-8e19-b9ba54e60a2a.png)

![image](https://user-images.githubusercontent.com/85340192/120778584-18d51d80-c544-11eb-888a-0e436947e028.png)

![image](https://user-images.githubusercontent.com/85340192/120779170-70738900-c544-11eb-84d7-880fc6f4c259.png)

**3. Document Databases**

![image](https://user-images.githubusercontent.com/85340192/120779412-aca6e980-c544-11eb-918e-8e92c5fe6bc2.png)

-- images removed by team --

**4. Key/Value Databases**

Created a table. Inserted values and then updated it. As same key will not be inserted it will update on 2nd time.

![image](https://user-images.githubusercontent.com/85340192/120780682-f8a65e00-c545-11eb-8cc7-eddd7b6979e4.png)

**Comment by SonicDMG** [comment]
Nice work Aashish, thank you. Here's your badge -> https://api.badgr.io/public/assertions/S1MWOaazRaKQHMAaPEAX1Q?identity__email=aashish72.it%40gmail.com. You may have noticed I had to remove some images because they contained your Astra DB token. You should delete this token from your Astra UI to be safe.

**Comment by aashish72it** [comment]
Thanks David! I will delete it & regenerate the same for future use.
