### ISSUE TITLE
[HW] Alan Paterson

### ISSUE THREAD

**Issue by AlanAndrewPaterson** [datastaxdevs/workshop-introduction-to-nosql#136]
**Name:** Alan Paterson
**Email:** alanandrewpaterson@googlemail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

![workshop_2a](https://user-images.githubusercontent.com/85345476/120790941-79a42c00-c52b-11eb-90cb-ffaef215b634.png)
![workshop_2b](https://user-images.githubusercontent.com/85345476/120790944-7a3cc280-c52b-11eb-91a5-a4011197db00.png)
![workshop_2c](https://user-images.githubusercontent.com/85345476/120790947-7b6def80-c52b-11eb-9627-038bd7b14c61.png)
![workshop_2d](https://user-images.githubusercontent.com/85345476/120790951-7c068600-c52b-11eb-95f1-6ee862e8259e.png)
![workshop_3a](https://user-images.githubusercontent.com/85345476/120790956-7d37b300-c52b-11eb-8a60-c59fe34cedca.png)
![workshop_3b](https://user-images.githubusercontent.com/85345476/120790958-7dd04980-c52b-11eb-81f9-02fad5d2640e.png)
![workshop_3c](https://user-images.githubusercontent.com/85345476/120790961-7f017680-c52b-11eb-89bc-ff77d3d5e958.png)
![workshop_3d](https://user-images.githubusercontent.com/85345476/120790963-7f9a0d00-c52b-11eb-8b83-80cf2e7b5ee0.png)
![workshop_3e](https://user-images.githubusercontent.com/85345476/120790966-8032a380-c52b-11eb-9930-a90ed779e632.png)
![workshop_3f](https://user-images.githubusercontent.com/85345476/120790970-80cb3a00-c52b-11eb-99f4-495e1e410a91.png)
![workshop_3g](https://user-images.githubusercontent.com/85345476/120790971-8163d080-c52b-11eb-8a4a-3ce3e39d3dac.png)
![workshop_4b](https://user-images.githubusercontent.com/85345476/120790974-81fc6700-c52b-11eb-8f27-3c116a9788de.png)
![workshop_4c](https://user-images.githubusercontent.com/85345476/120790979-832d9400-c52b-11eb-952e-16d4ade592a0.png)
![try-it-out_scenario](https://user-images.githubusercontent.com/85345476/120790937-7872ff00-c52b-11eb-8ded-84c1a9282bcd.png)

**Comment by SonicDMG** [comment]
Great job Alan, thank you. Here's your badge -> https://api.badgr.io/public/assertions/BqJ0HaJ6Qs2ntBoyng_dZQ?identity__email=alanandrewpaterson%40googlemail.com
