### ISSUE TITLE
[HW] RAJAN PRATAP SINGH

### ISSUE THREAD

**Issue by LONEWOLF-tech** [datastaxdevs/workshop-introduction-to-nosql#137]
**Name:**  RAJAN PRATAP SINGH
**Email:**  rajanpratap911@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/rajan-pratap-singh-0035b01a4/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![image](https://user-images.githubusercontent.com/53988654/120793707-dec04780-c554-11eb-959c-11cac9a3a080.png)
![image](https://user-images.githubusercontent.com/53988654/120793742-eaac0980-c554-11eb-91d9-7f5b247c0e6a.png)
![image](https://user-images.githubusercontent.com/53988654/120793817-03b4ba80-c555-11eb-8c22-d4e32ef9770c.png)

**Comment by SonicDMG** [comment]
Great work Rajan, thank you. Here's your badge -> https://api.badgr.io/public/assertions/Pvu2P-WbRZaqQE_UgWA7AQ?identity__email=rajanpratap911%40gmail.com
