### ISSUE TITLE
[HW] <Madeswaran>

### ISSUE THREAD

**Issue by Mades1997** [datastaxdevs/workshop-introduction-to-nosql#139]
**Name:** G.Madeswaran
**Email:** mades1997@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/madeswaran-gunasekaran-21195a189
![Assignment2](https://user-images.githubusercontent.com/85354199/120881960-627c4180-c5f2-11eb-9b2f-ac607ffcdf2e.PNG)
![Image3](https://user-images.githubusercontent.com/85354199/120881964-64de9b80-c5f2-11eb-86dc-24bef2bc7895.PNG)
![Image 4](https://user-images.githubusercontent.com/85354199/120881965-64de9b80-c5f2-11eb-9207-c8e813130cc5.PNG)
![Image2](https://user-images.githubusercontent.com/85354199/120881966-65773200-c5f2-11eb-8c44-69bf149c7607.PNG)
![Image1](https://user-images.githubusercontent.com/85354199/120881967-66a85f00-c5f2-11eb-8191-284377ea1fb1.PNG)

>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Hi Madeswaran, thank you for your submission. I see the try-it-out scenario and some of the workshop itself, but do you have any screens from completing either step IV or step V? That should be the end of the graphQL or graph sections?

**Comment by HadesArchitect** [comment]
Hey **G.Madeswaran**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/pIFQrQixTHW_edsx7Tu1Cg
