### ISSUE TITLE
[HW] <Panagiotis Antonoulas>

### ISSUE THREAD

**Issue by Pan1kas** [datastaxdevs/workshop-introduction-to-nosql#14]
![cas15](https://user-images.githubusercontent.com/56757964/117294766-f085d080-ae6a-11eb-97a0-763fdff7ebba.png)
-- images removed by team --
![cas13](https://user-images.githubusercontent.com/56757964/117294775-f4195780-ae6a-11eb-8901-1578ebd43deb.png)
-- images removed by team --
![cas6](https://user-images.githubusercontent.com/56757964/117294820-fe3b5600-ae6a-11eb-95c8-76c79f15b73f.png)
![cas5](https://user-images.githubusercontent.com/56757964/117294823-00051980-ae6b-11eb-881d-11d55fd9469d.png)
![cas4](https://user-images.githubusercontent.com/56757964/117294832-03000a00-ae6b-11eb-9e10-b7cfb0473b95.png)
![cas3](https://user-images.githubusercontent.com/56757964/117294833-04c9cd80-ae6b-11eb-84a2-21bf1f885ebe.png)
![cas2](https://user-images.githubusercontent.com/56757964/117294841-06939100-ae6b-11eb-9eba-229fad28fe98.png)
![cas1](https://user-images.githubusercontent.com/56757964/117294847-085d5480-ae6b-11eb-8428-22f6a70f6a77.png)
![hw-cas](https://user-images.githubusercontent.com/56757964/117294858-0a271800-ae6b-11eb-8ba4-b35cbcd03d22.png)

**Name:** Panagiotis Antonoulas
**Email:** niarfoug@hotmail.com
**Linkedin Profile:** https://www.linkedin.com/in/panagiotis-antonoulas-44bb88b5/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by Pan1kas** [comment]
Thank you very much, anything else from me to receive the badge? 


> Looks good Panagiotis, thank you.

**Comment by HadesArchitect** [comment]
Nope, you are good. Here we go! https://api.badgr.io/public/assertions/s-FiAaxBRDOhGsberoktkQ?identity__email=niarfoug%40hotmail.com
