### ISSUE TITLE
[HW] <Prakash Varandani>

### ISSUE THREAD

**Issue by prakashcv13** [datastaxdevs/workshop-introduction-to-nosql#140]
**Name:** <Prakash Varandani>
**Email:** <prakashcv13@gmail.com>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

![step-4](https://user-images.githubusercontent.com/17924657/120896273-7cdc0c80-c63e-11eb-828f-b9201da5f8a6.png)
![step 5](https://user-images.githubusercontent.com/17924657/120896460-523e8380-c63f-11eb-8180-ccc6c240393c.png)
![try-it-out](https://user-images.githubusercontent.com/17924657/120896277-7ea5d000-c63e-11eb-9e4f-dacef0c9fe80.png)

**Comment by SonicDMG** [comment]
Looks great Prakash, thank you. here's your badge -> https://api.badgr.io/public/assertions/fPmVSnIHQbum2fKH3eNecQ?identity__email=prakashcv13%40gmail.com
