### ISSUE TITLE
[HW] Feroz Yusuf Khatri

### ISSUE THREAD

**Issue by ferozyk** [datastaxdevs/workshop-introduction-to-nosql#142]
**Name:** Feroz Yusuf Khatri
**Email:** feroz.khatri23@gmail.com
**Linkedin Profile:** https://linkedin.com/in/feroz-khatri-40837580

Attach the homework screenshots below:
-----------------------------------------
![Screen Shot 2021-06-06 at 11 08 59 PM](https://user-images.githubusercontent.com/9567271/120934820-838d8100-c71d-11eb-816b-808e539c5906.png)

**Comment by SonicDMG** [comment]
Hi Feroz, great job in getting through the Graph notebook. The only thing I am missing is the completed screen from step 2 of the homework.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

**Comment by ferozyk** [comment]
Hi, my apologies on missing out the step 2. Please find attached the scenario completed screen.

![image](https://user-images.githubusercontent.com/9567271/121069010-9b7f0680-c7ea-11eb-8cf8-d1a52fd607c3.png)

**Comment by SonicDMG** [comment]
No worries at all Feroz. Thank you very much for following up. Here you go -> https://api.badgr.io/public/assertions/89diNpGpQJSg7velok-jng?identity__email=feroz.khatri23%40gmail.com
