### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by meetgkg** [datastaxdevs/workshop-introduction-to-nosql#144]
**Name:** Gaurav Kumar Gupta
**Email:** meetgkg@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/meetgkg/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![scenario completed](https://user-images.githubusercontent.com/12091816/121224270-04778480-c8a6-11eb-80c0-b55e0bd5b672.JPG)

![Astra Session Completion](https://user-images.githubusercontent.com/12091816/121224303-0c372900-c8a6-11eb-96cf-27ef72a8944e.JPG)

**Comment by meetgkg** [comment]
![scenario completed](https://user-images.githubusercontent.com/12091816/121224421-2c66e800-c8a6-11eb-8692-09b3848e63f9.JPG)

**Comment by SonicDMG** [comment]
Nice job Gaurav, thank you. Here you go -> https://api.badgr.io/public/assertions/tx-1x-VURd2JBjH81lGXlA?identity__email=meetgkg%40gmail.com
