### ISSUE TITLE
[HW] <Vemal K.S>

### ISSUE THREAD

**Issue by Vemal587** [datastaxdevs/workshop-introduction-to-nosql#145]
**Name:** <Vemal K.S>
**Email:** <vemal587@yahoo.com>
**Linkedin Profile:** <https://www.linkedin.com/in/vemal-k-s-106746113>

Attach the homework screenshots below:
-----------------------------------------
 1) Creation of Astra DB 

<img width="938" alt="nosql_0" src="https://user-images.githubusercontent.com/85180620/121550031-fce1e800-ca2b-11eb-9814-165b5005925a.PNG">

2) Tabular DataBases:

<img width="565" alt="nosql_1" src="https://user-images.githubusercontent.com/85180620/121550161-1edb6a80-ca2c-11eb-913f-028c6cb78bdc.PNG">

3) Document DataBases
![image](https://user-images.githubusercontent.com/85180620/121550402-55b18080-ca2c-11eb-91ae-264f0782bd53.png)

4) KeyValueDataBases
<img width="673" alt="nosql_3_1" src="https://user-images.githubusercontent.com/85180620/121551188-0e77bf80-ca2d-11eb-803f-93eac8728039.PNG">
Try-it-out Scenario:
<img width="769" alt="nosql_try_it_scenario" src="https://user-images.githubusercontent.com/85180620/121551278-20596280-ca2d-11eb-9495-4495f9443c2b.PNG">

**Comment by clun** [comment]
Great Job, thank you for your work.

Here is your badge:
https://badgr.com/public/assertions/kW5BS4kBS-6tUWu8qukpNA?identity__email=vemal587@yahoo.com
