### ISSUE TITLE
[HW] Julian Nadarzy

### ISSUE THREAD

**Issue by juliann** [datastaxdevs/workshop-introduction-to-nosql#146]
**Name:** Julian Nadarzy
**Email:** julian.nadarzy@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/julian-nadarzy-74b7b810/
![astra completed](https://user-images.githubusercontent.com/1125748/121709137-864ef400-cad8-11eb-990e-585141c6db85.png)
![scenario completed](https://user-images.githubusercontent.com/1125748/121709169-8e0e9880-cad8-11eb-80aa-9105f370b712.jpg)

Attach the homework screenshots below:
-----------------------------------------

**Comment by clun** [comment]
Great Job, thank you for your work.

Here is your badge:
https://badgr.com/public/assertions/DAMEeNqmTB2qdjQvqJY3nQ?identity__email=julian.nadarzy@gmail.com
