### ISSUE TITLE
[HW] Denis Kotnik

### ISSUE THREAD

**Issue by kotnikd3** [datastaxdevs/workshop-introduction-to-nosql#15]
**Name:** Denis Kotnik
**Email:** denis.kotnik@gmail.com
**Linkedin Profile:** www.linkedin.com/in/denis-kotnik

Attach the homework screenshots below:
-----------------------------------------
![1_1](https://user-images.githubusercontent.com/9354023/117309728-fb4c5f80-ae82-11eb-9c3e-1541eecb9326.png)
![2_1](https://user-images.githubusercontent.com/9354023/117309726-fab3c900-ae82-11eb-8901-c0589f27dcb0.png)
![2_2](https://user-images.githubusercontent.com/9354023/117309725-fab3c900-ae82-11eb-93d8-fbdbc6b399ee.png)
![3_1](https://user-images.githubusercontent.com/9354023/117309720-fa1b3280-ae82-11eb-8351-6162783706ff.png)
-- images removed by team --
![4_3](https://user-images.githubusercontent.com/9354023/117309714-f8ea0580-ae82-11eb-992e-22a162004a92.png)
![final](https://user-images.githubusercontent.com/9354023/117309712-f8516f00-ae82-11eb-985d-023d6559d3bd.png)
![datastax_final](https://user-images.githubusercontent.com/9354023/117983705-7dcb9800-b337-11eb-803a-9064c183362e.png)

**Comment by SonicDMG** [comment]
Hi Denis, do you also have the values from key 2?

**Comment by kotnikd3** [comment]
Hi SonicDMG, yes, I added a screenshot at the end (of homework).

**Comment by SonicDMG** [comment]
Ok, thank you

**Comment by HadesArchitect** [comment]
Here we go: https://api.badgr.io/public/assertions/TdSe6vaVR4eV-tp2lqHcJA?identity__email=denis.kotnik%40gmail.com
