### ISSUE TITLE
[HW] Introduction to NoSQL

### ISSUE THREAD

**Issue by faheem618816** [datastaxdevs/workshop-introduction-to-nosql#151]
**Name:** Faheem Ahmed
**Email:** faheem618816@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/faheemahmed618816/

Attach the homework screenshots below:
-----------------------------------------
**Homework Screenshots Step 4**

![Screenshot from 2021-06-16 21-39-30](https://user-images.githubusercontent.com/86013574/122259636-023da780-cef0-11eb-87b2-86132414e785.png)
![Screenshot from 2021-06-16 21-40-14](https://user-images.githubusercontent.com/86013574/122259642-04076b00-cef0-11eb-8702-f58f8123f5ae.png)
![Screenshot from 2021-06-16 21-40-19](https://user-images.githubusercontent.com/86013574/122259648-04a00180-cef0-11eb-91b8-130a1731efa4.png)
![Screenshot from 2021-06-16 21-40-27](https://user-images.githubusercontent.com/86013574/122259654-05d12e80-cef0-11eb-9031-1c0c265ab5bd.png)
![Screenshot from 2021-06-16 21-43-04](https://user-images.githubusercontent.com/86013574/122259659-0669c500-cef0-11eb-896e-3c55611b3363.png)
![Screenshot from 2021-06-16 21-43-46](https://user-images.githubusercontent.com/86013574/122259662-079af200-cef0-11eb-8ab7-a48954a6bdfd.png)
![Screenshot from 2021-06-16 21-43-49](https://user-images.githubusercontent.com/86013574/122259664-08338880-cef0-11eb-8454-a67051f58c25.png)
![Screenshot from 2021-06-16 21-44-13](https://user-images.githubusercontent.com/86013574/122259667-08cc1f00-cef0-11eb-88d4-e35e9ced5866.png)
![Screenshot from 2021-06-16 21-45-25](https://user-images.githubusercontent.com/86013574/122259669-0964b580-cef0-11eb-8ccb-23985ad75b55.png)
![Screenshot from 2021-06-16 21-45-45](https://user-images.githubusercontent.com/86013574/122259675-09fd4c00-cef0-11eb-85c5-d995e286526d.png)
![Screenshot from 2021-06-16 21-45-58](https://user-images.githubusercontent.com/86013574/122259682-0a95e280-cef0-11eb-9cfd-ef8c0c5cf99b.png)
![Screenshot from 2021-06-16 21-46-50](https://user-images.githubusercontent.com/86013574/122259687-0b2e7900-cef0-11eb-8838-770e84fe9ed8.png)
![Screenshot from 2021-06-16 21-47-03](https://user-images.githubusercontent.com/86013574/122259691-0bc70f80-cef0-11eb-8d6f-91b54263beac.png)

**Try It Out Scenario**

![Screenshot from 2021-06-16 22-16-09](https://user-images.githubusercontent.com/86013574/122261086-a4aa5a80-cef1-11eb-86c0-26fcc002ba61.png)
![Screenshot from 2021-06-16 22-16-38](https://user-images.githubusercontent.com/86013574/122261089-a5db8780-cef1-11eb-8ac9-8bcd0b347776.png)
![Screenshot from 2021-06-16 22-16-47](https://user-images.githubusercontent.com/86013574/122261093-a70cb480-cef1-11eb-96b8-d0a6df275d23.png)
![Screenshot from 2021-06-16 22-17-07](https://user-images.githubusercontent.com/86013574/122261096-a7a54b00-cef1-11eb-9a48-5dcb0a52f1b5.png)
![Screenshot from 2021-06-16 22-17-31](https://user-images.githubusercontent.com/86013574/122261102-a83de180-cef1-11eb-902b-a31bf0fedebf.png)
![Screenshot from 2021-06-16 22-17-58](https://user-images.githubusercontent.com/86013574/122261110-a96f0e80-cef1-11eb-850b-a14433c12aff.png)
![Screenshot from 2021-06-16 22-18-10](https://user-images.githubusercontent.com/86013574/122261111-aaa03b80-cef1-11eb-8f5a-8a8ea9cc8871.png)
![Screenshot from 2021-06-16 22-18-21](https://user-images.githubusercontent.com/86013574/122261113-ab38d200-cef1-11eb-98a6-1e3eaac1a687.png)
![Screenshot from 2021-06-16 22-18-29](https://user-images.githubusercontent.com/86013574/122261115-abd16880-cef1-11eb-9e23-0cdba98f8d5f.png)
![Screenshot from 2021-06-16 22-18-34](https://user-images.githubusercontent.com/86013574/122261117-ac69ff00-cef1-11eb-9fa2-55602e4f101f.png)
![Screenshot from 2021-06-16 22-18-38](https://user-images.githubusercontent.com/86013574/122261122-ad9b2c00-cef1-11eb-9419-29bc059246ff.png)
![Screenshot from 2021-06-16 22-18-45](https://user-images.githubusercontent.com/86013574/122261128-ae33c280-cef1-11eb-8f52-1632bce1b97a.png)
![Screenshot from 2021-06-16 22-18-59](https://user-images.githubusercontent.com/86013574/122261130-aecc5900-cef1-11eb-9ea8-ac5bef61b356.png)

**Comment by HadesArchitect** [comment]
Wow that was quick!

**Comment by HadesArchitect** [comment]
Hey **Faheem Ahmed**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/AFwR83VETSqLrJoDLXB1aw
