### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by iAmBritt** [datastaxdevs/workshop-introduction-to-nosql#155]
**Name:** britt svanqvist
**Email:** svanqvistbritt@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/britt-svanqvist-72b59a61/

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/86019254/122273163-6ad15800-cee1-11eb-97e6-a55adda2862f.png)

![image](https://user-images.githubusercontent.com/86019254/122273239-7fadeb80-cee1-11eb-85cc-6e9afa3091e6.png)

**Comment by RyanWelford** [comment]
Thanks Britt! Great job!

**Comment by HadesArchitect** [comment]
Hey **britt svanqvist**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/qN28elqTSSyVlH0q1Nn5sw
