### ISSUE TITLE
[HW] Karolina Skorupska

### ISSUE THREAD

**Issue by Haqual** [datastaxdevs/workshop-introduction-to-nosql#156]
**Name:**  Karolina Skorupska
**Email:** kskorupska13@gmail.com
**Linkedin Profile:**  https://www.linkedin.com/in/karolina-skorupska-525620184/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![KS_nosql4_1](https://user-images.githubusercontent.com/26491654/122274867-555d2d80-cee3-11eb-8e90-2150fea86e74.png)
![KS_nosql4_2](https://user-images.githubusercontent.com/26491654/122274870-568e5a80-cee3-11eb-9855-bd78eb0227bb.png)
![KS_scenario](https://user-images.githubusercontent.com/26491654/122274885-58f0b480-cee3-11eb-9d5f-617510abad65.png)

**Comment by HadesArchitect** [comment]
Hey **Karolina Skorupska**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/3Lp6_sXlRKWwqz1YnHz2Lw
