### ISSUE TITLE
[HW] <Gokcan Cantali>

### ISSUE THREAD

**Issue by gokcantali** [datastaxdevs/workshop-introduction-to-nosql#157]
**Name:** Gökcan Çantalı
**Email:** gokcantali@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/g%C3%B6kcan-%C3%A7antal%C4%B1-aa31319a/

Attach the homework screenshots below:
-----------------------------------------

<img width="1280" alt="Screen Shot 2021-06-16 at 21 26 29" src="https://user-images.githubusercontent.com/11981221/122274681-7f1a5280-ceeb-11eb-9fd7-2418bf2b9843.png">

<img width="1273" alt="Screen Shot 2021-06-16 at 21 28 36" src="https://user-images.githubusercontent.com/11981221/122274776-9f4a1180-ceeb-11eb-86fa-0bad3291b712.png">

<img width="1280" alt="Screen Shot 2021-06-16 at 21 36 56" src="https://user-images.githubusercontent.com/11981221/122274799-a709b600-ceeb-11eb-9544-21a667dbb01f.png">

**Comment by RyanWelford** [comment]
Very nice! Thanks, Gökcan!

**Comment by gokcantali** [comment]
Thank you all for the nice workshop!

Could you tell me where I can claim my participation badge?
