### ISSUE TITLE
[HW] Sunny Kumar

### ISSUE THREAD

**Issue by kumarsunny0013** [datastaxdevs/workshop-introduction-to-nosql#159]
**Name:** Sunny Kumar
**Email:** kumarsunny0013@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/kumarsunny0013

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/29102607/122276078-0b377480-cf02-11eb-9e18-362d9b1ea88b.png)
![image](https://user-images.githubusercontent.com/29102607/122278943-1cce4b80-cf05-11eb-96ae-13f74a683af2.png)
![image](https://user-images.githubusercontent.com/29102607/122279204-6c147c00-cf05-11eb-911d-80815cb381e5.png)
![image](https://user-images.githubusercontent.com/29102607/122279249-76367a80-cf05-11eb-993a-4f8ca8b623f9.png)

![image](https://user-images.githubusercontent.com/29102607/122277060-1343e400-cf03-11eb-82b0-57808b5ae778.png)

**Comment by HadesArchitect** [comment]
Hey **Sunny Kumar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/WCJm9_0qQ3K_mbTwaKYICQ
