### ISSUE TITLE
[HW] Kaustubh Alandkar

### ISSUE THREAD

**Issue by kaustubh-26** [datastaxdevs/workshop-introduction-to-nosql#16]
**Name:** Kaustubh Alandkar
**Email:** kaustubhalandkar@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/kaustubhalandkar

Attach the homework screenshots below:
-----------------------------------------

![1](https://user-images.githubusercontent.com/26898285/117331832-c22ce300-aeb4-11eb-9e3f-61130ab041de.png)
![2](https://user-images.githubusercontent.com/26898285/117331846-c5c06a00-aeb4-11eb-8280-e376107ead93.png)
![3](https://user-images.githubusercontent.com/26898285/117331863-c8bb5a80-aeb4-11eb-9ad6-2dbde1ed394f.png)
![4](https://user-images.githubusercontent.com/26898285/117331869-cb1db480-aeb4-11eb-8a27-af60a1655904.png)
![5](https://user-images.githubusercontent.com/26898285/117331877-cd800e80-aeb4-11eb-8b6f-f7b334ad6358.png)
![6](https://user-images.githubusercontent.com/26898285/117331887-cfe26880-aeb4-11eb-9ed7-cc0d8d9d6428.png)
![7](https://user-images.githubusercontent.com/26898285/117331898-d244c280-aeb4-11eb-90d0-bc77d58ca520.png)
![8](https://user-images.githubusercontent.com/26898285/117331906-d53fb300-aeb4-11eb-9208-e90f5da8bd6c.png)
![9](https://user-images.githubusercontent.com/26898285/117331912-d7097680-aeb4-11eb-9501-805627b91295.png)
-- images removed by team --
![16](https://user-images.githubusercontent.com/26898285/117331951-e5579280-aeb4-11eb-8682-d94a38f43f81.png)
-- images removed by team --
![18](https://user-images.githubusercontent.com/26898285/117331975-ebe60a00-aeb4-11eb-9e2f-91bab14ce907.png)
![19](https://user-images.githubusercontent.com/26898285/117331985-ee486400-aeb4-11eb-811a-b07535348ec8.png)
![20](https://user-images.githubusercontent.com/26898285/117331992-f0aabe00-aeb4-11eb-988f-c0fc44a416d3.png)

**Comment by SonicDMG** [comment]
Looks good Kaustubh, thank you.

**Comment by kaustubh-a** [comment]
Thank you @SonicDMG for reviewing.

**Comment by SonicDMG** [comment]
:D

**Comment by HadesArchitect** [comment]
Great job! Here we go! https://api.badgr.io/public/assertions/HJ-ivjwtSI6lKOKlmy8f7w?identity__email=kaustubhalandkar%40gmail.com

**Comment by kaustubh-a** [comment]
Thanks Aleks and DataStax team! :)
