### ISSUE TITLE
[HW] Aaspad Kar

### ISSUE THREAD

**Issue by Aaspad14** [datastaxdevs/workshop-introduction-to-nosql#160]
**Name:** Aaspad Kar
**Email:** aaspadkar@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/aaspad-kar-a917431aa/
![HandsOn](https://user-images.githubusercontent.com/59948476/122278023-24412500-cf04-11eb-800e-05eff0ec99a6.png)
![Completed](https://user-images.githubusercontent.com/59948476/122278045-2a370600-cf04-11eb-93f5-71e5066bdb81.png)

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Thanks Aaspad!

**Comment by HadesArchitect** [comment]
Hey **Aaspad Kar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/8Ww-2i-DTDegUMkxx9VJ0A
