### ISSUE TITLE
[HW] <Anish Siva>

### ISSUE THREAD

**Issue by Tsg2201** [datastaxdevs/workshop-introduction-to-nosql#161]
**Name:** anish siva 
**Email:** <anish.siva2001@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/anish-siva-1091881a0
![Capture 2](https://user-images.githubusercontent.com/59708005/122284975-cc0e2100-cf0b-11eb-90b3-4fb5aee9a929.JPG)
![Capture 3](https://user-images.githubusercontent.com/59708005/122284984-cdd7e480-cf0b-11eb-8281-8bf63fe303c5.JPG)
![Capture 4](https://user-images.githubusercontent.com/59708005/122284988-ce707b00-cf0b-11eb-8972-5102fd2af520.JPG)
![Capture](https://user-images.githubusercontent.com/59708005/122284994-cf091180-cf0b-11eb-858a-c2ae19251d4a.JPG)

>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Thanks Anish! Can you add your name to the top, and we'll issue a badge!

**Comment by clun** [comment]
Here is your badge: https://api.badgr.io/public/assertions/1kpZiLH_Tc-tVkDFpqBytQ?identity__email=anish.siva2001%40gmail.com
