### ISSUE TITLE
[HW] <Miguel Meneses>

### ISSUE THREAD

**Issue by mvprm** [datastaxdevs/workshop-introduction-to-nosql#162]
**Name:** Miguel Meneses
**Email:** <miguel.vprmeneses22@gmail.com>
**Linkedin Profile:** linkedin.com/in/miguel-meneses

Attach the homework screenshots below:
-----------------------------------------

- Step IV

![image](https://user-images.githubusercontent.com/45074378/122296431-4cc02380-cef2-11eb-94d7-4c60f8473e61.png)

![image](https://user-images.githubusercontent.com/45074378/122296537-711c0000-cef2-11eb-95e9-0feb7a8b66f9.png)

![image](https://user-images.githubusercontent.com/45074378/122298426-a590bb80-cef4-11eb-8da2-ab6ffa86ad1c.png)

![image](https://user-images.githubusercontent.com/45074378/122297882-f48a2100-cef3-11eb-8fe3-1e25c73d99c0.png)

![image](https://user-images.githubusercontent.com/45074378/122297979-14214980-cef4-11eb-85bb-e906cba94444.png)

![image](https://user-images.githubusercontent.com/45074378/122298014-23a09280-cef4-11eb-97bd-bad9939e054c.png)

- Try It Out Workshop

![image](https://user-images.githubusercontent.com/45074378/122298745-091ae900-cef5-11eb-8769-75a2ee64002c.png)

![image](https://user-images.githubusercontent.com/45074378/122298790-133ce780-cef5-11eb-9db1-5245fc09021d.png)

![image](https://user-images.githubusercontent.com/45074378/122298818-1e901300-cef5-11eb-8e0e-99216c1666bc.png)

![image](https://user-images.githubusercontent.com/45074378/122298892-35cf0080-cef5-11eb-9c1e-bed279881070.png)

![image](https://user-images.githubusercontent.com/45074378/122298927-41222c00-cef5-11eb-9f66-28698d0fd720.png)

![image](https://user-images.githubusercontent.com/45074378/122298976-4f704800-cef5-11eb-9852-77010f42ed02.png)

![image](https://user-images.githubusercontent.com/45074378/122299011-5a2add00-cef5-11eb-8a64-7394d96c8f4e.png)

**Comment by RyanWelford** [comment]
Thanks, Miguel! Can you add your name to the form at the top, and we'll issue a badge!

**Comment by mvprm** [comment]
> Thanks, Miguel! Can you add your name to the form at the top, and we'll issue a badge!

Hello, I've already updated the form. Thanks for the workshop!

**Comment by clun** [comment]
Thank you here is your badge 
https://api.badgr.io/public/assertions/l7ByCkxhQHOW7pL9J8sNxg?identity__email=miguel.vprmeneses22%40gmail.com
