### ISSUE TITLE
Alexander Pepe

### ISSUE THREAD

**Issue by PepeAlex** [datastaxdevs/workshop-introduction-to-nosql#163]
**Name:** Alexander Pepe
**Email:** it.alexpepe@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<img width="1440" alt="Screenshot 2021-06-16 at 22 18 54" src="https://user-images.githubusercontent.com/47187507/122301394-8b58dc80-cef8-11eb-9c60-a2760031a097.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 19 33" src="https://user-images.githubusercontent.com/47187507/122301398-8c8a0980-cef8-11eb-80f2-247e27cb6b28.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 26 04" src="https://user-images.githubusercontent.com/47187507/122301401-8dbb3680-cef8-11eb-8986-21235817f75a.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 26 30" src="https://user-images.githubusercontent.com/47187507/122301407-8eec6380-cef8-11eb-9393-18a1b475aab2.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 27 18" src="https://user-images.githubusercontent.com/47187507/122301411-8f84fa00-cef8-11eb-8e3d-1976af2135a1.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 27 57" src="https://user-images.githubusercontent.com/47187507/122301419-914ebd80-cef8-11eb-8539-5d14a0675c9a.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 31 01" src="https://user-images.githubusercontent.com/47187507/122301424-93b11780-cef8-11eb-9f69-e3292f167893.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 32 53" src="https://user-images.githubusercontent.com/47187507/122301434-96137180-cef8-11eb-89a0-fe41a5e3c9e2.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 33 04" src="https://user-images.githubusercontent.com/47187507/122301445-9875cb80-cef8-11eb-843f-fd07fdced703.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 33 34" src="https://user-images.githubusercontent.com/47187507/122301451-9a3f8f00-cef8-11eb-9499-356635ace0bb.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 33 53" src="https://user-images.githubusercontent.com/47187507/122301455-9ca1e900-cef8-11eb-813e-47f92e7d9ca2.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 34 45" src="https://user-images.githubusercontent.com/47187507/122301469-9f9cd980-cef8-11eb-8442-2eccbf712421.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 38 17" src="https://user-images.githubusercontent.com/47187507/122301481-a1ff3380-cef8-11eb-940f-0ee9db5f47ff.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 39 37" src="https://user-images.githubusercontent.com/47187507/122301485-a4618d80-cef8-11eb-8424-bca5de2f3e5d.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 41 43" src="https://user-images.githubusercontent.com/47187507/122301488-a6c3e780-cef8-11eb-8ff1-ad81bd8adac8.png">
<img width="1440" alt="Screenshot 2021-06-16 at 22 58 22" src="https://user-images.githubusercontent.com/47187507/122301495-a9264180-cef8-11eb-8305-17df11a2e0a4.png">
<img width="1440" alt="Screenshot 2021-06-16 at 23 00 39" src="https://user-images.githubusercontent.com/47187507/122301501-aaf00500-cef8-11eb-9d7e-cb290159325d.png">
<img width="1440" alt="Screenshot 2021-06-16 at 23 01 32" src="https://user-images.githubusercontent.com/47187507/122301506-acb9c880-cef8-11eb-9f80-3110ff8ab2ba.png">
<img width="1440" alt="Screenshot 2021-06-16 at 23 04 56" src="https://user-images.githubusercontent.com/47187507/122301513-af1c2280-cef8-11eb-8135-c85d08e3ea56.png">
<img width="1440" alt="Screenshot 2021-06-16 at 23 05 14" src="https://user-images.githubusercontent.com/47187507/122301523-b0e5e600-cef8-11eb-8a31-a039fa13be9e.png">
<img width="1440" alt="Screenshot 2021-06-16 at 23 06 10" src="https://user-images.githubusercontent.com/47187507/122301530-b2afa980-cef8-11eb-8304-9ae72b9881d9.png">
<img width="1440" alt="Screenshot 2021-06-16 at 23 10 08" src="https://user-images.githubusercontent.com/47187507/122301534-b4796d00-cef8-11eb-8ce4-208993ae5429.png">
<img width="1440" alt="Screenshot 2021-06-16 at 23 10 33" src="https://user-images.githubusercontent.com/47187507/122301545-b6dbc700-cef8-11eb-9660-31b756c80f04.png">
<img width="1440" alt="Screenshot 2021-06-16 at 23 10 55" src="https://user-images.githubusercontent.com/47187507/122301553-b93e2100-cef8-11eb-9bfa-5ac9fe00c188.png">

**Comment by RyanWelford** [comment]
Thanks Alexander! Well done!

**Comment by HadesArchitect** [comment]
Hey **Alexander Pepe**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Ar_yDQfoR9mZfJGHL2ClKA
