### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by kH24762iEDj** [datastaxdevs/workshop-introduction-to-nosql#165]
**Name:** VENKATESHWARAN A
**Email:** 953618114080@ritrjpm.ac.in
**Linkedin Profile:** https://www.linkedin.com/in/venkateshwaran-a-2b261120b

Attach the homework screenshots below:

<SCREENSHOTS>

**Comment by kH24762iEDj** [comment]
Good

**Comment by clun** [comment]
Hello, can you try again to upload the images please ? Thank you
