### ISSUE TITLE
[HW] Divya Srivastav

### ISSUE THREAD

**Issue by divyasrivastav-stargirl** [datastaxdevs/workshop-introduction-to-nosql#167]
**Name:** Divya Srivastav
**Email:** divyasrivastav20@gmail.coml
**Linkedin Profile:** <www.linkedin.com/in/divya-srivastav-007047136

![Screenshot (17)](https://user-images.githubusercontent.com/72591668/122346240-5e431300-cf66-11eb-9f74-82f0d46bfa02.png)

![Screenshot (18)](https://user-images.githubusercontent.com/72591668/122346245-5f744000-cf66-11eb-90d5-79afca167a4a.png)

![Screenshot (19)](https://user-images.githubusercontent.com/72591668/122346247-600cd680-cf66-11eb-963e-a63209dbbdc6.png)

![Screenshot (20)](https://user-images.githubusercontent.com/72591668/122346249-600cd680-cf66-11eb-8c91-fb429eaf1422.png)

![Screenshot (21)](https://user-images.githubusercontent.com/72591668/122346251-60a56d00-cf66-11eb-8d27-75ad9a24e7be.png)

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Divya Srivastav**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/gqyVTOXSSdadD0JrWJ4gSA
