### ISSUE TITLE
[HW] Sanjay Sreedhar

### ISSUE THREAD

**Issue by sanjsree** [datastaxdevs/workshop-introduction-to-nosql#168]
**Name:** Sanjay Sreedhar
**Email:** sanjaysreedhar88@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sanjaysreedhar/

Attach the homework screenshots below:
-----------------------------------------

![assignment4-graphQL](https://user-images.githubusercontent.com/51818773/122346988-2f796c80-cf67-11eb-9df7-6a0599604f4f.png)
![scenario_completed](https://user-images.githubusercontent.com/51818773/122346994-30aa9980-cf67-11eb-879d-55b5a9343b75.png)
![try-it-out_CQL_1](https://user-images.githubusercontent.com/51818773/122346999-30aa9980-cf67-11eb-8b82-0fe7e921d97c.png)

**Comment by HadesArchitect** [comment]
Hey **Sanjay Sreedhar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/LGEuWhxGQ7CdIxnIFUWhsw
