### ISSUE TITLE
[HW] Deepak Singh

### ISSUE THREAD

**Issue by DeepZeppelin** [datastaxdevs/workshop-introduction-to-nosql#169]
**Name:** Deepak Singh
**Email:** dksingh531@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/deepaksingh531/

Attach the homework screenshots below:
-----------------------------------------
**1. Create Astra Db Instance**
![1  Create Astra Db Instance](https://user-images.githubusercontent.com/71369291/122356319-4cff0400-cf70-11eb-954d-18149fe43f59.jpg)

**2. Tabular Databases**
![2  Tabular Databases](https://user-images.githubusercontent.com/71369291/122356388-60aa6a80-cf70-11eb-8e3f-33e46609ebf2.jpg)

**3. Document Databases**
![3  Document Databases](https://user-images.githubusercontent.com/71369291/122356401-64d68800-cf70-11eb-8b19-f60c631a54ad.jpg)

**4. Key-Value Databases**
![4  Key-Value Databases](https://user-images.githubusercontent.com/71369291/122356420-6902a580-cf70-11eb-8cb7-1be98a0e8ad6.jpg)

**Cassandra Try-it-out Scenario**
![Cassandra try-it-out scenario](https://user-images.githubusercontent.com/71369291/122356431-6c962c80-cf70-11eb-8c3c-b3995d575c7a.jpg)

**Comment by HadesArchitect** [comment]
Hey **Deepak Singh**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/SnJa3MuCTJORbNcg3EF28A
