### ISSUE TITLE
[HW] Indu

### ISSUE THREAD

**Issue by indu-web** [datastaxdevs/workshop-introduction-to-nosql#17]
**Name:** Indumathi Vellingiri
**Email:**  indumca@gmail.com
**Linkedin Profile:**https://www.linkedin.com/in/indugiri/
Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/82413375/117365834-bc171200-ae74-11eb-84f2-de2ad25629b2.png)

![image](https://user-images.githubusercontent.com/82413375/117365940-ea94ed00-ae74-11eb-9b50-0d593a995dd3.png)

![image](https://user-images.githubusercontent.com/82413375/117366046-0dbf9c80-ae75-11eb-8cce-dc1d036a13e6.png)

![image](https://user-images.githubusercontent.com/82413375/117366130-2af46b00-ae75-11eb-8d7a-df6d423cd437.png)

-- images removed by team --

![image](https://user-images.githubusercontent.com/82413375/117365692-883bec80-ae74-11eb-923a-69b644da8797.png)

 ![image](https://user-images.githubusercontent.com/82413375/117365485-31361780-ae74-11eb-9cc7-43b59a3e6986.png)

**Comment by SonicDMG** [comment]
Hi Indu, everything looks good except your submission is missing the "try-it-out" scenario here -> https://www.datastax.com/try-it-out. Please complete that and add a screenshot.

**Comment by indu-web** [comment]
![image](https://user-images.githubusercontent.com/82413375/117886413-024ce680-b264-11eb-84e3-fc7f33579faa.png)

**Comment by SonicDMG** [comment]
Looks good Indu, thank you.

**Comment by HadesArchitect** [comment]
Great job! https://api.badgr.io/public/assertions/TLm3-QFwQAGbowGtgUY1Gg?identity__email=indumca%40gmail.com
