### ISSUE TITLE
[HW] Michel de Ru

### ISSUE THREAD

**Issue by michelderu** [datastaxdevs/workshop-introduction-to-nosql#170]
**Name:** Michel de Ru
**Email:** michel.deru@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/mderu/
<img width="1570" alt="Screenshot 2021-06-17 at 10 52 27" src="https://user-images.githubusercontent.com/14891355/122364591-2d5ce100-cf5a-11eb-94c2-556585118e20.png">
<img width="2554" alt="Screenshot 2021-06-17 at 10 50 51" src="https://user-images.githubusercontent.com/14891355/122364597-2e8e0e00-cf5a-11eb-90cf-404aca5adea3.png">
<img width="1347" alt="Screenshot 2021-06-17 at 10 50 29" src="https://user-images.githubusercontent.com/14891355/122364603-2fbf3b00-cf5a-11eb-9e96-608fdaaf3472.png">
<img width="2144" alt="Screenshot 2021-06-17 at 10 49 37" src="https://user-images.githubusercontent.com/14891355/122364605-3057d180-cf5a-11eb-9ac7-82e9c3178012.png">

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Michel de Ru**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/g_P_ol1dQfWgJtWu2RXDJQ
