### ISSUE TITLE
[HW] Shivaraj Deyannavar

### ISSUE THREAD

**Issue by shivubd** [datastaxdevs/workshop-introduction-to-nosql#172]
**Name:** Shivaraj Deyannavar
**Email:** <shivarajdeyannavar@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/shivaraj-deyannavar-47519b194/>

Attach the homework screenshots below:
-----------------------------------------

## **1. Created Astra DB instance (nosql_db_hw)**
![step1](https://user-images.githubusercontent.com/62126060/122386032-1387c200-cf8b-11eb-857e-0510449286eb.JPG)

## **2. Tabular Databases**
![step2](https://user-images.githubusercontent.com/62126060/122386213-48941480-cf8b-11eb-864d-305996192f12.JPG)

## **3. Document Databases**
![step3](https://user-images.githubusercontent.com/62126060/122386277-5ea1d500-cf8b-11eb-9826-f902feb9fa68.JPG)

## **4. Key-value Databases**
![step4](https://user-images.githubusercontent.com/62126060/122386394-78dbb300-cf8b-11eb-9720-3f059b6f04b8.JPG)

## **5. Completed CQL Try-it-out Scenario**
![tio8](https://user-images.githubusercontent.com/62126060/122386432-82fdb180-cf8b-11eb-8560-6fb7232cdb5f.JPG)

**Comment by clun** [comment]
Congratulations here is your badge
https://api.badgr.io/public/assertions/QZynwxuJTJOQ96M1zNSavQ?identity__email=shivarajdeyannavar%40gmail.com
