### ISSUE TITLE
[HW] Prasanna koyyada

### ISSUE THREAD

**Issue by prasannna16** [datastaxdevs/workshop-introduction-to-nosql#173]
**Name:** Prasanna koyyada
**Email:** Prasannakoyyada2001@outlook.com
**Linkedin Profile:** <https://www.linkedin.com/in/prasanna-koyyada-230006202>

Attach the homework screenshots below:
--------------------------

![Screenshot (202)](https://user-images.githubusercontent.com/86059928/122405152-6f5b4680-cf9d-11eb-9dbf-453ab7f2a832.png)

![Screenshot (203)](https://user-images.githubusercontent.com/86059928/122405187-771aeb00-cf9d-11eb-84cd-b265812d673e.png)

![Screenshot (204)](https://user-images.githubusercontent.com/86059928/122406585-95cdb180-cf9e-11eb-879a-5144b780f57f.png)

---------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Prasanna koyyada**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/3IjhkBkoRgmfPWkNocPrNg
