### ISSUE TITLE
[HW]  Valakatla Krishnaveni

### ISSUE THREAD

**Issue by krishnavenivalakatla** [datastaxdevs/workshop-introduction-to-nosql#174]
**Name:** Valakatla Krishnaveni
**Email:** Valakatlakrishnaveni28@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/krishnaveni-valakatla-b32425202>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Screenshot (202)](https://user-images.githubusercontent.com/86063783/122419955-efd37480-cfa8-11eb-812a-81ad82f3bbfa.png)

![Screenshot (206)](https://user-images.githubusercontent.com/86063783/122420064-02e64480-cfa9-11eb-86b3-bc6bdde4107c.png)

**Comment by HadesArchitect** [comment]
Hey **Valakatla Krishnaveni**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/K0bvy3DARwiyI77jyezPAg
