### ISSUE TITLE
[HW] Andrew Vu

### ISSUE THREAD

**Issue by dr3wvu** [datastaxdevs/workshop-introduction-to-nosql#175]
**Name:** Andrew Vu
**Email:** dr3wvu@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/andrew-vu00/

[NoSQL Workshop.docx](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/6671412/NoSQL.Workshop.docx)
>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Andrew Vu**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/DwF3Kb3rQP62u-NpUGyIlw
