### ISSUE TITLE
[HW] Geeta Dyumani Akella

### ISSUE THREAD

**Issue by geetady** [datastaxdevs/workshop-introduction-to-nosql#176]
**Name:** Geeta Dyumani Akella
**Email:** g.akella@louisvuitton.com
**Linkedin Profile:** www.linkedin.com/in/geeta-dyumani-akella-28b27761

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/84493707/122430151-ea385780-cfc5-11eb-9153-1eb52c92d3db.png)
![image](https://user-images.githubusercontent.com/84493707/122430604-561ac000-cfc6-11eb-9b52-aab79559b612.png)

**Comment by HadesArchitect** [comment]
Hey **Geeta Dyumani Akella**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/SD0SEguaRSyRRuuq3qnjeA

**Comment by geetady** [comment]
Hi Alex,
 In the workshop , I noticed we can earn a free voucher to get certified.
Can you guide me on how to qualify for this offer please.




Geeta Dyumani AKELLA| Database Administrator | Louis Vuitton| 5 Tampines Central 1, #02-01 Tampines Plaza, Singapore 529541 | Mob : +65 8484 7782 |Tel: + 65 6508 0988 | ***@***.******@***.***>

**Comment by SonicDMG** [comment]
Hey there Geeta, please reach out to jack.fryer@datastax.com to get help with your voucher.
