### ISSUE TITLE
[HW] Maria Fernandez Novella

### ISSUE THREAD

**Issue by mariafn7** [datastaxdevs/workshop-introduction-to-nosql#177]
**Name:** Maria Fernandez Novella
**Email:** mfernandeznovella@gmail.com

Attach the homework screenshots below:
-----------------------------------------
1) Create Astra Db Instance

![Final 1](https://user-images.githubusercontent.com/86066898/122429308-f525c480-cf92-11eb-8598-d05c701d3f6e.png)

2) Tabular databases

![Final 2](https://user-images.githubusercontent.com/86066898/122429479-1a1a3780-cf93-11eb-83b8-bd1e71d4a90e.png)

3) Document Databases

![Final 3](https://user-images.githubusercontent.com/86066898/122429652-3a49f680-cf93-11eb-9af2-5ae8018e1b84.png)

4) KeyValue Databases

![Final 4](https://user-images.githubusercontent.com/86066898/122432349-885ff980-cf95-11eb-8183-8d387a3a26c6.png)

5) Try it out scenario

![Try it out](https://user-images.githubusercontent.com/86066898/122429901-6c5b5880-cf93-11eb-9cf6-f2b2fea9d820.png)
-----------------------------------------

Yesterday, I attended live the "Introduction to NoSQL Databases" hands-on workshop and performed the exercises with you. Today, I complete the try it out the scenario for homework. I would like to know how to redeem the voucher that entitles me to take one of the DataStax certifications for the Apache Cassandra exam for free.

Thank you very much for the workshop. It was great!

**Comment by HadesArchitect** [comment]
Hey **Maria Fernandez Novella**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/tmtRRX3mSGG8TO8Mybyl4w

**Comment by clun** [comment]
Hey Maria, I have registered you for the next batch of vouchers!
