### ISSUE TITLE
[HW] Siddhesh Aher

### ISSUE THREAD

**Issue by SiddheshAher1** [datastaxdevs/workshop-introduction-to-nosql#178]
**Name:** Siddhesh Aher
**Email:** siddheshaher1@gmail.com
**Linkedin Profile:** <www.linkedin.com/in/siddhesh-aher-1b619a212>

Attach the homework screenshots below:
-----------------------------------------

<
![ss1](https://user-images.githubusercontent.com/44492970/122433342-c409bc00-cfb3-11eb-894e-a57ed52050ec.jpg)

![ss3](https://user-images.githubusercontent.com/44492970/122433381-cd932400-cfb3-11eb-9f6c-ebda228b5569.jpg)

![ss4](https://user-images.githubusercontent.com/44492970/122433416-d71c8c00-cfb3-11eb-8027-bbf4bb1b1fe2.jpg)

>

**Comment by HadesArchitect** [comment]
Hey **Siddhesh Aher**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/kblisD-4QS6IL3p-N57FpQ
