### ISSUE TITLE
[HW] Praveen Kumar G

### ISSUE THREAD

**Issue by praveen5889** [datastaxdevs/workshop-introduction-to-nosql#179]
**Name:** Praveen Kumar G
**Email:** praveen5889@gmail.com
**Linkedin Profile:** <linkedin.com/in/praveen-kumar-8067a7121>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Scenario1](https://user-images.githubusercontent.com/86070162/122434717-f962d980-cfb4-11eb-8bea-d6a7aa06d7f7.png)

![Graphql](https://user-images.githubusercontent.com/86070162/122434748-fec02400-cfb4-11eb-9cfe-64363752c648.PNG)

![P1](https://user-images.githubusercontent.com/86070162/122434786-07185f00-cfb5-11eb-83fc-7d1e16b8d9ef.png)

![P2](https://user-images.githubusercontent.com/86070162/122434811-0d0e4000-cfb5-11eb-8a8e-0e073dd0afb2.png)

![P3](https://user-images.githubusercontent.com/86070162/122434838-139cb780-cfb5-11eb-8026-6dfa8363cadd.png)

**Comment by HadesArchitect** [comment]
Hey **Praveen Kumar G**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/38vz3w9bQ-GQTe6QT4urrg

**Comment by praveen5889** [comment]
thank you guys!!
