### ISSUE TITLE
[HW] Akshit Mangotra

### ISSUE THREAD

**Issue by Akshit6828** [datastaxdevs/workshop-introduction-to-nosql#18]
**Name:** Akshit Mangotra
**Email:** akshitmangotra@gmail.com
**Linkedin Profile:** [Akshit-Mangotra][Akshit-Mangotra]

Attach the homework screenshots below:
-----------------------------------------
#### Please Note : 
* Here the **Read and Write Request** are not 0 initially as I was also practising hands-on during the workshop. So once again, I started from the beginning as during the webinar I couldn't take the screenshots. 😢 
* Hurray! I have practised the workshop twice.😄  

![Part1](https://user-images.githubusercontent.com/57808363/117385395-a4866a80-af02-11eb-8fed-553083c648c2.png)

### STEP 2 :
- Part 1: **2(d) Before ```tracing on;``` Output:**

![Part 2 1 Before Tracing](https://user-images.githubusercontent.com/57808363/117386216-1f9c5080-af04-11eb-8c16-8aad8cfff6c4.png)

- Part 2**2(d) After ```tracing off;``` Output:**

![Part 2 3 Tracing Done](https://user-images.githubusercontent.com/57808363/117386485-a3eed380-af04-11eb-8c99-bd0e430eccf2.png)

### STEP 3 :
- Part 1:  **3(e)  Output:**  

-- images removed by team --

- Part 2:  **3(f)  Output:** 

![Part 3f 2](https://user-images.githubusercontent.com/57808363/117386939-6fc7e280-af05-11eb-9455-bf24f3a3d712.png)
 
### STEP 4 :
- Part 1:  **4(b)  Output on Playground:**  

-- images removed by team --

- Part 2:  **4(c)  Output on Playground:**  

-- images removed by team --

### Cassandra Query Language (CQL) scenario completed screenshot :

![Congratulations part](https://user-images.githubusercontent.com/57808363/117388064-a56dcb00-af07-11eb-8eb1-0c2e774998a9.png)

@clun  Please check my homework and let me know if any alterations are needed.

[Akshit-Mangotra]:https://www.linkedin.com/in/akshit-mangotra/

**Comment by SonicDMG** [comment]
Ok, thank you for your submission Akshit.

**Comment by Akshit6828** [comment]
Thanks, @SonicDMG for validation. 😄

**Comment by HadesArchitect** [comment]
Here we go: https://api.badgr.io/public/assertions/ugyG1zbITbijEgov7NKNMQ?identity__email=akshitmangotra%40gmail.com
