### ISSUE TITLE
[HW] Huzefa Rangwala

### ISSUE THREAD

**Issue by huzee9** [datastaxdevs/workshop-introduction-to-nosql#180]
**Name:** Huzefa Rangwala
**Email:** huzee.rangwala@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/huzefa-rangwala-84916355/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
practice steps

![image](https://user-images.githubusercontent.com/33800624/122437732-9b83c100-cfb7-11eb-966d-cccd4acd3979.png)

![image](https://user-images.githubusercontent.com/33800624/122438460-5dd36800-cfb8-11eb-8d72-1c466f0cb340.png)

![image](https://user-images.githubusercontent.com/33800624/122438698-9a9f5f00-cfb8-11eb-8b32-1213359c6225.png)

![image](https://user-images.githubusercontent.com/33800624/122438924-d4706580-cfb8-11eb-92b1-a7f40aa854a6.png)

Try it our scenario

![image](https://user-images.githubusercontent.com/33800624/122437484-624b5100-cfb7-11eb-89f8-8484e53a94d6.png)

**Comment by HadesArchitect** [comment]
Hey **Huzefa Rangwala**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/W9RtbSCRQ9WpkJSlgElaiw
