### ISSUE TITLE
[HW] Arjun

### ISSUE THREAD

**Issue by arjunm385** [datastaxdevs/workshop-introduction-to-nosql#181]
**Name:** Arjun
**Email:** arjunm385@gmail.com
**Linkedin Profile:** www.linkedin.com/in/arjun-501508141

Attach the homework screenshots below:
-----------------------------------------

![1](https://user-images.githubusercontent.com/86074282/122448201-236ec880-cfc2-11eb-91cf-3f1a036e40ad.jpg)

![2](https://user-images.githubusercontent.com/86074282/122448219-27024f80-cfc2-11eb-8ec6-706801486fc8.jpg)

![3](https://user-images.githubusercontent.com/86074282/122448226-28cc1300-cfc2-11eb-96bd-956da19a4040.jpg)

**Comment by HadesArchitect** [comment]
Hey **Arjun**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/iYjp9ejdQwOeobUS-iQ7uQ
