### ISSUE TITLE
[HW] Gabriel Francis

### ISSUE THREAD

**Issue by GabrielDaKing** [datastaxdevs/workshop-introduction-to-nosql#182]
**Name:** Gabriel Francis
**Email:** gncis8@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/gabriel-francis/

Just wanted to mention I wasn't able to do step 5 as the container ran into some sort of memory leak error and kept crashing.

Attach the homework screenshots below:
-----------------------------------------

![step4](https://user-images.githubusercontent.com/34449228/122448527-78aada00-cfc2-11eb-9d39-a02433fc4a46.jpg)
![scenario](https://user-images.githubusercontent.com/34449228/122448531-7b0d3400-cfc2-11eb-8e81-521b99924352.jpg)

**Comment by HadesArchitect** [comment]
Hey **Gabriel Francis**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/_LUn3cN6QKawmTWDaSXj5A

**Comment by clun** [comment]
For the container error yes you need to allow a minimum of 3GB of memory in the docker engine to make it work

**Comment by GabrielDaKing** [comment]
Ohhh okay thank you. I will give it another shot.
