### ISSUE TITLE
[HW] Aditi Anup

### ISSUE THREAD

**Issue by AditiAnup** [datastaxdevs/workshop-introduction-to-nosql#183]
**Name:** Aditi Anup
**Email:** aditianup242@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/aditi-anup-47a142161/

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/37284834/122442212-f4555880-cfbb-11eb-84d7-7ac994ee69de.png)
![image](https://user-images.githubusercontent.com/37284834/122445232-f7057d00-cfbe-11eb-8ca3-b68ffabf1613.png)
![image](https://user-images.githubusercontent.com/37284834/122445704-6d09e400-cfbf-11eb-8804-285d2dd7758e.png)
![image](https://user-images.githubusercontent.com/37284834/122445977-c40fb900-cfbf-11eb-81b8-f2961d73d8c6.png)
![image](https://user-images.githubusercontent.com/37284834/122446144-f5888480-cfbf-11eb-8b32-ed6b088e42c4.png)
![image](https://user-images.githubusercontent.com/37284834/122446248-1355e980-cfc0-11eb-97d0-f54fe48837a7.png)
![image](https://user-images.githubusercontent.com/37284834/122447282-3503a080-cfc1-11eb-864c-b2808abbe202.png)
![image](https://user-images.githubusercontent.com/37284834/122447529-74ca8800-cfc1-11eb-86aa-8ccca67287ff.png)
![image](https://user-images.githubusercontent.com/37284834/122447692-9f1c4580-cfc1-11eb-9cec-c200eed92546.png)
![image](https://user-images.githubusercontent.com/37284834/122448424-5f099280-cfc2-11eb-97cc-cd8724abf53b.png)
![image](https://user-images.githubusercontent.com/37284834/122448459-6630a080-cfc2-11eb-89f6-4392ad43fbee.png)

**Comment by HadesArchitect** [comment]
Hey **Aditi Anup**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ItrbuXVQSCWB6HKDv2V0Lw
