### ISSUE TITLE
[HW] Dhruv Mankad

### ISSUE THREAD

**Issue by dhruvhm** [datastaxdevs/workshop-introduction-to-nosql#184]
**Name:** Dhruv Mankad
**Email:** mankad1dhruv@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/dhruv-mankad/>

Attach the homework screenshots below:
-----------------------------------------
![Screenshot 2021-06-17 at 23-30-54 Swagger UI](https://user-images.githubusercontent.com/82724807/122450452-a5f88780-cfc4-11eb-9e0d-3124578451e4.png)
![Screenshot 2021-06-17 at 23-30-24 Swagger UI](https://user-images.githubusercontent.com/82724807/122450457-a729b480-cfc4-11eb-9a78-0ad533b3f07c.png)
![Screenshot 2021-06-17 at 23-30-05 Manage Database — DataStax Astra](https://user-images.githubusercontent.com/82724807/122450459-a7c24b00-cfc4-11eb-9f33-538e4231cc7a.png)
![try-it-out](https://user-images.githubusercontent.com/82724807/122450463-a7c24b00-cfc4-11eb-9b18-d3f1ab8e105d.jpg)
![Screenshot 2021-06-17 at 23-32-24 Swagger UI](https://user-images.githubusercontent.com/82724807/122450471-a8f37800-cfc4-11eb-9666-6df50905d823.png)
![Screenshot 2021-06-17 at 23-32-03 Swagger UI](https://user-images.githubusercontent.com/82724807/122450475-a8f37800-cfc4-11eb-9769-142b16c34343.png)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Dhruv Mankad**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/79Uc8BvlTtGL5hFLyJKP8Q
