### ISSUE TITLE
[HW] Sumanth Sundaramurthy

### ISSUE THREAD

**Issue by Sumanth23** [datastaxdevs/workshop-introduction-to-nosql#185]
**Name:** Sumanth Sundaramurthy
**Email:** sumanth.rsm@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/sumanth-sundaramurthy/>

Attach the homework screenshots below:
-----------------------------------------
<![Intro to NoSQL - DataStax (Sumanth)](https://user-images.githubusercontent.com/23018715/122451460-cd038900-cfc5-11eb-90a0-aadf608812d1.jpg)>

**Comment by Sumanth23** [comment]
Name - Sumanth Sundaramurthy

**Comment by HadesArchitect** [comment]
Hey **Sumanth Sundaramurthy**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Q1_xODXZRl23dCvexqlozQ
