### ISSUE TITLE
[HW] Zied Triki

### ISSUE THREAD

**Issue by ZiedTrikiDataScience** [datastaxdevs/workshop-introduction-to-nosql#186]
**Name:** Zied Triki
**Email:** triki.zied.aiesec@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/zied-triki-data-science/>

Attach the homework screenshots below:
-----------------------------------------
[Screenshots Intro to NOSQL Databases Homework Zied Triki.docx](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/6672413/Screenshots.Intro.to.NOSQL.Databases.Homework.Zied.Triki.docx)

**Comment by clun** [comment]
Great Job !

**Comment by HadesArchitect** [comment]
Hey **Zied Triki**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/AiFoaGTvShai-869u-Zp4w
