### ISSUE TITLE
[HW] Eka Sehyanto Ginting

### ISSUE THREAD

**Issue by eginting** [datastaxdevs/workshop-introduction-to-nosql#187]
**Name:** Eka Sehyanto Ginting
**Email:** e.ginting72@yahoo.com
**Linkedin Profile:** <https://www.linkedin.com/in/eka-sehyanto-ginting-3abaa6b1/>

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/86075535/122453065-3a092580-cfaa-11eb-87c3-68c1625d4451.png)

![image](https://user-images.githubusercontent.com/86075535/122453164-57d68a80-cfaa-11eb-8a08-eb3a1b8524cb.png)

**Comment by HadesArchitect** [comment]
Hey **Eka Sehyanto Ginting**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/vlBpZcy-S6CRMHNYd6NIxA
