### ISSUE TITLE
[HW] Kishan Vekariya

### ISSUE THREAD

**Issue by kiishn** [datastaxdevs/workshop-introduction-to-nosql#188]
**Name:** Kishan Vekariya
**Email:** Kishan.vekariya.1111@gmail.com
**Linkedin Profile:** http://linkedin.com/in/kishan-vekariya-77b353181

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
<img width="1552" alt="Screenshot 2021-06-17 at 11 57 29 PM" src="https://user-images.githubusercontent.com/85682323/122453902-59af4680-cfc8-11eb-9bfe-b3e427fcee3f.png">
<img width="1552" alt="Screenshot 2021-06-17 at 11 45 08 PM" src="https://user-images.githubusercontent.com/85682323/122453919-5f0c9100-cfc8-11eb-9ea2-a4677db3be3c.png">

**Comment by HadesArchitect** [comment]
Hey **Kishan Vekariya**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/DBKI-6DTQjyixu4xgr9DkQ
