### ISSUE TITLE
[HW] Keshava M M

### ISSUE THREAD

**Issue by keshavamm1** [datastaxdevs/workshop-introduction-to-nosql#189]
**Name:** Keshava M M
**Email:** keshavamm1@yahoo.com
**Linkedin Profile:** <linkedin.com/in/keshava-m-m-36a19a181>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
<img width="952" alt="step 4" src="https://user-images.githubusercontent.com/86076518/122455081-a47d8e00-cfc9-11eb-97f9-92a76b56fc32.PNG">
<img width="947" alt="try it out" src="https://user-images.githubusercontent.com/86076518/122455085-a6475180-cfc9-11eb-942a-a20f0b02213a.PNG">

**Comment by HadesArchitect** [comment]
Hey **Keshava M M**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/xi6ZxHhXTZunKgvNE-z5BA
