### ISSUE TITLE
[HW] Subha Ranjan Das

### ISSUE THREAD

**Issue by Subha-Ranjan-Das** [datastaxdevs/workshop-introduction-to-nosql#190]
**Name:** Subha Ranjan Das
**Email:** subhadas201201@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------
![Screenshot (66)](https://user-images.githubusercontent.com/86057597/122456770-8add4600-cfcb-11eb-9c37-fa2e26a2ff3b.png)

<SCREENSHOTS>
![Screenshot (67)](https://user-images.githubusercontent.com/86057597/122456365-17d3cf80-cfcb-11eb-91d1-1bef15b4d9b1.png)

**Comment by HadesArchitect** [comment]
Hey **Subha Ranjan Das**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/GFKgDyfpTmidD-S3kZoFVA
