### ISSUE TITLE
[HW] Zoe Gin

### ISSUE THREAD

**Issue by d1819** [datastaxdevs/workshop-introduction-to-nosql#191]
**Name:** Zoe Gin
**Email:** zoeyy.gn@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/zoe-g-900104194

Attach the homework screenshots below:
-----------------------------------------

<img width="675" alt="PartIV_CQL" src="https://user-images.githubusercontent.com/86076382/122456179-3f9b4700-cf7b-11eb-8a76-719e42366549.PNG">
<img width="957" alt="PartIV_GraphQL" src="https://user-images.githubusercontent.com/86076382/122456184-4033dd80-cf7b-11eb-9804-9a8933a5fb05.PNG">
<img width="952" alt="Scenario_completed" src="https://user-images.githubusercontent.com/86076382/122456340-6f4a4f00-cf7b-11eb-949c-a8b2c6166e70.PNG">

**Comment by HadesArchitect** [comment]
Hey **Zoe Gin**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/70P4Egn_QY2YZKx2eu_p2Q
