### ISSUE TITLE
[HW] Sanjeev Deo

### ISSUE THREAD

**Issue by sanjeevdeo** [datastaxdevs/workshop-introduction-to-nosql#192]
**Name:** Sanjeev Deo
**Email:** get.sanjeevdeo@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sanjeevdeo/

Attach the homework screenshots below:
-----------------------------------------
Step IV Completed:

![Step4-1](https://user-images.githubusercontent.com/17996181/122458834-5a65ce00-d004-11eb-9b44-4d9559a4494a.png)
![Step4-2](https://user-images.githubusercontent.com/17996181/122458865-62257280-d004-11eb-8d0d-b39ad647537e.png)

Try-it-out scenario Completed:
![Try](https://user-images.githubusercontent.com/17996181/122458984-85502200-d004-11eb-97af-f6ea172dd0ae.png)

**Comment by HadesArchitect** [comment]
Hey **Sanjeev Deo**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/FqqHxHq1S-eHlJA1alqBfA
