### ISSUE TITLE
[HW] Sushmita Kolhapurkar

### ISSUE THREAD

**Issue by sushmita-kolhapurkar** [datastaxdevs/workshop-introduction-to-nosql#193]
**Name:** Sushmita Kolhapurkar
**Email:** sushmita.developer@gmail.com
**Linkedin Profile:** <https://in.linkedin.com/in/sushmita-kolhapurkar-0a753311>

Attach the homework screenshots below:
-----------------------------------------

![a](https://user-images.githubusercontent.com/61219016/122461835-dcf97980-cf81-11eb-95c9-d87242f9a5fc.png)

**Comment by HadesArchitect** [comment]
Hey **Sushmita Kolhapurkar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/VhAqf86aRsyA6cub-_qjDQ
