### ISSUE TITLE
[HW] Nikhil Bachani

### ISSUE THREAD

**Issue by nikhilbachani** [datastaxdevs/workshop-introduction-to-nosql#194]
**Name:** Nikhil Bachani
**Email:** nikhilbachani25@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nikhilbachani/

Attach the homework screenshots below:
-----------------------------------------
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/37011200/122477267-11eae800-cfe5-11eb-9b2f-bb7dea3ab48f.png">
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/37011200/122477279-16af9c00-cfe5-11eb-93b6-2408eeeb02e7.png">
<img width="1440" alt="3" src="https://user-images.githubusercontent.com/37011200/122477287-17e0c900-cfe5-11eb-8d77-8bfcd3f75e12.png">

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Nikhil Bachani**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/j6n6aBvdSZmiJmQZn9Ef3w
