### ISSUE TITLE
[HW] Naveen A

### ISSUE THREAD

**Issue by hellohell258** [datastaxdevs/workshop-introduction-to-nosql#195]
**Name:** Naveen A
**Email:** naveenanand023@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/naveen-a-97554b1a2>

Attach the homework screenshots below:
-----------------------------------------

<
![Screenshot 2021-06-18 at 10 43 58 AM](https://user-images.githubusercontent.com/61055288/122511684-41b9e000-d025-11eb-9747-578911fcffe0.png)
>

**Comment by hellohell258** [comment]
It was a nice session thank you

**Comment by HadesArchitect** [comment]
Hey **Naveen A**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/dZ1FAHpqS06L7qhuxTYZbQ
