### ISSUE TITLE
[HW] Rounak Tadvi

### ISSUE THREAD

**Issue by RounakTadvi** [datastaxdevs/workshop-introduction-to-nosql#196]
**Name:** Rounak Tadvi
**Email:** rounaktadvi786@gmail.com
**Linkedin Profile:** www.linkedin.com/in/rounaktadvi/

Attach the homework screenshots below:
-------------------------------------
![Screenshot 2021-06-18 at 1 12 52 PM](https://user-images.githubusercontent.com/38634459/122558795-1d2d2a80-d05c-11eb-9831-3a952f951677.png)
![Screenshot 2021-06-18 at 4 23 34 PM](https://user-images.githubusercontent.com/38634459/122558800-1e5e5780-d05c-11eb-8ca9-b044ea30ad68.png)
----

![Screenshot 2021-06-18 at 1 03 05 PM](https://user-images.githubusercontent.com/38634459/122558784-1a323a00-d05c-11eb-8cea-1a2857dc1494.png)
![Screenshot 2021-06-18 at 1 03 39 PM](https://user-images.githubusercontent.com/38634459/122559044-6ed5b500-d05c-11eb-83d9-1a0b588ca5a5.png)

**Comment by clun** [comment]
Thank you Rounak for your attendance and your questions. Hope to see you in the next sessions. 👍
