### ISSUE TITLE
[HW] Angelika Zygmunt 

### ISSUE THREAD

**Issue by faraday-crypto** [datastaxdevs/workshop-introduction-to-nosql#197]
**Name:** Angelika Zygmunt
**Email:** zygmuntange@gmail.com
**Linkedin Profile:** <LINK> linkedin.com/in/angelika-z-1029671b6

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
1
![imagen](https://user-images.githubusercontent.com/84669673/122453202-6329b600-cfaa-11eb-8316-51c5e31a9544.png)
2a
![imagen](https://user-images.githubusercontent.com/84669673/122453406-9ec48000-cfaa-11eb-9d9f-a359ba012dbc.png)
2b
![imagen](https://user-images.githubusercontent.com/84669673/122453452-ac7a0580-cfaa-11eb-9db7-5faf908e34b0.png)
![imagen](https://user-images.githubusercontent.com/84669673/122453503-b996f480-cfaa-11eb-92e0-f77c63e5a0ea.png)
2c
![imagen](https://user-images.githubusercontent.com/84669673/122453544-c7e51080-cfaa-11eb-9331-c8f278ea001e.png)
![imagen](https://user-images.githubusercontent.com/84669673/122453583-d2070f00-cfaa-11eb-86b4-58eaba574383.png)
![imagen](https://user-images.githubusercontent.com/84669673/122453647-dc290d80-cfaa-11eb-8840-1c34de615e10.png)
2d
![imagen](https://user-images.githubusercontent.com/84669673/122453820-eb0fc000-cfaa-11eb-8438-b4bbd44368bc.png)
![imagen](https://user-images.githubusercontent.com/84669673/122453890-01b61700-cfab-11eb-9df5-067a06536a72.png)
![imagen](https://user-images.githubusercontent.com/84669673/122454042-32964c00-cfab-11eb-8bbb-44add4657e05.png)
3a
![imagen](https://user-images.githubusercontent.com/84669673/122454162-5e193680-cfab-11eb-8b4c-02d235f9a5db.png)
![imagen](https://user-images.githubusercontent.com/84669673/122454196-683b3500-cfab-11eb-9d78-228fb27a6339.png)
3b

![imagen](https://user-images.githubusercontent.com/84669673/122454396-a20c3b80-cfab-11eb-8834-583b7f0f71e5.png)

3c

![imagen](https://user-images.githubusercontent.com/84669673/122447615-38d4fa00-cfa4-11eb-856b-8cb6b8a491ef.png)

3d

![imagen](https://user-images.githubusercontent.com/84669673/122448097-b26ce800-cfa4-11eb-974c-acd179ebfe57.png)
3e

![imagen](https://user-images.githubusercontent.com/84669673/122447866-78034b00-cfa4-11eb-9369-b6bbb5d52850.png)

3f

![imagen](https://user-images.githubusercontent.com/84669673/122448548-28714f00-cfa5-11eb-9874-4f85be8efab9.png)

3g

![imagen](https://user-images.githubusercontent.com/84669673/122448602-36bf6b00-cfa5-11eb-887d-83976b116e95.png)

4b

![imagen](https://user-images.githubusercontent.com/84669673/122451472-789de080-cfa8-11eb-958c-6a20baa33a4c.png)

![imagen](https://user-images.githubusercontent.com/84669673/122451603-a4b96180-cfa8-11eb-82df-eb85eeea762d.png)
4c
![imagen](https://user-images.githubusercontent.com/84669673/122452131-36c16a00-cfa9-11eb-9bc9-11aa5ee64b7a.png)
![imagen](https://user-images.githubusercontent.com/84669673/122452195-4a6cd080-cfa9-11eb-9f6f-3c2cd938808c.png)
![imagen](https://user-images.githubusercontent.com/84669673/122453001-29f14600-cfaa-11eb-8b33-1c6468905746.png)
![imagen](https://user-images.githubusercontent.com/84669673/122453018-2eb5fa00-cfaa-11eb-8b36-8a21b156ef0c.png)

**Comment by HadesArchitect** [comment]
Hey **Angelika Zygmunt**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Xi0TuZT_T6y38xUBn8eWBg
