### ISSUE TITLE
[HW] Shivangi Saxena

### ISSUE THREAD

**Issue by shivangisaxena16** [datastaxdevs/workshop-introduction-to-nosql#198]
**Name:** Shivangi Saxena
**Email:** shivangisaxena034@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/shivangi-saxena-815012194/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

### **Create Astra Db Instance**

![2021-06-17 (1)](https://user-images.githubusercontent.com/82510951/122553957-2e8b1e00-cfed-11eb-8be5-368ede5a7206.png)

**Tabular databases**

![2021-06-17 (2)](https://user-images.githubusercontent.com/82510951/122554140-7447e680-cfed-11eb-96ed-697405beea98.png)
![2021-06-17 (3)](https://user-images.githubusercontent.com/82510951/122554154-77db6d80-cfed-11eb-8b23-ca5315c1a25d.png)

### **Document Databases**

**_Cassandra knows JSON_** 

![2021-06-17 (3)](https://user-images.githubusercontent.com/82510951/122554447-db659b00-cfed-11eb-9499-763d11b1be29.png)

**_Create your Application token_** 

![2021-06-17 (6)](https://user-images.githubusercontent.com/82510951/122554590-0cde6680-cfee-11eb-94a2-883fbc8c0763.png)
![2021-06-17 (7)](https://user-images.githubusercontent.com/82510951/122554603-1071ed80-cfee-11eb-9a8b-dc50f2fee056.png)
![2021-06-17 (8)](https://user-images.githubusercontent.com/82510951/122554613-136cde00-cfee-11eb-9500-42c20da1dce3.png)
![2021-06-17 (9)](https://user-images.githubusercontent.com/82510951/122554618-15cf3800-cfee-11eb-98b0-a645aa118f6f.png)

### **KeyValue Databases**

**_Create a table with GraphQL_**

![2021-06-18](https://user-images.githubusercontent.com/82510951/122554868-5c249700-cfee-11eb-9d84-04057856c692.png)

**_Populate the table_**

![2021-06-18(9)](https://user-images.githubusercontent.com/82510951/122566821-d5c38180-cffc-11eb-81d8-36b180849ba2.png)

**Comment by HadesArchitect** [comment]
Hey **Shivangi Saxena**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/V2mJzZBUSz2xmukagVwaUw
