### ISSUE TITLE
[HW] Karthikeyan P

### ISSUE THREAD

**Issue by karthikeyanp1985** [datastaxdevs/workshop-introduction-to-nosql#199]
**Name:** Karthikeyan P
**Email:** KARTHIK.JAVA@GMAIL.COM
**Linkedin Profile:** <https://www.linkedin.com/in/karthikeyan-parthasarathy-68b11196/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![nosql_stepIV Screenshot](https://user-images.githubusercontent.com/86114735/122570989-e4944d80-d069-11eb-9c9f-cd119d50e8d6.PNG)

![3G](https://user-images.githubusercontent.com/86114735/122570994-e6f6a780-d069-11eb-9c12-d22f8619cd1c.PNG)

![3F](https://user-images.githubusercontent.com/86114735/122570996-e6f6a780-d069-11eb-806a-9de99a70fa76.PNG)

![3E](https://user-images.githubusercontent.com/86114735/122571000-e78f3e00-d069-11eb-9f5e-de87c66a5989.PNG)

**Comment by HadesArchitect** [comment]
Hey **Karthikeyan P**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/QUIIP8szQAe4Gbgo2TnKjA
