### ISSUE TITLE
[HW]  Amisha Sahu

### ISSUE THREAD

**Issue by Amisha328** [datastaxdevs/workshop-introduction-to-nosql#20]
**Name:** Amisha Sahu
**Email:** amishasahu328@gmail.com
**Linkedin Profile:**  [Amisha-Sahu][Amisha-Sahu]

Attach the homework screenshots below:
-----------------------------------------
### Part 1 :
![part 1](https://user-images.githubusercontent.com/58816552/117397943-e58a7900-af1a-11eb-93f7-558c754a7f74.png)

### Part 2:
![part 2 1](https://user-images.githubusercontent.com/58816552/117397987-f9ce7600-af1a-11eb-95ef-6bf3ee6108ff.png)
![part 2 3](https://user-images.githubusercontent.com/58816552/117398015-00f58400-af1b-11eb-97e9-114afe0c8c8b.png)

### Part 3:
![part 3 1](https://user-images.githubusercontent.com/58816552/117398053-15398100-af1b-11eb-9800-e59a7b39f4a4.png)
-- images removed by team --

### Part 4:
-- images removed by team --

### Cassandra Query Language (CQL) : 
![final](https://user-images.githubusercontent.com/58816552/117398145-5762c280-af1b-11eb-9503-5eebf9523232.png)

<SCREENSHOTS>

[Amisha-Sahu]: https://www.linkedin.com/in/amisha-sahu/

**Comment by Amisha328** [comment]
Thank You for accepting my work @SonicDMG

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/cIHyhR3KQaSlJworIyWcig?identity__email=amishasahu328%40gmail.com

**Comment by HadesArchitect** [comment]
Well done!

**Comment by Amisha328** [comment]
Thanks a lot!
