### ISSUE TITLE
[HW] Prerna Padhee

### ISSUE THREAD

**Issue by PrernaPadhee** [datastaxdevs/workshop-introduction-to-nosql#200]
**Name:** Prerna Padhee
**Email:** prernapadhee@hotmail.com
**Linkedin Profile:** https://www.linkedin.com/in/prerna-padhee-a887a2141/

Attach the homework screenshots below:
-----------------------------------------
<img width="960" alt="CQL_Console" src="https://user-images.githubusercontent.com/29208607/122634589-a2681c00-d0fc-11eb-869a-0d14294b21e7.png">
<img width="960" alt="scenario" src="https://user-images.githubusercontent.com/29208607/122634594-aa27c080-d0fc-11eb-8d34-74c4163325a3.png">

**Comment by HadesArchitect** [comment]
Hey **Prerna Padhee**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/YasiNIv2TY6VCu_EaMuS8w
