### ISSUE TITLE
[HW] Anish Siva

### ISSUE THREAD

**Issue by Tsg2201** [datastaxdevs/workshop-introduction-to-nosql#201]
**Name:** Anish Siva 
**Email:** anish.siva2001@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/anish-siva-1091881a0

![Capture 2](https://user-images.githubusercontent.com/59708005/122637550-f7139300-d10c-11eb-95ae-7b9fd63e61e1.JPG)

![Capture 3](https://user-images.githubusercontent.com/59708005/122637551-f8dd5680-d10c-11eb-9998-447f925af7df.JPG)

![Capture 4](https://user-images.githubusercontent.com/59708005/122637552-f975ed00-d10c-11eb-9588-91aace272c58.JPG)

![Capture](https://user-images.githubusercontent.com/59708005/122637553-fa0e8380-d10c-11eb-9c25-d2a27ff61628.JPG)

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Anish Siva**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/hXmhVAXlREq4oaMGffpuIA
