### ISSUE TITLE
[HW] Rupam Mukherjee

### ISSUE THREAD

**Issue by RupamMukherjee** [datastaxdevs/workshop-introduction-to-nosql#202]
**Name:** Rupam Mukherjee
**Email:** rupammukherji1997@yahoo.com
**Linkedin Profile:** www.linkedin.com/in/rupam-mukherjee15497

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Step IV Key-Value databases(4c  Populating the Table) SS3](https://user-images.githubusercontent.com/46292971/122641102-bcb3f100-d120-11eb-8aac-96e1d17d65a9.png)

![Step IV Key-Value databases(4c  Populating the Table) SS4](https://user-images.githubusercontent.com/46292971/122641105-bde51e00-d120-11eb-8e55-13b4c8009a4d.png)

![Try-It-Out Scenario SS](https://user-images.githubusercontent.com/46292971/122641106-be7db480-d120-11eb-83ee-0c1afa06861b.png)

![Step IV Key-Value databases(4c  Populating the Table) SS1](https://user-images.githubusercontent.com/46292971/122641107-bf164b00-d120-11eb-8e66-81e721092bc1.png)

![Step IV Key-Value databases(4c  Populating the Table) SS2](https://user-images.githubusercontent.com/46292971/122641108-bf164b00-d120-11eb-9fc4-833087667d13.png)

**Comment by HadesArchitect** [comment]
Hey **Rupam Mukherjee**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/dg5p73NNQ0yrh4gbnWZvMg
