### ISSUE TITLE
[HW] Sedef Çakmak

### ISSUE THREAD

**Issue by sedefcakmak** [datastaxdevs/workshop-introduction-to-nosql#204]
**Name:** Sedef Çakmak
**Email:** scakmak19@ku.edu.tr
**Linkedin Profile:** www.linkedin.com/in/sedef-çakmak-372a69199

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![image](https://user-images.githubusercontent.com/86186809/122671023-6c469d00-d1cd-11eb-8aa4-43ccb8511fe5.png)
![image](https://user-images.githubusercontent.com/86186809/122671040-7e284000-d1cd-11eb-8580-322dc92e5e8e.png)
![image](https://user-images.githubusercontent.com/86186809/122671095-c3e50880-d1cd-11eb-85de-5db7b2a57a6d.png)

![image](https://user-images.githubusercontent.com/86186809/122671108-cfd0ca80-d1cd-11eb-88f9-c8bc5d6c3b1c.png)

![image](https://user-images.githubusercontent.com/86186809/122671119-dbbc8c80-d1cd-11eb-8100-52c48a18c3fa.png)

![image](https://user-images.githubusercontent.com/86186809/122671135-eb3bd580-d1cd-11eb-838d-3f91a55382f7.png)

![image](https://user-images.githubusercontent.com/86186809/122671149-f858c480-d1cd-11eb-894e-d3700283e5b1.png)

**Comment by RyanWelford** [comment]
Thanks Sedef!

**Comment by SonicDMG** [comment]
Here's your badge, nice job. https://api.badgr.io/public/assertions/d8kpVixaSb-Y5TzlQCNymw?identity__email=scakmak19%40ku.edu.tr
