### ISSUE TITLE
[HW] Zenab Habib

### ISSUE THREAD

**Issue by zenzensen** [datastaxdevs/workshop-introduction-to-nosql#205]
**Name:** Zenab Habib
**Email:** zenhabib3@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/zenab-habib-b0b0471ab/

Attach the homework screenshots below:
-----------------------------------------

STEP 4:

![Cql console](https://user-images.githubusercontent.com/64529365/122688849-37bdfa00-d23c-11eb-8857-c0248994fd68.jpg)

Try-it-Out Scenario
![Screenshot 2021-06-21 025519](https://user-images.githubusercontent.com/64529365/122688872-794ea500-d23c-11eb-9484-c76062bf4948.jpg)

**Comment by RyanWelford** [comment]
Thanks Zenab!

**Comment by HadesArchitect** [comment]
Hey **Zenab Habib**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/6Pmn-OxBQuuopRnD3rQKkQ
