### ISSUE TITLE
[HW] Tan Siong Min

### ISSUE THREAD

**Issue by funnnybear** [datastaxdevs/workshop-introduction-to-nosql#206]
**Name:** Tan Siong Min
**Email:** tansiongmin@gmail.com
**Linkedin Profile:** https://sg.linkedin.com/in/siong-min-tan-58859470

Attach the homework screenshots below:
-----------------------------------------

![Nosql workshop - Step IV practice part2](https://user-images.githubusercontent.com/4475350/122926488-7d90d480-d39a-11eb-8c93-ac7bbde73120.PNG)
![Nosql workshop - Step IV practice](https://user-images.githubusercontent.com/4475350/122926502-7f5a9800-d39a-11eb-8daa-4432d9e014b5.PNG)
![Nosql workshop - cql completed](https://user-images.githubusercontent.com/4475350/122926505-7f5a9800-d39a-11eb-9f75-6896f0e880df.PNG)

**Comment by SonicDMG** [comment]
Looks good Tan, nice job.

**Comment by HadesArchitect** [comment]
Hey **Tan Siong Min**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/FojfNNVPRW2Zl9BjKGLxog
