### ISSUE TITLE
[HW] <Aakanksha Singh>

### ISSUE THREAD

**Issue by AakankshaS09** [datastaxdevs/workshop-introduction-to-nosql#207]
**Name:** Aakanksha Singh
**Email:** demoiddone@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot (226)](https://user-images.githubusercontent.com/86301260/122923692-92616e00-d382-11eb-8b9c-7348c202bdad.png)
![Screenshot (219)](https://user-images.githubusercontent.com/86301260/122923696-93929b00-d382-11eb-98dd-a0312fa5cf4b.png)
![Screenshot (220)](https://user-images.githubusercontent.com/86301260/122923699-942b3180-d382-11eb-9107-01130ab2efe8.png)
![Screenshot (221)](https://user-images.githubusercontent.com/86301260/122923702-94c3c800-d382-11eb-8b02-36cf08595977.png)
![Screenshot (222)](https://user-images.githubusercontent.com/86301260/122923707-95f4f500-d382-11eb-944c-7661703aa38a.png)
![Screenshot (223)](https://user-images.githubusercontent.com/86301260/122923709-95f4f500-d382-11eb-8c2c-ff1b3448c759.png)
![Screenshot (224)](https://user-images.githubusercontent.com/86301260/122923710-968d8b80-d382-11eb-875c-459302a57f79.png)
![Screenshot (225)](https://user-images.githubusercontent.com/86301260/122923714-97262200-d382-11eb-94d6-81589b36a95b.png)
![11](https://user-images.githubusercontent.com/86301260/122927345-6ba53680-d386-11eb-9e75-58ce3eedea79.png)
![12](https://user-images.githubusercontent.com/86301260/122927351-6cd66380-d386-11eb-942e-4bc9a7516696.png)
![13](https://user-images.githubusercontent.com/86301260/122927355-6d6efa00-d386-11eb-919c-9ab388db9984.png)
![14](https://user-images.githubusercontent.com/86301260/122927356-6d6efa00-d386-11eb-8b93-585928e91c45.png)
![15](https://user-images.githubusercontent.com/86301260/122927358-6e079080-d386-11eb-818e-b51399a24e78.png)
![16](https://user-images.githubusercontent.com/86301260/122927359-6e079080-d386-11eb-8e52-61fa8f5f5167.png)
![17](https://user-images.githubusercontent.com/86301260/122927363-6ea02700-d386-11eb-9147-279a01a7fa27.png)
![s1](https://user-images.githubusercontent.com/86301260/122927364-6f38bd80-d386-11eb-9faf-fec89967fd27.png)
![Screenshot (237)](https://user-images.githubusercontent.com/86301260/122927366-6f38bd80-d386-11eb-8d8c-96cc834b6a08.png)
![Screenshot (238)](https://user-images.githubusercontent.com/86301260/122927373-7069ea80-d386-11eb-9f07-e27fc106bb2d.png)
![Screenshot (240)](https://user-images.githubusercontent.com/86301260/122927375-7069ea80-d386-11eb-9319-3b0a37a9fd3f.png)
![Screenshot (252)](https://user-images.githubusercontent.com/86301260/122927378-719b1780-d386-11eb-844f-4822586e31ef.png)
![Screenshot (253)](https://user-images.githubusercontent.com/86301260/122927382-719b1780-d386-11eb-910c-ce22f37133d8.png)
![Screenshot (254)](https://user-images.githubusercontent.com/86301260/122927383-7233ae00-d386-11eb-8a72-7e17302e3d38.png)
![Screenshot (255)](https://user-images.githubusercontent.com/86301260/122927385-72cc4480-d386-11eb-8303-5ef1be499546.png)
![Screenshot (256)](https://user-images.githubusercontent.com/86301260/122927388-72cc4480-d386-11eb-9327-d87eb72eb398.png)
![Screenshot (257)](https://user-images.githubusercontent.com/86301260/122927389-7364db00-d386-11eb-9a6d-ae30ea21b1ac.png)
![2](https://user-images.githubusercontent.com/86301260/122927393-73fd7180-d386-11eb-9f33-f53498f29472.png)
![5](https://user-images.githubusercontent.com/86301260/122927397-73fd7180-d386-11eb-943d-846eac52e679.png)
![8](https://user-images.githubusercontent.com/86301260/122927398-74960800-d386-11eb-9fc6-ebfdfa6f257b.png)
![9](https://user-images.githubusercontent.com/86301260/122927399-752e9e80-d386-11eb-8462-6fd90ef5daf7.png)
![10](https://user-images.githubusercontent.com/86301260/122927400-752e9e80-d386-11eb-804c-0c38b7e3f707.png)

**Comment by SonicDMG** [comment]
BTW, nice job in blocking all of your tokens. Thank you.

**Comment by AakankshaS09** [comment]
Below I have attached the "Scenario completed" screenshot  :

![Screenshot (261)](https://user-images.githubusercontent.com/86301260/123206931-2560ec00-d4da-11eb-8cc8-5fc3bafb879b.png)

**Comment by HadesArchitect** [comment]
Hey **Aakanksha Singh**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/PEt8AAShRiyw81m9QFPfmA

**Comment by SonicDMG** [comment]
Thank you for following up with the completed scenario Aakanksha.

**Comment by AakankshaS09** [comment]
Thank you so much. I wanted to ask if there is any way I can use this Badge for my Linkedin Profile?

**Comment by SonicDMG** [comment]
Yes, you can add it to the "Featured" section in your profile. Just click on the + and add your badge URL as a link.

**Comment by AakankshaS09** [comment]
Okay. Thank you again.
