### ISSUE TITLE
[HW] Dawid

### ISSUE THREAD

**Issue by Uord** [datastaxdevs/workshop-introduction-to-nosql#208]
**Name:** Dawid
**Email:** deivxd@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/dawid-zakrzewski/

Attach the homework screenshots below:
-----------------------------------------

![3](https://user-images.githubusercontent.com/21041401/122997187-06fcd280-d3ac-11eb-8089-eec8861ef971.png)
![4](https://user-images.githubusercontent.com/21041401/122997202-09f7c300-d3ac-11eb-83e2-d29be7722722.png)
![5](https://user-images.githubusercontent.com/21041401/122997285-20058380-d3ac-11eb-9b27-f9b923f3a688.png)
![try-it-out](https://user-images.githubusercontent.com/21041401/122997210-0bc18680-d3ac-11eb-93e8-85f47fac7519.png)

**Comment by SonicDMG** [comment]
Nice job getting all the way through step V Dawid. Looks good.

**Comment by HadesArchitect** [comment]
Hey **Dawid**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ljvgDJ03S0WLI_95eO68_A
