### ISSUE TITLE
[HW] RIYA TERI

### ISSUE THREAD

**Issue by riya0108** [datastaxdevs/workshop-introduction-to-nosql#209]
**Name:** RIYA TERI
**Email:** riyateri01@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/riyateri/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Screenshot (152)](https://user-images.githubusercontent.com/70089241/123057007-1b30e600-d425-11eb-8ed4-1cc0b31cfcc5.png)

![Screenshot (151)](https://user-images.githubusercontent.com/70089241/123057020-1ec46d00-d425-11eb-92e1-e65c67a27041.png)

**Comment by SonicDMG** [comment]
Nice job Riya!

**Comment by HadesArchitect** [comment]
Hey **RIYA TERI**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/jTFJhfLMRW2peDPlcOIEFg

**Comment by riya0108** [comment]
Thanks a lot @SonicDMG and @HadesArchitect 😁
