### ISSUE TITLE
[HW] <Deepan surya raj S V>

### ISSUE THREAD

**Issue by DeepansuryarajSV** [datastaxdevs/workshop-introduction-to-nosql#21]
**Name:** [**Deepan surya raj S V**]
**Email:** [**deepansurya2001@gmail.com**]
![Screenshot (95)](https://user-images.githubusercontent.com/83365307/117444368-01137500-af57-11eb-8a26-1b0c81777986.png)
![Screenshot (96)](https://user-images.githubusercontent.com/83365307/117444396-0a9cdd00-af57-11eb-873a-456c443a0993.png)
![Screenshot (97)](https://user-images.githubusercontent.com/83365307/117444406-0e306400-af57-11eb-8fb2-fa2675ce0938.png)
![Screenshot (98)](https://user-images.githubusercontent.com/83365307/117444411-1092be00-af57-11eb-8808-e5238fd9b156.png)
![Screenshot (99)](https://user-images.githubusercontent.com/83365307/117444418-125c8180-af57-11eb-8d8a-a69358f82dbc.png)
![Screenshot (100)](https://user-images.githubusercontent.com/83365307/117444433-15f00880-af57-11eb-95ba-fd9cca8953fc.png)
![Screenshot (101)](https://user-images.githubusercontent.com/83365307/117444441-18eaf900-af57-11eb-8337-596b5e2725d0.png)
![Screenshot (102)](https://user-images.githubusercontent.com/83365307/117444454-1c7e8000-af57-11eb-92bc-0b89e396903e.png)
![Screenshot (103)](https://user-images.githubusercontent.com/83365307/117444765-89921580-af57-11eb-8730-f2d26afcd357.png)
![Screenshot (104)](https://user-images.githubusercontent.com/83365307/117444786-8f87f680-af57-11eb-9fc0-92c817409dd5.png)
![Screenshot (106)](https://user-images.githubusercontent.com/83365307/117444801-944caa80-af57-11eb-843a-508c8d077662.png)
![Screenshot (107)](https://user-images.githubusercontent.com/83365307/117444824-9ca4e580-af57-11eb-91a4-1c2be1c563b4.png)
-- images removed by team --
![Screenshot (110)](https://user-images.githubusercontent.com/83365307/117444832-9e6ea900-af57-11eb-95c2-3407c207f385.png)
![Screenshot (111)](https://user-images.githubusercontent.com/83365307/117444834-9f073f80-af57-11eb-9131-4608b8c093b8.png)
![Screenshot (112)](https://user-images.githubusercontent.com/83365307/117444838-9f9fd600-af57-11eb-82a4-a3b00ccd447e.png)
![Screenshot (113)](https://user-images.githubusercontent.com/83365307/117444842-9f9fd600-af57-11eb-8a0b-9e430aa30093.png)
![Screenshot (114)](https://user-images.githubusercontent.com/83365307/117444846-a0386c80-af57-11eb-942d-68f6ca253396.png)

-- images removed by team --
![Screenshot (115)](https://user-images.githubusercontent.com/83365307/117446188-5781b300-af59-11eb-8de1-64f758df817d.png)
![Screenshot (116)](https://user-images.githubusercontent.com/83365307/117446193-5a7ca380-af59-11eb-9e32-6ae10686a714.png)

**COMPLETED SCENARIO**
![Screenshot (117)](https://user-images.githubusercontent.com/83365307/117446289-7b44f900-af59-11eb-8581-9af98a2f083c.png)

**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks good Deepan, thank you.

**Comment by HadesArchitect** [comment]
Great job! https://api.badgr.io/public/assertions/kNxT2yKcR5Sbzwk4mpiw8A?identity__email=deepansurya2001%40gmail.com
