### ISSUE TITLE
[HW] Gökcan Çantalı

### ISSUE THREAD

**Issue by gokcantali** [datastaxdevs/workshop-introduction-to-nosql#210]
Name: Gökcan Çantalı
Email: gokcantali@gmail.com
Linkedin Profile: https://www.linkedin.com/in/g%C3%B6kcan-%C3%A7antal%C4%B1-aa31319a/

Attach the homework screenshots below:
-----------------------------------------

<img width="1280" alt="graphql" src="https://user-images.githubusercontent.com/11981221/123086060-a57c4880-d42b-11eb-8f68-ff557767e941.png">

<img width="1273" alt="cqlconsole" src="https://user-images.githubusercontent.com/11981221/123086216-d0ff3300-d42b-11eb-9303-9d3349cf44bd.png">

<img width="1280" alt="cassandratutorial" src="https://user-images.githubusercontent.com/11981221/123086289-e7a58a00-d42b-11eb-9995-659538ae1bcb.png">

**Comment by SonicDMG** [comment]
Looks great Gökcan, thank you.

**Comment by SonicDMG** [comment]
Here you go -> https://api.badgr.io/public/assertions/UuMd1PlvSvm7CaHMZ2OeKw?identity__email=gokcantali%40gmail.com

**Comment by gokcantali** [comment]
Thank you David!
