### ISSUE TITLE
[HW] Anurag Ram Tripathi

### ISSUE THREAD

**Issue by a08119** [datastaxdevs/workshop-introduction-to-nosql#212]
**Name:** Anurag Ram Tripathi
**Email:** a08119@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/anurag-tripathi-587a64127/

Attach the homework screenshots below:
-----------------------------------------
![Chapter-4](https://user-images.githubusercontent.com/21354906/123120610-150d2a80-d462-11eb-9ebe-5241402fabcb.PNG)
![Scenario_Completed](https://user-images.githubusercontent.com/21354906/123120665-222a1980-d462-11eb-8a27-ad03408a05fe.PNG)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Anurag Ram Tripathi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/qjEWtb5bTcK8cjoEp2sLnw
