### ISSUE TITLE
[HW] Steven Matison

### ISSUE THREAD

**Issue by ds-steven-matison** [datastaxdevs/workshop-introduction-to-nosql#216]
**Name:** Steven Matison
**Email:** steven.matison@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/steven-matison/

Attach the homework screenshots below:
-----------------------------------------

<img width="1641" alt="Screen Shot 2021-07-19 at 11 37 56 AM" src="https://user-images.githubusercontent.com/70520951/126190117-946a1513-4560-4bf4-aadc-e2702b464c23.png">

![Screen Shot 2021-07-19 at 11 56 12 AM](https://user-images.githubusercontent.com/70520951/126190122-488e8718-ac8a-49fd-885a-fc625e7cdb71.png)

**Comment by HadesArchitect** [comment]
Hey **Steven Matison**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ePpELRS6QKu2PFjzSIcmPQ
