### ISSUE TITLE
[HW] Jeetendra Singh

### ISSUE THREAD

**Issue by jeet-singh-win** [datastaxdevs/workshop-introduction-to-nosql#217]
**Name:** Jeetendra Singh
**Email:** jeet.singh.win@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Cassandra Completed](https://user-images.githubusercontent.com/18393034/126909437-9f8b509b-7be1-487b-ab0a-bf9fbf61cad8.JPG)
![Cassandra Task IV](https://user-images.githubusercontent.com/18393034/126909440-fdc0a43b-7796-4891-9181-e3b00e8a463e.JPG)

**Comment by HadesArchitect** [comment]
Hey **Jeetendra Singh**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/VG_q_KCaT8aBJkxQJX8jkw
