### ISSUE TITLE
URL `/graphql/nosql1.` produces errors `Server cannot be reached`

### ISSUE THREAD

**Issue by Akshit6828** [datastaxdevs/workshop-introduction-to-nosql#22]

**Comment by Akshit6828** [comment]
Url ending with a dot(.) was not working. As URL when copied shows error could not connect to the server.
- Thus changing **pick url `/graphql/nosql1.`** to **pick url `/graphql/nosql1`** 

Please view the samples below:

![ERROR](https://user-images.githubusercontent.com/57808363/117498361-52435900-af97-11eb-8f0e-3c6411902782.png)



### Thus after removing the dot(.) in the suffix it works:

![Error Solved](https://user-images.githubusercontent.com/57808363/117498376-58d1d080-af97-11eb-9ab3-b3eef23ceb8d.png)


Please correct me if there was any error with my system @clun.

**Comment by Akshit6828** [comment]
@HadesArchitect, please correct me if there is anything wrong with the issue?

**Comment by HadesArchitect** [comment]
Thank you, merged it :)
