### ISSUE TITLE
[HW] Akif Nuri Demir

### ISSUE THREAD

**Issue by AkifNDemir** [datastaxdevs/workshop-introduction-to-nosql#220]
**Name:** Akif Nuri Demir
**Email:** akif.n.demir@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/akif-nuri-demir/

Attach the homework screenshots below:
-----------------------------------------

![ss1](https://user-images.githubusercontent.com/32599513/127319650-aa155ffe-b4ea-4283-a94a-680eda610a28.png)
![ss2](https://user-images.githubusercontent.com/32599513/127319652-1413f001-0839-472c-b40e-a354021adedf.png)
![ss3](https://user-images.githubusercontent.com/32599513/127319655-b94431f6-a09b-4628-89ab-8be49c8ef281.png)
![scenario](https://user-images.githubusercontent.com/32599513/127319757-f500d4f0-85e5-40cf-8755-39af69b7f0c5.png)

**Comment by HadesArchitect** [comment]
Hey **Akif Nuri Demir**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/CqH-qRuuTiCa5u_UCOjCvg
