### ISSUE TITLE
[HW] Thiago Fernandes da Silva Oliveira

### ISSUE THREAD

**Issue by thiagofdso** [datastaxdevs/workshop-introduction-to-nosql#221]
**Name:** THIAGO FERNANDES DA SILVA OLIVEIRA
**Email:** thiagofdso.ufpa@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/thiago-oliveira-1083b76a/

Attach the homework screenshots below:
-----------------------------------------
Workshop step IV
![IV 1](https://user-images.githubusercontent.com/7494894/127320706-7c6ef4b7-329b-435a-b617-a45602b08784.png)
![IV 2](https://user-images.githubusercontent.com/7494894/127320717-2c718493-4180-46ba-8899-8a7918c00ce5.png)

Try-out
![Try-Out](https://user-images.githubusercontent.com/7494894/127320756-c95ad529-4aa7-4f1c-bc6a-936880e0b8c8.png)

**Comment by HadesArchitect** [comment]
Hey **THIAGO FERNANDES DA SILVA OLIVEIRA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/HEvceWjhQ3-IYUuuu7DdUg
