### ISSUE TITLE
[HW] İsmet Taha Arslan

### ISSUE THREAD

**Issue by ismettt08** [datastaxdevs/workshop-introduction-to-nosql#223]
**Name:** İsmet Taha Arslan
**Email:** ismet.taha@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ismet-taha-arslan/

Attach the homework screenshots below:
-----------------------------------------

![Ekran Görüntüsü (17)](https://user-images.githubusercontent.com/8142922/127344453-3d45d1d8-d6de-45a7-8ca7-54131b37ecff.png)
![Ekran Görüntüsü (18)](https://user-images.githubusercontent.com/8142922/127344467-92318574-c7a1-4f3b-8606-f0c3320bcf0a.png)
![Ekran Görüntüsü (19)](https://user-images.githubusercontent.com/8142922/127344473-a53d4f79-848c-41f9-a15f-ac71022c8efb.png)

**Comment by HadesArchitect** [comment]
Hey **İsmet Taha Arslan**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/kDhvhykETFaCeR9XJvJcmw
