### ISSUE TITLE
[HW] <Sumit Das>

### ISSUE THREAD

**Issue by Sumitdas009** [datastaxdevs/workshop-introduction-to-nosql#224]
**Name:** Sumit Kumar Das
**Email:** sumitkumardas090@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sumit-kumar-das-19196912b/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
-- image removed by team --
<img width="450" alt="studio_create_graph" src="https://user-images.githubusercontent.com/64792024/127353774-f34bef39-b37b-4083-b0cf-4e577ee39180.png">
<img width="250" alt="studio_home" src="https://user-images.githubusercontent.com/64792024/127353778-c7c8e7af-dce4-4920-b982-3863c397b3f1.png">
<img width="450" alt="studio_notebook_1" src="https://user-images.githubusercontent.com/64792024/127353782-95202a9f-d74c-4923-9704-bec70b9eaadb.png">
<img width="450" alt="studio_notebook_2" src="https://user-images.githubusercontent.com/64792024/127353785-5041801f-e85e-4d09-b4fa-59e2aa428205.png">
<img width="400" alt="studio_test_connection2" src="https://user-images.githubusercontent.com/64792024/127353792-cd1a2e1e-95d5-465d-bbcb-3de21cbd8c04.png">
-- image removed by team --
<img width="357" alt="01" src="https://user-images.githubusercontent.com/64792024/127353797-f80262c0-5c84-4336-a04a-e787feeaf382.png">
<img width="450" alt="02" src="https://user-images.githubusercontent.com/64792024/127353798-b809d49e-c064-496f-8283-d56cce1324e5.png">
<img width="336" alt="03" src="https://user-images.githubusercontent.com/64792024/127353801-af435c66-36e3-4a76-b296-9d9a0d1ff2b0.png">
<img width="339" alt="04" src="https://user-images.githubusercontent.com/64792024/127353805-8e6a5437-e70d-4819-bbe9-c5f0186e4fb3.png">
<img width="448" alt="05" src="https://user-images.githubusercontent.com/64792024/127353810-7894df5d-98df-4c1a-bac8-6ae78c2ecaca.png">
<img width="349" alt="cqlconsole1" src="https://user-images.githubusercontent.com/64792024/127353814-101645df-b12e-48e5-a07b-b7b1b21db00e.png">
-- image removed by team --
<img width="343" alt="graphql2" src="https://user-images.githubusercontent.com/64792024/127353818-f9f079e8-260e-43a3-9b75-0a36b44c5971.png">

**Comment by SonicDMG** [comment]
Nice job getting through the Graph DB portion as well. :)

**Comment by HadesArchitect** [comment]
Hey **Sumit Kumar Das**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/sCSxt6CwTVaQLbx7nx_PDA

**Comment by SonicDMG** [comment]
Also, I had to removed a set of your images because they contained your Astra token. To ensure there are no security issues please delete your token from the Astra UI.
