### ISSUE TITLE
[HW] Vishwanath Deshpande

### ISSUE THREAD

**Issue by vishwanathdesh** [datastaxdevs/workshop-introduction-to-nosql#225]
**Name:** Vishwanath Deshpande
**Email:** vinath007@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/vishwanathdeshpande/

Attach the homework screenshots below:
-----------------------------------------

<
![21-23-09](https://user-images.githubusercontent.com/40995012/127356082-360105a4-1c6f-4c90-8234-ca4e8cac2a29.png)
![21-25-12](https://user-images.githubusercontent.com/40995012/127356100-f81136bb-8210-4e2f-b106-8241e34d3478.png)
>

**Comment by HadesArchitect** [comment]
Hey **Vishwanath Deshpande**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/PbDnidScTseR_nIcnuTMxg
