### ISSUE TITLE
[HW] <PARTHA PRATIM HALDER>

### ISSUE THREAD

**Issue by Partha2k00** [datastaxdevs/workshop-introduction-to-nosql#227]
**Name:** PARTHA PRATIM HALDER
**Email:** morningstar.partha@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/partha-pratim-halder-10022918a>

Attach the homework screenshots below:
-----------------------------------------
<![Screenshot (71)](https://user-images.githubusercontent.com/87129415/127357882-f8df15a0-093e-4523-8ab2-22828942d0d6.png)
![Screenshot (72)](https://user-images.githubusercontent.com/87129415/127357890-491914d2-b939-4477-970c-e86d117042b4.png)>

**Comment by HadesArchitect** [comment]
Hey **PARTHA PRATIM HALDER**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/omzYHWiASsi1p_O-eXxQ1Q
