### ISSUE TITLE
[HW] <ASHISH JAIN>

### ISSUE THREAD

**Issue by asjjain** [datastaxdevs/workshop-introduction-to-nosql#228]
**Name:** ASHISH JAIN
**Email:** ashish.jain1911@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ashish-jain-45443a5/?lipi=urn%3Ali%3Apage%3Aprofile_view_index_index%3B5gUAK6zRRL6DPQMmJrhy8Q%3D%3D

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/37781281/127361019-31a33008-3ad4-4302-8a7a-31b6e1dd2bbe.png)

![image](https://user-images.githubusercontent.com/37781281/127361739-98af0526-787e-442c-9e96-539ed45f6834.png)

![image](https://user-images.githubusercontent.com/37781281/127362735-9f022e16-e77c-461d-bc76-0fbd53b5922a.png)

**Comment by HadesArchitect** [comment]
Hey **ASHISH JAIN**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/2zkrZ5F-SaeuJIl-9C0rnQ
