### ISSUE TITLE
[HW] Tanat Tonguthaisri

### ISSUE THREAD

**Issue by 000** [datastaxdevs/workshop-introduction-to-nosql#229]
**Name:** Tanat Tonguthaisri
**Email:** tanatt@sau.ac.th
**Linkedin Profile:** https://www.linkedin.com/in/epicure/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

<img width="960" alt="Intro-DataStax-NoSQL-stepIV" src="https://user-images.githubusercontent.com/575755/127362325-71e097d4-73d5-4e0f-97a0-2f7a03853616.png">

![image](https://user-images.githubusercontent.com/575755/127354306-584ed0b9-7ea3-4524-bd27-da1efeaaac8e.png)

**Comment by HadesArchitect** [comment]
Hey **Tanat Tonguthaisri**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/cvR7mUjzQjayAvx7CRPquQ
