### ISSUE TITLE
[HW] Umang Dakh

### ISSUE THREAD

**Issue by Denny-UD** [datastaxdevs/workshop-introduction-to-nosql#230]
**Name:** Umang Dakh
**Email:** umangdakh@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/umang-dakh/

Attach the homework screenshots below:
-----------------------------------------
![Screenshot (166)](https://user-images.githubusercontent.com/77261658/127366107-17fef272-b343-4b2a-8ccf-4f77a58f393f.png)
![Screenshot (167)](https://user-images.githubusercontent.com/77261658/127366119-cb2fdca9-1a5f-470f-81e6-8b1c499643d6.png)
![Screenshot (168)](https://user-images.githubusercontent.com/77261658/127366130-62a0e513-87a5-4c60-b464-1ebf483643a7.png)
-- image removed by team --
![Screenshot (177)](https://user-images.githubusercontent.com/77261658/127366162-8ee26ad6-e495-4e35-8050-f8b728f34e78.png)
![Screenshot (172)](https://user-images.githubusercontent.com/77261658/127366186-89664a5e-4d99-487b-879d-a97ec7ffaf81.png)
![Screenshot (173)](https://user-images.githubusercontent.com/77261658/127366193-1a886cd0-16cb-41c8-96e9-b3328cc24041.png)
![Screenshot (174)](https://user-images.githubusercontent.com/77261658/127366211-15d57e6b-1484-466e-b700-0571e77b2497.png)
![Screenshot (175)](https://user-images.githubusercontent.com/77261658/127366224-d774335e-f20a-4ae1-b72b-810fe65b3d95.png)

**Comment by HadesArchitect** [comment]
Hey **Umang Dakh**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/dhxwfU6hSyi5CQo6KigtbA

**Comment by SonicDMG** [comment]
Also, I had to removed a set of your images because they contained your Astra token. To ensure there are no security issues please delete your token from the Astra UI.
