### ISSUE TITLE
[HW] Caio Andrade

### ISSUE THREAD

**Issue by darkonig** [datastaxdevs/workshop-introduction-to-nosql#235]
**Name:** Caio Andrade
**Email:** idev.caio@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/caio-andrade/

Attach the homework screenshots below:
-----------------------------------------

![Screen Shot 2021-07-28 at 12 08 34 PM](https://user-images.githubusercontent.com/10310537/127367031-6986e45f-784b-4687-a104-fbd6a1a25a52.png)
-- image removed by team --

**Comment by HadesArchitect** [comment]
Hey **Caio Andrade**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/DtZf6dXsQLuJTOorVhiiSw

**Comment by SonicDMG** [comment]
Also, I had to removed one of your images because they contained your Astra token. To ensure there are no security issues please delete your token from the Astra UI.

**Comment by darkonig** [comment]
Thanks, that was my mistake.
