### ISSUE TITLE
[HW] Nandess

### ISSUE THREAD

**Issue by itsmenandess** [datastaxdevs/workshop-introduction-to-nosql#239]
**Name:** Nandesskumar
**Email:** itsmenandess@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nandesskumar-vaithilingam-429a0336/

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/10086707/127367385-98ece74a-b4e1-494b-a19d-fa9fff02c02d.png)

**Comment by SonicDMG** [comment]
Hi Nandesskumar, thank you for your submission. The workshop exercise looks good, but we are missing the scenario from step 2 of the homework.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete that as well and provide a screenshot. Thank you. :)

**Comment by itsmenandess** [comment]
Name: Nandesskumar
Email: itsmenandess@gmail.com
Linkedin Profile: https://www.linkedin.com/in/nandesskumar-vaithilingam-429a0336/

Completed the request one.

1. Missing the scenario from step 2 of the homework.
Step 1:
![image](https://user-images.githubusercontent.com/10086707/127690114-e3a0541a-94a0-4bde-8817-65fd5a1dec30.png)

Step 2:
![image](https://user-images.githubusercontent.com/10086707/127690371-cd163793-8409-438c-bede-fe753b5e5009.png)

Step 3:
![image](https://user-images.githubusercontent.com/10086707/127691390-57c3d41a-da32-4d2a-bb02-433776c3bea1.png)

Step 4
![image](https://user-images.githubusercontent.com/10086707/127692132-0565193a-4e6f-49c0-b60a-fec0361d2c8b.png)

![image](https://user-images.githubusercontent.com/10086707/127692169-d0d78900-2d96-4799-a805-c0597d25157b.png)


2. Complete try-it-out scenario and make a screenshot of the "scenario completed" screen
![image](https://user-images.githubusercontent.com/10086707/127689641-654d0454-d2ff-4a00-8fa9-60d824254561.png)

**Comment by itsmenandess** [comment]
Any update? and i am waiting for badge

**Comment by HadesArchitect** [comment]
Hey **Nandesskumar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/YZYDM_XYSI-9r8r-X06lCw
