### ISSUE TITLE
[HW] Subhadeep Roy

### ISSUE THREAD

**Issue by subhadeep18** [datastaxdevs/workshop-introduction-to-nosql#24]
**Name:** Subhadeep Roy
**Email:** subhadeep1808@gmail.com
**Linkedin Profile:** www.linkedin.com/in/subhadeep-1808

Attach the homework screenshots below:
-----------------------------------------

![1-Astra_Instance_created](https://user-images.githubusercontent.com/48452458/117543498-c97df900-b03a-11eb-8806-32addf4d79b7.JPG)
![2 1-Tabular_Database_created](https://user-images.githubusercontent.com/48452458/117543502-cd118000-b03a-11eb-955d-b61c0c659811.JPG)
![2 2-Working_with_Partitions](https://user-images.githubusercontent.com/48452458/117543505-cedb4380-b03a-11eb-8cab-e16b35ba0057.JPG)
![2 3-Debugging_with_filtering](https://user-images.githubusercontent.com/48452458/117543509-d0a50700-b03a-11eb-94aa-689b91aff448.JPG)
![3 1-Document_database_created](https://user-images.githubusercontent.com/48452458/117543514-d3076100-b03a-11eb-9831-253a842dfe75.JPG)
-- images removed by team --
![4 3-KeyValue_Database_accessed_from_console](https://user-images.githubusercontent.com/48452458/117543538-e3b7d700-b03a-11eb-82e3-3c6b7ef4bf63.JPG)
![Try_it_out](https://user-images.githubusercontent.com/48452458/117543539-e7e3f480-b03a-11eb-8e85-4537c287adfb.JPG)

**Comment by SonicDMG** [comment]
Looks good Subhadeep, thank you.

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/8blP7JqnTz6EpAPyilhD6g?identity__email=subhadeep1808%40gmail.com

**Comment by HadesArchitect** [comment]
Well done!
