### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by godricpursue** [datastaxdevs/workshop-introduction-to-nosql#240]
**Name:** Altan Şimşir
**Email:** simsiraltan@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/altan-%C5%9Fim%C5%9Fir-28ba12211/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS
![cassandrascenario](https://user-images.githubusercontent.com/88106373/127367525-db5281c2-f77f-4f24-97ca-95d5f1ddd558.jpg)
![astradb4](https://user-images.githubusercontent.com/88106373/127367529-65d3eeb0-dd80-46fd-b543-c552c71e5dd3.jpg)
>

**Comment by HadesArchitect** [comment]
Hey **Altan Şimşir**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/dYDxUwCiRxSIKtTJFKTEgQ
