### ISSUE TITLE
[HW] Amol Vyavaharkar

### ISSUE THREAD

**Issue by amol071** [datastaxdevs/workshop-introduction-to-nosql#241]
**Name:** Amol Vyavaharkar
**Email:** amol07@live.com
**Linkedin Profile:** https://www.linkedin.com/in/amolksv/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot (7)](https://user-images.githubusercontent.com/65177818/127367098-a6f83592-51d8-4a24-a73b-b9e82a078ad9.png)

![unknown](https://user-images.githubusercontent.com/65177818/127367617-ba54244f-6367-49c5-b360-bb43503e91ce.png)

**Comment by HadesArchitect** [comment]
Hey **Amol Vyavaharkar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/NurbVusmQF-0OxIJ3fhJKg
