### ISSUE TITLE
[HW] <Midhesh Mahadevan Shankar>

### ISSUE THREAD

**Issue by midhesh** [datastaxdevs/workshop-introduction-to-nosql#248]
**Name:** Midhesh Mahadevan Shankar
**Email:** midhesh286@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/midhesh-shankar-44017120b>

Attach the homework screenshots below:
-----------------------------------------
4c on graphql
![cassandra_graphql](https://user-images.githubusercontent.com/58551063/127367834-5d556268-affd-4298-b22b-886da8d017e1.png)

4c on cql console
![cassandra_cql console](https://user-images.githubusercontent.com/58551063/127367840-6f9f6bc5-acd1-4165-b9cd-1e40f0be0272.png)

try it out scenario
![try_it_out_scenario](https://user-images.githubusercontent.com/58551063/127367850-8f515b24-dea5-4991-abb9-6fecaa48f0c4.png)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Midhesh Mahadevan Shankar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/2f3Bs5EwSDWEtMgSMbL_Gw
