### ISSUE TITLE
[HW] <ZUHAIR KHAJA MOINUDDIN>

### ISSUE THREAD

**Issue by zuomozu** [datastaxdevs/workshop-introduction-to-nosql#251]
**Name:** ZUHAIR
**Email:** zuhairmoinuddin@gmail.com
**Linkedin Profile:** <www.linkedin.com/in/zuhair-moinuddin>

Attach the homework screenshots below:
-----------------------------------------
![garph nosql](https://user-images.githubusercontent.com/49607944/127368394-6e74b2e5-a205-4158-a209-eb171c49f0ff.png)
![playground  nosql](https://user-images.githubusercontent.com/49607944/127368410-b7b14295-2850-4ff2-a619-2734a2c953a8.png)
![Cassandra QL](https://user-images.githubusercontent.com/49607944/127368421-a09abdb4-a3c8-49a9-8eca-13446de3d9aa.png)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **ZUHAIR**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ajnhN8coRYW1k9Q2gYElUQ
