### ISSUE TITLE
[HW] <ADHIRAJ DEV GOSWAMI>

### ISSUE THREAD

**Issue by Adhiraj21** [datastaxdevs/workshop-introduction-to-nosql#254]
**Name:** Adhiraj Dev Goswami
**Email:** adhirajdevg223@gmail.com
**Linkedin Profile:** <|www.linkedin.com/in/Adhiraj21
![homework](https://user-images.githubusercontent.com/68478974/127368593-43105202-46d3-4428-aa51-eaeee1c29511.PNG)
![homework 2](https://user-images.githubusercontent.com/68478974/127368613-dffcda08-7a55-4ca8-9d42-7581671df9db.PNG)
>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by Adhiraj21** [comment]
Name- Adhiraj Dev Goswami

**Comment by Adhiraj21** [comment]
![homework 3](https://user-images.githubusercontent.com/68478974/127532862-de8ad059-e454-42d5-8f5b-f9e0f065ea24.PNG)

**Comment by Adhiraj21** [comment]
![hOMEWORK 4](https://user-images.githubusercontent.com/68478974/127535549-67d2ce94-f4b3-4a21-a8ab-dd2ccf2af0c6.PNG)

**Comment by Adhiraj21** [comment]
![homework 5](https://user-images.githubusercontent.com/68478974/127704556-7863679b-5272-4c84-a3e3-83889a26422e.PNG)

**Comment by HadesArchitect** [comment]
Hey **Adhiraj Dev Goswami**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/4jdpTT6URkK9iGqwqiqFqw
