### ISSUE TITLE
[HW] Cira 

### ISSUE THREAD

**Issue by cirmar** [datastaxdevs/workshop-introduction-to-nosql#255]
**Name:** Cira Foster
**Email:** cfoster32@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/cfoster32/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Doc-DB-1](https://user-images.githubusercontent.com/10169348/127368602-2e1cc852-7fd5-4128-b10a-52ce2b93c899.png)

![Tabular-Data](https://user-images.githubusercontent.com/10169348/127368615-31270f5b-a994-4988-a756-ff18cd65343a.png)

![Try-It-Out-Datastax](https://user-images.githubusercontent.com/10169348/127368621-74d1ab29-b14e-4498-96b4-20bc9eda3dd5.png)

**Comment by HadesArchitect** [comment]
Hey **Cira Foster**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Fs24jeWrTJux_rS4btggug
