### ISSUE TITLE
[HW] Aparna Mookerjee

### ISSUE THREAD

**Issue by aparnarepo** [datastaxdevs/workshop-introduction-to-nosql#26]
**Name:** Aparna Mookerjee
**Email:** aparna.mookerjee@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------
### 1. Create Astra Instance: 

**database**: nosql_db and **keyspace**: nosql1

![Web capture_7-5-2021_231014_astra datastax com](https://user-images.githubusercontent.com/61774409/117563990-2921e600-b0c7-11eb-8f1c-35afcd61dc47.jpeg)

### 2. Tabular Databases

**2a. Describe keyspaces**

![2a Describe Keyspaces](https://user-images.githubusercontent.com/61774409/117564160-4c996080-b0c8-11eb-9342-82b5d7d37f38.jpg)

**2b Create Table**

**Table videos created
Describe keyspace nosql1;
nosql1.videos table structure**

![Web capture_7-5-2021_231843_astra datastax com](https://user-images.githubusercontent.com/61774409/117564221-ad289d80-b0c8-11eb-95a3-9a4f33b25575.jpeg)

**2c Working with Data**

**Insert some entries, read values and real by id**

![Web capture_7-5-2021_232111_astra datastax com](https://user-images.githubusercontent.com/61774409/117564304-1ad4c980-b0c9-11eb-9b82-1fcdcaf0790c.jpeg)

**2d Working with Partitions**

**Create new table users_by_city
Insert some entries
List values with partition key**

![Web capture_7-5-2021_232439_astra datastax com](https://user-images.githubusercontent.com/61774409/117564499-f0cfd700-b0c9-11eb-8e7b-7aea09423d89.jpeg)

**Query with debugging enabled.
Forcing full scan = slow (allow filtering)
stop debugging**

![Web capture_7-5-2021_232711_astra datastax com](https://user-images.githubusercontent.com/61774409/117564643-b9adf580-b0ca-11eb-855c-f9b1b354e6ff.jpeg)

### 3 Document Databases

**3a Cassandra knows JSON**

**Insert and retrieve data from Cassandra as JSON**

![Web capture_7-5-2021_232930_astra datastax com](https://user-images.githubusercontent.com/61774409/117564707-01348180-b0cb-11eb-832e-cefd3c1c468d.jpeg)

**3b Create Application Token**

-- images removed by team --

**3c Create empty collection**
Note col1 already created. Screenshot taken after creation hence showing Error: 409 instead of 201 Created

-- images removed by team --

**3d Create a new Document**

-- images removed by team --
**3e Find all documents of a collection**

-- images removed by team --
**3f Retrieve a document by its id**

-- images removed by team --

**3g Search document using a where clause**

-- images removed by team --

**Search document by id and where clause {title}**

-- images removed by team --

### 4 Key  value Databases
 
**4b Create a table with QraphQL**

-- images removed by team --
**Check table in cqlsh (describe keyspace nosql1)**

![4b1 Descrive keyspace in cqlsh](https://user-images.githubusercontent.com/61774409/117565706-4ad39b00-b0d0-11eb-8e6b-5823f60b107a.jpg)

**4c Populate the table**

-- images removed by team --

**Check in cqlsh**

![4c populate the table check in cqlsh](https://user-images.githubusercontent.com/61774409/117565808-e36a1b00-b0d0-11eb-86d4-60c94b38961c.jpg)

**Execute another insert** 

-- images removed by team --

**Check in cqlsh**

![4c2 populate the table check in cqlsh](https://user-images.githubusercontent.com/61774409/117565860-2d530100-b0d1-11eb-9349-4cdf00bc31a3.jpg)

### Home work Part II

**Try it out** 

https://www.datastax.com/try-it-out
**Cassandra Query Language (CQL) 
Completion screenshot**

![Web capture_9-5-2021_123757_www datastax com (2)](https://user-images.githubusercontent.com/61774409/117566172-ba4a8a00-b0d2-11eb-9886-85293c173dd5.jpeg)

**Cassandra Data Modeling: (on try-it-out page left bottom)
Completion screenshot**

![Web capture_9-5-2021_12534_www datastax com](https://user-images.githubusercontent.com/61774409/117566228-085f8d80-b0d3-11eb-85cf-2514846087dc.jpeg)

**Comment by SonicDMG** [comment]
Looks good Aparna, thank you.

**Comment by HadesArchitect** [comment]
Well done Aparna! https://api.badgr.io/public/assertions/e5vctnTTRrOjeZye1q-D9A?identity__email=aparna.mookerjee%40gmail.com
