### ISSUE TITLE
[HW] ABAAN MUSTAFA SHAIKH

### ISSUE THREAD

**Issue by AbaanShaikh** [datastaxdevs/workshop-introduction-to-nosql#262]
**Name:** ABAAN MUSTAFA SHAIKH
**Email:** abaanshaikh2612@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/abaan-shaikh-648a0a19b/
Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot (26)](https://user-images.githubusercontent.com/56254975/127369177-260557fb-f253-4934-bee7-3ec97a496114.png)
![Screenshot (27)](https://user-images.githubusercontent.com/56254975/127369184-cc5f63e4-3132-4c21-80c0-d43118abafa9.png)

**Comment by HadesArchitect** [comment]
Hey **ABAAN MUSTAFA SHAIKH**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/C-RlhuAqSJaf61TnX6QQSg
