### ISSUE TITLE
[HW] <JeanApuada>

### ISSUE THREAD

**Issue by maikenapuada** [datastaxdevs/workshop-introduction-to-nosql#267]
**Name:** JeanApuada
**Email:** maikenapuada@hotmail.ca
**Linkedin Profile:** <https://www.linkedin.com/in/jean-maiken-apuada-a951491b9/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![completedscenaario](https://user-images.githubusercontent.com/43075235/127369721-cff0ed76-2741-4523-b1dd-2cc4e9611425.png)
![astra2](https://user-images.githubusercontent.com/43075235/127369723-98b1fe0a-d225-4982-b27c-5f015f15038e.png)
![astra1](https://user-images.githubusercontent.com/43075235/127369724-642b6c9d-1002-4fe1-bb93-3f8895566465.png)

**Comment by HadesArchitect** [comment]
Hey **JeanApuada**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/FwOZTbubTrCb_D-cUhwrzQ
