### ISSUE TITLE
[HW] NANDAN MISHRA

### ISSUE THREAD

**Issue by NandanM15** [datastaxdevs/workshop-introduction-to-nosql#269]
**Name:** Nandan Mishra
**Email:** mishranandan21@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nandan-mishra-720297170/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot (1)](https://user-images.githubusercontent.com/88100201/127369098-beb637d8-9baf-4d7e-8947-29e2e8db6413.png)
![Newunknown](https://user-images.githubusercontent.com/88100201/127369105-0ab199b5-9f02-490f-800f-19b342bd4c88.png)

**Comment by HadesArchitect** [comment]
Hey **Nandan Mishra**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/lNuWu_6xR1OT3qkpQlNQzQ
