### ISSUE TITLE
[HW] <Workshop-Introduction-to-NoSQL DB>

### ISSUE THREAD

**Issue by ambedkar1985** [datastaxdevs/workshop-introduction-to-nosql#27]
**Name:** K S A R AMBEDKAR
**Email:** <ambedkar1985@gmail.com>
**Linkedin Profile:** <ambedkar1985@gmail.com>

Attach the homework screenshots below:
-----------------------------------------
-- images removed by team --

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks good, thank you.

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/Cm1u24bZSh6f0C6L3GT5XA?identity__email=ambedkar1985%40gmail.com
