### ISSUE TITLE
[HW] Salman Faris P P

### ISSUE THREAD

**Issue by salmanfarispp** [datastaxdevs/workshop-introduction-to-nosql#270]
**Name:** Salman Faris P P
**Email:** salmanfarispp25@gmail.com
**Linkedin Profile:** www.linkedin.com/in/salmanfarispp

Attach the homework screenshots below:
-----------------------------------------
![Screenshot (689)](https://user-images.githubusercontent.com/71908341/127369856-001f2a8a-2042-4f4e-808e-39c8c90912fb.png)
![Screenshot (690)](https://user-images.githubusercontent.com/71908341/127369863-3507ff29-19ca-4c94-b1ee-c3662e59652e.png)

**Comment by HadesArchitect** [comment]
Hey **Salman Faris P P**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/tqRYK_ItR_KPT9CvarsjYg

**Comment by salmanfarispp** [comment]
Thank you  : )
