### ISSUE TITLE
[HW] ERIKSON

### ISSUE THREAD

**Issue by erikson99** [datastaxdevs/workshop-introduction-to-nosql#272]
**Name:** ERIKSON
**Email:** erixon@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/erikson/

Attach the homework screenshots below:
-----------------------------------------

![dtsx-step01](https://user-images.githubusercontent.com/72220866/127370062-9db74c59-e54a-45a7-91bb-7dd38e3f1fd2.png)
![dtsx-step02](https://user-images.githubusercontent.com/72220866/127370091-4615bc2e-a3b5-4341-8509-8a44e4c100d7.png)

**Comment by HadesArchitect** [comment]
Hey **ERIKSON**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/FFax1PWrTQucO1ZB5HVqqA
