### ISSUE TITLE
[HW] <Ganesh Hegde>

### ISSUE THREAD

**Issue by hegderganesh96** [datastaxdevs/workshop-introduction-to-nosql#273]
**Name:** Ganesh Ramachandra Hegde
**Email:** hegderganesh96@gmail.com
**Linkedin Profile:** <linkedin.com/in/ganeshrhegde>

Attach the homework screenshots below:
-----------------------------------------

<<img width="1440" alt="Screenshot 2021-07-28 at 11 05 59 PM" src="https://user-images.githubusercontent.com/79307163/127370471-72084093-e3f4-4052-8ab7-616e6680c231.png">
<img width="1389" alt="Screenshot 2021-07-28 at 11 05 15 PM" src="https://user-images.githubusercontent.com/79307163/127370497-0ea32d74-93f1-4d67-8bed-033231c716f8.png">
<img width="1440" alt="Screenshot 2021-07-28 at 11 14 23 PM" src="https://user-images.githubusercontent.com/79307163/127371148-a43d73ba-6db3-449b-bf46-bb6acb21ff8c.png">>

**Comment by HadesArchitect** [comment]
Hey **Ganesh Ramachandra Hegde**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/aGv7q2YESTumjoEnxYL2fA
