### ISSUE TITLE
[HW] Kiran Shinde

### ISSUE THREAD

**Issue by KPS250** [datastaxdevs/workshop-introduction-to-nosql#274]
**Name:** Kiran Shinde
**Email:** kpshinde25@gmail.com
**Linkedin Profile:** https://in.linkedin.com/in/kps250

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/33733142/127370424-313ef105-9784-4ed9-9d15-fbab6a88f234.png)

![image](https://user-images.githubusercontent.com/33733142/127370519-9d178a75-b8ec-4269-a0fc-e822258fa475.png)

**Comment by HadesArchitect** [comment]
Hey **Kiran Shinde**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/6fcb-V03RCSGMaR4x1zsvg
