### ISSUE TITLE
[HW] Dilpreet Singh Bedi

### ISSUE THREAD

**Issue by Dilpreet-S** [datastaxdevs/workshop-introduction-to-nosql#275]
**Name:** Dilpreet Singh Bedi
**Email:** edudbedi@gmail.com
**Linkedin Profile:** www.linkedin.com/in/dilpreet-singh-bedi

Attach the homework screenshots below:
------------------------------------------------
![image](https://user-images.githubusercontent.com/65917202/127370598-250ecd19-9b77-4df5-9d79-62926b1698bb.png)

![image](https://user-images.githubusercontent.com/65917202/127370645-8f21b31f-fe64-4d90-8de4-09265ca7135a.png)

![image](https://user-images.githubusercontent.com/65917202/127370526-686a596f-564c-40ca-99da-b808bde2e2d6.png)

**Comment by HadesArchitect** [comment]
Hey **Dilpreet Singh Bedi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/fXg2aEo1TieQelDl2cBRvg
