### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by Kokardka** [datastaxdevs/workshop-introduction-to-nosql#276]
**Name:** Martyna Tomaszewska
**Email:** martyna.tomaszewska86@gmail.com
**Linkedin Profile:** <www.linkedin.com/in/martyna-tomaszewska-programmer

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![1](https://user-images.githubusercontent.com/72028760/127369309-51cff679-987c-40fc-8a0a-74c9cf7d70b7.jpg)

![2](https://user-images.githubusercontent.com/72028760/127369323-892805fa-f7b4-4af5-abb4-48cbe966d60b.jpg)

![3](https://user-images.githubusercontent.com/72028760/127369331-bd4c27fb-3b35-4a77-90d8-a28c580a1b65.jpg)

![4](https://user-images.githubusercontent.com/72028760/127703945-6e2f1f14-b0c2-4d74-9376-e45c7895c59c.jpg)

![5](https://user-images.githubusercontent.com/72028760/127370790-3b8901b2-3f81-4faf-88a9-5f60a5973ac7.jpg)

I am looking for a first job as a SQL Developer,  Database Programmer or SQL Database Administrator :)
Thank You for the lessons, I want to learn more about SQL language and I will be pleased if I will get a Badge :)
Thanks !

**Comment by SonicDMG** [comment]
Hi there Martyna, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by SonicDMG** [comment]
> I am looking for a first job as a SQL Developer, Database Programmer or SQL Database Administrator :)
> Thank You for the lessons, I want to learn more about SQL language and I will be pleased if I will get a Badge :)

This is great. I hope our workshops can help you on that path. Always feel free to reach out for questions or anything.

**Comment by Kokardka** [comment]
![2](https://user-images.githubusercontent.com/72028760/128832084-fa894f99-13cd-4929-b19e-5263ef14d9a4.jpg)

![1](https://user-images.githubusercontent.com/72028760/128832102-af275986-7a54-4e38-baaf-43d5a88acfc4.jpg)

**Comment by HadesArchitect** [comment]
Hey **Martyna Tomaszewska**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/pQrmWfpjSeibwBrtsTTI5Q

**Comment by Kokardka** [comment]
Thank You :)
