### ISSUE TITLE
[HW] <Marcin Misiak>

### ISSUE THREAD

**Issue by Misiorro007** [datastaxdevs/workshop-introduction-to-nosql#277]
**Name:** Marcin Misiak
**Email:** m.misiak2@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/marcin-misiak-47557393/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
-- images removed by team --

**Comment by Misiorro007** [comment]
I've corrected the name and email adress - sorry for the mess :)

**Comment by HadesArchitect** [comment]
Hey **Marcin Misiak**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/0KbyzmMWQg-YO-oFQFMRPQ

**Comment by SonicDMG** [comment]
Also, I had to remove your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.
