### ISSUE TITLE
[HW] <Apuroop Mahadev>

### ISSUE THREAD

**Issue by ApuroopMahadev** [datastaxdevs/workshop-introduction-to-nosql#278]
**Name:** Apuroop Mahadev
**Email:** apuroop.mahadev@outlook.com
**Linkedin Profile:** <https://www.linkedin.com/in/apuroopmahadev/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Screenshot (360)](https://user-images.githubusercontent.com/74767636/127371557-adb4ecf5-7997-4235-b2bb-43eb45abbcdd.png)

![Screenshot (359)](https://user-images.githubusercontent.com/74767636/127371558-dcbce302-f9a3-4989-9026-53ab02ebe400.png)

**Comment by HadesArchitect** [comment]
Hey **Apuroop Mahadev**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/1Hz4Msm_SMWfZAiOkCJeTQ
