### ISSUE TITLE
[HW] Maheswararao Kenguva

### ISSUE THREAD

**Issue by Maheshkenguva26** [datastaxdevs/workshop-introduction-to-nosql#281]
**Name:** Maheswararao Kenguva
**Email:** kenguva.mahesh@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/maheswararao-kenguva-378b2614a/

Attach the homework screenshots below:
-----------------------------------------

<img width="1792" alt="Screenshot 2021-07-28 at 11 08 01 PM" src="https://user-images.githubusercontent.com/61454165/127371853-1ebfbcea-5892-453f-a5a2-76742116729f.png">
<img width="1792" alt="Screenshot 2021-07-28 at 10 58 59 PM" src="https://user-images.githubusercontent.com/61454165/127371890-8b748cbe-401f-49c2-b7c2-e5673651c17d.png">

**Comment by HadesArchitect** [comment]
Hey **Maheswararao Kenguva**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/VdPqXfnTTSe00ZSfZwPdng
