### ISSUE TITLE
[HW] <Vaishnavi Choudhari- Intro to NoSQL>

### ISSUE THREAD

**Issue by Vaish02Navee08** [datastaxdevs/workshop-introduction-to-nosql#282]
**Name:** Vaishnavi Suresh Choudhari
**Email:** tinavi3008@gmail.com
**Linkedin Profile:** [Vaishnavi_Linkedin](https://www.linkedin.com/in/vaishnavi-choudhari-75a17b194/)

Attach the homework screenshots below:
-----------------------------------------

<
-- images removed by team --

![astra console](https://user-images.githubusercontent.com/87558182/127370893-5cc4d775-f67f-4b0b-a2af-2837befc745a.png)
![astra1](https://user-images.githubusercontent.com/87558182/127370902-a9254908-022f-496d-b344-9eb9b1085af8.png)
![astra2](https://user-images.githubusercontent.com/87558182/127370935-7bef15fd-c7ef-4859-8806-2ad675ad8549.png)
![astra3](https://user-images.githubusercontent.com/87558182/127370947-ecb7af7a-cff0-4d13-9cca-39a4dde09569.png)
-- images removed by team --
![tio2](https://user-images.githubusercontent.com/87558182/127371034-c2755f95-c0a8-44ed-af01-70da0e6035c0.png)
![tioscenaqrio](https://user-images.githubusercontent.com/87558182/127371040-7ce5f1de-4f47-4f29-8fc5-2ca5ed449a30.png)

>

**Comment by HadesArchitect** [comment]
Hey **Vaishnavi Suresh Choudhari**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/IVYmu7cvS76Yn4ijlbFrIw

**Comment by SonicDMG** [comment]
Also, I had to remove some of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.
