### ISSUE TITLE
[HW] Saiyam Jain

### ISSUE THREAD

**Issue by CyberSaiyam** [datastaxdevs/workshop-introduction-to-nosql#284]
**Name:** Saiyam Jain
**Email:** saiyamjain442@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/saiyam-jain-b8ba181a9/

Attach the homework screenshots below:
-----------------------------------------

![DataStax Assignment](https://user-images.githubusercontent.com/59705243/127372000-d4170cd1-e538-4c5d-b01d-2368f0d65624.png)

![DataStax Assignment2](https://user-images.githubusercontent.com/59705243/127372020-c1b9f5cc-655c-4df2-90e7-b4fbc44c22e1.png)

**Comment by HadesArchitect** [comment]
Hey **Saiyam Jain**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/7iJW08JdSeWYZvX1OEjWPQ
