### ISSUE TITLE
[HW] Miguel Castelo

### ISSUE THREAD

**Issue by kahleroth** [datastaxdevs/workshop-introduction-to-nosql#288]
**Name:** Miguel Castelo
**Email:** ma.castelo25@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/miguel-c-7a537737/

Attach the homework screenshots below:
-----------------------------------------

![homework1](https://user-images.githubusercontent.com/15842608/127372841-29bea401-dcf2-4ae5-864c-bffb69946fe2.png)
![homework2](https://user-images.githubusercontent.com/15842608/127372853-225e8ea5-77b4-4479-9729-1c0142d95393.png)
![homework3](https://user-images.githubusercontent.com/15842608/127372861-0ca4e52d-22d8-462f-80d5-c4024e4665ee.png)

**Comment by HadesArchitect** [comment]
Hey **Miguel Castelo**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/MlKhNsNFSdehWdGj5nS9wg

**Comment by kahleroth** [comment]
> Hey **Miguel Castelo**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/MlKhNsNFSdehWdGj5nS9wg

Thank you!
