### ISSUE TITLE
[HW] <NAME> OLAWAUNMI ANOTA

### ISSUE THREAD

**Issue by lami35** [datastaxdevs/workshop-introduction-to-nosql#29]
**Name:** <NAME>
**Email:** <email>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------
Your Interactive Bash Terminal.
$ cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 4.0-beta2 | CQL spec 3.4.5 | Native protocol v4]
Use HELP for help.
cqlsh> 
cqlsh> 
cqlsh> CREATE KEYSPACE demo WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> CREATE KEYSPACE demo WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
?            CLEAR        CREATE       DESCRIBE     HELP         PAGING       SHOW         UPDATE
ALTER        CLS          DEBUG        DROP         INSERT       REVOKE       SOURCE       USE
BEGIN        CONSISTENCY  DELETE       EXPAND       LIST         SELECT       TRACING      exit
CAPTURE      COPY         DESC         GRANT        LOGIN        SERIAL       TRUNCATE     quit
cqlsh> CREATE KEYSPACE demo WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};DESCRIBE KEYSPACES;
AlreadyExists: Keyspace 'demo' already exists

demo    system_auth         system_schema  system_views         
system  system_distributed  system_traces  system_virtual_schema

cqlsh> 
?            CLEAR        CREATE       DESCRIBE     HELP         PAGING       SHOW         UPDATE
ALTER        CLS          DEBUG        DROP         INSERT       REVOKE       SOURCE       USE
BEGIN        CONSISTENCY  DELETE       EXPAND       LIST         SELECT       TRACING      exit
CAPTURE      COPY         DESC         GRANT        LOGIN        SERIAL       TRUNCATE     quit
cqlsh> DESCRIBE KEYSPACES;
?            CLEAR        CREATE       DESCRIBE     HELP         PAGING       SHOW         UPDATE
ALTER        CLS          DEBUG        DROP         INSERT       REVOKE       SOURCE       USE
BEGIN        CONSISTENCY  DELETE       EXPAND       LIST         SELECT       TRACING      exit
CAPTURE      COPY         DESC         GRANT        LOGIN        SERIAL       TRUNCATE     quit
cqlsh> DESCRIBE KEYSPACES;

demo    system_auth         system_schema  system_views         
system  system_distributed  system_traces  system_virtual_schema

cqlsh> 
?            CLEAR        CREATE       DESCRIBE     HELP         PAGING       SHOW         UPDATE
ALTER        CLS          DEBUG        DROP         INSERT       REVOKE       SOURCE       USE
BEGIN        CONSISTENCY  DELETE       EXPAND       LIST         SELECT       TRACING      exit
CAPTURE      COPY         DESC         GRANT        LOGIN        SERIAL       TRUNCATE     quit
cqlsh> CREATE TABLE demo.users (lastname text PRIMARY KEY, firstname text, email text);
?            CLEAR        CREATE       DESCRIBE     HELP         PAGING       SHOW         UPDATE
ALTER        CLS          DEBUG        DROP         INSERT       REVOKE       SOURCE       USE
BEGIN        CONSISTENCY  DELETE       EXPAND       LIST         SELECT       TRACING      exit
CAPTURE      COPY         DESC         GRANT        LOGIN        SERIAL       TRUNCATE     quit
cqlsh> CREATE TABLE demo.users (lastname text PRIMARY KEY, firstname text, email text);
cqlsh> INSERT INTO users (lastname, firstname, email) VALUES ('Polson', 'Lino', 'lino@example.com');
InvalidRequest: Error from server: code=2200 [Invalid query] message="No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename"
cqlsh> CREATE TABLE demo.users (lastname text PRIMARY KEY, firstname text, email text);
AlreadyExists: Table 'demo.users' already exists
cqlsh> INSERT INTO users (lastname, firstname, email) VALUES ('Round', 'Craig', 'craig@example.com');
InvalidRequest: Error from server: code=2200 [Invalid query] message="No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename"
cqlsh> INSERT INTO users (lastname, firstname, email) VALUES ('Round', 'Craig', 'craig@example.com');
?            CLEAR        CREATE       DESCRIBE     HELP         PAGING       SHOW         UPDATE
ALTER        CLS          DEBUG        DROP         INSERT       REVOKE       SOURCE       USE
BEGIN        CONSISTENCY  DELETE       EXPAND       LIST         SELECT       TRACING      exit
CAPTURE      COPY         DESC         GRANT        LOGIN        SERIAL       TRUNCATE     quit
cqlsh> INSERT INTO users (lastname, firstname, email) VALUES ('Round', 'Craig', 'craig@example.com');
InvalidRequest: Error from server: code=2200 [Invalid query] message="No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename"
cqlsh> 
cqlsh> USE demo;
cqlsh:demo> INSERT INTO users (lastname, firstname, email) VALUES ('Round', 'Craig', 'craig@example.com');
cqlsh:demo> INSERT INTO users (lastname, firstname, email) VALUES ('Pratico', 'Cassi', 'cassi@example.com');
cqlsh:demo> COPY demo.users (lastname, firstname, email) FROM '~/users.csv' WITH HEADER = TRUE;
Using 1 child processes

Starting copy of demo.users with columns [lastname, firstname, email].
Processed: 9 rows; Rate:      13 rows/s; Avg. rate:      20 rows/s
9 rows imported from 1 files in 0.442 seconds (0 skipped).
cqlsh:demo> SELECT * FROM users;

 lastname  | email             | firstname
-----------+-------------------+-----------
     Audly |  sandie@gmail.com |    Sandie
       Fry | viviene@gmail.com |   Viviene
       Phi | krystle@gmail.com |   Krystle
   Cimbura |  trudie@gmail.com |    Trudie
     Karna |     zia@gmail.com |       Zia
 Ursulette | aeriela@gmail.com |   Aeriela
     Timon | nananne@gmail.com |   Nananne
   Pratico | cassi@example.com |     Cassi
     Round | craig@example.com |     Craig
  Callista | katleen@gmail.com |   Katleen
      Harl |   gilda@gmail.com |     Gilda

(11 rows)
cqlsh:demo> UPDATE users SET email = 'lpolson@example.com'  WHERE lastname = 'Polson';
cqlsh:demo> UPDATE users SET email = 'lpolson@example.com'  WHERE lastname = 'Polson';
?            CLEAR        CREATE       DESCRIBE     HELP         PAGING       SHOW         UPDATE
ALTER        CLS          DEBUG        DROP         INSERT       REVOKE       SOURCE       USE
BEGIN        CONSISTENCY  DELETE       EXPAND       LIST         SELECT       TRACING      exit
CAPTURE      COPY         DESC         GRANT        LOGIN        SERIAL       TRUNCATE     quit
cqlsh:demo> UPDATE users SET email = 'lpolson@example.com'  WHERE lastname = 'Polson';
cqlsh:demo> SELECT * FROM users WHERE lastname = 'Polson';

 lastname | email               | firstname
----------+---------------------+-----------
   Polson | lpolson@example.com |      null

(1 rows)
cqlsh:demo> DELETE FROM users WHERE lastname='Polson'
        ...

**Comment by SonicDMG** [comment]
Hi lami35. Thank you for your submission. Please provide a screenshot of the "try-it-out" scenario from the homework step 2.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

**Comment by lami35** [comment]
cqlsh> CREATE TABLE demo.users (lastname text PRIMARY KEY, firstname text, email text);
cqlsh> USE demo;
cqlsh:demo> INSERT INTO users (lastname, firstname, email) VALUES ('Round', 'Craig', 'craig@example.com');
cqlsh:demo> INSERT INTO users (lastname, firstname, email) VALUES ('Pratico', 'Cassi', 'cassi@example.com');
cqlsh:demo> INSERT INTO users (lastname, firstname, email) VALUES ('Polson', 'Lino', 'lino@example.com');
cqlsh:demo> COPY demo.users (lastname, firstname, email) FROM '~/users.csv' WITH HEADER = TRUE;
Using 1 child processes

Starting copy of demo.users with columns [lastname, firstname, email].
Processed: 9 rows; Rate:      15 rows/s; Avg. rate:      23 rows/s
9 rows imported from 1 files in 0.398 seconds (0 skipped).
cqlsh:demo> SELECT * FROM users;

 lastname  | email             | firstname
-----------+-------------------+-----------
     Audly |  sandie@gmail.com |    Sandie
       Fry | viviene@gmail.com |   Viviene
       Phi | krystle@gmail.com |   Krystle
    Polson |  lino@example.com |      Lino
   Cimbura |  trudie@gmail.com |    Trudie
     Karna |     zia@gmail.com |       Zia
 Ursulette | aeriela@gmail.com |   Aeriela
     Timon | nananne@gmail.com |   Nananne
   Pratico | cassi@example.com |     Cassi
     Round | craig@example.com |     Craig
  Callista | katleen@gmail.com |   Katleen
      Harl |   gilda@gmail.com |     Gilda

(12 rows)
cqlsh:demo> SELECT * FROM users WHERE lastname = 'Polson';

 lastname | email            | firstname
----------+------------------+-----------
   Polson | lino@example.com |      Lino

(1 rows)
cqlsh:demo> UPDATE users SET email = 'lpolson@example.com'  WHERE lastname = 'Polson';
cqlsh:demo> SELECT * FROM users WHERE lastname = 'Polson';

 lastname | email               | firstname
----------+---------------------+-----------
   Polson | lpolson@example.com |      Lino

(1 rows)
cqlsh:demo> DELETE FROM users WHERE lastname='Polson';
cqlsh:demo>

**Comment by SonicDMG** [comment]
Ok, looks good lami35, thank you.

**Comment by HadesArchitect** [comment]
Well done! https://api.badgr.io/public/assertions/ZUqFtuIFSWiUTVABUV_icQ?identity__url=https%3A%2F%2Fgithub.com%2Flami35
