### ISSUE TITLE
Cristopher Yerena

### ISSUE THREAD

**Issue by cristoyerenahs** [datastaxdevs/workshop-introduction-to-nosql#291]
**Name:** Cristopher Yerena
**Email:** cristoye_hs@outlook.es
**Linkedin Profile:** https://www.linkedin.com/in/cristopher-yerena-403a21167/

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/60819833/127371196-bbb93229-5641-4b3e-8b1e-56842ff408a0.png)

![image](https://user-images.githubusercontent.com/60819833/127371254-4498f196-4d4e-46df-9831-741c7029f7c8.png)

![image](https://user-images.githubusercontent.com/60819833/127371364-6047ef60-11b9-42e2-a8ff-19097ab2baa7.png)

![image](https://user-images.githubusercontent.com/60819833/127371559-feb78df6-2302-488d-aac6-4eef6be9d16e.png)

![image](https://user-images.githubusercontent.com/60819833/127371716-ae81b064-0bbd-421c-ba83-10cb2be03efb.png)

![image](https://user-images.githubusercontent.com/60819833/127372567-74e4f3c0-d418-4007-bfed-86129adee7a1.png)

![image](https://user-images.githubusercontent.com/60819833/127373668-8f9b8181-a929-4efa-93c2-2b34e75771cb.png)

![image](https://user-images.githubusercontent.com/60819833/127370864-92eef544-f53c-4f06-ae18-18443a9c6336.png)

**Comment by cristoyerenahs** [comment]
Thanks

**Comment by HadesArchitect** [comment]
Hey **Cristopher Yerena**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/NThvEXdRQZ6NC5s4p2YKgA
