### ISSUE TITLE
[HW] <Yesha Soni>

### ISSUE THREAD

**Issue by yeshasoni** [datastaxdevs/workshop-introduction-to-nosql#296]
**Name:** Yesha Soni
**Email:** yeshasoni1999@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/yesha-soni-7724571b3>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot (65)](https://user-images.githubusercontent.com/87908818/127375532-38150569-5c20-41b9-a34e-fe800023d621.png)
![Screenshot (67)_LI](https://user-images.githubusercontent.com/87908818/127375573-b7799d06-6462-4ed1-9e0e-65a3d628561f.jpg)
![Screenshot (76)](https://user-images.githubusercontent.com/87908818/127375630-d819b845-f3d4-4f31-9fa0-440bae9136bf.png)

**Comment by HadesArchitect** [comment]
Hey **Yesha Soni**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/7FEYXDBURmmxA150mAiaSg
