### ISSUE TITLE
[HW] Osama Buhamad

### ISSUE THREAD

**Issue by OsamaBuhamad** [datastaxdevs/workshop-introduction-to-nosql#304]
**Name:** Osama Buhamad
**Email:** osamabuhamad@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/osama-buhamad/

Attach the homework screenshots below:
-----------------------------------------

Step 4:
![4_final](https://user-images.githubusercontent.com/7606429/127381120-0d3168f1-c430-47c4-bcfb-bded89f696da.PNG)

Step 5 (Docker):
![5](https://user-images.githubusercontent.com/7606429/127381159-9af1f884-6ad0-4b15-964a-dc81b9a4520b.PNG)

The  try-it-out scenario:
![scenario_complete](https://user-images.githubusercontent.com/7606429/127381251-61cba6e9-479e-4812-8ea5-f2a81cc15ced.PNG)

**Comment by HadesArchitect** [comment]
Hey **Osama Buhamad**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/cYHO4PgFQjK9gAItsEbnzw
