### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by ssr-1998** [datastaxdevs/workshop-introduction-to-nosql#306]
**Name:** Shubham Singh Rana
**Email:** shubhamsinghrana9@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/shubham-singh-rana-225744138/

Attach the homework screenshots below:
-----------------------------------------

![Manage Database — DataStax Astra - Google Chrome 29-07-2021 00_16_28](https://user-images.githubusercontent.com/61390050/127381677-62e939bd-3c6f-4a74-8f11-adc840622f55.png)

![datastaxdevs_workshop-introduction-to-nosql_ Hands-on for Introduction to NoSQL - Google Chrome 29-07-2021 00_35_04](https://user-images.githubusercontent.com/61390050/127381747-8fdbfb3d-9f50-452d-9cda-5545c8159094.png)

**Comment by HadesArchitect** [comment]
Hey **Shubham Singh Rana**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/kk4A6eLWTAKADGaf0qibuQ
