### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by gustavofpereira** [datastaxdevs/workshop-introduction-to-nosql#307]
**Name:** GUSTAVO FURTADO PEREIRA
**Email:** gustavo.pereira@sofist.com.br
**Linkedin Profile:** https://www.linkedin.com/in/gustavo-pereira-915b4a/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![step I](https://user-images.githubusercontent.com/48485573/127383026-e989921c-e627-4e54-9b60-0ec5b58ed58a.png)
![step II](https://user-images.githubusercontent.com/48485573/127383039-c0da4879-6f2f-4312-9297-ee86e7ed2519.png)
![step III](https://user-images.githubusercontent.com/48485573/127383047-576cd927-3ce6-42be-a48e-e2ad385f7098.png)
![step IV](https://user-images.githubusercontent.com/48485573/127383059-ae0d4d54-a995-46e6-9576-d998a8a73fb5.png)
![try-it-out scenario](https://user-images.githubusercontent.com/48485573/127383074-00af8095-2e2b-4b0a-8d9c-6a2b329608cf.png)

**Comment by HadesArchitect** [comment]
Hey **GUSTAVO FURTADO PEREIRA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/fKIbfv0TRIGN9JQx0lpijA
