### ISSUE TITLE
[HW] SAMNIT MEHANDIRATTA

### ISSUE THREAD

**Issue by lankabhedi** [datastaxdevs/workshop-introduction-to-nosql#308]
**Name:** Samnit Mehandiratta
**Email:** slmehandiratta@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/lankabhedi/

Attach the homework screenshots below:
-----------------------------------------

-- image removed by team --
![image](https://user-images.githubusercontent.com/50140975/127383651-1957ee40-6a91-45be-bdc5-968c546181e7.png)
-- image removed by team --
![image](https://user-images.githubusercontent.com/50140975/127383734-fa3705fc-672c-451e-bd40-7c481ef196d7.png)

![image](https://user-images.githubusercontent.com/50140975/127383060-b4c623d1-fecc-4439-8168-15a1230437f1.png)

**Comment by HadesArchitect** [comment]
Hey **Samnit Mehandiratta**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/x8zkELbvSsOU3sA3lwM-OA
