### ISSUE TITLE
[HW] Prateek Raj Singh

### ISSUE THREAD

**Issue by spunkprs** [datastaxdevs/workshop-introduction-to-nosql#31]
Name: Prateek Raj Singh
Email: prateekraj1988@gmail.com
Linkedin Profile: https://www.linkedin.com/in/prateek-raj-35a5b453/

Attach the homework screenshots below:
-----------------------------------------

Tabular DB

<img width="1792" alt="1" src="https://user-images.githubusercontent.com/16477041/117627457-cfd4b800-b195-11eb-8372-2e07d43b41c4.png">
<img width="1792" alt="2" src="https://user-images.githubusercontent.com/16477041/117627477-d5ca9900-b195-11eb-84c7-7f3b1038bc97.png">
<img width="1792" alt="3" src="https://user-images.githubusercontent.com/16477041/117627485-d6fbc600-b195-11eb-89fb-69ddc3bc3877.png">
<img width="1792" alt="4" src="https://user-images.githubusercontent.com/16477041/117627507-dc591080-b195-11eb-9a7f-4945b51c8956.png">
<img width="1792" alt="5" src="https://user-images.githubusercontent.com/16477041/117627525-e1b65b00-b195-11eb-8df1-4a6583a98959.png">
<img width="1792" alt="6" src="https://user-images.githubusercontent.com/16477041/117627546-e7ac3c00-b195-11eb-998b-2b753cde97af.png">
<img width="1792" alt="7" src="https://user-images.githubusercontent.com/16477041/117627585-f0047700-b195-11eb-8f46-42698edab6c8.png">
<img width="1792" alt="8" src="https://user-images.githubusercontent.com/16477041/117627597-f2ff6780-b195-11eb-9d5b-14d875183069.png">
<img width="1792" alt="9" src="https://user-images.githubusercontent.com/16477041/117627605-f5fa5800-b195-11eb-843b-1de64b06c2fd.png">
<img width="1792" alt="10" src="https://user-images.githubusercontent.com/16477041/117627613-f98ddf00-b195-11eb-99eb-bfb2e049a17a.png">
<img width="1792" alt="11" src="https://user-images.githubusercontent.com/16477041/117627633-fe529300-b195-11eb-8fa7-9fac0e48ad18.png">
<img width="1792" alt="12" src="https://user-images.githubusercontent.com/16477041/117627661-03afdd80-b196-11eb-8a59-fcc052273c0d.png">

Document DB

<img width="1792" alt="1" src="https://user-images.githubusercontent.com/16477041/117627809-2641f680-b196-11eb-9b73-6b426f613d8b.png">
<img width="1792" alt="2" src="https://user-images.githubusercontent.com/16477041/117627841-2c37d780-b196-11eb-98ff-c2135e6cfad4.png">
-- images removed by team --

KeyValue DB

-- images removed by team --
<img width="1792" alt="3" src="https://user-images.githubusercontent.com/16477041/117628064-6012fd00-b196-11eb-865a-e3839d26df1b.png">
-- images removed by team --
<img width="1792" alt="5" src="https://user-images.githubusercontent.com/16477041/117628079-63a68400-b196-11eb-9050-dcb9e41c7768.png">
-- images removed by team --
<img width="1792" alt="7" src="https://user-images.githubusercontent.com/16477041/117628093-66a17480-b196-11eb-89b7-59ecc0d901b6.png">

Try It Out Scenario

<img width="1792" alt="13" src="https://user-images.githubusercontent.com/16477041/117628274-9781a980-b196-11eb-81ce-bcbcc51acfca.png">

**Comment by SonicDMG** [comment]
Looks good Prateek, thank you.

**Comment by HadesArchitect** [comment]
Great job, here we go: https://api.badgr.io/public/assertions/wa-q2xX7SfSC2JCivVm9MA?identity__email=prateekraj1988%40gmail.com
