### ISSUE TITLE
[HW] Josses Leono

### ISSUE THREAD

**Issue by JL1606** [datastaxdevs/workshop-introduction-to-nosql#310]
**Name:** Josses Leono
**Email:** josses_pmr@yahoo.com
**Linkedin Profile:** https://www.linkedin.com/in/josses-leono/

Attach the homework screenshots below:
-----------------------------------------

### Step 1

<img width="1918" alt="Step 1" src="https://user-images.githubusercontent.com/38059655/127385274-8e365ba7-afe8-49eb-9c9e-0f0228b87043.png">

### Step 2

<img width="1918" alt="Step 2" src="https://user-images.githubusercontent.com/38059655/127385268-547f8f9c-21aa-4b9a-a804-303d1ca9844e.png">

### Step 3

<img width="1438" alt="Step 3" src="https://user-images.githubusercontent.com/38059655/127385265-859308d3-cfc3-4c61-a95c-f3c2b71406ed.png">

### Step 4

<img width="1919" alt="Step 4" src="https://user-images.githubusercontent.com/38059655/127385393-ccee40ab-8ada-4f84-9319-00c740242eb6.png">

### Try it out

<img width="1366" alt="Try it out" src="https://user-images.githubusercontent.com/38059655/127385246-edf7c8b8-9134-4a60-b837-ed4b2d2d214c.png">

**Comment by HadesArchitect** [comment]
Hey **Josses Leono**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Sgoenxx8TNe1TFE0aDvmkw
