### ISSUE TITLE
[HW] <Thomas Brentnall>

### ISSUE THREAD

**Issue by khelderb** [datastaxdevs/workshop-introduction-to-nosql#311]
**Name:** Thomas Brentnall
**Email:** thcbrentnall@outlook.com
**Linkedin Profile:** <https://www.linkedin.com/in/thomas-b-3b9a50100/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot (40)](https://user-images.githubusercontent.com/49045017/127388015-8c80aa63-44ff-45b2-87cf-5bf0d80b2acd.png)
![Screenshot (39)](https://user-images.githubusercontent.com/49045017/127388018-beebb70a-af53-42e8-858e-a96474c5d692.png)

**Comment by HadesArchitect** [comment]
Hey **Thomas Brentnall**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/kApSgYUdQmG0pDwcPJVJ2Q
