### ISSUE TITLE
[HW] <Anish Kumar Nagpal>

### ISSUE THREAD

**Issue by anish-nagpal** [datastaxdevs/workshop-introduction-to-nosql#312]
**Name:** Anish Kumar Nagpal
**Email:** anish.nagpal07@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/anish-nagpal-csm-safe-agilist-safe-practitioner-6299a24b/
[Homework - Anish Nagpal.docx](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/6896147/Homework.-.Anish.Nagpal.docx)
>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Anish Kumar Nagpal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/6hbGKuJ9Tea4gIp1ThSXeg

**Comment by anish-nagpal** [comment]
Thank you for providing the opportunity to learn !!
