### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by srihawi** [datastaxdevs/workshop-introduction-to-nosql#313]
**Name:** Samer Rihawi
**Email:** srihawi84@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/samerrihawi/

Attach the homework screenshots below:
-----------------------------------------

![screenshot1](https://user-images.githubusercontent.com/12184277/127396866-c63cff01-5e25-48e6-a8ce-eada5c023a57.JPG)
![screenshot2](https://user-images.githubusercontent.com/12184277/127396870-7fbe4a2b-3bd4-42f7-8764-2887fa93867e.JPG)
![screenshot3](https://user-images.githubusercontent.com/12184277/127396873-45812bf3-1e82-43b6-accf-7162dc8e367f.JPG)
![screenshot4](https://user-images.githubusercontent.com/12184277/127396875-bd62fb1c-ca6e-4f0d-95db-9f154a60be69.JPG)
![screenshot5](https://user-images.githubusercontent.com/12184277/127396876-c9c8ca57-bbb5-46c7-aa2e-ff9baeee8234.JPG)
![screenshot6](https://user-images.githubusercontent.com/12184277/127396879-da60df5d-5ab5-4228-b024-25902cbfbc40.JPG)
![screenshot7](https://user-images.githubusercontent.com/12184277/127396882-57d4cc1a-9f67-41bb-92d6-2e1f40dcc60f.JPG)
![screenshot8](https://user-images.githubusercontent.com/12184277/127396884-7aef8cf0-280a-4afd-80ca-044075f0967e.JPG)
![screenshot9](https://user-images.githubusercontent.com/12184277/127396888-898fc3d9-8855-4ff8-a768-d6714424c13d.JPG)

**Comment by HadesArchitect** [comment]
Hey **Samer Rihawi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/-Xx0zFHXQp2Q5DcmMz1Cdg
