### ISSUE TITLE
[HW] Luis Eduardo Partichelli Potrich

### ISSUE THREAD

**Issue by LuisPotrich** [datastaxdevs/workshop-introduction-to-nosql#315]
**Name:** Luis Eduardo Partichelli Potrich
**Email:** dudupotrich@gmail.com
**Linkedin Profile:** linkedin.com/in/luispotrich/

Attach the homework screenshots below:
-----------------------------------------
1)
![SC](https://user-images.githubusercontent.com/13707176/127413422-a74f3f89-0116-4dd3-ad76-978df95b6f6d.png)

2)
![Print_try](https://user-images.githubusercontent.com/13707176/127413427-29ec27b2-5843-4dca-b5bf-6d13d4ea5b64.png)

EXTRA:

create keyspace abc with replication = {'class':'SimpleStrategy', 'replication_factor':1};

create table abc.def (thanks text primary key, for text);

insert into abc.def (thanks,for) values ('the','course');

select * from abc.def;

![Print_end](https://user-images.githubusercontent.com/13707176/127413426-bc39dd74-5d85-49c8-b931-43dc39bcc54a.png)

**Comment by LuisPotrich** [comment]
These are my screenshots.

Thank you very much for the introductory course. :)

**Comment by HadesArchitect** [comment]
Hey **Luis Eduardo Partichelli Potrich**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/kqscO8AmT66DfVMFX1If6w
