### ISSUE TITLE
[HW] Andrius Pontim

### ISSUE THREAD

**Issue by AndriusHP** [datastaxdevs/workshop-introduction-to-nosql#316]
**Name:** Andrius Pontim
**Email:** andrius_pontim@dell.com
**Linkedin Profile:** https://www.linkedin.com/in/andriuspontim/

Attach the homework screenshots below:
-----------------------------------------

![workshop_practice_steps_pt I](https://user-images.githubusercontent.com/87487200/127416162-f0ed2936-ad06-42fd-8995-af477ce966c1.jpg)

![workshop_practice_steps_pt II](https://user-images.githubusercontent.com/87487200/127416175-ecddb658-976f-4322-9b5a-2338df684e66.jpg)

![tryitout_scenario](https://user-images.githubusercontent.com/87487200/127416183-30b7d198-4525-490b-9e3f-e8dbff4a424a.jpg)

**Comment by HadesArchitect** [comment]
Hey **Andrius Pontim**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Hq4GOOqbQzSYieQHeiVZig
