### ISSUE TITLE
No SQL - Samarth

### ISSUE THREAD

**Issue by samarthbansal258** [datastaxdevs/workshop-introduction-to-nosql#317]
**Name:** Samarth Bansal
**Email:** samarth.bansal@pathways.in
**Linkedin Profile:** https://www.linkedin.com/in/samarth-bansal-06b043218/

Attach the homework screenshots below:
-----------------------------------------
 (Step 4) I experimented with values !
<img width="1440" alt="Screenshot 2021-07-29 at 9 21 48 AM" src="https://user-images.githubusercontent.com/86355086/127428976-53d0a37a-d5a2-49d9-9a62-9e1eb39f3416.png">

(Scenario Completed)
<img width="1440" alt="Screenshot 2021-07-29 at 9 05 02 AM" src="https://user-images.githubusercontent.com/86355086/127428273-8851613e-b092-4ee9-9b1f-5e8bc15490f4.png">
(Scenario Completed)

**Comment by HadesArchitect** [comment]
Hey **Samarth Bansal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/3C0y3e7FQIqD3ZFkb-6NUQ
