### ISSUE TITLE
[HW] NoSQL-Luis

### ISSUE THREAD

**Issue by ldruizsan** [datastaxdevs/workshop-introduction-to-nosql#319]
**Name:** Luis Ruiz-Santiago
**Email:** ldruizsan@gmail.com
**Linkedin Profile:** linkedin.com/in/luisruiz1

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![scenario_complete](https://user-images.githubusercontent.com/69827353/131777428-bae8c5bd-2636-4870-9443-28f0692b7ee1.png)
![Inkedtry-it-out-3d_LI](https://user-images.githubusercontent.com/69827353/131777754-d0c80e22-8c75-4c9f-acb6-2e7edc48b2e0.jpg)
![Inkedtry-it-out-3f_LI](https://user-images.githubusercontent.com/69827353/131777756-9edbf687-d79e-4ab1-bfdc-1af3ef46cc5e.jpg)
![try-it-out-2-tables1](https://user-images.githubusercontent.com/69827353/131777890-b3652168-f9d8-4f9e-9110-0b89aa974bba.png)
![try-it-out-2-videos1](https://user-images.githubusercontent.com/69827353/131777948-0bdeac56-bdd8-4da3-96ef-18b8feb595b1.png)
![try-it-out-3f](https://user-images.githubusercontent.com/69827353/131778178-253d38d7-add5-4207-b2b2-8020d9641131.png)
![try-it-out-3g](https://user-images.githubusercontent.com/69827353/131778210-fec40beb-a1a3-4d6a-af04-f34af2385c76.png)
![try-it-out-3d](https://user-images.githubusercontent.com/69827353/131778232-4d8cc360-49c0-4720-9456-d8607c97567d.png)
![try-it-out-3e](https://user-images.githubusercontent.com/69827353/131778303-2ac13565-ac4b-4811-8757-c8808639eebf.png)
![try-it-out-4-key_value](https://user-images.githubusercontent.com/69827353/127436319-5a01cab6-9399-45a4-8ecf-580df46a54dc.png)
![try-it-out-1](https://user-images.githubusercontent.com/69827353/127436320-1f4be9ae-3c8d-4975-92a9-9e0211bd0890.png)

**Comment by SonicDMG** [comment]
Hi there Luis, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by SonicDMG** [comment]
Also, I had to remove many of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.

**Comment by ldruizsan** [comment]
I updated the images and hid the Astra key. Also added is the "scenario completed" screen.

**Comment by HadesArchitect** [comment]
Hey **Luis Ruiz**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/-R0BIbTsSfWEx5Jobw_U2g
