### ISSUE TITLE
[HW] <K S A R AMBEDKAR>

### ISSUE THREAD

**Issue by ambedkar1985** [datastaxdevs/workshop-introduction-to-nosql#32]
**Name:** K S A R AMBEDKAR
**Email:** <ambedkar1985@gmail.com
[HW Assignment of Introduction to NoSQL Databases.pdf](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/6453288/HW.Assignment.of.Introduction.to.NoSQL.Databases.pdf)
>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks good, thank you.

**Comment by HadesArchitect** [comment]
Duplicate of #27
