### ISSUE TITLE
[HW] Drishti Nishchhal Sahu

### ISSUE THREAD

**Issue by drishtinishchhal** [datastaxdevs/workshop-introduction-to-nosql#320]
**Name:** DRISHTI NISHCHHAL SAHU
**Email:** drishti_nishchhal@rediffmail.com
**Linkedin Profile:** https://www.linkedin.com/in/drishti-nishchhal-sahu-2b021b3a/

Attach the homework screenshots below:
-----------------------------------------
### **_Key-Value DB-_**

<img width="1559" alt="Key_Value_2021-07-29 at 11 56 16 AM" src="https://user-images.githubusercontent.com/88125050/127442496-3d6363f5-f586-427f-bc4f-d4e23aba75bd.png">

<img width="1602" alt="Key_Value_Screenshot 2021-07-29 at 9 54 13 AM" src="https://user-images.githubusercontent.com/88125050/127442877-736187f7-a2b7-47f5-b8f7-9b770956e6d2.png">

<img width="1603" alt="Key_Value_Screenshot 2021-07-29 at 9 53 37 AM" src="https://user-images.githubusercontent.com/88125050/127442925-ba68c709-b1a3-43cc-b68d-ff17c765524e.png">

### **_Tabular DB -_**

<img width="1592" alt="Tabular_Screenshot 2021-07-29 at 9 59 51 AM" src="https://user-images.githubusercontent.com/88125050/127431819-1be6b8ea-5e98-47f2-a593-230f77fbcb6b.png">

###  **_Document Databases -_**

<img width="1497" alt="Document_Screenshot_2021-07-29 at 11 11 46 AM" src="https://user-images.githubusercontent.com/88125050/127437871-996da8b6-d4a0-447b-b5e1-8ad48243c0d5.png">

<img width="1246" alt="Screenshot_Try_It_Out" src="https://user-images.githubusercontent.com/88125050/127515421-def1eb70-eed3-4b06-83b5-c6f7c67f05df.png">

**Comment by drishtinishchhal** [comment]
@HadesArchitect @RyanWelford @SonicDMG - Please let me know if anything is missing in screenshot, thank you.

**Comment by drishtinishchhal** [comment]
Added TryItOut screen shot.

**Comment by HadesArchitect** [comment]
Hey **DRISHTI NISHCHHAL SAHU**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/_FhmZZFFRxSAiQ69GUSRvw
