### ISSUE TITLE
[HW] Sachin Shivaji Patil

### ISSUE THREAD

**Issue by thesachinpatil** [datastaxdevs/workshop-introduction-to-nosql#324]
**Name:** Sachin Shivaji Patil
**Email:** sachinspatil1990@gmail.com
**Linkedin Profile:** -

Attach the homework screenshots below:
-----------------------------------------
Scenario:
<img width="957" alt="scenario-completed" src="https://user-images.githubusercontent.com/17435782/127460592-36d987b3-565f-4bd8-9a73-9d75fa93a006.png">

Step1:
![step1](https://user-images.githubusercontent.com/17435782/127460659-b4561a48-20df-4e27-a689-daf9975b43de.png)

Step2:

a: 
![step2a](https://user-images.githubusercontent.com/17435782/127460750-f324d991-6a68-431f-b192-c13fb0f5992d.png)

b:
![step2b](https://user-images.githubusercontent.com/17435782/127460785-0b42d67a-8d5f-44d1-bd9b-aa9a8b96f721.png)

c:
![step2c](https://user-images.githubusercontent.com/17435782/127460825-391272ce-9791-4413-9a7a-da2bf10d1b40.png)

d:
![step2d](https://user-images.githubusercontent.com/17435782/127460862-34c1966a-fa88-4e8b-9417-627c6beedd61.png)

Step3:

a:
![step3a](https://user-images.githubusercontent.com/17435782/127461018-025bdb41-0fc1-4a65-b707-1f32c5c761a4.png)

b:
<img width="960" alt="step3b" src="https://user-images.githubusercontent.com/17435782/127461028-fdcf948e-29ec-406a-b532-6388273397f9.png">

c:
![step3c](https://user-images.githubusercontent.com/17435782/127461039-46497f2d-0c86-4704-b0e6-06954fc2b74d.png)

d:
<img width="931" alt="step3d" src="https://user-images.githubusercontent.com/17435782/127461057-39acb85a-62a4-4aed-9dfe-87e41c1bec19.png">

e:
<img width="960" alt="step3e" src="https://user-images.githubusercontent.com/17435782/127461074-2b0b3446-6f2e-4e74-8429-738bb265108c.png">

f:
<img width="954" alt="step3f" src="https://user-images.githubusercontent.com/17435782/127461105-eaf342b9-a13f-488c-ba24-5a954faab83f.png">

g:
<img width="950" alt="step3g" src="https://user-images.githubusercontent.com/17435782/127461127-bc7cf6cd-11b1-4284-9a96-bd1a26882ae9.png">

Step4:

b:
![step4b](https://user-images.githubusercontent.com/17435782/127461211-6a1d7435-4f7b-48fd-8de5-c28d61add20c.png)

c1:
![step4c](https://user-images.githubusercontent.com/17435782/127461230-09947b21-90df-48fb-bb62-0230899e661f.png)

c2:
![step4c-1](https://user-images.githubusercontent.com/17435782/127461237-0de02745-aad0-4314-9d4d-6b9dfd97b62f.png)

**Comment by HadesArchitect** [comment]
Hey **Sachin Shivaji Patil**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/h63EyMYTSW6cWSK3TSo8yA
