### ISSUE TITLE
[HW] Sterlin Peter

### ISSUE THREAD

**Issue by SterlinPeter** [datastaxdevs/workshop-introduction-to-nosql#325]
**Name:** Sterlin Peter
**Email:** sterlinpeter98@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/54246219/127465651-cc5a58d4-6508-424b-ab69-48495eb2e685.png)
![image](https://user-images.githubusercontent.com/54246219/127465732-b2f24a1a-7ec0-42ba-a332-133bc348aba6.png)

**Comment by HadesArchitect** [comment]
Hey **Sterlin Peter**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/fBdjIVw-QgWGXzy8g8KTUQ
