### ISSUE TITLE
[HW] <DON ANNE SNEHA GAMLATHMOHOTTY>

### ISSUE THREAD

**Issue by annesneha18** [datastaxdevs/workshop-introduction-to-nosql#326]
**Name:** DON ANNE SNEHA GAMLATHMOHOTTY
**Email:** grusthappy@hotmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/don-anne-sneha-gamlathmohotty-20875718b/>

Attach the homework screenshots below:
-----------------------------------------

<
![image](https://user-images.githubusercontent.com/86648529/127465981-4a329749-adbd-4f2b-8d86-6849e4728295.png)
>

**Comment by SonicDMG** [comment]
Hi there Don, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by SonicDMG** [comment]
Ok, I see your completed scenario in issue https://github.com/datastaxdevs/workshop-introduction-to-nosql/issues/327.

**Comment by HadesArchitect** [comment]
Hey **DON ANNE SNEHA GAMLATHMOHOTTY**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/sZ_dSA2uT36rG7ic9GcTBA
