### ISSUE TITLE
[HW] Siddharth Phatarphod

### ISSUE THREAD

**Issue by psid23** [datastaxdevs/workshop-introduction-to-nosql#328]
**Name:** Siddharth Phatarphod
**Email:** spp23@hotmail.com
**Linkedin Profile:** https://www.linkedin.com/in/siddharth-p-9565399/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![image](https://user-images.githubusercontent.com/40687015/127472854-015bed11-c72e-4bf3-8fea-b44a146e95f0.png)
![image](https://user-images.githubusercontent.com/40687015/127473015-7117a510-1955-46ad-bc85-cf05722a4793.png)

**Comment by HadesArchitect** [comment]
Hey **Siddharth Phatarphod**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/KoYOSgjlQrikraTqHGZE3Q
