### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by akshayanand1294** [datastaxdevs/workshop-introduction-to-nosql#329]
**Name:** Akshay Anand
**Email:** akshayanandpat0@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/akshay-anand-452760107/
![last_screenshot_step_4](https://user-images.githubusercontent.com/40790005/127475450-d5cd54a4-2a2b-4d83-8cc1-96277a54b6c0.JPG)
![output_from_key_value_table](https://user-images.githubusercontent.com/40790005/127475728-18373645-c1d3-44d0-bf35-08dca05870b1.JPG)

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

After completing till Stage 4, copying the description of my keyspace **nosql123**

token@cqlsh:nosql123> describe keyspace nosql123;

CREATE KEYSPACE nosql123 WITH replication = {'class': 'NetworkTopologyStrategy', 'us-east4': '3'}  AND durable_writes = true;

CREATE TABLE nosql123.key_value (
    key text PRIMARY KEY,
    value text
) WITH additional_write_policy = '99PERCENTILE'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.UnifiedCompactionStrategy', 'log_all': 'true', 'num_shards': '128'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99PERCENTILE';

CREATE TABLE nosql123.users_by_city (
    city text,
    lastname text,
    email text,
    firstname text,
    PRIMARY KEY (city, lastname, email)
) WITH CLUSTERING ORDER BY (lastname ASC, email ASC)
    AND additional_write_policy = '99PERCENTILE'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.UnifiedCompactionStrategy', 'log_all': 'true', 'num_shards': '128'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99PERCENTILE';

CREATE TABLE nosql123.videos (
    videoid uuid PRIMARY KEY,
    email text,
    frames list<int>,
    tags set<text>,
    title text,
    upload timestamp,
    url text
) WITH additional_write_policy = '99PERCENTILE'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.UnifiedCompactionStrategy', 'log_all': 'true', 'num_shards': '128'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99PERCENTILE';

CREATE TABLE nosql123.col1 (
    key text,
    p0 text,
    p1 text,
    p2 text,
    p3 text,
    p4 text,
    p5 text,
    p6 text,
    p7 text,
    p8 text,
    p9 text,
    p10 text,
    p11 text,
    p12 text,
    p13 text,
    p14 text,
    p15 text,
    p16 text,
    p17 text,
    p18 text,
    p19 text,
    p20 text,
    p21 text,
    p22 text,
    p23 text,
    p24 text,
    p25 text,
    p26 text,
    p27 text,
    p28 text,
    p29 text,
    p30 text,
    p31 text,
    p32 text,
    p33 text,
    p34 text,
    p35 text,
    p36 text,
    p37 text,
    p38 text,
    p39 text,
    p40 text,
    p41 text,
    p42 text,
    p43 text,
    p44 text,
    bool_value tinyint,
    dbl_value double,
    leaf text,
    text_value text,
    PRIMARY KEY (key, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21, p22, p23, p24, p25, p26, p27, p28, p29, p30, p31, p32, p33, p34, p35, p36, p37, p38, p39, p40, p41, p42, p43, p44)
) WITH CLUSTERING ORDER BY (p0 ASC, p1 ASC, p2 ASC, p3 ASC, p4 ASC, p5 ASC, p6 ASC, p7 ASC, p8 ASC, p9 ASC, p10 ASC, p11 ASC, p12 ASC, p13 ASC, p14 ASC, p15 ASC, p16 ASC, p17 ASC, p18 ASC, p19 ASC, p20 ASC, p21 ASC, p22 ASC, p23 ASC, p24 ASC, p25 ASC, p26 ASC, p27 ASC, p28 ASC, p29 ASC, p30 ASC, p31 ASC, p32 ASC, p33 ASC, p34 ASC, p35 ASC, p36 ASC, p37 ASC, p38 ASC, p39 ASC, p40 ASC, p41 ASC, p42 ASC, p43 ASC, p44 ASC)
    AND additional_write_policy = '99PERCENTILE'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.UnifiedCompactionStrategy', 'log_all': 'true', 'num_shards': '128'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX col1_leaf_idx ON nosql123.col1 (leaf) USING 'StorageAttachedIndex';
CREATE CUSTOM INDEX col1_text_value_idx ON nosql123.col1 (text_value) USING 'StorageAttachedIndex';
CREATE CUSTOM INDEX col1_bool_value_idx ON nosql123.col1 (bool_value) USING 'StorageAttachedIndex';
CREATE CUSTOM INDEX col1_dbl_value_idx ON nosql123.col1 (dbl_value) USING 'StorageAttachedIndex';

**Comment by HadesArchitect** [comment]
Hey **Akshay Anand**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/-9J-PZaeRs6vzdOF4WaSFA
