### ISSUE TITLE
[HW] KHANSA KHANAM U 

### ISSUE THREAD

**Issue by khankhanprof** [datastaxdevs/workshop-introduction-to-nosql#33]
**Name:** KHANSA KHANAM U 
**Email:** khankhanprof@protonmail.com
**Linkedin Profile:** https://www.linkedin.com/in/khansa-khanam-baa07115a/

-----------------------------------------
**STEP 1: CREATE ASTRA INSTANCE** 
![image](https://user-images.githubusercontent.com/82834648/117925935-91fe9d80-b315-11eb-8333-d814055bc46e.png)

**STEP 2: TABULAR DATABASES** 
![image](https://user-images.githubusercontent.com/82834648/117942369-9bddcc00-b328-11eb-8444-5ff640c94467.png)
![image](https://user-images.githubusercontent.com/82834648/117942443-b1eb8c80-b328-11eb-8a1e-47654502920d.png)
![image](https://user-images.githubusercontent.com/82834648/117942503-c2036c00-b328-11eb-9339-957ae4316dd0.png)

**2d. working with partitions :**
![image](https://user-images.githubusercontent.com/82834648/117943058-5f5ea000-b329-11eb-8c1f-ccf7d7e89074.png)
![image](https://user-images.githubusercontent.com/82834648/117943856-325ebd00-b32a-11eb-9d60-ff22fa5ee797.png)
![image](https://user-images.githubusercontent.com/82834648/117944190-9ed9bc00-b32a-11eb-9644-1bee8eb69c22.png)
![image](https://user-images.githubusercontent.com/82834648/117944393-d6486880-b32a-11eb-81c7-18a46e5a13fd.png)

**STEP 3: DOCUMENT  DATABASES**
![image](https://user-images.githubusercontent.com/82834648/117952312-aef59980-b332-11eb-81bb-66b9b0103ee5.png)
-- images removed by team --

**STEP 4: KEYVALUE DATABASES**
-- images removed by team --

**TRY-IT-OUT-SCENARIO**
![image](https://user-images.githubusercontent.com/82834648/117975689-8f6b6a80-b34c-11eb-9cd5-a2c80a5df4ec.png)
![image](https://user-images.githubusercontent.com/82834648/117975885-cb9ecb00-b34c-11eb-85f1-8193fa1803a7.png)

**Comment by SonicDMG** [comment]
Looks good Khansa, thank you.

**Comment by khankhanprof** [comment]
thank you so much sir !

**Comment by HadesArchitect** [comment]
Well done! Here we go: https://api.badgr.io/public/assertions/F9Q5t4aiQ9iCjT7fwoCDUA?identity__email=khankhanprof%40protonmail.com
