### ISSUE TITLE
[HW] Kaushal Devlekar

### ISSUE THREAD

**Issue by Kaushaldev15** [datastaxdevs/workshop-introduction-to-nosql#330]
**Name:** Kaushal Devlekar
**Email:** kaushaldev15@outlook.com
**Linkedin Profile:** https://www.linkedin.com/in/kaushal-devlekar-006a1a218/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![2](https://user-images.githubusercontent.com/47110249/127482238-66f6fdeb-cff8-46e4-9924-b075b9e04806.png)
![1](https://user-images.githubusercontent.com/47110249/127482241-392c9420-dca8-4490-b77b-c3ec22f37e4c.png)

**Comment by HadesArchitect** [comment]
Hey **Kaushal Devlekar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/gC-tiOZ7QJi3Z384OjU1hw
