### ISSUE TITLE
[HW] Saakshi

### ISSUE THREAD

**Issue by SaakshiSuresh** [datastaxdevs/workshop-introduction-to-nosql#334]
**Name:** Saakshi Suresh
**Email:** saakshisuresh11@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

![nosql1](https://user-images.githubusercontent.com/74911931/127489217-dd0523a2-0bb2-4dd7-98f6-0e6634066956.jpg)
![nosql2](https://user-images.githubusercontent.com/74911931/127489220-5b892548-8278-4875-8a7a-18ab6aab2877.jpg)
![nosql3](https://user-images.githubusercontent.com/74911931/127489224-1b04414a-9c6f-4b80-903f-d2f3dd7d91f2.jpg)
![nosql4](https://user-images.githubusercontent.com/74911931/127489237-63e1c531-f36c-418c-942a-25618ad5fb15.jpg)

**Comment by HadesArchitect** [comment]
Hey **Saakshi Suresh**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/gtzDtMzoSt68JRNw30HQRQ
