### ISSUE TITLE
[HW] <Rahul Raj Kanagaraj>

### ISSUE THREAD

**Issue by RahulRajdkp** [datastaxdevs/workshop-introduction-to-nosql#335]
**Name: Rahul Raj Kanagaraj
**Email: rahulrajdk@yahoo.com 
**Linkedin Profile: https://www.linkedin.com/in/rahulrajkanagaraj/

Attach the homework screenshots below:
-----------------------------------------
![no_sql_graphdb_exe](https://user-images.githubusercontent.com/57712808/127502059-103c9b7a-753a-47ab-a0d9-e1a1ab8499d3.PNG)
![no_sql_4](https://user-images.githubusercontent.com/57712808/127502099-9377ffc0-0e9e-41c4-b141-282b9e57da91.PNG)

I also created this infographic after our workshop:
---------------------------------------------------------------
[NoSQL Databases.pdf](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/6900909/NoSQL.Databases.pdf)
![NoSQL Databases](https://user-images.githubusercontent.com/57712808/127502464-8e281bea-13f7-40d0-8e93-c6346d1cbfa6.png)

**Comment by SonicDMG** [comment]
Hi there Rahul, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by RahulRajdkp** [comment]
Hello,

I missed attaching the screenshot of try-it-out. Please find attached now.
![datastax-try-it-out](https://user-images.githubusercontent.com/57712808/129050375-8c3885b8-fc8a-4363-a4f9-fff42cf80451.PNG)

**Comment by HadesArchitect** [comment]
Hey **Rahul Raj Kanagaraj**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/h8dhAi5NQkWhMht5nG8Wlg

**Comment by SonicDMG** [comment]
Thank you very much for following up.
