### ISSUE TITLE
[HW] Markus Fleischmann

### ISSUE THREAD

**Issue by oldrover** [datastaxdevs/workshop-introduction-to-nosql#336]
**Name:** Markus Fleischmann
**Email:** oldrover@web.de
**Linkedin Profile:** http://www.linkedin.com/in/markusfleischmann

Attach the homework screenshots below:
-----------------------------------------

![Screenshot1](https://i.postimg.cc/sfPcGKms/screen1.jpg)
![Screenshot2](https://i.postimg.cc/t4ctGcqt/screen2.jpg)
![Screenshot3](https://i.postimg.cc/ncH147S7/screen3.jpg)
![Screenshot4](https://i.postimg.cc/XYqchWbY/screen4.jpg)
![Screenshot5](https://i.postimg.cc/nr1G8crC/screen5.jpg)
![Screenshot6](https://i.postimg.cc/qMjxjRWF/screen6.jpg)
![Screenshot7](https://i.postimg.cc/RFKTRTz1/screen7.jpg)

**Comment by HadesArchitect** [comment]
Hey **Markus Fleischmann**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/RBAj0BQcSy2P9j2TTAE0zQ
