### ISSUE TITLE
[HW] Syed Awes Hashmi

### ISSUE THREAD

**Issue by Awes786** [datastaxdevs/workshop-introduction-to-nosql#337]
**Name:** Syed Awes Hashmi
**Email:** aweshashmi786@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/syed-awes-hashmi-4b3265a2

Attach the homework screenshots below:
-----------------------------------------
<img width="960" alt="graphschema" src="https://user-images.githubusercontent.com/16688716/127516350-599fa62e-d1a4-412f-a50c-09e863f2515f.png">
<img width="960" alt="step5" src="https://user-images.githubusercontent.com/16688716/127515453-463a5cf6-ba51-4a33-86e9-30360af9a09d.png">
<img width="960" alt="console" src="https://user-images.githubusercontent.com/16688716/127516844-e15128ad-1c75-47d2-a683-7ba24b4f4ab1.png">
<img width="954" alt="scnerio" src="https://user-images.githubusercontent.com/16688716/127515469-15096061-17dc-40be-89b6-29af36189b95.png">

**Comment by Awes786** [comment]
Added Homework and respective screenshots.

Thanks,
Syed Awes Hashmi

**Comment by HadesArchitect** [comment]
Hey **Syed Awes Hashmi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/IHNi0EUAS9CeUjkdfxOnBg
