### ISSUE TITLE
[HW] Soumya Joardar

### ISSUE THREAD

**Issue by SoumyaJoardar** [datastaxdevs/workshop-introduction-to-nosql#338]
**Name:** Soumya Joardar
**Email:** soumyajoadar1994@gmail.com
**Linkedin Profile:** www.linkedin.com/in/soumya-joardar-6092aa8b

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS
![scenario_completed](https://user-images.githubusercontent.com/88152821/127517678-fb791a7d-e350-4d77-b8c1-a26ecf886aed.PNG)
![CQL_key_value_check](https://user-images.githubusercontent.com/88152821/127517588-478d9202-27ca-4f1a-ab5e-2c9595e32706.PNG)
![insert](https://user-images.githubusercontent.com/88152821/127517663-95fd00b8-a738-408d-8836-4a68557d6ef3.PNG)
![cql_check2](https://user-images.githubusercontent.com/88152821/127517720-fa0ec932-79a8-4a5a-b133-ebf996b59054.PNG)
![Capture3](https://user-images.githubusercontent.com/88152821/127517701-89bada12-9c5b-4c4c-838e-ad85f3055d0f.PNG)
![last](https://user-images.githubusercontent.com/88152821/127517665-a9cf44cd-ca61-45c7-bf8c-78dfe781b23d.PNG)
>

**Comment by SoumyaJoardar** [comment]
I did not get the badge. Is there anything I need to do for it?

**Comment by HadesArchitect** [comment]
Hey **Soumya Joardar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/rE6sfDdhS4mhBUFbpHT7Fg
