### ISSUE TITLE
[HW] Jiahui Chen

### ISSUE THREAD

**Issue by JiahuiChen99** [datastaxdevs/workshop-introduction-to-nosql#339]
**Name:** Jiahui Chen
**Email:** Jiahui1@hotmail.es
**Linkedin Profile:** <https://www.linkedin.com/in/jiahui-chen-123941180/>

Attach the homework screenshots below:
-----------------------------------------
![Captura de pantalla 2021-07-29 171903](https://user-images.githubusercontent.com/37770349/127518908-eacfcf33-9e33-4752-8c5d-de3c52a483f2.png)

![Captura de pantalla 2021-07-29 172153](https://user-images.githubusercontent.com/37770349/127519364-b8bd7370-5937-435d-87c2-a0cee2cc8d73.png)

![Captura de pantalla 2021-07-29 172403](https://user-images.githubusercontent.com/37770349/127519771-f4907137-f1a9-4055-8b49-4e5cebd141d6.png)

**Comment by HadesArchitect** [comment]
Hey **Jiahui Chen**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/fq6Ohgj5SOGwpXb476mmxA
