### ISSUE TITLE
[HW] BatEl Yaish

### ISSUE THREAD

**Issue by BatElYaish** [datastaxdevs/workshop-introduction-to-nosql#340]
**Name:** BatEl Yaish
**Email:** batelyaish@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/batel-yaish-2b293599/

Attach the homework screenshots below:
-----------------------------------------
![step 4](https://user-images.githubusercontent.com/61110382/127525194-9513d836-2bef-497c-9bb1-adfd592f1fec.jpg)
![try-it-out scenario](https://user-images.githubusercontent.com/61110382/127525231-0e96f7a3-5dda-46d2-8442-1122df1a332a.jpg)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **BatEl Yaish**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/8MUi6U1YS8eco5QJnPaGTQ
