### ISSUE TITLE
[workshop-introduction-to-nosql] <NoSQL Database> by: Nidhi Mathur

### ISSUE THREAD

**Issue by Sunidhimathur** [datastaxdevs/workshop-introduction-to-nosql#341]
**Name:** Nidhi Mathur
**Email:** nidhiskr2014@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nidhi-mathur-9093681ab/

Attaching the homework screenshots below:

-- images removed by team --

![10](https://user-images.githubusercontent.com/66857025/127527581-69546187-1bc2-4574-b439-8210dc2c4360.png)

-- image removed by team --

![12](https://user-images.githubusercontent.com/66857025/127527587-7497bbb9-5459-4768-a1f5-3d144719a9db.png)

![13](https://user-images.githubusercontent.com/66857025/127527590-9ec07376-cbcb-4352-9a96-d5cf2e207e06.png)

**Comment by Sunidhimathur** [comment]
Please review my homework!

**Comment by HadesArchitect** [comment]
Hey **Nidhi Mathur**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/AI29XdRJTsuMe2uiuvqb3g

**Comment by SonicDMG** [comment]
Also, I had to remove many of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.
