### ISSUE TITLE
Homework HARSHDEEP

### ISSUE THREAD

**Issue by binnyharsh** [datastaxdevs/workshop-introduction-to-nosql#342]
**Name:** HARSHDEEP
**Email:** harsh238deep@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/harsh-deep-b051b31b2>

----------------------------------------------
**Attach the homework screenshots below:**
---------------------------------------------

**### _Step 4(c):_**
PLAYGROUND SCREENSHOTS:
* Table key_value1 created:
![image](https://user-images.githubusercontent.com/42540275/127524035-e41eb610-b6e0-4c8d-8491-dafdbff11931.png)

* Data inserted into key_value1 table:
![image](https://user-images.githubusercontent.com/42540275/127524180-df303436-30c1-40ec-a586-b3d013f9dd6c.png)

* 3rd record added to the table key_value1 :
![image](https://user-images.githubusercontent.com/42540275/127524564-8182dab2-a6dd-41f5-8549-35c925aca8f4.png)

NOSQL SCREENSHOTS:
* Checking table key_value1:
![image](https://user-images.githubusercontent.com/42540275/127524824-d534d200-3c6d-4129-a479-949d1e572af3.png)

* 1st select statement:
![image](https://user-images.githubusercontent.com/42540275/127524944-51d8a953-bfc4-4f6e-bf70-1120a88fb42b.png)

* Fetching records after the three insertions:
![image](https://user-images.githubusercontent.com/42540275/127525041-bea15913-3d43-4b02-9f00-28564d37e418.png)

--------------------------------------------------------------------------

TRY-IT-OUT SCENARIO SCREENSHOTS:
![image](https://user-images.githubusercontent.com/42540275/127529754-60ea2ee5-89d1-4008-a997-98b9f9a9a139.png)

![image](https://user-images.githubusercontent.com/42540275/127529703-595f02c4-85c0-45da-975a-67275416cd26.png)

![image](https://user-images.githubusercontent.com/42540275/127529812-800265a9-9b30-445d-b2fb-588b7f6b95b8.png)

**Comment by HadesArchitect** [comment]
Hey **HARSHDEEP**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/eAOoV1T9Qx2aVV-SyHGj2g
