### ISSUE TITLE
[HW - Introduction to NotOnly SQL Databases] <Isaac Santos de Oliveira>

### ISSUE THREAD

**Issue by OliveiraIsaac** [datastaxdevs/workshop-introduction-to-nosql#343]
**Name:** Isaac Santos de Oliveira
**Email:** oi.oliveiraisaac@gmail.com
**Linkedin Profile:** < https://www.linkedin.com/in/isaac-santos-de-oliveira >

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

Screenshot of the last completed step from step IV:

![print screen](https://user-images.githubusercontent.com/88154073/127528032-03dab20a-599c-41bb-87f6-46e63da61bfe.png)

Screenshot of the "scenario completed" screen:

![print screen 2](https://user-images.githubusercontent.com/88154073/127528023-a1a28d0a-8ee3-4a79-aa89-dbf433d4e12a.png)

**Comment by HadesArchitect** [comment]
Hey **Isaac Santos de Oliveira**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/syZiX4KSQP6S9dd6b3uKeA
