### ISSUE TITLE
[HW] <Introduction to NoSQL databases>

### ISSUE THREAD

**Issue by Nagalaxmi-K** [datastaxdevs/workshop-introduction-to-nosql#344]
**Name:** Nagalaxmi K
**Email:** nagalakshmi.rcr@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nagalakshmi-kothapalli-068a6a56/

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/69446601/127528558-a2bc7bca-ca0c-496d-aa35-a070f7059eed.png)
![image](https://user-images.githubusercontent.com/69446601/127528573-0c34ba60-39cb-46dd-a109-1386c3167f41.png)
![image](https://user-images.githubusercontent.com/69446601/127528605-996a5928-30b7-46f7-8f2c-f1425dfe271b.png)
![image](https://user-images.githubusercontent.com/69446601/127528622-082af113-23aa-416c-8b24-c12c9c3f590f.png)
![image](https://user-images.githubusercontent.com/69446601/127528636-ac71555c-7f5b-4040-b9fc-957ddf282863.png)
![image](https://user-images.githubusercontent.com/69446601/127528650-184528ef-4bc6-43d3-b5b9-42f3ddd64b05.png)

**Comment by HadesArchitect** [comment]
Hey **Nagalaxmi K**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/EQLpMY9XT4qdNe15-kZmUQ
