### ISSUE TITLE
[HW] Steven Vch.

### ISSUE THREAD

**Issue by unStatiK** [datastaxdevs/workshop-introduction-to-nosql#345]
**Name:** Steven Vch.
**Email:** unstatik@staremax.com

Attach the homework screenshots below:
-----------------------------------------

![4_1](https://user-images.githubusercontent.com/343531/127530180-1f78b35f-75c1-4eec-b01a-0b1f0f40df6b.png)
![5](https://user-images.githubusercontent.com/343531/127530195-329a9853-c85d-4e65-87da-dfc263ee0d4d.png)

**Comment by HadesArchitect** [comment]
Hey **Steven Vch.**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Vwi46fWLT86u1UzkRXafaA
