### ISSUE TITLE
[HW] Divya Shah

### ISSUE THREAD

**Issue by D-HackCoder** [datastaxdevs/workshop-introduction-to-nosql#347]
**Name:** Divya Shah
**Email:** divyashah00068@gmail.com
**Linkedin Profile:** https://bit.ly/DivyLinkedIn

Attach the homework screenshots below:
-----------------------------------------

![Try It Out _ Datastax - Google Chrome 29-07-2021 22_07_37](https://user-images.githubusercontent.com/57376086/127531495-f388c52f-e693-4a7f-a113-f8ff6b75d016.png)

-----------------------------------------

![InkedTry It Out _ Datastax - Google Chrome 29-07-2021 22_08_01_LI](https://user-images.githubusercontent.com/57376086/127531962-c05245fd-f8aa-4a0f-ac1f-db14a809e33a.jpg)

![InkedManage Database — DataStax Astra - Google Chrome 29-07-2021 22_09_22_LI](https://user-images.githubusercontent.com/57376086/127531980-dd66f8cd-cbec-46e5-b5ad-da884f8181cb.jpg)

![InkedPlayground - https___784086ea-592e-4e2f-a81c-d6d631af58ca-asia-south1 apps astra datastax com_api_graphql_yourKeyspace - Google Chrome 29-07-2021 22_09_38_LI](https://user-images.githubusercontent.com/57376086/127531998-14f7f692-4a97-4977-8669-e651a3f9a4a0.jpg)

**Comment by HadesArchitect** [comment]
Hey **Divya Shah**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/KR7ClCe8QJyOsjv9CL49ZA
