### ISSUE TITLE
[HW] Mohammed Majd Talo

### ISSUE THREAD

**Issue by mohammedtalo** [datastaxdevs/workshop-introduction-to-nosql#35]
**Name:** Mohammed Majd Talo
**Email:** mhmdmjdtalo@hotmail.com
**Linkedin Profile:** www.linkedin.com/in/mohammedtale

Attach the homework screenshots below:
-----------------------------------------

**### Exercise 1:**

<img width="954" alt="exercise 1" src="https://user-images.githubusercontent.com/57559012/118276842-27965a80-b4d9-11eb-9850-3943b4b2ac02.PNG">

**### Exercise 2:**

<img width="959" alt="exercise 2 1" src="https://user-images.githubusercontent.com/57559012/118326646-4cf58980-b516-11eb-8a98-c4750a8601d6.PNG">

<img width="960" alt="exercise 2 2" src="https://user-images.githubusercontent.com/57559012/118326648-4e26b680-b516-11eb-9603-60b7512926a0.PNG">

<img width="960" alt="exercise 2 3" src="https://user-images.githubusercontent.com/57559012/118326650-4ebf4d00-b516-11eb-853a-be2e21dd1155.PNG">

<img width="959" alt="exercise 2 4" src="https://user-images.githubusercontent.com/57559012/118326653-4ebf4d00-b516-11eb-8cc0-589114f46dc2.PNG">

<img width="958" alt="exercise 2 5" src="https://user-images.githubusercontent.com/57559012/118326655-4f57e380-b516-11eb-89a3-12c7663f380f.PNG">

<img width="960" alt="exercise 2 6" src="https://user-images.githubusercontent.com/57559012/118326658-4ff07a00-b516-11eb-9628-2ebbe40437ef.PNG">

**### **Exercise 3****

-- images removed by team --

<img width="960" alt="Exercise 3 6" src="https://user-images.githubusercontent.com/57559012/118331975-6d274780-b51a-11eb-8c7e-dcf9f37a1a68.PNG">

**### Exercise 4**

-- images removed by team --

<img width="960" alt="Exerice 4 4" src="https://user-images.githubusercontent.com/57559012/118332084-934ce780-b51a-11eb-8160-c438cfc80cb2.PNG">

### **Homework 👍** 

<img width="960" alt="Homework 1" src="https://user-images.githubusercontent.com/57559012/118332643-77961100-b51b-11eb-871c-0706b97cf3a8.PNG">

<img width="960" alt="Homework 2" src="https://user-images.githubusercontent.com/57559012/118332646-782ea780-b51b-11eb-8343-665b48714768.PNG">

**Comment by HadesArchitect** [comment]
Looks good to me, approved.

**Comment by HadesArchitect** [comment]
Here we go. Congrats! https://api.badgr.io/public/assertions/8inh88dQRtOfkmW1zKDTYw?identity__email=mhmdmjdtalo%40hotmail.com
