### ISSUE TITLE
[HW] RITURAJ SAHA

### ISSUE THREAD

**Issue by Trickmaster-Maestro** [datastaxdevs/workshop-introduction-to-nosql#354]
**Name:** RITURAJ SAHA
**Email:** sahaporitosh@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/rituraj-saha-19082a201

Attach the homework screenshots below:
-----------------------------------------
![Screenshot (671)](https://user-images.githubusercontent.com/88152413/127539633-392ac24c-2e23-4ed8-b6e2-23da57633f1c.png)
![Screenshot (672)](https://user-images.githubusercontent.com/88152413/127539660-e4e07dc9-ef0f-49c9-a5cd-a846465e50b0.png)
![Screenshot (673)](https://user-images.githubusercontent.com/88152413/127539690-7ec773d9-d6f9-4a01-9ac4-091ce7bddbb8.png)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **RITURAJ SAHA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/FL_lKfOWSe-7VMYF8Gn5tA
