### ISSUE TITLE
[HW] Manish Kumar Tiwari

### ISSUE THREAD

**Issue by tiwarikmanish** [datastaxdevs/workshop-introduction-to-nosql#355]
**Name:** Manish Kumar Tiwari
**Email:** manish.tiwari.270784@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/tiwarikmanish/

Attach the homework screenshots below:
-----------------------------------------

![Step_4_Final](https://user-images.githubusercontent.com/42186238/127540549-1cf109b8-8e02-4e8c-b2b5-2f9e7326c807.jpg)
![Step2_Final](https://user-images.githubusercontent.com/42186238/127540552-34850f50-202f-4f10-8a2c-672765fd597b.jpg)
![Step3_Final](https://user-images.githubusercontent.com/42186238/127540554-c7c2af0a-c117-4594-a966-ce5502092427.jpg)
![try_it_out_scenario_completed](https://user-images.githubusercontent.com/42186238/127540555-c5cf9f5f-ad94-4183-972d-e5342167b832.jpg)

**Comment by HadesArchitect** [comment]
Hey **Manish Kumar Tiwari**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/vo0N4rLlRbGBonPogVPfNw
