### ISSUE TITLE
[HW] <Joana Mariz>

### ISSUE THREAD

**Issue by Joanavmariz** [datastaxdevs/workshop-introduction-to-nosql#356]
**Name:** Joana Mariz
**Email:** joanavmariz@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/joana-mariz-7b6a521bb/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Captura Web_29-7-2021_184235_a111b229-cc7c-42a2-8a42-192ef21f506e-eu-central-1 apps astra datastax c](https://user-images.githubusercontent.com/88158984/127540192-c658f5aa-7967-4762-ad94-0d98f77bc994.jpeg)

![Captura Web_29-7-2021_184336_astra datastax com](https://user-images.githubusercontent.com/88158984/127540203-bc4701d0-4eb2-4742-926d-7c4e97d929d8.jpeg)

![image](https://user-images.githubusercontent.com/88158984/127540931-b909dbed-ae58-497d-b3d6-d5e9e87a371d.png)

**Comment by HadesArchitect** [comment]
Hey **Joana Mariz**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/H0OdDOckREKRpGiyvjMokw
