### ISSUE TITLE
[HW] <Sriram_Bharadwaj_Sampathkumar>

### ISSUE THREAD

**Issue by srirambharadwaj1994** [datastaxdevs/workshop-introduction-to-nosql#357]
**Name:** Sriram Bharadwaj Sampathkumar
**Email:** bharadwajsriram1@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/srirambharadwajs/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![final2](https://user-images.githubusercontent.com/54514717/127542778-acd218a8-0507-4468-9811-ec3c65c03a7e.jpg)
![Apache cassandra](https://user-images.githubusercontent.com/54514717/127542788-1615d386-8be8-4158-a22b-da947dcbe89c.jpg)
![final](https://user-images.githubusercontent.com/54514717/127542793-94df03f6-ed20-4925-8d77-8cb8d3614464.jpg)
![final1](https://user-images.githubusercontent.com/54514717/127542797-43c80097-7a74-4680-8322-14c2becbf9af.jpg)

**Comment by srirambharadwaj1994** [comment]
![final1](https://user-images.githubusercontent.com/54514717/127542383-367dc944-e550-40b1-81a1-439999a8b30b.jpg)
![final2](https://user-images.githubusercontent.com/54514717/127542388-1710aa52-e074-4ca8-b8ba-63d314e4f547.jpg)
![Apache cassandra](https://user-images.githubusercontent.com/54514717/127542390-9b13cbb3-3b4c-41cc-96ac-ca44734bfc1b.jpg)
![final](https://user-images.githubusercontent.com/54514717/127542392-71824cf2-ecf9-442b-8e9e-0a0f6b5fd24c.jpg)

**Comment by HadesArchitect** [comment]
Hey **Sriram Bharadwaj Sampathkumar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/6LpoegPrQFOrMkqFS2UyYA
