### ISSUE TITLE
[HW] <Thomas J. Short>

### ISSUE THREAD

**Issue by KyronFeast** [datastaxdevs/workshop-introduction-to-nosql#358]
**Name:** Thomas J. Short
**Email:** thomasshort1984@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/thomas-james-short/
Attach the homework screenshots below:
-----------------------------------------
![step4](https://user-images.githubusercontent.com/42007448/127542529-b50257da-0846-4d79-b4e1-295cd86e499e.PNG)
![Sceniro](https://user-images.githubusercontent.com/42007448/127542553-8d6e66e3-451a-4ee4-bdca-be25cae3c8af.PNG)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Thomas J. Short**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/5y5GsUNXSBOV1h9okRwDAw
