### ISSUE TITLE
[HW] <ATITHI KUMARI>

### ISSUE THREAD

**Issue by Ati19** [datastaxdevs/workshop-introduction-to-nosql#359]
**Name:** ATITHI KUMARI
**Email:** atithi19@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/atithi-kumari-132883a0

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

<img width="1024" alt="Screenshot 2021-07-29 at 11 28 12 PM" src="https://user-images.githubusercontent.com/57137664/127541987-49afb173-478b-42d3-8c56-5f262d98e2f8.png">
<img width="1024" alt="Screenshot 2021-07-29 at 11 27 54 PM" src="https://user-images.githubusercontent.com/57137664/127542000-e2f64229-7099-4d3e-a3d3-d61750215955.png">
<img width="1024" alt="Screenshot 2021-07-29 at 11 33 27 PM" src="https://user-images.githubusercontent.com/57137664/127542727-a03c9a0c-6d56-4ff5-9262-c633e0762a95.png">

**Comment by HadesArchitect** [comment]
Hey **ATITHI KUMARI**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/xFsfc9kYQeqk0T3q6--DjQ
