### ISSUE TITLE
[HW] <Shruti Prasanna>

### ISSUE THREAD

**Issue by shrutisprasanna** [datastaxdevs/workshop-introduction-to-nosql#360]
**Name:** Shruti Susila Prasanna
**Email:** shrutipras2021@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/shruti-prasanna-a709a9218/

Here are the screenshots of the homework

![Screenshot (73)](https://user-images.githubusercontent.com/88101697/127544063-e8cd0406-d879-4f49-8f86-398037a1adff.png)
-- images removed by team --
![Screenshot (76)](https://user-images.githubusercontent.com/88101697/127544073-8dc555c9-4552-4e67-ad74-41a93cecfc47.png)
-- image removed by team --
![Screenshot (78)](https://user-images.githubusercontent.com/88101697/127544078-97b0491f-2d85-48f2-80d5-4ebf64af157e.png)
![Screenshot (79)](https://user-images.githubusercontent.com/88101697/127544081-4589f179-3edb-4db1-9310-d582fcbae748.png)
![Screenshot (80)](https://user-images.githubusercontent.com/88101697/127544084-ff61392c-27e5-4816-bc30-e9444b73433a.png)
![Screenshot (81)](https://user-images.githubusercontent.com/88101697/127544086-2398d5c3-40be-48a9-a818-2fc7c5eb362f.png)
![Screenshot (82)](https://user-images.githubusercontent.com/88101697/127544392-464302c5-d7de-4fc5-bda0-08e0ea566f44.png)

**Comment by shrutisprasanna** [comment]
Is this the correct place to upload them?

**Comment by shrutisprasanna** [comment]
I have completed all the questions done during the seminar along with the 'Try it out'. I hope I put enough screenshots

**Comment by HadesArchitect** [comment]
Hey **Shruti Susila Prasanna**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/P36ctuD8QD-onWpLvZFZeg

**Comment by SonicDMG** [comment]
Of course. While logged into Astra, click on your organization drop down on the top left of the UI -> organization settings -> Token management. Then, the token should be listed on the page. Click the ellipses (3 stacked dots) on the right of your token. Choose "delete".
