### ISSUE TITLE
[HW] <Dheeraj Kashyap>

### ISSUE THREAD

**Issue by dheekash** [datastaxdevs/workshop-introduction-to-nosql#361]
**Name:** Dheeraj Kashyap
**Email:** kash.dheeraj.yap@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/dheeraj-kashyap-5a318653/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Inkedlast_page_LI](https://user-images.githubusercontent.com/85519051/127544370-e7f5306e-0da1-4dcf-9bff-0b943b635aef.jpg)
<img width="960" alt="scenario" src="https://user-images.githubusercontent.com/85519051/127544425-2dc4e0bb-6a83-443b-861b-d0ebd3ad9193.PNG">

**Comment by HadesArchitect** [comment]
Hey **Dheeraj Kashyap**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/pWbWGyt0SXiSptRNg5bvKg
