### ISSUE TITLE
[HW] <Marcin>

### ISSUE THREAD

**Issue by xxnajmanxx** [datastaxdevs/workshop-introduction-to-nosql#363]
**Name:** Marcin Najdzion
**Email:** marcin12104@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/najdzion/

Attach the homework screenshots below:
-----------------------------------------

![screen1](https://user-images.githubusercontent.com/88161124/127546918-18edf68a-d525-41da-8592-cadb3288fb8a.jpg)

![screen2](https://user-images.githubusercontent.com/88161124/127547346-20554ee2-de32-449b-88c5-3dbeb05e2b6b.jpg)

**Comment by hemidactylus** [comment]
Hi, Marcin,
well done! You're almost there. Could you please add a screenshot similar to the first one (a SELECT in CQL Console over table key_value) but done after the last GraphQL mutation, the one that alters a value from "bbbb" to "cccc"? Then we can grade the homework as 'passed' and issue you a badge!
(see "Check with CQL Console the values should have been updated." at the very end of step 4 in the repo's README).

See you soon and keep up the good work!

**Comment by HadesArchitect** [comment]
Hey **Marcin Najdzion**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/HNlFCt4uQHWuwx9grBo2iA
