### ISSUE TITLE
[HW] <Puneet Malviya>

### ISSUE THREAD

**Issue by Puneet251083** [datastaxdevs/workshop-introduction-to-nosql#364]
**Name:** Puneet Malviya
**Email:** Puneet.malviya@hotmail.com
**Linkedin Profile:** https://www.linkedin.com/in/puneetmalviya/

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/55555983/127540540-7fedb6c2-e2ed-409f-8f46-f9170d34bd38.png)

![image](https://user-images.githubusercontent.com/55555983/127541259-ed52b30a-73c9-46ed-a848-f7c71e492b46.png)

![image](https://user-images.githubusercontent.com/55555983/127541879-17b1b32d-7606-4d6c-a48e-bf0d0edce66e.png)

![image](https://user-images.githubusercontent.com/55555983/127542059-c711d001-6a8a-4010-92a8-3bb62daf45c6.png)

![image](https://user-images.githubusercontent.com/55555983/127542180-60b220a7-2f30-4868-b902-2758c68b3e0b.png)

![image](https://user-images.githubusercontent.com/55555983/127542364-93b7976a-65bb-44ec-aefc-20c285a4104d.png)

![image](https://user-images.githubusercontent.com/55555983/127542477-a179d650-0f07-4528-a8c4-c84506c59591.png)

![image](https://user-images.githubusercontent.com/55555983/127542642-a420f413-fe22-4e24-9542-9fb9fac96477.png)

![image](https://user-images.githubusercontent.com/55555983/127543033-32e546b5-16d2-409a-aae2-ade61ace8324.png)

![image](https://user-images.githubusercontent.com/55555983/127544039-e9bd68f9-1ef2-4a92-9388-1325b494b07d.png)

![image](https://user-images.githubusercontent.com/55555983/127544253-4386eda3-95bf-4897-8a98-35d8450ffa20.png)

![image](https://user-images.githubusercontent.com/55555983/127546515-2aed6249-9564-4a4d-9ae7-bb6393669425.png)

![image](https://user-images.githubusercontent.com/55555983/127546772-4c3ac396-1ca7-444e-8339-de380814f88c.png)

![image](https://user-images.githubusercontent.com/55555983/127547398-f63d9a31-cdaa-4fed-9196-a6cba66bf103.png)

![image](https://user-images.githubusercontent.com/55555983/127548104-838e08fc-0af1-4706-b22b-d5709df17cec.png)

![image](https://user-images.githubusercontent.com/55555983/127548346-d38b52a7-7fc9-40c1-959b-bd8be111e53f.png)

**Comment by hemidactylus** [comment]
Hi, Puneet!
Well done, congratulations: enjoy your badge!

I had to delete two images above that were showing your Astra DB secret token. Please revoke the token and generate a new one to ensure your database's security!

**Comment by HadesArchitect** [comment]
Hey **Puneet Malviya**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Uqh3qZJ7S4KjBBqsb3-2aQ
