### ISSUE TITLE
[HW] Emerson M. Zaro

### ISSUE THREAD

**Issue by emersonzaro** [datastaxdevs/workshop-introduction-to-nosql#365]
**Name:** Emerson M. Zaro
**Email:** emersonzaro@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ezaro/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![tryitout](https://user-images.githubusercontent.com/68870773/127548922-7494c332-cfbc-44ff-aa62-3fa9bf7e3335.png)
![workshop1](https://user-images.githubusercontent.com/68870773/127548928-0fe3cf60-0cc6-449b-846c-43fec07b5e85.png)
![workshop2](https://user-images.githubusercontent.com/68870773/127548932-b48aee71-7aaa-43e6-8197-0f7d91660dcd.png)
![workshop3](https://user-images.githubusercontent.com/68870773/127548934-43ed9b30-8bcd-4c1b-9eda-3be3675e4424.png)

**Comment by HadesArchitect** [comment]
Hey **Emerson M. Zaro**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Bqs43w5PTeueZ_NLMIdR8g
