### ISSUE TITLE
[HW] Fábio Emilio Costa

### ISSUE THREAD

**Issue by fabiocosta0305** [datastaxdevs/workshop-introduction-to-nosql#366]
**Name:** Fábio Emilio Costa
**Email:** fabiocosta0305@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/fabiocosta0305/

Attach the homework screenshots below:
-----------------------------------------

![NoSQL2](https://user-images.githubusercontent.com/840093/127549472-f1d705f6-3368-4e4b-acf0-f62ffec60a32.png)
![NoSQL3](https://user-images.githubusercontent.com/840093/127549485-ff69c725-b4f3-4f91-be14-e4da5f35e23b.png)

**Comment by HadesArchitect** [comment]
Hey **Fábio Emilio Costa**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/fdj--thXQ3m7l9nD_3Io2A
