### ISSUE TITLE
[HW] workshop-introduction-to-nosql

### ISSUE THREAD

**Issue by chatterjeesunit** [datastaxdevs/workshop-introduction-to-nosql#369]
**Name:** SUNIT CHATTERJEE
**Email:** chatterjeesunit@yahoo.com
**Linkedin Profile:** www.linkedin.com/in/sunitchatterjee

Attach the homework screenshots below:
-----------------------------------------

**Screenshot of Step 4 of HW**

<img width="1792" alt="Screenshot 2021-07-30 at 12 36 45 AM" src="https://user-images.githubusercontent.com/34455433/127552080-408e521b-7c2d-4c2a-9f2b-dda14e80e32c.png">

**Screenshot of scenario completed**

<img width="1789" alt="Screenshot 2021-07-30 at 12 40 07 AM" src="https://user-images.githubusercontent.com/34455433/127552092-38c2962a-5d22-4954-9a49-993bafd2b878.png">

**Comment by HadesArchitect** [comment]
Hey **SUNIT CHATTERJEE**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/G8WAln9-SDGowheoL2S1jg
