### ISSUE TITLE
[HW] <Vishnuvardan T D>

### ISSUE THREAD

**Issue by VishVais** [datastaxdevs/workshop-introduction-to-nosql#370]
**Name:** Vishnuvardan T D
**Email:** vishnuvardan.td@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/vishnuvardan-t-d-558a1016>

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/88162580/127552982-7a5e9f33-63d7-4db1-8a1b-7c77a949d5b2.png)

![image](https://user-images.githubusercontent.com/88162580/127553062-b08eb5fc-5461-4ab4-8bf3-4915004eb6d9.png)

![image](https://user-images.githubusercontent.com/88162580/127558943-24a26e12-e4ca-4997-b7a2-6f37e844f6f6.png)

**Comment by HadesArchitect** [comment]
Hey **Vishnuvardan T D**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/vgWV1tjDSqqFCqgPVqUwDg

**Comment by VishVais** [comment]
Thanks for providing the badge.
