### ISSUE TITLE
[HW] <Vaibhav Rai>

### ISSUE THREAD

**Issue by vaibhavrai200** [datastaxdevs/workshop-introduction-to-nosql#371]
**Name:** Vaibhav Rai
**Email:** vaibhavrai@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/raivaibhav/

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/88158669/127542710-5c2c0158-9bde-4113-9c1a-1d741ee1dbd6.png)
![image](https://user-images.githubusercontent.com/88158669/127546850-f59e9167-2d51-4c7a-b3fc-e6fc1844de82.png)
![scenario](https://user-images.githubusercontent.com/88158669/127547434-cc32191d-05a6-42f2-ba36-3bafa948bb52.png)

**Comment by HadesArchitect** [comment]
Hey **Vaibhav Rai**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/RPd7-XbdQZa827Q8xaTYjw
