### ISSUE TITLE
[HW] <SHUBHAM CHANDRA>

### ISSUE THREAD

**Issue by Shubham-com** [datastaxdevs/workshop-introduction-to-nosql#372]
**Name:** SHUBHAM CHANDRA
**Email:** shubhamchandra4091@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/shubham-chandra-bbbb28197/>

Attach the homework screenshots below:
-----------------------------------------
<h2>Creating a Table</h2>

-- images removed by team --

<SCREENSHOTS>

**Comment by Shubham-com** [comment]
![Screenshot (409)](https://user-images.githubusercontent.com/66332826/128636951-0ab7dd7d-c041-4fb5-a4be-8870b2e6e203.png)

**Comment by HadesArchitect** [comment]
Hey **SHUBHAM CHANDRA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/np7dwjPvTaeKmvGBXTUFrw

**Comment by SonicDMG** [comment]
Also, I had to remove your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.

**Comment by Shubham-com** [comment]
Thanks @SonicDMG I will delete it..and regenerate it for further use.
