### ISSUE TITLE
[HW] <Saubhagya Sharma>

### ISSUE THREAD

**Issue by saubhagya-sharma** [datastaxdevs/workshop-introduction-to-nosql#373]
**Name:** Saubhagya Sharma
**Email:** saubhagya812003@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/saubhagya-sharma-41064a201

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
<img width="662" alt="nosql on graphql" src="https://user-images.githubusercontent.com/81666054/127559986-6fc16716-8988-4345-86c5-846adaf2da3a.png">
<img width="719" alt="scenario completion" src="https://user-images.githubusercontent.com/81666054/127559978-8472460c-f4e4-458c-8d6b-2ff253ab74bf.png">

**Comment by HadesArchitect** [comment]
Hey **Saubhagya Sharma**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/1_-9m2i5RpmLaP8Yu3P-0A
