### ISSUE TITLE
[HW] <ORKUN KURUN>

### ISSUE THREAD

**Issue by OrkunKURUN** [datastaxdevs/workshop-introduction-to-nosql#375]
**Name:** ORKUN KURUN
**Email:** kurunorkun@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/orkun-kurun-53ba57147/
![ss1](https://user-images.githubusercontent.com/44517787/127564088-3d6f7830-eab3-4782-ac2a-cd9bfbf6fd09.jpg)
![ss2](https://user-images.githubusercontent.com/44517787/127564096-1844044f-56da-4345-ad81-caf85150019f.jpg)
![ss3](https://user-images.githubusercontent.com/44517787/127564107-7759b737-e4fb-4734-983a-9a9ca98f79c6.jpg)
>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **ORKUN KURUN**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/j0IupCoxTU2y009tvkEIlw
