### ISSUE TITLE
[HW] <Leonardo Grossi>

### ISSUE THREAD

**Issue by leogrossi** [datastaxdevs/workshop-introduction-to-nosql#376]
**Name:** Leonardo Grossi
**Email:** leonardo.grossi@icloud.com
**Linkedin Profile:** <https://www.linkedin.com/in/leonardovianagrossi/>
![LeonardoGrossi2](https://user-images.githubusercontent.com/69981202/127570213-cc49dd86-8b88-4a6e-ac63-39478d6ca2e5.png)
![LeonardoGrossi](https://user-images.githubusercontent.com/69981202/127570223-21db6c59-a416-469e-af49-dfb2652429a0.png)
>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Leonardo Grossi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/cH7JFsp0Sy-wGtfO_dslUw
