### ISSUE TITLE
[HW] Kseniya Mikhaylova

### ISSUE THREAD

**Issue by kkmikhaylova** [datastaxdevs/workshop-introduction-to-nosql#377]
**Name:** Kseniya Mikhaylova
**Email:** kkmikhaylova@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/kseniya-mikhaylova-644659218/

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/44542762/127570275-f25bb32d-48f0-4089-8584-527e395a1a14.png)

![image](https://user-images.githubusercontent.com/44542762/127567484-6fcec6b2-de75-4098-806f-278ce971e62d.png)

**Comment by HadesArchitect** [comment]
Hey **Kseniya Mikhaylova**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/sxVvwWObTcGdpAHt4Ys-AA
