### ISSUE TITLE
[HW] Omid Naghizadeh

### ISSUE THREAD

**Issue by OmidNaghizadeh1355** [datastaxdevs/workshop-introduction-to-nosql#378]
**Name:** Omid Naghizadeh
**Email:** omid.naghizadeh@icloud.com
**Linkedin Profile:** https://www.linkedin.com/in/omidnaghizadeh/

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/56911352/127575138-73908e2f-4d8b-4dba-98aa-52c4c5e529ec.png)
![image](https://user-images.githubusercontent.com/56911352/127575376-b9edd75c-b998-47c3-8f03-65ca898662e0.png)
![image](https://user-images.githubusercontent.com/56911352/127575734-9c393626-c3aa-40b5-8095-3fac8c2fdaa2.png)
![image](https://user-images.githubusercontent.com/56911352/127576163-5399ebc3-8fb2-4cf8-8019-99949491ce9c.png)
![image](https://user-images.githubusercontent.com/56911352/127576280-3461b94c-04ff-4313-bcfd-2c3612b5d090.png)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Hi there Omid, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

Nice job getting through the GraphDB portion as well. :D

**Comment by OmidNaghizadeh1355** [comment]
![image](https://user-images.githubusercontent.com/56911352/129315942-7101a54a-7b49-4786-b83c-f3167517e106.png)

**Comment by OmidNaghizadeh1355** [comment]
Hi David,


Done :)

On August 11, 2021 at 4:49 PM, David Jones-Gilardi ***@***.***> wrote:






Hi there Omid, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete try-it-out scenario and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

Nice job getting through the GraphDB portion as well. :D

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HadesArchitect** [comment]
Hey **Omid Naghizadeh**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/8gzZubL4SfaYMiO8JcmBPQ
