### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by NancyJaneBullis** [datastaxdevs/workshop-introduction-to-nosql#379]
**Name:** Nancy Bullis
**Email:** nancybullis3@gmail.com
**Linkedin Profile:** www.linkedin.com/in/nancyjanebullis

Attach the homework screenshots below:
-----------------------------------------
<SCREENSHOTS>

[screenShot1NosqlIntro.docx](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/6904073/screenShot1NosqlIntro.docx)

**Comment by SonicDMG** [comment]
Hi there Nancy, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by NancyJaneBullis** [comment]
Thanks for the follow-up. Here is my screen shot for Step 2. 
[screenShotDataStaxStep2.docx](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/6971768/screenShotDataStaxStep2.docx)

**Comment by SonicDMG** [comment]
Wonderful, nice job. Thank YOU for following up as well.

**Comment by HadesArchitect** [comment]
Hey **Nancy Bullis**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/LaWstLd9SdWbcbdqDxzqng

**Comment by NancyJaneBullis** [comment]
Thank you!
