### ISSUE TITLE
[HW] Jonathan Duarte Martinez

### ISSUE THREAD

**Issue by JDRXcr** [datastaxdevs/workshop-introduction-to-nosql#380]
**Name:** Jonathan Duarte Martinez
**Email:** jj.duartem@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/jonathan-duarte-mart%C3%ADnez-229138203/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![homework9](https://user-images.githubusercontent.com/2062278/127580779-9ea19f6b-1eff-4a6b-84bc-ed0171f97931.JPG)

**Comment by SonicDMG** [comment]
Hi there Jonathan, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by JDRXcr** [comment]
![nosqlHW2](https://user-images.githubusercontent.com/2062278/129688815-69b1ed8d-8fd2-48a1-8b71-2bec94efa2b4.JPG)
![nosqlHW3](https://user-images.githubusercontent.com/2062278/129688819-0bb867da-57d9-4049-b088-9a5bb2f1fc3b.JPG)

**Comment by HadesArchitect** [comment]
Hey **Jonathan Duarte Martinez**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/pn61CRJQS4eKLl5Crycpng
