### ISSUE TITLE
[HW] Otacilio Filho

### ISSUE THREAD

**Issue by otacilio-psf** [datastaxdevs/workshop-introduction-to-nosql#381]
**Name:** Otacilio Pedro dos Santos Filho
**Email:** otaciliopedro@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/otacilio-psf/

Attach the homework screenshots below:
-----------------------------------------

**Step IV**

![IV-a](https://user-images.githubusercontent.com/66729019/127581470-a33838e3-319f-4cc9-a9b1-90ea90d2c52e.png)

![IV-b](https://user-images.githubusercontent.com/66729019/127581411-7966f0aa-bc67-46e1-94dd-6f6d36f850f6.png)

**Step V**

![V-a](https://user-images.githubusercontent.com/66729019/127595709-0007e687-f29c-4f17-b3a0-13dc00acb529.png)

![V-b](https://user-images.githubusercontent.com/66729019/127596015-85787a7e-3b49-4232-a786-91003c6a527d.png)

**try-it-out scenario**

![try-it-out scenario](https://user-images.githubusercontent.com/66729019/127597054-0b4464ed-3f50-4185-b3b6-428d6bebc010.png)

Note: I accidentally submitted the Giveaway Claim Form twice, sorry I hope it's not a problem

**Comment by HadesArchitect** [comment]
Hey **Otacilio Pedro dos Santos Filho**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/WMUqli83S3-qC0wCl_0_gg

**Comment by SonicDMG** [comment]
Nice job getting through the GraphDB portion as well. :D
