### ISSUE TITLE
[HW] SANOJ KUMAR

### ISSUE THREAD

**Issue by sanojtomar** [datastaxdevs/workshop-introduction-to-nosql#382]
**Name:** SANOJ KUMAR
**Email:** SANOJTOMAR@GMAIL.COM
**Linkedin Profile:** https://www.linkedin.com/in/sanojtomar/

Attach the homework screenshots below:
-----------------------------------------

**Console**
![image](https://user-images.githubusercontent.com/11496706/127596905-04350838-c607-489b-84e4-890142174cff.png)

**Playground**

![image](https://user-images.githubusercontent.com/11496706/127596831-42df94f4-06a3-4032-a9df-936237d61f67.png)

**Try It Out**
![image](https://user-images.githubusercontent.com/11496706/127597135-fad74d72-8909-42d2-9987-c35c37dd7505.png)

**Comment by HadesArchitect** [comment]
Hey **SANOJ KUMAR**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/dy_BKt3HRCWxHYWaklzlmA
