### ISSUE TITLE
[HW] <Introduction to NoSQL>

### ISSUE THREAD

**Issue by SonuJacob** [datastaxdevs/workshop-introduction-to-nosql#383]
**Name:** Sonu Anna Jacob
**Email:** jacobasonu@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sonu-anna-jacob/

Attach the homework screenshots below:
----------------------
![Screenshot (1046)](https://user-images.githubusercontent.com/72950437/127599043-360660d1-5f7e-4dbc-aa5f-ced82fede6e9.png)
![Screenshot (1045)](https://user-images.githubusercontent.com/72950437/127599054-d8d25165-7799-428f-abbe-b8570043d192.png)

-------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Sonu Anna Jacob**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/7g8nN50jR2uVpXzbbmLNbQ
