### ISSUE TITLE
[HW] <Pervez Sayyed>

### ISSUE THREAD

**Issue by iamprs** [datastaxdevs/workshop-introduction-to-nosql#384]
**Name:** Pervez Sayyed
**Email:** pervezrasoolsayyed@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/pervezrasoolsayyed

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/67779201/127601618-34f5d0e9-15c1-4107-812b-375e4087dcf5.png)
![image](https://user-images.githubusercontent.com/67779201/127601674-9e1f50b9-4757-4efc-9dae-3515625fd12b.png)
![image](https://user-images.githubusercontent.com/67779201/127601712-d295ae4a-2a5a-4ca4-8b5b-d6e32311cfd6.png)
![image](https://user-images.githubusercontent.com/67779201/127601765-cc093a2d-1418-41be-bd73-86e066979bb2.png)
![image](https://user-images.githubusercontent.com/67779201/127601839-73b851b8-192c-4aac-afd2-0e1efb23389e.png)
![image](https://user-images.githubusercontent.com/67779201/127601882-4cfaf53b-491f-450a-92cc-416f865c2128.png)
![image](https://user-images.githubusercontent.com/67779201/127601913-d961527c-d1b9-4061-be31-5504d5f57114.png)
![image](https://user-images.githubusercontent.com/67779201/127601937-774b2aa1-8db2-4f33-b974-b949a149fff6.png)
![image](https://user-images.githubusercontent.com/67779201/127600980-cfa3fc83-9ed2-4d1f-8b88-a6efebb2fa3a.png)
![image](https://user-images.githubusercontent.com/67779201/127601293-97288302-5151-4e49-a617-5f0dea929d42.png)
![image](https://user-images.githubusercontent.com/67779201/127601482-78e49080-64fb-4dab-9c7e-be1f5873ad87.png)
![image](https://user-images.githubusercontent.com/67779201/127602318-c9bea502-f441-4ec8-9ca4-8a6e0e91f399.png)
![image](https://user-images.githubusercontent.com/67779201/127602412-b5c853b0-bed5-479b-bec5-1e7d17c56138.png)
![image](https://user-images.githubusercontent.com/67779201/127602490-eda02003-7819-430c-a632-319d356a0aa5.png)
![image](https://user-images.githubusercontent.com/67779201/127602555-b3310140-099f-4f97-b9c7-a47628d4d272.png)
![image](https://user-images.githubusercontent.com/67779201/127602635-43a2d312-792d-4f56-bfbc-d49ee9198d97.png)
![image](https://user-images.githubusercontent.com/67779201/127602674-9c59d5d7-5c57-49bd-b56c-112b0c6da7a3.png)
![image](https://user-images.githubusercontent.com/67779201/127602729-cecf61e3-a71b-4413-b72d-a3f93a53f70d.png)
![image](https://user-images.githubusercontent.com/67779201/127602774-b6419784-6051-4ab9-ab4c-886815afca53.png)
![image](https://user-images.githubusercontent.com/67779201/127602816-da06b436-9074-42d6-b64a-b887cfe30682.png)

**Comment by iamprs** [comment]
what a great! learning experience, enjoyed a lots. thanks team.

**Comment by hemidactylus** [comment]
Hello! Congratulations, you completed the homework!
But warning: the Swagger UI screenshots were showing your secret DB token in its entirety so I deleted the images. Please consider revoking the token in your Astra DB console and generating a new one for future uses.

**Comment by HadesArchitect** [comment]
Hey **Pervez Sayyed**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/XpT9ZHnESYyv2qDvH_fWuQ
