### ISSUE TITLE
[HW] <Yogendra Thursday, July 29, 2021  NoSQL>

### ISSUE THREAD

**Issue by yogendrasoni79** [datastaxdevs/workshop-introduction-to-nosql#385]
**Name:** Yogendra Bhardwaj
**Email:** Yogendrabhardwaj@outlook.com 
**Linkedin Profile:** https://www.linkedin.com/in/yogendrabhardwaj/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![msedge_4s2PAKHHxi](https://user-images.githubusercontent.com/6441478/127602851-828bd189-be42-4755-bad7-63433ea6c8e7.png)

![msedge_xxp32Lr8C1](https://user-images.githubusercontent.com/6441478/127602903-8567c64d-0cee-4e5b-9a2b-4be091034fa3.png)

![msedge_xaGwAh3BDL](https://user-images.githubusercontent.com/6441478/127602952-3f2a4142-27a4-400b-89ed-1476216598e9.png)

**Comment by hemidactylus** [comment]
Hello! Congratulations, you completed the homework!
But warning: the first screenshot was showing your secret DB token almost in its entirety so I deleted the image. Please consider revoking the token in your Astra DB console and generating a new one for future uses.

**Comment by HadesArchitect** [comment]
Hey **Yogendra Bhardwaj**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/c0GbtfGrSdWsufMuSynlNg
