### ISSUE TITLE
[HW] <VARNIKA MITTAL>

### ISSUE THREAD

**Issue by VarnikaMittal** [datastaxdevs/workshop-introduction-to-nosql#386]
**Name:** VARNIKA MITTAL
**Email:** me.varnika@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/varnika-mittal-b1978761/

Attach the homework screenshots below:
-----------------------------------------

<2ND STEP COMPLETION SCREENSHOTS>
![image](https://user-images.githubusercontent.com/82815271/127601850-fc75e085-cfe6-46a7-9a67-340f18d360e1.png)

<3RD STEP COMPLETION SCREENSHOTS>
![image](https://user-images.githubusercontent.com/82815271/127602051-0b6e90cc-c0e8-4c00-b040-afe05257315e.png)

<4TH STEP COMPLETION SCREENSHOTS>
![image](https://user-images.githubusercontent.com/82815271/127602154-0fd2ba91-62a2-4c13-94ac-d3c5ac23d8c6.png)

<SCENARIO COMPLETION SCREENSHOTS>
![image](https://user-images.githubusercontent.com/82815271/127603526-1a11fe43-28d8-41b9-9759-8c15a544277c.png)
![image](https://user-images.githubusercontent.com/82815271/127603545-7b3fe11f-6c23-440c-8a8d-d92b888bc6c2.png)

**Comment by HadesArchitect** [comment]
Hey **VARNIKA MITTAL**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/JkVoMvKYSjCGzEqyADwrZg
