### ISSUE TITLE
[HW] ABHISHEK PUROHIT

### ISSUE THREAD

**Issue by abhishekpurohit84** [datastaxdevs/workshop-introduction-to-nosql#388]
**Name:** ABHISHEK PUROHIT
**Email:** abhishekpurohit84@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/abhishek-purohit-2046591a/

Attach the homework screenshots below:
-----------------------------------------

![Screenshot 2021-07-30 113659](https://user-images.githubusercontent.com/88179810/127609036-443f3796-7813-4b1c-905b-1d23f48fd46f.png)
![Screenshot 2021-07-30 111721](https://user-images.githubusercontent.com/88179810/127609056-9c893eeb-2841-4786-b465-ae6ddbb6156c.png)
![Screenshot 2021-07-30 111750](https://user-images.githubusercontent.com/88179810/127609060-b4ce47e6-be4d-4b64-9a27-4d921d0e515d.png)

**Comment by HadesArchitect** [comment]
Hey **ABHISHEK PUROHIT**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/hqNu2c-9TmKvKle3692SUg

**Comment by abhishekpurohit84** [comment]
Thanks much. It was a great leaning session.
