### ISSUE TITLE
[HW] Ananya Banerjee | Introduction to NOSQL Workshop

### ISSUE THREAD

**Issue by aspiringananya** [datastaxdevs/workshop-introduction-to-nosql#390]
**Name:** Ananya Banerjee
**Email:** aspiringananya@gmail.com
**Linkedin Profile:**  https://www.linkedin.com/in/ananya-b-982a6b51/

Attach the homework screenshots below:
-----------------------------------------

<img width="1393" alt="Screenshot 2021-07-29 at 8 50 34 PM" src="https://user-images.githubusercontent.com/33785332/127614986-11afecc2-641f-4f9e-81f0-d94a0f21e847.png">
<img width="1425" alt="Screenshot 2021-07-29 at 8 50 49 PM" src="https://user-images.githubusercontent.com/33785332/127615012-e65aa4e7-485a-4205-a5d7-42b5e7ae45f4.png">
<img width="1419" alt="Screenshot 2021-07-29 at 8 51 39 PM" src="https://user-images.githubusercontent.com/33785332/127615079-50b60ad3-1c65-4081-b056-9497db8bf46a.png">
<img width="1411" alt="Screenshot 2021-07-29 at 8 52 16 PM" src="https://user-images.githubusercontent.com/33785332/127615278-b1845d63-4272-452a-9cf7-3d6c3a53a9a5.png">
<img width="1418" alt="Screenshot 2021-07-29 at 8 52 58 PM" src="https://user-images.githubusercontent.com/33785332/127615417-9a4596e0-e015-450f-a0aa-512fa8711e64.png">
<img width="1418" alt="Screenshot 2021-07-29 at 8 53 13 PM" src="https://user-images.githubusercontent.com/33785332/127615480-c62a9808-c546-4113-a921-bf9ae3610577.png">
<img width="1422" alt="Screenshot 2021-07-29 at 8 53 53 PM" src="https://user-images.githubusercontent.com/33785332/127615528-cd392ba1-ac4c-451d-bef6-380fb816670e.png">
<img width="1422" alt="Screenshot 2021-07-29 at 8 54 15 PM" src="https://user-images.githubusercontent.com/33785332/127615625-6d1a3b65-2441-4da6-81ff-44a01cbef1f1.png">
<img width="1418" alt="Screenshot 2021-07-29 at 9 53 33 PM" src="https://user-images.githubusercontent.com/33785332/127615682-5c4d0657-a8fb-4178-a24d-5c42f3e712a2.png">
<img width="1411" alt="Screenshot 2021-07-29 at 9 53 48 PM" src="https://user-images.githubusercontent.com/33785332/127615743-394c969d-212e-474f-83cd-8aac66357d58.png">
<img width="1418" alt="Screenshot 2021-07-29 at 8 52 35 PM" src="https://user-images.githubusercontent.com/33785332/127615880-a2abc962-54ec-4564-8ea6-a26aa8f2f124.png">
<img width="1400" alt="Screenshot 2021-07-30 at 12 15 57 PM" src="https://user-images.githubusercontent.com/33785332/127615937-f23c19f8-096a-46cd-a526-842c31ba9f61.png">
<img width="1403" alt="Screenshot 2021-07-30 at 12 17 29 PM" src="https://user-images.githubusercontent.com/33785332/127615964-6c4a1c2d-bdd3-4f67-9d8c-75e9836e8a1c.png">
<img width="1076" alt="Screenshot 2021-07-30 at 12 28 21 PM" src="https://user-images.githubusercontent.com/33785332/127615995-a667a850-59fc-4b2c-8acb-2f63e187f22f.png">
<img width="1410" alt="Screenshot 2021-07-30 at 12 28 54 PM" src="https://user-images.githubusercontent.com/33785332/127616009-bef836cc-d15f-44d7-adf5-9b5dbb6e5d9d.png">
<img width="1422" alt="Screenshot 2021-07-30 at 12 32 04 PM" src="https://user-images.githubusercontent.com/33785332/127616056-509fb1d5-8a82-4c0e-8e15-d9d19d8f277a.png">
<img width="1416" alt="Screenshot 2021-07-30 at 12 32 24 PM" src="https://user-images.githubusercontent.com/33785332/127616092-d27c9179-5aea-445e-9f54-a44f26489be7.png">
<img width="1420" alt="Screenshot 2021-07-30 at 12 32 55 PM" src="https://user-images.githubusercontent.com/33785332/127616139-b71ada11-c127-4a93-aeed-026fa5f76978.png">
<img width="1423" alt="Screenshot 2021-07-30 at 12 33 50 PM" src="https://user-images.githubusercontent.com/33785332/127616195-f5d6f2f7-dc32-44ac-bb7c-dd51d4bff4f2.png">
<img width="1417" alt="Screenshot 2021-07-30 at 11 06 57 AM" src="https://user-images.githubusercontent.com/33785332/127616365-e9188b0e-b56c-4a6e-a311-fe868ee99db6.png">
<img width="1419" alt="Screenshot 2021-07-30 at 11 07 25 AM" src="https://user-images.githubusercontent.com/33785332/127616422-a7d9de54-2f4a-4e4c-85f1-ed62e1f1befa.png">
<img width="1422" alt="Screenshot 2021-07-30 at 11 07 54 AM" src="https://user-images.githubusercontent.com/33785332/127616520-693d17d2-2a13-45ce-abfb-eb0db1641549.png">
<img width="1419" alt="Screenshot 2021-07-30 at 11 08 23 AM" src="https://user-images.githubusercontent.com/33785332/127616666-9a46f90e-0d08-42c9-b997-2e7ad160c970.png">
<img width="1422" alt="Screenshot 2021-07-30 at 11 08 42 AM" src="https://user-images.githubusercontent.com/33785332/127616762-a3c45578-7f62-471c-9540-da708a0bed78.png">
<img width="1420" alt="Screenshot 2021-07-30 at 11 09 19 AM" src="https://user-images.githubusercontent.com/33785332/127616843-d1222405-fc3a-400c-a32d-f99c867c6134.png">
<img width="1065" alt="Screenshot 2021-07-30 at 11 09 06 AM" src="https://user-images.githubusercontent.com/33785332/127616892-2cc8e59d-a58c-4f6a-9b98-677f4ecdf185.png">

**Comment by hemidactylus** [comment]
Hello, well done! Enjoy your badge!
But warning: I had to remove two images which were showing your secret Astra DB token. Please consider revoking the token and creating a new one!

**Comment by HadesArchitect** [comment]
Hey **Ananya Banerjee**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/o8ZCxF76RGawkEVPszRfSQ
