### ISSUE TITLE
[HW] <RENUKA MANE>

### ISSUE THREAD

**Issue by renuka244** [datastaxdevs/workshop-introduction-to-nosql#391]
**Name:** RENUKA MANE
**Email:** renukamane1998@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------
STEP 4 SCREENSHOTS:
![image](https://user-images.githubusercontent.com/76238639/127617877-0187b852-047a-4879-bd31-b2391fa184b2.png)
![image](https://user-images.githubusercontent.com/76238639/127617925-dc84979a-5120-4d3a-a097-3b2e381219f0.png)
![image](https://user-images.githubusercontent.com/76238639/127617983-efacf0e7-e09f-413f-8a7e-02d117750767.png)
![image](https://user-images.githubusercontent.com/76238639/127618027-4ffbaffd-76e9-4133-a214-017834f8d31b.png)
![image](https://user-images.githubusercontent.com/76238639/127618064-d4123115-f02c-49a1-9f3c-1dc5338fe19e.png)

**Comment by HadesArchitect** [comment]
Hey **RENUKA MANE**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/66-0joogS-ej5xSTI036cg
