### ISSUE TITLE
[HW] Pier Falbo

### ISSUE THREAD

**Issue by falbop** [datastaxdevs/workshop-introduction-to-nosql#392]
**Name:** Pier Falbo
**Email:** subguitar2002@yahoo.it
**Linkedin Profile:** none

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/13572748/127626194-8d5e047b-9144-4b31-b727-76e548300a85.png)

![image](https://user-images.githubusercontent.com/13572748/127621060-043feb0b-3786-45a1-84be-c29a32e7431d.png)

![image](https://user-images.githubusercontent.com/13572748/127621178-693c3223-8958-47c3-b182-f945d46a5936.png)

![image](https://user-images.githubusercontent.com/13572748/127621229-76490cab-b2cf-4350-9b52-999acd723d7b.png)

![image](https://user-images.githubusercontent.com/13572748/127621289-6f78b613-d234-40ba-ac22-08d86e6a32b8.png)

![image](https://user-images.githubusercontent.com/13572748/127621345-c90be1c4-b8d6-483c-93aa-7ee8a2ff5def.png)

![image](https://user-images.githubusercontent.com/13572748/127621462-e4223a86-b211-484e-9318-26fe9c43ebea.png)

![image](https://user-images.githubusercontent.com/13572748/127621518-e8723bda-1a49-4815-b493-bef235034104.png)

![image](https://user-images.githubusercontent.com/13572748/127621559-103bc279-6f59-4962-b4aa-2c0ffe62289e.png)

**Comment by hemidactylus** [comment]
Hi, Pier,
well done! You deserve a badge!
Unfortunately we cannot issue you the badge unless you add your email address above (I added a sample line to add it to the submission text).
Thank you!

**Comment by falbop** [comment]
Hi @hemidactylus please use this: subguitar2002@yahoo.it

Cheers!
P

**Comment by falbop** [comment]
Hi @hemidactylus  @HadesArchitect  @SonicDMG  @RyanWelford 
any news? :)

KR
P

**Comment by HadesArchitect** [comment]
Hey **Pier Falbo**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/D5hvnmYOSRq9TfYdD0pWzQ
