### ISSUE TITLE
[HW] <PRAKASH UDHAYAKUMAR>

### ISSUE THREAD

**Issue by prakash007** [datastaxdevs/workshop-introduction-to-nosql#394]
**Name:** PRAKASH UDHAYAKUMAR
**Email:** u.prakash007@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/prakashudhayakumar/>

Attach the homework screenshots below:
-----------------------------------------

![Screenshot_20](https://user-images.githubusercontent.com/3389904/127639657-10db0312-e37f-4632-9e4f-2410e17e8393.png)

![Screenshot_22](https://user-images.githubusercontent.com/3389904/127639320-1aa6da02-6e78-423d-8116-83397c646ef9.png)

**Comment by HadesArchitect** [comment]
Hey **PRAKASH UDHAYAKUMAR**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/QBVK3T9QT3ego7XET-Vvlg
