### ISSUE TITLE
[HW] <Akash Kumar>

### ISSUE THREAD

**Issue by a15akash** [datastaxdevs/workshop-introduction-to-nosql#395]
**Name:** Akash kumar
**Email:** akashkumar15.2013@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/akash-kumar-65b68642/

Attach the homework screenshots below:
-----------------------------------------
![scenario_1_completed](https://user-images.githubusercontent.com/88190514/127642103-46919f9a-1f68-417b-9499-261526537cdf.PNG)

![scenario_2_completed](https://user-images.githubusercontent.com/88190514/127642242-0ca6679c-5d51-4365-86bb-83a059a3c2d2.PNG)

**Comment by HadesArchitect** [comment]
Hey **Akash kumar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/73B2Pp8VSBubz2afEAY-Kg
