### ISSUE TITLE
[HW] Zbigniew Mocarski

### ISSUE THREAD

**Issue by zbyniek5000** [datastaxdevs/workshop-introduction-to-nosql#396]
**Name:** Zbigniew Mocarski
**Email:** zbyniek5000@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/zbigniew-mocarski-4781857a/

Attach the homework screenshots below:
-----------------------------------------

![obraz](https://user-images.githubusercontent.com/42603492/127645182-3b52e20b-6479-4fe8-b1e3-1645f332f9e7.png)

**Comment by HadesArchitect** [comment]
Hey **Zbigniew Mocarski**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/cZY0LW4_TiSIjtLDB2R1Ag
