### ISSUE TITLE
[HW] Abhay Tiwari

### ISSUE THREAD

**Issue by Abhaytiwarikit** [datastaxdevs/workshop-introduction-to-nosql#398]
**Name:** Abhay Tiwari
**Email:** abhaytiwarikit@gmail.com
**Linkedin Profile:** www.linkedin.com/in/abhay-tiwari-215a04148

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Looks good Abhay! Thanks for the thorough documentation. FYI, I removed the images as some of them included the Astra token. We recommend deleting the token for security.

**Comment by HadesArchitect** [comment]
Hey **Abhay Tiwari**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/iIgPuOTRQuqv1aved0qmjA
