### ISSUE TITLE
[HW] Irfan Ahmad

### ISSUE THREAD

**Issue by write2irfanahmad** [datastaxdevs/workshop-introduction-to-nosql#399]
**Name:** Irfan Ahmad
**Email:** write2irfanahmad@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ranairfanahmad/

Attach the homework screenshots below:
-----------------------------------------
<![image](https://user-images.githubusercontent.com/88191624/127646253-9a746d31-c057-4a30-85b0-e3556bd5311c.png)>
<
![image](https://user-images.githubusercontent.com/88191624/127646330-5b29afec-7df3-43e9-bfee-c554d4ad773e.png)
>
<
![image](https://user-images.githubusercontent.com/88191624/127646524-954b5f75-3bd7-46dc-9bf6-cbe77ac16fde.png)
>

**Comment by write2irfanahmad** [comment]
how long will it take to review my HW, ? @HadesArchitect @SonicDMG @RyanWelford

**Comment by RyanWelford** [comment]
Hi Irfan, sorry for the wait, been a bit backed up. Well done on the homework though!

**Comment by HadesArchitect** [comment]
Hey **Irfan Ahmad**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/JEBoXcCeTpCqxiu0WvXjhw
