### ISSUE TITLE
[HW] DAMLA SEVİNÇ TOKDEMİR

### ISSUE THREAD

**Issue by damlaSevinc** [datastaxdevs/workshop-introduction-to-nosql#400]
**Name:** DAMLA SEVİNÇ TOKDEMİR
**Email:** sevincdamla@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/damla-sevinç-156993115/

Attach the homework screenshots below:
-----------------------------------------
**1 . CREATE ASTRADB INSTANCE**
<img width="1420" alt="Screen Shot 2021-07-30 at 15 06 12" src="https://user-images.githubusercontent.com/84271633/127650589-97f84d0d-009f-4ea8-b340-65395731c34e.png">

<img width="1420" alt="Screen Shot 2021-07-30 at 15 04 10" src="https://user-images.githubusercontent.com/84271633/127650367-f0cfda82-1181-4257-bc35-c15fc0564f46.png">

**2 . TABULAR DATABASES**
<img width="1420" alt="Screen Shot 2021-07-30 at 15 13 26" src="https://user-images.githubusercontent.com/84271633/127651347-f723cfe0-a48d-4916-a1e0-ceb9a79abe5f.png">

**3 . DOCUMENT DATABASES**
<img width="1420" alt="Screen Shot 2021-07-30 at 15 29 11" src="https://user-images.githubusercontent.com/84271633/127653083-7d37953c-8464-4582-aa8e-e7e895cde18f.png">

<img width="1420" alt="Screen Shot 2021-07-30 at 15 18 02" src="https://user-images.githubusercontent.com/84271633/127651888-f1e31089-87be-45b8-a672-adc79b035bef.png">

<img width="1420" alt="Screen Shot 2021-07-30 at 15 21 08" src="https://user-images.githubusercontent.com/84271633/127652281-c3c76789-a318-4ffc-8dab-2fcb1f1641a1.png">

<img width="1420" alt="Screen Shot 2021-07-30 at 15 23 34" src="https://user-images.githubusercontent.com/84271633/127652589-eed7a7d0-e1b0-4865-a628-774f7bd5a717.png">

**4. KEYVALUE DATABASES**
I applied key_value part for GraphQL. Also, I applied GraphQL API section playground steps (books)
<img width="1427" alt="Screen Shot 2021-07-30 at 14 15 09" src="https://user-images.githubusercontent.com/84271633/127653760-f706b7de-e0b6-47f5-a44f-ae89b9ffb228.png">
<img width="1420" alt="Screen Shot 2021-07-30 at 14 19 00" src="https://user-images.githubusercontent.com/84271633/127653766-775bdd4a-cad6-4601-b4ef-6a910bc8af1a.png">
<img width="1420" alt="Screen Shot 2021-07-30 at 14 44 27" src="https://user-images.githubusercontent.com/84271633/127653769-f2809a9f-d85b-4bf4-9f74-43b039e810c5.png">
<img width="1420" alt="Screen Shot 2021-07-30 at 14 45 08" src="https://user-images.githubusercontent.com/84271633/127653773-d8ac6e27-f7d3-419f-ab4c-db83a94f1876.png">
<img width="1420" alt="Screen Shot 2021-07-30 at 14 47 21" src="https://user-images.githubusercontent.com/84271633/127653779-1d18c4a8-54dd-4d44-aa2c-ef22e6e6bf4d.png">
<img width="1420" alt="Screen Shot 2021-07-30 at 14 47 56" src="https://user-images.githubusercontent.com/84271633/127653786-0c03f14d-eddc-43ea-8455-3ecb2fc61d0b.png">
--- Playground books:
<img width="1427" alt="Screen Shot 2021-07-29 at 20 39 28" src="https://user-images.githubusercontent.com/84271633/127653703-ec15ff3f-be5b-44b9-b67a-68a9de1e0858.png">
<img width="1427" alt="Screen Shot 2021-07-29 at 20 41 09" src="https://user-images.githubusercontent.com/84271633/127653712-c3b076de-33ca-44bc-9487-cabba480c131.png">
<img width="1427" alt="Screen Shot 2021-07-29 at 20 41 48" src="https://user-images.githubusercontent.com/84271633/127653722-92b957f5-76f0-4e2d-9ee5-2bd83c1a0e6f.png">
<img width="1427" alt="Screen Shot 2021-07-29 at 20 42 25" src="https://user-images.githubusercontent.com/84271633/127653727-868d8602-e3e6-4f02-b15f-9fb41a88f2c2.png">
<img width="1427" alt="Screen Shot 2021-07-29 at 20 43 39" src="https://user-images.githubusercontent.com/84271633/127653735-5f53995d-d66f-4764-8dab-ddcc682a1d87.png">
<img width="1427" alt="Screen Shot 2021-07-29 at 20 44 26" src="https://user-images.githubusercontent.com/84271633/127653744-550209c7-05c0-43de-b02c-0bb2e0b4cd1d.png">

**Scenario completed screenschots:**
>
<img width="1420" alt="Screen Shot 2021-07-30 at 14 55 11" src="https://user-images.githubusercontent.com/84271633/127653832-2819953b-92f3-4814-9c29-481e8cb1afb8.png">
<img width="1420" alt="Screen Shot 2021-07-30 at 14 55 23" src="https://user-images.githubusercontent.com/84271633/127653840-56d933e6-054a-4e06-b936-d0b00ed69505.png">
<img width="1420" alt="Screen Shot 2021-07-30 at 14 54 28" src="https://user-images.githubusercontent.com/84271633/127653818-32001e35-5b20-4dda-891a-c5927cd82e41.png"

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Thanks Damla! I removed a couple images that included your Astra token. We recommend deleting the token.

**Comment by HadesArchitect** [comment]
Hey **DAMLA SEVİNÇ TOKDEMİR**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/aS-C16JnQKairxz3c398Bg
