### ISSUE TITLE
[HW] Nilesh Gaikwad | Workshop Introduction to nosql

### ISSUE THREAD

**Issue by nilesh-gaikwad** [datastaxdevs/workshop-introduction-to-nosql#401]
**Name:** Nilesh Gaikwad
**Email:** nilesh.gaikwad@outlook.com
**Linkedin Profile:** https://www.linkedin.com/in/gaikwadnilesh/

Attach the homework screenshots below:
-----------------------------------------

<img width="1435" alt="Screen Shot 2021-07-30 at 9 03 14 AM" src="https://user-images.githubusercontent.com/16022810/127656879-4221b514-3a0f-4fb6-b0ce-15d6c4b76c19.png">
<img width="957" alt="Screen Shot 2021-07-30 at 9 03 32 AM" src="https://user-images.githubusercontent.com/16022810/127656890-4fbc5e9d-5192-4480-8e0a-9412940f1ef2.png">

**Comment by SonicDMG** [comment]
Hi there Nilesh, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by nilesh-gaikwad** [comment]
Thanks David for quick review.
Apologies for missing that screenshot. 

Please find same below.
<img width="1288" alt="Cassandra_Demo" src="https://user-images.githubusercontent.com/16022810/129067134-5c6b6e78-2170-4e08-8cc0-4ef93977cbbb.png">

**Comment by HadesArchitect** [comment]
Hey **Nilesh Gaikwad**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/GH3hZwOiQkixwMCto7NCDQ
