### ISSUE TITLE
[HW] Girish Kumar Eduru

### ISSUE THREAD

**Issue by girisheduru** [datastaxdevs/workshop-introduction-to-nosql#403]
**Name:** Girish Kumar Eduru
**Email:**  girishkumar.eduru@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/girish-kumar-eduru-72798121/

Attach the homework screenshots below:
-----------------------------------------
Screenshot of the completed Step 4 
![Screenshot 2021-07-30 at 16 02 10](https://user-images.githubusercontent.com/19798980/127670525-52a7308f-0bb1-4088-95f1-98a4e6c16c95.png)

Screenshot of the completed step 5 
Wait for the application to start (30s) and open http://localhost:9091
Application starts but URL give no response on my MAC 
![Screenshot 2021-07-30 at 16 25 25](https://user-images.githubusercontent.com/19798980/127674000-cee1fbd8-58f7-4f88-89c2-f400492cbfcc.png)
![Screenshot 2021-07-30 at 16 26 09](https://user-images.githubusercontent.com/19798980/127674019-7c4d7ed9-5720-4651-b255-a82f6b662b31.png)
![Screenshot 2021-07-30 at 16 28 17](https://user-images.githubusercontent.com/19798980/127674051-e48ffec6-3b16-4473-a6a1-2210ce31fdcd.png)

Katacoda Tryout scenario screenshots 
![Screenshot 2021-07-30 at 16 33 56](https://user-images.githubusercontent.com/19798980/127674635-a0ea939c-28ea-4bee-afd0-aaf2970761fc.png)
![Screenshot 2021-07-30 at 16 33 43](https://user-images.githubusercontent.com/19798980/127674674-ea67edc5-0fa1-4455-baaf-51a532e2d699.png)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Girish Kumar Eduru**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/t0to1IEnQUaF3wBru0DFsw
