### ISSUE TITLE
[HW] Arpita Jana

### ISSUE THREAD

**Issue by Arpita003** [datastaxdevs/workshop-introduction-to-nosql#404]
**Name:** Arpita Jana
**Email:** arpitajana102@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/arpita-jana-7524745a/>

Attach the homework screenshots below:
-----------------------------------------
![Untitled45](https://user-images.githubusercontent.com/88202421/127677491-a7f4baae-0c21-43af-8766-d93ab82da638.png)
![Untitled](https://user-images.githubusercontent.com/88202421/127677517-c1f3be02-70cc-4952-b273-b130a6558e53.png)
![Untitled3A](https://user-images.githubusercontent.com/88202421/127677535-614aece1-d5b7-4a60-bfc9-f1315c559a7b.png)
![Untitled41](https://user-images.githubusercontent.com/88202421/127677545-680b940c-bdfa-463b-b88e-a281e99ae09d.png)
![Untitled42](https://user-images.githubusercontent.com/88202421/127677557-02e11f97-e0ea-4e18-8f2d-06cb274efac4.png)
![Untitled43](https://user-images.githubusercontent.com/88202421/127677575-c58ae113-d339-433e-8350-db3852ade6c0.png)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Hi there Arpita, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by Arpita003** [comment]
Hi David,

I have completed the step 2 task.
Please find the screen shot.

[image: image.png]

**Comment by SonicDMG** [comment]
Hi again Arpita. It looks like your image did not attach properly. You mind posting that again?

**Comment by Arpita003** [comment]
Sure, here it is.
Please let me know it is ok or not.

**Comment by HadesArchitect** [comment]
Hey **Arpita Jana**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/8TzIjZVdSyaR8aou8b83BQ
