### ISSUE TITLE
HW-Naveen Kumar Gupta

### ISSUE THREAD

**Issue by nvngpt** [datastaxdevs/workshop-introduction-to-nosql#405]
**Name:** Naveen Kumar Gupta
**Email:** gnaveensoft@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/naveen-gupta-653303147

Attach the homework screenshots below:
-----------------------------------------

![Screenshot_2021-07-30-22-00-59-18](https://user-images.githubusercontent.com/67554947/127684508-aafe5ac6-16e4-42b5-b193-f50be5ef7b70.jpg)
![Screenshot_2021-07-30-22-00-44-22](https://user-images.githubusercontent.com/67554947/127684524-aae01359-23a1-4669-aad7-16187fcca0c7.jpg)
![Screenshot_2021-07-30-22-00-18-50](https://user-images.githubusercontent.com/67554947/127684534-13c788e8-55be-411d-84a1-1aabceeb61e3.jpg)
![Screenshot_2021-07-30-21-59-49-01](https://user-images.githubusercontent.com/67554947/127684539-284792fd-3a49-475f-8006-d17e8f386a07.jpg)

**Comment by SonicDMG** [comment]
Hi there Naveen, thank you for your submission. We are missing step 1 from the homework.
1. Complete the practice steps of this workshop as explained below, steps I-IV are mandatory, step V is optional. Take screenshots of the last completed step from either step IV or V. NOTE: When taking screenshots ensure NOT to copy your Astra DB key!

Please include the required screenshot for your badge. :)

**Comment by HadesArchitect** [comment]
Hey **Naveen Kumar Gupta**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/KWsinverTA6e-A2BU6CKeQ
