### ISSUE TITLE
[HW] Saideep Dicholkar

### ISSUE THREAD

**Issue by saideepd** [datastaxdevs/workshop-introduction-to-nosql#407]
**Name:** Saideep Dicholkar
**Email:** dicholkarsaideep@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/saideep-dicholkar

Attach the homework screenshots below:
-----------------------------------------

SCREENSHOTS:
![NoSQL_Step4](https://user-images.githubusercontent.com/30663492/127687608-d0dad1e1-6382-470a-a82e-bf7911a8c196.PNG)

![NoSQL_TryItOutScenario](https://user-images.githubusercontent.com/30663492/127687628-4f4177b4-75dc-4aa5-9d94-a2b69562f30d.PNG)

**Comment by HadesArchitect** [comment]
Hey **Saideep Dicholkar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/W80TqwA6QwqEnp2OjDU7SQ
