### ISSUE TITLE
[HW] Bhavesh Vani

### ISSUE THREAD

**Issue by BhaveshVani** [datastaxdevs/workshop-introduction-to-nosql#408]
**Name:**  Bhavesh Vani
**Email:**  w.bhavesh@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/bhavesh-vani-634aa628/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
<img width="697" alt="homwork_nosql_workshop" src="https://user-images.githubusercontent.com/6427654/127688003-d1237f72-4086-4011-a5da-e7e920727baa.PNG">
<img width="960" alt="Try-it-out-scenario" src="https://user-images.githubusercontent.com/6427654/127688020-8393cea2-9bfb-4009-b392-c9566504079b.PNG">

**Comment by HadesArchitect** [comment]
Hey **Bhavesh Vani**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/6BysNmmES4ub8Ff8hT5CwA
