### ISSUE TITLE
[HW] Tyler Hartshorn

### ISSUE THREAD

**Issue by tylerhartshorn** [datastaxdevs/workshop-introduction-to-nosql#41]
**Name:** Tyler Hartshorn
**Email:** tylerhartshorn@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/tyler-hartshorn-18016684/

Thanks so much, awesome training!
Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
-- images removed by team --

**Comment by SonicDMG** [comment]
Hi Tyler, thanks for your submission. I noticed you got the validation error when working via the graphQL exercise. I'll take that as my fault. I updated the instructions to be a lot clearer this morning so it should help you get past that if you got stuck there.

**Comment by tylerhartshorn** [comment]
Thanks for your flexibility. I did validate the graphQL correctly, the instructions were great honestly. My issue was that I completed all the exercises and then only afterward realized I needed to screenshot. So I went back quickly and I guess I was not as thorough the second time around.

**Comment by SonicDMG** [comment]
Haha, no worries. That happens. I totally understand having to go back through and do all of the work again just to take screenshots is probably not the best fun. :)

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/elIT17yuQY6xloiJHaK3yA?identity__email=tylerhartshorn%40gmail.com
