### ISSUE TITLE
[HW] Vince Andrei Isip

### ISSUE THREAD

**Issue by Kiel-Hyre** [datastaxdevs/workshop-introduction-to-nosql#411]
**Name:** Vince Andrei Isip
**Email:** vinceadisip@gmail.com
**Linkedin Profile:** www.linkedin.com/in/vince-andrei-isip-08a52b112

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

- Activity 4
![Screenshot from 2021-07-31 01-44-56](https://user-images.githubusercontent.com/40416631/127691873-884d7cc5-06b3-4594-876e-8ff353cdc004.png)

- Activity 5
![Screenshot from 2021-07-31 01-31-32](https://user-images.githubusercontent.com/40416631/127692562-e3bca35f-8ad4-4331-a412-0ebf39f6c858.png)

- Try it out
![Screenshot from 2021-07-31 01-38-31](https://user-images.githubusercontent.com/40416631/127691303-bf857810-0a52-4f4f-90c3-b2d234d28699.png)

- Some Snippet from 1-3
![Screenshot from 2021-07-31 01-14-32](https://user-images.githubusercontent.com/40416631/127692001-0dcd83d2-26ac-4a38-83da-54e80e2be6a6.png)
![Screenshot from 2021-07-31 01-18-24](https://user-images.githubusercontent.com/40416631/127692013-d0ec3bad-275c-4e6f-b83e-15af6ba2158e.png)
![Screenshot from 2021-07-31 01-22-47](https://user-images.githubusercontent.com/40416631/127692033-ca3b967b-302c-4044-968e-78e5778cd8ae.png)

**Comment by HadesArchitect** [comment]
Hey **Vince Andrei Isip**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/pn0zgU6zTEWl58nsGfwPHQ

**Comment by SonicDMG** [comment]
Nice job getting through the Graph portion as well. :D
