### ISSUE TITLE
[HW] SantoshBhat

### ISSUE THREAD

**Issue by santoshbhats** [datastaxdevs/workshop-introduction-to-nosql#412]
**Name:** Santosh Bhat
**Email:** santosh.bhats@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/bhatsantosh

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/13821698/127691433-6a286b19-6233-4c82-88b2-15200e150bf1.png)

![image](https://user-images.githubusercontent.com/13821698/127691302-f65c0d6e-5853-4e9c-8115-82edff8b90e9.png)

**Comment by HadesArchitect** [comment]
Hey **Santosh Bhat**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/kI37wr_xQri3LBcel0eq7g
