### ISSUE TITLE
[HW]  Kuna Lakshmi Vara Prasad

### ISSUE THREAD

**Issue by klvp** [datastaxdevs/workshop-introduction-to-nosql#413]
**Name:**  Kuna Lakshmi Vara Prasad
**Email:**  klvpfeb98@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/lakshmi-vara-prasad-kuna-255134171/

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/43074474/127696432-f11efe3f-ba42-4802-94fc-103dd8d238d5.png)

-- image removed by team --

![KetValueDB](https://user-images.githubusercontent.com/43074474/127696492-ed1ecec7-b6d4-4389-98e2-a46546919173.jpg)

![TabularDB](https://user-images.githubusercontent.com/43074474/127696511-d3cb6000-9abe-40ea-8f6c-f5df5691303b.jpg)

**Comment by HadesArchitect** [comment]
Hey **Kuna Lakshmi Vara Prasad**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/QUD9dARdS7eBF0Yop2UqYQ

**Comment by SonicDMG** [comment]
Also, I had to remove one of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.
