### ISSUE TITLE
[HW] Prakash Vaithilingam

### ISSUE THREAD

**Issue by prakashnsm** [datastaxdevs/workshop-introduction-to-nosql#414]
**Name:** Prakash Vaithilingam
**Email:** prakash.nsm@gmail.com
**Linkedin Profile:**  https://www.linkedin.com/in/prakashnsm/

Attach the homework screenshots below:
-----------------------------------------
Scenario: 
![image](https://user-images.githubusercontent.com/3167450/127698797-2c6aa080-9649-4a92-a591-aaee313811c8.png)

1-4: completed 5th one In Progress, i am having some issue in Datasax Studio container is not running, currently looking into that

4:
![2021-07-29_10h30_08](https://user-images.githubusercontent.com/3167450/127698365-7e395a74-ad85-458e-aa04-ffc8b20e5ba3.png)
![2021-07-29_10h35_22](https://user-images.githubusercontent.com/3167450/127698379-32ab84f8-2647-4333-a268-986f9eeca2bc.png)

**Comment by HadesArchitect** [comment]
Hey **Prakash Vaithilingam**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/RhhAEy1OQ3yZ1QlaIWX21A
