### ISSUE TITLE
[HW] SaiRaghava Katepally

### ISSUE THREAD

**Issue by sairaghavak** [datastaxdevs/workshop-introduction-to-nosql#415]
**Name:**  SaiRaghava Katepally
**Email:** ksairaghava1@gmail.com
**Linkedin Profile:** 

Attach the homework screenshots below:
-----------------------------------------
<img width="691" alt="1-sairaghava-k-scenario-completed" src="https://user-images.githubusercontent.com/16429828/127705970-d303ef39-bbe5-4485-85a6-902a96c06240.png">

<img width="922" alt="2-sairaghava-k-step-4-completed-1" src="https://user-images.githubusercontent.com/16429828/127705992-34a1febf-2187-4c53-a510-90cba7ba7c9f.png">

<img width="924" alt="3-sairaghava-k-step-4-completed-2" src="https://user-images.githubusercontent.com/16429828/127705942-d93e2f9b-cc74-4312-8c31-1f2d7208cd04.png">

**Comment by HadesArchitect** [comment]
Hey **SaiRaghava Katepally**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/AFr6uC__TU-OJWfR5lvT6w
