### ISSUE TITLE
[HW] Paras

### ISSUE THREAD

**Issue by daveparas420** [datastaxdevs/workshop-introduction-to-nosql#416]
**Name:** Paras Dave
**Email:** paras.16beceg045@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/paras-dave-059044194/

Attach the homework screenshots below:
-----------------------------------------

![step4](https://user-images.githubusercontent.com/60460708/127709970-d167e073-4eb7-4b63-bc6e-04c271d2e315.PNG)

![tryitout](https://user-images.githubusercontent.com/60460708/127709882-1659b033-fda5-45c9-aff6-0d8e61cfbdb2.PNG)

**Comment by HadesArchitect** [comment]
Hey **Paras Dave**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/rMxj09RmTGOetvN8swpFCA
