### ISSUE TITLE
[HW] Aditya

### ISSUE THREAD

**Issue by AdityaNavisite** [datastaxdevs/workshop-introduction-to-nosql#418]
**Name:** Aditya
**Email:** Adayal@navisite.com
**Linkedin Profile:** https://www.linkedin.com/in/aditya-dayal-0455a0106/

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/88215844/127788722-82f66947-99b5-40f1-b527-d356415e453d.png)

![image](https://user-images.githubusercontent.com/88215844/127788746-74ecefc0-2308-4f29-8581-6147ae8bba81.png)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Hi there Aditya, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by AdityaNavisite** [comment]
![image](https://user-images.githubusercontent.com/88215844/129284647-b0581b99-2581-4d20-86db-98a3cb0e1250.png)

**Comment by HadesArchitect** [comment]
Hey **Aditya**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/hCVtcn50TlWPTlRit4Ma-w

**Comment by AdityaNavisite** [comment]
How can I share it on LinkedIn ?

**Comment by SonicDMG** [comment]
You can add it as a featured item via the badge URL in your LinkedIn profile.
