### ISSUE TITLE
[HW] <ANSH>

### ISSUE THREAD

**Issue by Ansh01-alt** [datastaxdevs/workshop-introduction-to-nosql#419]
**Name:** ANSH
**Email:** bhartiansh01@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/ansh-bharti-889206191>

Attach the homework screenshots below:
4th part completed:-
![ASTRA work](https://user-images.githubusercontent.com/84898635/127725610-0019399b-2738-44e2-a2dd-dcf0ab1490b6.png)
![Astra work2](https://user-images.githubusercontent.com/84898635/127725615-c8374ad1-d703-4c66-9404-605506a6379f.png)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Hi there Ansh, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by HadesArchitect** [comment]
Hey **ANSH**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/e-2NFEs0T1SpNCXL3N8gfw
