### ISSUE TITLE
[HW] Bryan Moreno

### ISSUE THREAD

**Issue by sersoker** [datastaxdevs/workshop-introduction-to-nosql#42]
**Name:** Bryan Moreno Picamán
**Email:** bserso@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/bryanmp/

Attach the homework screenshots below:
-----------------------------------------

![Captura de pantalla de 2021-05-19 18-51-37](https://user-images.githubusercontent.com/23105777/118858739-c48e3480-b8d9-11eb-8580-f1bc9be8d46e.png)
![Captura de pantalla de 2021-05-19 18-51-54](https://user-images.githubusercontent.com/23105777/118858742-c5bf6180-b8d9-11eb-9d00-b9031df0a76e.png)
![Captura de pantalla de 2021-05-19 18-53-50](https://user-images.githubusercontent.com/23105777/118858745-c657f800-b8d9-11eb-8a7f-d7728fdf7320.png)
![Captura de pantalla de 2021-05-19 18-58-05](https://user-images.githubusercontent.com/23105777/118858747-c6f08e80-b8d9-11eb-9143-ddf29e05031e.png)
![Captura de pantalla de 2021-05-19 18-58-08](https://user-images.githubusercontent.com/23105777/118858750-c7892500-b8d9-11eb-8b34-86f04c4811a2.png)
![Captura de pantalla de 2021-05-19 18-58-12](https://user-images.githubusercontent.com/23105777/118858753-c821bb80-b8d9-11eb-9c22-0ae4aa21a4ab.png)
![Captura de pantalla de 2021-05-19 18-58-14](https://user-images.githubusercontent.com/23105777/118858757-c8ba5200-b8d9-11eb-80d4-3870bffb8f6c.png)
![Captura de pantalla de 2021-05-19 19-10-04](https://user-images.githubusercontent.com/23105777/118858760-c952e880-b8d9-11eb-8008-4b8721444d4e.png)
-- images removed by team --
![Captura de pantalla de 2021-05-19 19-33-45](https://user-images.githubusercontent.com/23105777/118858776-cc4dd900-b8d9-11eb-89b4-5335c66de3bb.png)
-- images removed by team --
![Captura de pantalla de 2021-05-19 19-36-34](https://user-images.githubusercontent.com/23105777/118858783-cce66f80-b8d9-11eb-83a2-3d0e1d188efe.png)
-- images removed by team --
![Captura de pantalla de 2021-05-19 19-37-37](https://user-images.githubusercontent.com/23105777/118858786-cd7f0600-b8d9-11eb-9dbe-c394d9fdc420.png)
![Captura de pantalla de 2021-05-19 18-30-28](https://user-images.githubusercontent.com/23105777/118858816-d4a61400-b8d9-11eb-9b51-d752fadf707f.png)

**Comment by SonicDMG** [comment]
Looks great Bryan, thank you.

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/69eEC3FKQCi6t5Oc0i9N2g?identity__email=bserso%40gmail.com
