### ISSUE TITLE
[HW] Bhanu Rawat

### ISSUE THREAD

**Issue by Bhanu890** [datastaxdevs/workshop-introduction-to-nosql#422]
**Name:** Bhanu Rawat
**Email:** rawatbhanu777@gmail.com
**Linkedin Profile:** www.linkedin.com/in/bhanu-rawat
![stepIV](https://user-images.githubusercontent.com/68594291/127731549-d10f6a2b-b8d4-4718-ab4e-e71017d100be.png)
![Tryitout](https://user-images.githubusercontent.com/68594291/127731553-1f2e4616-7e25-4985-8d52-8a10d8b9ac7e.png)

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Bhanu Rawat**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/vqM2sSreQOWM6uAMfMss_g
