### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by Vasudha-2010** [datastaxdevs/workshop-introduction-to-nosql#423]
**Name:** VASUDHA SINGH
**Email:** vasudha.singh2105@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/vasudha-singh21/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

<img width="960" alt="Nosql" src="https://user-images.githubusercontent.com/69085327/127731772-d9391263-623c-4032-a91a-ba6c035b7e46.PNG">
<img width="957" alt="Nosql2" src="https://user-images.githubusercontent.com/69085327/127731775-9af8ca76-3e58-4cfb-966b-7c1f429963ff.PNG">

**Comment by HadesArchitect** [comment]
Hey **VASUDHA SINGH**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Q0tOi1yGSD-tmcqkjlHAjQ
