### ISSUE TITLE
[HW] Sreenivas Kundanam

### ISSUE THREAD

**Issue by kemalsreenivas** [datastaxdevs/workshop-introduction-to-nosql#424]
**Name:** Sreenivas Kundanam
**Email:** kundanamsreenivas@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sreenivas-k-316247a6/

Attach the homework screenshots below:
-----------------------------------------
<img width="1437" alt="Try-it-out" src="https://user-images.githubusercontent.com/18084707/127733265-f686b6ce-3d88-42fe-9a65-d0896292f5db.png">
<img width="1437" alt="CQL-console-1" src="https://user-images.githubusercontent.com/18084707/127733273-97ebb804-1694-45ad-8b94-2a3ed523ceb7.png">
<img width="1434" alt="CQL-console-2" src="https://user-images.githubusercontent.com/18084707/127733275-189945e0-ded5-4d60-adef-3418ce764e98.png">
<img width="1436" alt="GraphQL" src="https://user-images.githubusercontent.com/18084707/127733278-a9a0e594-523d-47a8-88bb-238a9cbf62d2.png">

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Sreenivas Kundanam**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/HsswamGSTtG4htKzT0sGyg
