### ISSUE TITLE
[HW] <Amit Bajaj>

### ISSUE THREAD

**Issue by monuamit3k** [datastaxdevs/workshop-introduction-to-nosql#425]
**Name:** Amit Bajaj
**Email:** amitbajaj76@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/itveda4business/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![image](https://user-images.githubusercontent.com/76740527/127735206-01e882a1-6ef1-499a-b0c0-c35a23e6d0fa.png)
![image](https://user-images.githubusercontent.com/76740527/127735208-b6a3f53b-1bbe-4a54-b951-63511ef74355.png)
![image](https://user-images.githubusercontent.com/76740527/127735220-a113d217-0d90-4722-b6f8-a000bff2766d.png)
![image](https://user-images.githubusercontent.com/76740527/127735236-54e089af-289b-4248-892e-27fd69d57174.png)

**Comment by SonicDMG** [comment]
Hi there Amit, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by monuamit3k** [comment]
Hi David,

I have completed the Try it Out Scenario.
Pls find a screenshot below

[image: image.png]
Thanks


Best rgds

Amit

98112-07764


“One never reaches anywhere sitting on the shore”

**Comment by HadesArchitect** [comment]
Hey **Amit Bajaj**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/E4scQosyTlKnDY9TBesk5g
