### ISSUE TITLE
[HW] <VIVIN V ABRAHAM>

### ISSUE THREAD

**Issue by VIVINVABRAHAM** [datastaxdevs/workshop-introduction-to-nosql#427]
**Name:** VIVIN V ABRAHAM
**Email:** vivinvabraham2022b@mca.ajce.in
**Linkedin Profile:** <linkedin.com/in/vivinvabraham>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![4 question last output](https://user-images.githubusercontent.com/77099002/127741475-7f3b2f1a-1321-4e0a-8e24-7441bc806986.jpg)
![Scenario](https://user-images.githubusercontent.com/77099002/127741477-274abf2e-a740-4a4d-bcaf-47ea69b62594.jpg)
![1 question last output](https://user-images.githubusercontent.com/77099002/127741479-50e7bc2e-91ae-4ef4-bf9d-165be335b7c0.jpg)
![2question last output](https://user-images.githubusercontent.com/77099002/127741480-ea367f61-9393-4ad1-b34d-604eb0771cb3.jpg)
-- image removed by team --

**Comment by HadesArchitect** [comment]
Hey **VIVIN V ABRAHAM**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/RNchjfFdS0ySH2ZUkTTedQ

**Comment by SonicDMG** [comment]
Also, I had to remove one of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.
