### ISSUE TITLE
[HW] Arpit Shah

### ISSUE THREAD

**Issue by ashah3347** [datastaxdevs/workshop-introduction-to-nosql#429]
**Name:** Arpit Shah
**Email:** ashah3347@gmail.com
**Linkedin Profile:** linkedin.com/in/arpit-shah-89b1632b

Attach the homework screenshots below:
-----------------------------------------
![Try-it-out-1](https://user-images.githubusercontent.com/35557109/127749295-3c852321-4f83-416a-bd4e-4775200f2208.png)
-- image removed by team --
![Astra-console-1](https://user-images.githubusercontent.com/35557109/127749309-057f6487-79ac-4c2f-befa-e5e105888365.png)
-- image removed by team --

**Comment by HadesArchitect** [comment]
Hey **Arpit Shah**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/oG1hu6SVRwOZS4C7Urj-xw

**Comment by SonicDMG** [comment]
Also, I had to remove some of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.
