### ISSUE TITLE
[HW] Workshop introduction to nosql: Activity report by Alessandro Almada Leal (ID 1794813829)

### ISSUE THREAD

**Issue by AlessandroAlmadaLeal** [datastaxdevs/workshop-introduction-to-nosql#430]
**Name:** Alessandro Almada Leal
**Email:** alessandro.aleh42@gmail.com
**Linkedin Profile:** <https://br.linkedin.com/in/alessandro-almada-79b9b2101>

Attach the homework screenshots below:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Aless/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Aless/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

DATE | TIME | SIZE (KB) | FILE NAME
-- | -- | -- | --
29/07/2021 | 22:27 | 191.390 | 1_Create_Astra_Db_Instance_Evidence.jpg
29/07/2021 | 22:31 | 176.115 | 2a_Describe_your_Keyspace_Evidence.jpg
29/07/2021 | 22:39 | 214.840 | 2b_Create_tables_Evidence.jpg
29/07/2021 | 22:46 | 197.941 | 2c_Working_with_DATA_Evidence.jpg
29/07/2021 | 22:52 | 163.988 | 2d_Working_with_PARTITIONS_Evidence.jpg
30/07/2021 | 02:57 | 197.923 | 3a_Cassandra_knows_JSON_Evidence_A.jpg
30/07/2021 | 02:59 | 203.774 | 3a_Cassandra_knows_JSON_Evidence_B.jpg
30/07/2021 | 03:11 | 293.492 | 3b_Create_your_Application_token_Evidence.jpg
30/07/2021 | 03:26 | 166.877 | 3c_Create_a_new_empty_collection_Evidence.jpg
31/07/2021 | 16:57 | 186.724 | 3d_Create_a_new_document_Evidence.jpg
31/07/2021 | 16:58 | 158.976 | 3e_Find_all_documents_of_a_collection_Evidence.jpg
31/07/2021 | 16:58 | 172.049 | 3f_Retrieve_a_document_from_its_id_Evidence.jpg
31/07/2021 | 16:59 | 168.191 | 3g_Search_document_from_a_where_clause_Evidence.jpg
31/07/2021 | 15:25 | 132.330 | 4b_Create_a_table_with_GraphQL_Evidence.jpg
31/07/2021 | 15:29 | 143.794 | 4c_Populate_the_table_Evidence.jpg
31/07/2021 | 15:31 | 133.095 | 4c_Populate_the_table_UpdateByGraphQL_Evidence.jpg
31/07/2021 | 17:09 | 81.893 | #_Try_it_Out_Scenario_Evidence.png
</body>

</html>

-----------------------------------------

<SCREENSHOTS>

![1_Create_Astra_Db_Instance_Evidence](https://user-images.githubusercontent.com/60022798/127751482-6ae0c30e-73e8-4cbb-93ac-6f0312014e00.jpg)

![2a_Describe_your_Keyspace_Evidence](https://user-images.githubusercontent.com/60022798/127751483-1b32baec-b24e-470e-9d3a-99eccf12cefd.jpg)

![2b_Create_tables_Evidence](https://user-images.githubusercontent.com/60022798/127751484-2e8199ce-2767-4bbd-ae99-bb299c62e178.jpg)

![2c_Working_with_DATA_Evidence](https://user-images.githubusercontent.com/60022798/127751485-1d5cdd28-42b7-4179-9514-f811d6e660bc.jpg)

![2d_Working_with_PARTITIONS_Evidence](https://user-images.githubusercontent.com/60022798/127751486-50b0b24a-9540-4894-a0ac-726a6a745dbd.jpg)

![3a_Cassandra_knows_JSON_Evidence_A](https://user-images.githubusercontent.com/60022798/127751487-8325e6e2-07c2-4fa8-b500-16fdbf8efff5.jpg)

![3a_Cassandra_knows_JSON_Evidence_B](https://user-images.githubusercontent.com/60022798/127751488-d53be71f-6765-4d5f-8b4b-e6b19b4f9fbf.jpg)

![3b_Create_your_Application_token_Evidence](https://user-images.githubusercontent.com/60022798/127751491-a60d636c-f23b-4ba7-9c4c-80bf89b5d034.jpg)
![3c_Create_a_new_empty_collection_Evidence](https://user-images.githubusercontent.com/60022798/127751492-b86563af-43ce-4512-bea7-7ac75c1d40b8.jpg)

![3d_Create_a_new_document_Evidence](https://user-images.githubusercontent.com/60022798/127751493-e0338c50-002e-467a-bbca-b611dd3dcdb8.jpg)

![3e_Find_all_documents_of_a_collection_Evidence](https://user-images.githubusercontent.com/60022798/127751494-820e27b0-ff9c-4473-9e4a-881367384f37.jpg)

![3f_Retrieve_a_document_from_its_id_Evidence](https://user-images.githubusercontent.com/60022798/127751495-e728fbd1-852a-42b5-8c4d-dc80c3b77e9f.jpg)

![3g_Search_document_from_a_where_clause_Evidence](https://user-images.githubusercontent.com/60022798/127751496-2cb82061-2b0e-4b0e-bbb3-a6d8ebb431c7.jpg)

![4b_Create_a_table_with_GraphQL_Evidence](https://user-images.githubusercontent.com/60022798/127751497-80b1a14c-39e8-4a87-8c8e-d16b8c0c9fb2.jpg)

![4c_Populate_the_table_Evidence](https://user-images.githubusercontent.com/60022798/127751498-ed6af71a-7c22-4ef7-bc96-4447e5fdc415.jpg)

![4c_Populate_the_table_UpdateByGraphQL_Evidence](https://user-images.githubusercontent.com/60022798/127751499-a30218f4-0236-4929-af03-72c3ab91787b.jpg)

![#_Try_it_Out_Scenario_Evidence](https://user-images.githubusercontent.com/60022798/127751500-89135583-c68c-4ba6-8ccb-8166486199aa.png)

**Comment by AlessandroAlmadaLeal** [comment]
Hi Guys,

@SonicDMG, 

I have submitted my homework 31-july-2021, but I'm kind a worried about the badge.

- Guess that I'm lost the time to submit my HW? 
- It's mandatory to submit on the same day of the workshop to get the correction and badge?

I know it's a large list of homeworks to evaluate, but I'm a little afraid that my homework wasn't valid due to my lateness to send.

Thanks best regards,

A.A.Leal

**Comment by SonicDMG** [comment]
Hey there. You are fine on the badge and I will approve it here in a moment. I apologize it took so long for us to get these out this time around.

**Comment by HadesArchitect** [comment]
Hey **Alessandro Almada Leal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/EYVN0eBvS0G7EjA93JViuA
