### ISSUE TITLE
[HW] <Tomasz Cejko>

### ISSUE THREAD

**Issue by Kropiciel** [datastaxdevs/workshop-introduction-to-nosql#431]
**Name:** Tomasz Cejko
**Email:** tomcej9@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/tomasz-cejko>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

A screenshot of the last completed step in GraphQL:
![graphql](https://user-images.githubusercontent.com/49128251/127752473-0abf233e-37bf-4428-aa76-de5f4b3f7b7b.png)

The result in CQL:
![cass](https://user-images.githubusercontent.com/49128251/127752484-732355a1-77e2-473a-bd93-c56f0f1b121d.png)

And the completion of the try-it-out scenario:
![compl](https://user-images.githubusercontent.com/49128251/127752500-a8cab210-a8ab-42d2-85ae-7f7be80a64c9.png)

Please let me know if there's anything else you need.

Thanks!

**Comment by HadesArchitect** [comment]
Hey **Tomasz Cejko**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ZY2gCyQeReKyC0lYbPKLUw
