### ISSUE TITLE
[HW] Mohammed Husain Sayyed

### ISSUE THREAD

**Issue by husain-sayyed** [datastaxdevs/workshop-introduction-to-nosql#433]
**Name:** Mohammed Husain Sayyed
**Email:** husain.sayyed@gmail.com
**Linkedin Profile:** www.linkedin.com/in/mohammedhusainsayyed

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![image](https://user-images.githubusercontent.com/23516810/127759780-86842391-ff13-4e40-873f-c809eedcee38.png)

![image](https://user-images.githubusercontent.com/23516810/127770284-12de371d-cc75-4304-84de-27d32830dd3e.png)

![image](https://user-images.githubusercontent.com/23516810/127770290-41c0c496-f47a-4c23-9b0d-28492f6dd2c4.png)

![image](https://user-images.githubusercontent.com/23516810/127770292-ca2c2653-f996-45b3-b192-eb6b6f8c52a8.png)

![image](https://user-images.githubusercontent.com/23516810/127770297-813adff9-24a8-450d-8791-b613f6e589d5.png)

![image](https://user-images.githubusercontent.com/23516810/127770305-24e3b793-acd2-4cec-80f4-82747e988ff4.png)

--step5 screens

![image](https://user-images.githubusercontent.com/23516810/129113444-23fbe1da-ac45-42d2-9101-51d338bbca2c.png)

![image](https://user-images.githubusercontent.com/23516810/129113465-76b24008-c5d3-43ff-b784-46ecd0fe56c9.png)

![image](https://user-images.githubusercontent.com/23516810/129113503-0a9b2c1d-ee02-4ae3-afa7-f6eda018d1a2.png)

![image](https://user-images.githubusercontent.com/23516810/129113515-0176c537-a5c6-4687-a9ba-116bcfaee2fd.png)

**Comment by husain-sayyed** [comment]
kindly review

**Comment by husain-sayyed** [comment]
adding h/w step 5 screens  i missed to add, just realised.

**Comment by HadesArchitect** [comment]
Hey **Mohammed Husain Sayyed**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/PUiji338QzOBrLAFU0eKsg

**Comment by SonicDMG** [comment]
Nice job getting through the Graph portion as well. :D

**Comment by husain-sayyed** [comment]
Thanks SonicDMG, its great to connect with you guys.
