### ISSUE TITLE
[HW] <ABHISHIEK BHADAURIA>

### ISSUE THREAD

**Issue by AbhishiekBhadauria** [datastaxdevs/workshop-introduction-to-nosql#435]
**Name:** ABHISHIEK BHADAURIA
**Email:** ab4898@srmist.edu.in
**Linkedin Profile:** <https://www.linkedin.com/in/abhishiek-bhadauria-119225191/
![Screenshot (4)](https://user-images.githubusercontent.com/68178954/127761387-98fd3a9a-7186-4b28-8487-deb3cd657298.png)

![Screenshot (14)](https://user-images.githubusercontent.com/68178954/129312003-c6d79d8b-dbcf-4eb9-9fe7-34a711e13197.png)
4c7c-4bd8-9237-7728242b8ba5.jpg)
![Screenshot (5)_LI](https://user-images.githubusercontent.com/68178954/127761389-8955202a-
![Screenshot (6)_LI](https://user-images.githubusercontent.com/68178954/127761401-b6307732-007e-440b-b9e8-28448c0f0e88.jpg)
![Screenshot (7)_LI](https://user-images.githubusercontent.com/68178954/127761417-c8c364fb-3ab7-4e3a-b60f-e63a452a6100.jpg)
![Screenshot (8)_LI](https://user-images.githubusercontent.com/68178954/127761431-8205a7e2-0328-4e04-adb6-cef043b8a712.jpg)

**Comment by SonicDMG** [comment]
Hi there Abhishiek, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by AbhishiekBhadauria** [comment]
> 
> 
> Hi there Abhishiek, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
> 2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen
> 
> Please complete this and provide a screenshot of the completed scenario.

Added The Screenshot of completed scenario

**Comment by HadesArchitect** [comment]
Hey **ABHISHIEK BHADAURIA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/MZpJ6-8AQCiFT8_PtALRRA
