### ISSUE TITLE
[HW] <AKAVARAPU NAGA SRI HARSHA>

### ISSUE THREAD

**Issue by sri201822** [datastaxdevs/workshop-introduction-to-nosql#436]
**Name:** AKAVARAPU NAGA SRI HARSHA
**Email:** sriharsha863@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/sriharsha863>

Attach the homework screenshots below:
-----------------------------------------
Performed all the steps till step IV...Attaching screenshots of Step IV
![Screenshot (74)](https://user-images.githubusercontent.com/39739377/127762074-0a6b30c2-ae4a-421b-b448-3306d15733a8.png)
![Screenshot (75)](https://user-images.githubusercontent.com/39739377/127762077-a02c7c6e-dd3b-4e47-becc-719751b1c07e.png)

Attaching Screenshot of try-it-out Scenario completed below:
![Screenshot (72)](https://user-images.githubusercontent.com/39739377/127762099-a00d2e76-e409-4640-ad4f-1ffc78d3bfd0.png)

**Comment by HadesArchitect** [comment]
Hey **AKAVARAPU NAGA SRI HARSHA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/o-TIPOWpSSiK4LwiG7nhWA

**Comment by sri201822** [comment]
Thank you :)
