### ISSUE TITLE
[HW] S. Sai Krishna

### ISSUE THREAD

**Issue by SaiKrishna6873** [datastaxdevs/workshop-introduction-to-nosql#437]
**Name:** Saripudi Sai Krishna
**Email:**  saripudi.saikrishna12@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------
![Screenshot (1)](https://user-images.githubusercontent.com/65037947/127762762-e30f8886-22b2-4b7b-9fe7-08e599489686.png)
![Screenshot (2)](https://user-images.githubusercontent.com/65037947/127762773-345910f8-2d12-4244-bf7a-22963cf662e5.png)
![Screenshot (3)](https://user-images.githubusercontent.com/65037947/127762778-50b482fa-c399-41b2-a5a7-d40f4ffd3b6d.png)

**Comment by HadesArchitect** [comment]
Hey **Saripudi Sai Krishna**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/uAm7583MQBGxCE-mtMq1Fw
