### ISSUE TITLE
[HW] Arun Prasath Karunakaran

### ISSUE THREAD

**Issue by arunprasathkarunakaran** [datastaxdevs/workshop-introduction-to-nosql#438]
**Name:** Arun Prasath Karunakaran
**Email:** confidentarun@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/arunpkarunakaran/

Attach the homework screenshots below:
-----------------------------------------

![PracticeStep_IV_PG_ArunK](https://user-images.githubusercontent.com/22268379/127762800-f0590098-7fce-4dc7-bf20-e8f571a427a4.png)
![PracticeStep_IV_CSQL_ArunK](https://user-images.githubusercontent.com/22268379/127762803-91d22e22-43b3-4c7d-b65e-3a5e6808ae82.png)
![Try-it-out_Scenario_ArunK](https://user-images.githubusercontent.com/22268379/127762808-63b24ed8-600d-4fbc-b07e-7cd2be86867e.png)

**Comment by HadesArchitect** [comment]
Hey **Arun Prasath Karunakaran**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/RObKeHTAQC-isDaQkw9rPw
