### ISSUE TITLE
[HW] <Subrat Kumar Samal>

### ISSUE THREAD

**Issue by SubratSamal1509** [datastaxdevs/workshop-introduction-to-nosql#439]
**Name:** Subrat_Kumar_Samal
**Email:** subratsamal1509@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/subrat-kumar-samal/>

Attach the homework screenshots below:
-----------------------------------------
-- images removed by team --
![image](https://user-images.githubusercontent.com/35253887/127762288-53d6c025-ad85-4bfb-960d-71bf452854cd.png)
![image](https://user-images.githubusercontent.com/35253887/127762299-94c6156e-c524-4cd9-a281-1092f06a4807.png)
![image](https://user-images.githubusercontent.com/35253887/127762305-0cfad484-06d1-4075-84ba-c7e42d66dd64.png)
![image](https://user-images.githubusercontent.com/35253887/129436134-019ffd35-648c-4314-8921-e5cee232a9da.png)
![image](https://user-images.githubusercontent.com/35253887/129436143-dbac0942-d7b8-4188-abe4-a491b74f28a8.png)
![image](https://user-images.githubusercontent.com/35253887/129436164-f0b895e4-7863-422f-b849-a351ba1d8bb1.png)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Hi there Subrat, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by SonicDMG** [comment]
Also, I had to remove some of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.

**Comment by SubratSamal1509** [comment]
Hi Team,

I have attached the screenshot for completion of " try-it-out scenario
<https://www.datastax.com/try-it-out>" in Github.
Also for your reference PFB the same:
[image: image.png]

Thanks & Regards,
Subrat Kumar Samal

**Comment by HadesArchitect** [comment]
Hey **Subrat_Kumar_Samal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/UUj8RtCOSF6Dor0I2DEixQ
