### ISSUE TITLE
[HW] SUNIL KUMAR PATRO

### ISSUE THREAD

**Issue by sunilkpatro080190** [datastaxdevs/workshop-introduction-to-nosql#44]
**Name:** SUNIL KUMAR PATRO
**Email:** sunilkpatro080190@gmail.com
**Linkedin Profile:** www.linkedin.com/in/sunilpatro1990

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

-- images removed by team --
![4b  Create a table with GraphQL-Part2](https://user-images.githubusercontent.com/84149628/118865248-61fb5f80-b8fe-11eb-8d47-b69213a061dc.png)
-- images removed by team --
![4c  Populate the table - Part3](https://user-images.githubusercontent.com/84149628/118865258-632c8c80-b8fe-11eb-8395-7825643d225c.png)
![4c  Populate the table - Part4](https://user-images.githubusercontent.com/84149628/118865259-632c8c80-b8fe-11eb-9a2a-8456816715e2.png)
![Create Astra Instance - Create Database with Keyspace](https://user-images.githubusercontent.com/84149628/118865262-63c52300-b8fe-11eb-87fa-a0a97dafd0a3.png)
![try-iy-out_scenarios_completion](https://user-images.githubusercontent.com/84149628/118865264-645db980-b8fe-11eb-9b23-1f25830be9ae.png)
![2a  Describe your Keyspace - Part1](https://user-images.githubusercontent.com/84149628/118865265-64f65000-b8fe-11eb-8e30-e6e7cb4930eb.png)
![2a  Describe your Keyspace - Part2](https://user-images.githubusercontent.com/84149628/118865267-64f65000-b8fe-11eb-9c9f-624864092e84.png)
![2a  Describe your Keyspace - Part3](https://user-images.githubusercontent.com/84149628/118865269-658ee680-b8fe-11eb-9f7f-c47cbdffeb48.png)
![2b  Create tables - Part1](https://user-images.githubusercontent.com/84149628/118865271-66277d00-b8fe-11eb-820c-6b1e544c5b55.png)
![2b  Create tables - Part2](https://user-images.githubusercontent.com/84149628/118865273-66277d00-b8fe-11eb-98b7-79890e827004.png)
![2c  Working with DATA - Part1](https://user-images.githubusercontent.com/84149628/118865278-66c01380-b8fe-11eb-9d98-03c894c34d23.png)
![2c  Working with DATA - Part2](https://user-images.githubusercontent.com/84149628/118865279-6758aa00-b8fe-11eb-8cae-31ed59489502.png)
![2d  Working with PARTITIONS - Part1](https://user-images.githubusercontent.com/84149628/118865280-6758aa00-b8fe-11eb-9408-05389a3e43ff.png)
![2d  Working with PARTITIONS - Part2](https://user-images.githubusercontent.com/84149628/118865281-67f14080-b8fe-11eb-8fb8-d8f050600d73.png)
![2d  Working with PARTITIONS - Part3](https://user-images.githubusercontent.com/84149628/118865284-67f14080-b8fe-11eb-9885-4b53202fe0e6.png)
![2d  Working with PARTITIONS - Part4](https://user-images.githubusercontent.com/84149628/118865288-6889d700-b8fe-11eb-92cb-e86919e2a458.png)
![2d  Working with PARTITIONS - Part5](https://user-images.githubusercontent.com/84149628/118865289-69226d80-b8fe-11eb-887b-374d4875307c.png)
![2d  Working with PARTITIONS - Part6](https://user-images.githubusercontent.com/84149628/118865293-69226d80-b8fe-11eb-8c86-952bebd20364.png)
![2d  Working with PARTITIONS - Part7](https://user-images.githubusercontent.com/84149628/118865297-69bb0400-b8fe-11eb-8cbc-934a4420b6bc.png)
![3a  Cassandra knows JSON](https://user-images.githubusercontent.com/84149628/118865298-6a539a80-b8fe-11eb-8c0c-1f54520160f1.png)
![3b  Create your Application token - Part1](https://user-images.githubusercontent.com/84149628/118865299-6a539a80-b8fe-11eb-91c4-31ed302ca33c.png)
![3b  Create your Application token - Part2](https://user-images.githubusercontent.com/84149628/118865300-6aec3100-b8fe-11eb-8085-bd36bf01ecb1.png)
![3b  Create your Application token - Part3](https://user-images.githubusercontent.com/84149628/118865303-6b84c780-b8fe-11eb-8d68-d6ad6fac3f5b.png)
-- images removed by team --

**Comment by SonicDMG** [comment]
Nice job Sunil, thank you.

**Comment by SonicDMG** [comment]
Here's your badge Sunil. Thank you for your patience. https://api.badgr.io/public/assertions/LlvTVtPoT1m-U0sN105NIQ?identity__email=sunilkpatro080190%40gmail.com
