### ISSUE TITLE
[HW] Anvesh Saxena

### ISSUE THREAD

**Issue by anvsh** [datastaxdevs/workshop-introduction-to-nosql#440]
**Name:** Anvesh Saxena
**Email:** anvsh@live.in
**Linkedin Profile:** https://www.linkedin.com/in/anvesh-saxena/

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/2460159/127767029-17119c6f-2e71-4727-9f0b-3bd6e2348b47.png)
![image](https://user-images.githubusercontent.com/2460159/127767107-21647286-6348-42f5-9f7f-7f8df6884038.png)

Feedback
-----------
Thanks for the great and thorough deep dive into the world of NoSQL. The content, pace and further learning materials are superb. Looking forward to learnings

**Comment by HadesArchitect** [comment]
Hey **Anvesh Saxena**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/5281UXKxTAaz2oHjCG_AVw
