### ISSUE TITLE
[HW] Hasnat Abdullah

### ISSUE THREAD

**Issue by programmerHasnat** [datastaxdevs/workshop-introduction-to-nosql#442]
**Name:** HAsnat Abdullah
**Email:** ijklmn012012@gmail.com
**Linkedin Profile:** <LINK>https://www.linkedin.com/in/hasnat-abdullah-9842821b7

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot (31)](https://user-images.githubusercontent.com/83762455/127774895-46f87fe4-799e-488a-9f1c-fbd206b305f2.png)

![Screenshot (30)](https://user-images.githubusercontent.com/83762455/127774896-89a65ac4-7660-4a90-bf09-cd30a6e9f3d4.png)

![Screenshot (22)](https://user-images.githubusercontent.com/83762455/127774901-7759728e-db6a-452f-a7e4-21473d605160.png)

![Screenshot (23)](https://user-images.githubusercontent.com/83762455/127774905-f9d63d37-2f56-4375-80cc-89d4c0fa692c.png)

**Comment by programmerHasnat** [comment]
![Screenshot (31)](https://user-images.githubusercontent.com/83762455/127774454-28295f5f-f996-4ef6-a63e-7bda215a8560.png)

**Comment by programmerHasnat** [comment]
![Screenshot (30)](https://user-images.githubusercontent.com/83762455/127774920-cad52d83-f9ae-4e40-a3c6-9b65ad84b2bf.png)
![Screenshot (23)](https://user-images.githubusercontent.com/83762455/127774933-31b23e35-603d-49a4-8430-af4b8668e020.png)
![Screenshot (22)](https://user-images.githubusercontent.com/83762455/127774950-87e4eb00-d8c8-4538-aa53-2ba6f9a0dbab.png)

**Comment by HadesArchitect** [comment]
Hey **HAsnat Abdullah**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/_TYZepU3QQqvtNn8blbeCA
