### ISSUE TITLE
[HW] Nikhil Gupta

### ISSUE THREAD

**Issue by niksdgr8** [datastaxdevs/workshop-introduction-to-nosql#443]
**Name:** Nikhil Gupta
**Email:** nikhilgupta18101993@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/niksdgr8/

Attach the homework screenshots below:
-----------------------------------------

![DataStax_Homework_NikhilGupta](https://user-images.githubusercontent.com/16701331/127773860-bf69c52a-052f-4864-a2fb-f6ac05eeafd2.jpg)
![DataStax_Scenario_NikhilGupta](https://user-images.githubusercontent.com/16701331/127774280-1e688fe6-d983-4bf6-b3ba-3e570a2b2680.jpg)

**Comment by HadesArchitect** [comment]
Hey **Nikhil Gupta**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/IEVM5x1-SMORSlFuL4w_sw
