### ISSUE TITLE
[HW] <Muhammed Mushir Alam>

### ISSUE THREAD

**Issue by alammushir** [datastaxdevs/workshop-introduction-to-nosql#444]
**Name:** Muhammed Mushir Alam
**Email:** alam.mushir@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/muhammed-mushir-alam-25b8a38/

Attach the homework screenshots below:
-----------------------------------------
Try it out:
![image](https://user-images.githubusercontent.com/66112202/127773861-ddedf6e6-3470-40d0-a275-1d6cd38794ab.png)

Key-Value:
![image](https://user-images.githubusercontent.com/66112202/127773891-387c5dc0-0d8e-468d-885f-03ce44bbc771.png)

**Comment by HadesArchitect** [comment]
Hey **Muhammed Mushir Alam**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/CZgTnTPwQRyLbCnCRTSQcw
