### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by MacSts** [datastaxdevs/workshop-introduction-to-nosql#446]
**Name:** Maciej Stasiłowicz
**Email:** maciej.stasilowicz@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/maciej-stasi%C5%82owicz-142379148/

Attach the homework screenshots below:
-----------------------------------------

-- image removed by team --
![Homework - Token Setup](https://user-images.githubusercontent.com/88286443/127780559-09cecb7a-e299-47e6-b1ac-2a456b89c48b.PNG)
![Homework - TryItOut1](https://user-images.githubusercontent.com/88286443/127780561-57ab3902-7577-4c8a-b5a2-2d7c0d9cc04a.PNG)
![Homework - TryItOut2](https://user-images.githubusercontent.com/88286443/127780562-3fc6994d-bf02-4d48-a396-c6dc0dd59bc0.PNG)
![Homework - AstraDB](https://user-images.githubusercontent.com/88286443/127780563-f1366b6a-ca15-40eb-bff2-0d5d50a61550.PNG)
![Homework - GraphQL](https://user-images.githubusercontent.com/88286443/127780564-5fa7a972-7bf7-49b2-ac34-bc58e63d8b16.PNG)
![Homework - Swagger](https://user-images.githubusercontent.com/88286443/127780566-79d4cfa9-8250-4dc6-b248-dcffd95f0494.PNG)
>
>

**Comment by HadesArchitect** [comment]
Hey **Maciej Stasiłowicz**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/0hOSOIBNSuyXP4iq0CX4XQ

**Comment by SonicDMG** [comment]
Also, I had to remove one of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.
