### ISSUE TITLE
[HW] Saurabh Malviya

### ISSUE THREAD

**Issue by MalviyaSaurabh** [datastaxdevs/workshop-introduction-to-nosql#448]
**Name:** Saurabh Malviya
**Email:** malviya.saurabh4u@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/saurabh-malviya-34763616/

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/45642123/127784876-4aab11fa-eff5-4f0e-b828-36968c27ef36.png)
![image](https://user-images.githubusercontent.com/45642123/127784883-4a9e8d24-e485-49a5-914d-837a27dfa78c.png)

![image](https://user-images.githubusercontent.com/45642123/127784887-487f4164-3245-495a-b026-a4a43506f0d1.png)
![image](https://user-images.githubusercontent.com/45642123/127784888-5748ad2f-662b-4afa-ad1a-648309fe7db4.png)

![image](https://user-images.githubusercontent.com/45642123/127784891-b2bbdee3-92e0-4725-b3cf-2bc72f1ecea3.png)

**Comment by MalviyaSaurabh** [comment]
@HadesArchitect @SonicDMG @RyanWelford request you to please review this.

**Comment by HadesArchitect** [comment]
Hey **Saurabh Malviya**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/imvIm3TrRdmfDjLi5ztttw
