### ISSUE TITLE
[HW] Vinícius Nunes da Costa

### ISSUE THREAD

**Issue by viniciusnvcosta** [datastaxdevs/workshop-introduction-to-nosql#449]
**Name:** Vinícius Nunes Viana da Costa
**Email:** viniciusnvcosta47@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/vinicius-nunes-da-costa/>

Attach the homework screenshots below:
-----------------------------------------

## Part 1

<img width="960" alt="Part_1" src="https://user-images.githubusercontent.com/66750204/127790708-5cd01e54-11e0-4824-a7a6-761dde1599d3.png">

## Part 4

<img width="960" alt="Part_4-1" src="https://user-images.githubusercontent.com/66750204/127791355-ff0c020a-53a8-4708-98b3-22b291b0cfad.png">

<img width="960" alt="Part_4" src="https://user-images.githubusercontent.com/66750204/127790808-7b0ca7e7-a7a7-4566-bb81-e24bf1a19705.png">

## Part 5

> Unfortunately wasn't able to run the dse-studio due to some errors but here's the attempt at least :)
<img width="960" alt="Part_5" src="https://user-images.githubusercontent.com/66750204/127790850-7a0275e0-3ca7-477b-a466-04f4b339eec6.png">

## try it out scenario

<img width="959" alt="try-it-out" src="https://user-images.githubusercontent.com/66750204/127791441-caeb8283-fa02-4a77-b189-e01283c83c3d.png">

**Comment by HadesArchitect** [comment]
Hey **Vinícius Nunes Viana da Costa**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/x7Cv6yu2T0yevk9kL6Ms0Q
