### ISSUE TITLE
[HW] <CHIMAINGUYEN>

### ISSUE THREAD

**Issue by nchimai15** [datastaxdevs/workshop-introduction-to-nosql#450]
**Name:** Chi Mai NGUYEN
**Email:** chimn@uio.no
**Linkedin Profile:** https://www.linkedin.com/in/chi-mai-nguyen-56583148/

Attach the homework screenshots below:
-----------------------------------------

![Screenshot 2021-08-02 at 11 25 28](https://user-images.githubusercontent.com/88317311/127838980-0ecfa8a6-fbec-438f-9f40-32b9f95ea96e.png)
![Screenshot 2021-08-02 at 11 27 33](https://user-images.githubusercontent.com/88317311/127839005-60c8c448-1482-4307-b624-99cf499133fa.png)
![Screenshot 2021-08-02 at 11 27 42](https://user-images.githubusercontent.com/88317311/127839018-915cd166-0a98-449f-beb6-381625787048.png)

**Comment by HadesArchitect** [comment]
Hey **Chi Mai NGUYEN**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/YT4lIWs_TV6QdwdyHNq4zQ
