### ISSUE TITLE
[HW] <Vibhuti Pathak>

### ISSUE THREAD

**Issue by Vibhuti-Pathak** [datastaxdevs/workshop-introduction-to-nosql#452]
**Name:** Vibhuti Pathak
**Email:** vibhuti20pathak@gmail.com
**Linkedin Profile:** <www.linkedin.com/in/vibhuti-pathak-bb51b596>

Attach the homework screenshots below:
-----------------------------------------

[<SCREENSHOTS>]
<img width="724" alt="0" src="https://user-images.githubusercontent.com/88325441/127860702-22937530-3d8c-46b3-8bcc-787cb53b5ee4.PNG">
<img width="635" alt="1" src="https://user-images.githubusercontent.com/88325441/127860726-7553b105-e6c5-45f9-8dcf-e032067a6df3.PNG">
<img width="263" alt="1 1" src="https://user-images.githubusercontent.com/88325441/127860746-3a23a36e-074f-4bb9-a621-f39ea2eb7062.PNG">
<img width="840" alt="2" src="https://user-images.githubusercontent.com/88325441/127860753-c624191f-c1e2-48fa-a274-ed843bf0049c.PNG">
<img width="260" alt="2 1" src="https://user-images.githubusercontent.com/88325441/127860765-bb0656ea-575e-480e-bc5d-ffa92bf869f6.PNG">
<img width="796" alt="3" src="https://user-images.githubusercontent.com/88325441/127860772-49096451-dd56-4bf6-8b68-ba988ab187d2.PNG">
<img width="288" alt="4" src="https://user-images.githubusercontent.com/88325441/127860779-5c908086-7077-4358-b61a-de28c73629ff.PNG">

![IMG_20210816_222254](https://user-images.githubusercontent.com/88325441/129601200-0ab543db-e41f-4fda-b83b-bffb56562b33.jpg)

**Comment by SonicDMG** [comment]
Hi there Vibhuti, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by Vibhuti-Pathak** [comment]
Hi attached the try ut out scenario screen shot
![Screenshot_2021-08-16-22-18-40-44](https://user-images.githubusercontent.com/88325441/129600111-e5c915ee-3450-4c2d-8c41-67f9e66f0216.png)

**Comment by Vibhuti-Pathak** [comment]
Hi please find attached snip.
![IMG_20210816_222254](https://user-images.githubusercontent.com/88325441/129600784-0987bed9-f027-4051-a2be-e646b33b3341.jpg)

**Comment by HadesArchitect** [comment]
Hey **Vibhuti Pathak**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/yPciS_kpSiq1c8DztPCXYw
