### ISSUE TITLE
[HW] JEREMY MEJIA EKEL

### ISSUE THREAD

**Issue by jeremyekel** [datastaxdevs/workshop-introduction-to-nosql#453]
**Name:** JEREMY MEJIA EKEL
**Email:** jeremyekel25@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/jeremyekel/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

-- images removed by team --

**Check with CQL Console**
![image](https://user-images.githubusercontent.com/60430194/128005016-16e3e65f-fedb-4ed4-b5da-b37bc49b5b6e.png)

**Execute this query**
![image](https://user-images.githubusercontent.com/60430194/128005145-f8cc3e0a-262a-45a6-ae56-6a3aa5b81896.png)

**Comment by SonicDMG** [comment]
Hi there Jeremy, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by jeremyekel** [comment]
Sorry for the inconvenience, here is the screenshot.

![image](https://user-images.githubusercontent.com/60430194/129269739-4e78d099-b829-499c-8dc1-8005294a1059.png)

**Comment by SonicDMG** [comment]
No inconvenience at all. Thank you for following up.

**Comment by HadesArchitect** [comment]
Hey **JEREMY MEJIA EKEL**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/OepWmMlkTK2WI6i30jng3Q

**Comment by jeremyekel** [comment]
Thank you very much!
