### ISSUE TITLE
[HW] Anant Swaroop Satsangi

### ISSUE THREAD

**Issue by XaNaNtX** [datastaxdevs/workshop-introduction-to-nosql#454]
**Name:** Anant Swaroop Satsangi
**Email:** anantswaroop5@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/anant-swaroop-satsangi-0a4978218

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot 2021-08-03 at 02-40-50 Manage Database — DataStax Astra](https://user-images.githubusercontent.com/88288195/127925542-e731f353-c4a7-4a6a-9ee9-5de41f4874ed.png)
![Screenshot 2021-08-03 at 02-40-27 Playground - https bb6840d4-d3eb-43a5-bcea-f6376bfcf374-asia-south1 apps astra datastax c](https://user-images.githubusercontent.com/88288195/127925549-754dad9c-99af-4c0d-8e2b-f69d3ce16ddf.png)
![Screenshot 2021-08-03 at 02-37-13 Manage Database — DataStax Astra](https://user-images.githubusercontent.com/88288195/127925553-41c46cb4-584d-4030-9a2e-68ead98618e4.png)
![Screenshot 2021-08-03 at 02-36-57 Playground - https bb6840d4-d3eb-43a5-bcea-f6376bfcf374-asia-south1 apps astra datastax c](https://user-images.githubusercontent.com/88288195/127925560-f33502d5-61ac-4089-a110-c4eccb703e4a.png)
![Screenshot 2021-08-03 at 01-46-18 Swagger UI](https://user-images.githubusercontent.com/88288195/127926202-4e81fd5a-9bde-40a3-b3fb-c193b7a3945c.png)
![Screenshot 2021-08-03 at 01-26-10 Dashboard — DataStax Astra](https://user-images.githubusercontent.com/88288195/127925575-067f884b-f96f-4e72-bd36-09e7498f6cdb.png)
![Screenshot 2021-08-03 at 01-19-57 Manage Database — DataStax Astra](https://user-images.githubusercontent.com/88288195/127925579-5cb0d501-866f-4fe5-ae08-67fa6248d1ac.png)

**Comment by SonicDMG** [comment]
Hi there Anant, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by XaNaNtX** [comment]
2nd step? ok.
`describe keyspaces;`
`describe keyspaces nsql1;`
`describe videos;`
I can not create table twice so here is table info screenshot.
![Screenshot 2021-08-14 at 11-43-36 Manage Database — DataStax Astra](https://user-images.githubusercontent.com/88288195/129436156-c2e4e033-611e-4368-8be2-ea330338d1b1.png)
![Screenshot 2021-08-14 at 11-54-21 Manage Database — DataStax Astra](https://user-images.githubusercontent.com/88288195/129437272-c2647c9e-1448-49e5-9eed-b879f6e9388e.png)

![Screenshot 2021-08-14 at 11-45-43 Manage Database — DataStax Astra](https://user-images.githubusercontent.com/88288195/129436158-4455d6e6-62b9-491b-9e1a-603f362ac549.png)

**Comment by SonicDMG** [comment]
Thank you for following up. What we are looking for is for you to completed the scenario at this link https://www.datastax.com/try-it-out and provide a screen. :)

**Comment by XaNaNtX** [comment]
Well I don't know this is the part of workshop;
Here you go :)
![Screenshot 2021-08-29 at 01-39-01 Try It Out](https://user-images.githubusercontent.com/88288195/131229955-67ffe7d9-b671-4aaf-b934-e8ddc57c780e.png)
![Screenshot 2021-08-29 at 01-38-40 Try It Out](https://user-images.githubusercontent.com/88288195/131229956-b092ca5b-d3a9-4524-b810-1b73dfd1258f.png)
![Screenshot 2021-08-29 at 01-39-35 Try It Out](https://user-images.githubusercontent.com/88288195/131229957-23cfa53d-e2e5-40ab-abc1-ec6ff8220ad1.png)
![Screenshot 2021-08-29 at 01-39-51 Try It Out](https://user-images.githubusercontent.com/88288195/131229960-823080d8-4252-4f40-902c-7b7b8f081d49.png)
![Screenshot 2021-08-29 at 01-40-19 Try It Out](https://user-images.githubusercontent.com/88288195/131229961-1098aa99-c018-400c-920a-3b260265117c.png)
![Screenshot 2021-08-29 at 01-40-34 Try It Out](https://user-images.githubusercontent.com/88288195/131229964-855220c8-c01c-4c9b-8dcc-fdd45bb9262e.png)
![Screenshot 2021-08-29 at 01-40-49 Try It Out](https://user-images.githubusercontent.com/88288195/131229966-e1d02dd0-06c9-43ce-832b-222f8fea724a.png)
![Screenshot 2021-08-29 at 01-37-58 Try It Out](https://user-images.githubusercontent.com/88288195/131229969-8c3d0155-173a-4d0f-9bd5-c5d0097de322.png)

**Comment by XaNaNtX** [comment]
Wait !! should my email connected to my linkedin account? that I provided to You?

**Comment by HadesArchitect** [comment]
Hey **Anant Swaroop Satsangi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/kVoLovXLR8qoPym--Uf1_g

**Comment by XaNaNtX** [comment]
I want to move my badge to another email.
