### ISSUE TITLE
[HW] <Sandeep>

### ISSUE THREAD

**Issue by singhsandy** [datastaxdevs/workshop-introduction-to-nosql#457]
**Name:** Sandeep
**Email:** singhsandeep221078@gmail.com
**Linkedin Profile:** www.linkedin.com/in/sandeep-singh-26840820

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![AstraDB](https://user-images.githubusercontent.com/88395328/128052195-87ebfe36-6cc0-4283-bbed-c916f0ce28a2.JPG)
![TRY_IT_OUT](https://user-images.githubusercontent.com/88395328/128052204-907ff6f1-3218-4df3-bb26-a671600496bb.JPG)

**Comment by HadesArchitect** [comment]
Hey **Sandeep**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/SLAjnV30TQWo6u5xbymybg
