### ISSUE TITLE
[HW] <Ajay Hanuman Kadam>

### ISSUE THREAD

**Issue by AjayKadam091** [datastaxdevs/workshop-introduction-to-nosql#458]
**Name:** Ajay Hanuman Kadam
**Email:** kadamajay383@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/7394ajaykadam/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
<img width="739" alt="4" src="https://user-images.githubusercontent.com/69312681/128055012-770c607b-c5b4-46d5-b07b-57b4d1a8129e.png">
<img width="833" alt="1" src="https://user-images.githubusercontent.com/69312681/128055045-4add5d7d-e6b9-4d49-981f-4f83fa5c1852.png">
<img width="678" alt="3" src="https://user-images.githubusercontent.com/69312681/128055057-03d583ae-512c-4bbf-b266-b4d850c65a25.png">
<img width="742" alt="2" src="https://user-images.githubusercontent.com/69312681/128055077-1ec6ea0a-37d1-49da-8379-71db0afc0025.png">
<img width="576" alt="5" src="https://user-images.githubusercontent.com/69312681/128055182-3c748959-3591-4470-bb55-dbdf07ee05dd.png">

**Comment by HadesArchitect** [comment]
Hey **Ajay Hanuman Kadam**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Of6ewXHBTeqdammsocV5qw
