### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by louhenheimo** [datastaxdevs/workshop-introduction-to-nosql#459]
Name: Petri Louhenheimo
Email: petril@iki.fi
Linkedin Profile: https://www.linkedin.com/in/louhenheimo/

Attach the homework screenshots below:
-----------------------------------------

![w4-1-InkedGXVdf3waJ8_LI](https://user-images.githubusercontent.com/1541962/128064347-00e39f4d-2ddc-4375-bae6-5f663d517c90.jpg)
![w4-InkedigkncPVPD3_LI](https://user-images.githubusercontent.com/1541962/128064370-2a43c514-313e-467c-a3e2-341d163895d2.jpg)
![w4-InkedoMtkll5Cu6_LI](https://user-images.githubusercontent.com/1541962/128064391-17855120-643a-4bbb-ab9c-83d59dc285b1.jpg)

**Comment by HadesArchitect** [comment]
Hey **Petri Louhenheimo**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/UJVc3BRPQBOuGGUjCqdoMg
