### ISSUE TITLE
[HW] Piotr Wlazeł

### ISSUE THREAD

**Issue by Nieokorzesany** [datastaxdevs/workshop-introduction-to-nosql#46]
**Name:** Piotr Wlazeł
**Email:** pancu1222@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/piotr-wlaze%C5%82-896202128/

Attach the homework screenshots below:
-----------------------------------------
-- images removed by team --
![2c](https://user-images.githubusercontent.com/38163577/118880420-1e9af400-b8f2-11eb-827d-ca923a914360.png)
![2a](https://user-images.githubusercontent.com/38163577/118880422-1f338a80-b8f2-11eb-87f7-33b160d1885d.png)

![nosql](https://user-images.githubusercontent.com/38163577/118866135-fe633900-b8e1-11eb-9fb2-e9583afc6170.png)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Nice job Piotr, thank you.

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/yhcMuYGzQryVJU7GgevGFg?identity__email=pancu1222%40gmail.com
