### ISSUE TITLE
[HW] <Jasleen Singh>

### ISSUE THREAD

**Issue by Jazzy4uu** [datastaxdevs/workshop-introduction-to-nosql#460]
**Name:** Jasleen Singh Bhangoo
**Email:** jasleen3046@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/jasleen-singh-81549b43/>

Attach the homework screenshots below:
-----------------------------------------

<![image](https://user-images.githubusercontent.com/87227269/128068970-332b1799-14b2-4520-b362-27baa7ec8d18.png)>
-- removed by team --

**Comment by HadesArchitect** [comment]
Hey **Jasleen Singh Bhangoo**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/p4g4kzl_RsGLf50B_2cyXA

**Comment by SonicDMG** [comment]
Also, I removed your document because it included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.
