### ISSUE TITLE
[HW] <Domingos Arlindo Fondo>

### ISSUE THREAD

**Issue by DomingosFondo** [datastaxdevs/workshop-introduction-to-nosql#461]
**Name:** Domingos Arlindo Fondo
**Email:** fondo.mingo@gmail.com
**Linkedin Profile:** www.linkedin.com/in/Domingos-Fondo

Attach the homework screenshots below:
-----------------------------------------
![Screenshot (45)](https://user-images.githubusercontent.com/46943232/128083379-b52ceb22-6a5f-4097-8029-e1dddf94da20.png)
![Screenshot (46)](https://user-images.githubusercontent.com/46943232/128083385-fc3027d7-63e0-4532-9f1a-b42260c9156c.png)
![Screenshot (41)_LI](https://user-images.githubusercontent.com/46943232/128083387-7eec9a7b-9174-486a-ad04-9a34ab7a1926.jpg)
![Screenshot (42)_LI](https://user-images.githubusercontent.com/46943232/128083397-010ae3f2-9d5d-47c6-ad12-c5160f20ba5d.jpg)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Domingos Arlindo Fondo**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/E1nmQIWXSYinQg1yDG7sJw
