### ISSUE TITLE
[HW] Sachin Gupta

### ISSUE THREAD

**Issue by DevSachinGupta** [datastaxdevs/workshop-introduction-to-nosql#463]
**Name:** Sachin Gupta
**Email:** sachingupta01@live.com
**Linkedin Profile:** https://www.linkedin.com/in/devsachingupta/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot from 2021-08-04 13-00-35](https://user-images.githubusercontent.com/12891680/128141212-ff573af7-0dd5-4127-a434-86dcfb43c031.png)
![Screenshot from 2021-08-04 13-00-52](https://user-images.githubusercontent.com/12891680/128141235-e3c21c27-7bcb-4912-ba5a-fe2a286a24e4.png)
-- image removed by team --
![Screenshot from 2021-08-04 13-04-50](https://user-images.githubusercontent.com/12891680/128141245-fa599c59-1b01-41e9-8eea-eefa6b7a3fe8.png)

**Comment by HadesArchitect** [comment]
Hey **Sachin Gupta**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/84X3d3SZQiKObVAMsmg33w

**Comment by SonicDMG** [comment]
Also, I had to remove one of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.

**Comment by DevSachinGupta** [comment]
I had removed the Astra token after completing the task from my account.
