### ISSUE TITLE
[HW] Syeda Mehwish Naseem

### ISSUE THREAD

**Issue by mehwishnaseem** [datastaxdevs/workshop-introduction-to-nosql#464]
**Name:** Syeda Mehwish Naseem
**Email:** smehwish.naseem@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/syeda-mehwish-naseem-60615b28/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
<img width="1015" alt="scenario completed" src="https://user-images.githubusercontent.com/80165711/128230011-7c93f3e0-a827-4b57-bbde-bb4210ccb152.png">
<img width="1440" alt="step IV" src="https://user-images.githubusercontent.com/80165711/128230023-ecae9895-3ba4-42de-afbe-5fd5edc6a993.png">
<img width="1440" alt="Step III" src="https://user-images.githubusercontent.com/80165711/128232075-b68f0f5e-b215-4e4b-a6d2-6e1aefaa90d9.png">
<img width="1440" alt="Step II" src="https://user-images.githubusercontent.com/80165711/128231302-e08c6bef-c2c1-47e4-9051-05e917b3a20b.png">
<img width="1440" alt="Step I" src="https://user-images.githubusercontent.com/80165711/128231536-d3b5493c-6db6-4d19-908d-017b382494a2.png">

**Comment by HadesArchitect** [comment]
Hey **Syeda Mehwish Naseem**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Zg5RpoIRQv-oH389nxh3dg
