### ISSUE TITLE
[HW] Sandip Roy

### ISSUE THREAD

**Issue by sandiproy54** [datastaxdevs/workshop-introduction-to-nosql#465]
**Name:** Sandip Roy
**Email:** sandiproy54@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sandip-roy-88553626/

Attach the homework screenshots below:
-----------------------------------------

![Exercise 1](https://user-images.githubusercontent.com/88462723/128263564-ac818757-512f-4a8e-8517-91002c6cd06b.png)
![Exercise 2](https://user-images.githubusercontent.com/88462723/128263567-26084f6f-69f0-4d6c-9e21-3d9a2fc2ff29.png)
![Exercise 3](https://user-images.githubusercontent.com/88462723/128263573-b136b98d-441d-4032-b5bc-f58e0409f8c5.png)
![Exercise 4](https://user-images.githubusercontent.com/88462723/128263574-5336dce1-99e0-4362-83fc-7516ea080216.png)

**Comment by SonicDMG** [comment]
Hi there Sandip, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by sandiproy54** [comment]
![try-it-out_page1](https://user-images.githubusercontent.com/88462723/129433722-7c582d86-2bbc-4760-b469-344ce72ea615.png)
![try-it-out_page2](https://user-images.githubusercontent.com/88462723/129433728-9edb7a6c-e432-43b8-999a-b7f84109c0cd.png)

**Comment by sandiproy54** [comment]
Completed the step 2. Screen shots are attached

**Comment by HadesArchitect** [comment]
Hey **Sandip Roy**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/7Nef_hIhTDG4XA4NoxNjOQ
