### ISSUE TITLE
[HW] Assignment NoSQL Workshop

### ISSUE THREAD

**Issue by brucew2099** [datastaxdevs/workshop-introduction-to-nosql#466]
**Name:** Alan Kwok
**Email:** alankwok1@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/alan-k-0593a0109/

Attach the homework screenshots below:
-----------------------------------------

PART IV

![NoSQL_Part4_1](https://user-images.githubusercontent.com/14793800/128278451-1f01647c-b947-4f57-8b05-fbb950e036e2.png)

![NoSQL_Part4_2](https://user-images.githubusercontent.com/14793800/128278464-b3d73790-acc9-4a65-8237-12ac04e26e25.png)

PART V

![NoSQL_Part5](https://user-images.githubusercontent.com/14793800/128278470-0913c032-dd63-4188-8f54-4a50d074d495.png)

TRY IT OUT

![NoSQL_try_it_out](https://user-images.githubusercontent.com/14793800/128278517-e8f1726d-e210-438f-9b14-4b86b3c02a88.png)

**Comment by HadesArchitect** [comment]
Hey **Alan Kwok**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ltqgliEuT4uCekaCR6QTjQ

**Comment by SonicDMG** [comment]
Nice job getting through the graph portion. :D
