### ISSUE TITLE
[HW] Gabriel Galperin

### ISSUE THREAD

**Issue by Nireplag** [datastaxdevs/workshop-introduction-to-nosql#467]
**Name:** Gabriel Galperin
**Email:** galperin@alunos.utfpr.edu.br
**Linkedin Profile:** www.linkedin.com/in/gabriel-galperin-03a88511a

Attach the homework screenshots below:
-----------------------------------------
![ex1](https://user-images.githubusercontent.com/70478646/128284622-19a5a395-ed17-485c-8db3-4bdaf9ea8c16.png)
![ex2](https://user-images.githubusercontent.com/70478646/128284632-6e4b8886-6fe0-4fc8-ae63-2ab01fb3765b.png)
-- image removed by team --
![ex4](https://user-images.githubusercontent.com/70478646/128284659-3f12751b-3ca6-40a8-8f26-81e633a14ec0.png)
![extra](https://user-images.githubusercontent.com/70478646/128284674-fb0ba5e6-5c56-489d-b8f9-d3c0bf551623.png)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Gabriel Galperin**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/GkXk6b-kR3uvQ_unfQUwzQ

**Comment by SonicDMG** [comment]
Also, I had to remove one of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.
