### ISSUE TITLE
[HW] <Shamshad Akther>

### ISSUE THREAD

**Issue by shamshadkhan** [datastaxdevs/workshop-introduction-to-nosql#468]
**Name:** Shamshad Akther
**Email:** shamshad.cse90@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/shamshad-akther/>

Attach the homework screenshots below:
-----------------------------------------
### 1. KeyValue Databases
![1](https://user-images.githubusercontent.com/12265243/128395887-2baf8f51-6a92-4102-a429-0a5ca7f6555b.PNG)

**✅ 4a. Create a table with GraphQL**
![2](https://user-images.githubusercontent.com/12265243/128395909-ea27ebed-10c7-48cc-a041-067fb043fe44.PNG)
![2a](https://user-images.githubusercontent.com/12265243/128395911-73f45eb8-01c0-475a-895c-bd7db2625423.PNG)

**✅ 4b. Populate the table**
![3](https://user-images.githubusercontent.com/12265243/128395969-b214df65-1ac8-4e42-afa2-238f92469c3f.PNG)
![3a](https://user-images.githubusercontent.com/12265243/128395968-6c7c450f-ce8a-4fb1-8892-8ae5fa87bfa1.PNG)

**✅ 4c. Update the value**
![4](https://user-images.githubusercontent.com/12265243/128395993-4c2bef23-21eb-4a0a-8aaa-addb5439c253.PNG)
![4a](https://user-images.githubusercontent.com/12265243/128395991-06a2dfee-0c53-44ad-885f-00f45c5fd7b9.PNG)

### 2. Try-it-out scenario
![5](https://user-images.githubusercontent.com/12265243/128396207-56f8b64e-fb7b-431f-a2e4-ea665202d7c2.PNG)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Shamshad Akther**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/1G1dYjszT_qs5IyQ00loyA
