### ISSUE TITLE
[HW] Ronny Schweda

### ISSUE THREAD

**Issue by deshaggy** [datastaxdevs/workshop-introduction-to-nosql#469]
**Name:** Ronny Schweda
**Email:** RS1711@gmx.de
**Xing Profile:** https://www.xing.com/profile/Ronny_Schweda

Attach the homework screenshots below:
-----------------------------------------
### *END OF STEP 1:*
![grafik](https://user-images.githubusercontent.com/44342073/128403514-b106c2fb-31da-430d-affe-e85db25bb8bd.png)

### *END OF STEP 2:*
![grafik](https://user-images.githubusercontent.com/44342073/128403444-cef06a22-fa07-4ddd-b0d3-df0e6d6e167a.png)

### *END OF STEP 3:*
![grafik](https://user-images.githubusercontent.com/44342073/128403387-249bf9b8-42c5-4d04-9e7e-325e90934db2.png)

### *END OF STEP 4:*
![grafik](https://user-images.githubusercontent.com/44342073/128403327-5b582838-08e1-4706-aeb5-34afe8e68a1e.png)

### *END OF STEP 5:*
![grafik](https://user-images.githubusercontent.com/44342073/128403256-49cab781-5b36-43d0-a5fb-228ba5da00a0.png)

### *END OF CQL TUTORIAL:*
![grafik](https://user-images.githubusercontent.com/44342073/128403120-02ced607-f654-49aa-a330-c147d790f840.png)

**Comment by HadesArchitect** [comment]
Hey **Ronny Schweda**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/V9KyqHmiTNaOywax0m0DEw
