### ISSUE TITLE
[HW] SIDDHARTH

### ISSUE THREAD

**Issue by echosidd** [datastaxdevs/workshop-introduction-to-nosql#47]
**Name:** Siddharth Kumar Singh
**Email:** <siddharth10102289@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/siddharth-kumar-singh-03025b176/>

Attach the homework screenshots below:
-----------------------------------------

<img width="1440" alt="s1" src="https://user-images.githubusercontent.com/57224041/118870632-6460b800-b904-11eb-8408-fa14946bef49.png">
<img width="1440" alt="s2-1" src="https://user-images.githubusercontent.com/57224041/118870665-6fb3e380-b904-11eb-8e37-72d75caacb6c.png">
<img width="1440" alt="s2-2" src="https://user-images.githubusercontent.com/57224041/118870692-780c1e80-b904-11eb-8d41-33ab9145841d.png">
<img width="1440" alt="s3-1" src="https://user-images.githubusercontent.com/57224041/118870727-7fcbc300-b904-11eb-9edd-7839819153cb.png">
-- images removed by team --
<img width="1440" alt="s4-1" src="https://user-images.githubusercontent.com/57224041/118870790-8bb78500-b904-11eb-8d96-673d8a7a98ca.png">
<img width="1440" alt="s4-2" src="https://user-images.githubusercontent.com/57224041/118870804-8fe3a280-b904-11eb-9307-bfc51f58369b.png">
<img width="1440" alt="scenario" src="https://user-images.githubusercontent.com/57224041/118870829-93772980-b904-11eb-81f6-a12800c3fd00.png">

**Comment by echosidd** [comment]
@SonicDMG I see some of the home-works have badge issued, can you let me know if there is something missing here. Thanks!

**Comment by HadesArchitect** [comment]
Good job!

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/zjWqbPxHQ4SKoLOeHY_vKA?identity__email=siddharth10102289%40gmail.com
