### ISSUE TITLE
[HW] <PRASANNA PERERA>

### ISSUE THREAD

**Issue by agprasanna** [datastaxdevs/workshop-introduction-to-nosql#471]
**Name:** Prasanna Perera
**Email:** agpperera7@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/agpperera

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/15875118/128616831-2980ca20-52f6-4031-a1f5-6249766c62ce.png)

![image](https://user-images.githubusercontent.com/15875118/128616834-3edd37e8-164f-481d-a2ca-3024c1a98010.png)

![image](https://user-images.githubusercontent.com/15875118/128616852-76a80de9-8311-4ccb-b07f-061060584e1b.png)

![image](https://user-images.githubusercontent.com/15875118/128616858-f3ae232a-89ee-4623-96b9-4a939c120983.png)

![image](https://user-images.githubusercontent.com/15875118/128616859-dcc51226-81d1-416a-bb6d-4dbb6b32c441.png)

![image](https://user-images.githubusercontent.com/15875118/128616862-11232449-0298-4ad3-9186-d1f1827f388e.png)

![image](https://user-images.githubusercontent.com/15875118/128616866-5459f7ed-7428-41f2-93d9-b0077a6d4bb4.png)

**Comment by HadesArchitect** [comment]
Hey **Prasanna Perera**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/8acwzixJSje5bTQO1utxwg
