### ISSUE TITLE
[HW] Harmanpreet Singh

### ISSUE THREAD

**Issue by singh-harmanpreet** [datastaxdevs/workshop-introduction-to-nosql#472]
**Name:** Harmanpreet SIngh
**Email:** singh.hps18@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/harmanpreet-s/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

_Try-it-out Scenerio_
a. Assignment
![Assignment](https://user-images.githubusercontent.com/59172539/128634630-c4505771-e6ec-437c-a662-32b4ae8b2218.png)

b. Completion acknowledgment
![Acknowledgement of completion](https://user-images.githubusercontent.com/59172539/128634561-cb275016-9ba3-413f-9763-31f71355f0a5.png)
________________________________________________________________________________________________________________________________________

### **1. Create Astra Db Instance**
assignment_db
![image](https://user-images.githubusercontent.com/59172539/128635272-c53aedc9-14ee-404b-b6b9-dd3229b555a3.png)

### **2. Tabular databases**

(a) Describe your Keyspace:
![image](https://user-images.githubusercontent.com/59172539/128635316-16b0e507-2a47-42aa-b7ef-6e43ef84cc91.png)

(b) Create tables:
![image](https://user-images.githubusercontent.com/59172539/128635452-a76a597a-e0bb-467f-a7b3-7ab49d81942f.png)

(c) Working with Data:
![image](https://user-images.githubusercontent.com/59172539/128635650-57cc857b-d22d-4b48-bd74-20a048d57199.png)

(d) Working with PARTITIONS:
![image](https://user-images.githubusercontent.com/59172539/128635743-7cdd1d4f-0648-4ce4-923c-0d715f6a3da4.png)

### **3. Document Databases**

(a) Cassandra knows JSON:
![image](https://user-images.githubusercontent.com/59172539/128635939-aef91c38-607f-42b7-b5d8-06db828de748.png)

(b) Create your application token:
![image](https://user-images.githubusercontent.com/59172539/128636031-05a19d29-6449-445b-8c3a-db5ca287c9a1.png)

(c) Create a new empty collection:
![image](https://user-images.githubusercontent.com/59172539/128636130-38fe07d7-b4ab-4d75-b195-b69767219067.png)

(d) Create a new document:
![image](https://user-images.githubusercontent.com/59172539/128636164-da25d607-bbe3-44cd-a46d-abbc17d8b1ae.png)

(e) Find all documents of a collection:
![image](https://user-images.githubusercontent.com/59172539/128636214-3cc49ac6-fc50-4281-ad21-57e259711df2.png)

(f) Retrieve a document from its id:
![image](https://user-images.githubusercontent.com/59172539/128636254-700a09d4-bc71-4896-8ad2-1dc35ab9ed39.png)

(g) Search document from a where clause:
![image](https://user-images.githubusercontent.com/59172539/128636299-c2f4b309-0723-4d8f-8358-87b649318b40.png)

### **4. Key/Value Databases**
(b) Create a table with GraphQL
_GraphQL Playground_
![image](https://user-images.githubusercontent.com/59172539/128636485-c46f19ea-ae12-4601-8abb-6897b6061a62.png)

_CQL console_
![image](https://user-images.githubusercontent.com/59172539/128636508-29c143bf-fe7a-41c0-9d3a-a4f6acebbfe8.png)

(c) Populate the table
_GraphQL Playground_
![image](https://user-images.githubusercontent.com/59172539/128636592-33ac5cfe-8d77-449b-8779-1b5a14dc0fbe.png)

_CQL console_
![image](https://user-images.githubusercontent.com/59172539/128636634-0eee58d1-0648-422e-aa46-e31627903854.png)

**Comment by singh-harmanpreet** [comment]
DataStax Studio container throws exception:
![image](https://user-images.githubusercontent.com/59172539/128637289-8b81c1b5-b01e-4784-80e8-a4087b52f746.png)

**Comment by hemidactylus** [comment]
Hi, Harmanpreet!
Very well done, you completed all steps!
Thanks for reporting the problem you're having with Step 5 (graph DB), we'll look into it and contact you further. In the meantime enjoy your badge!

**Comment by HadesArchitect** [comment]
Hey **Harmanpreet SIngh**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/6yawuZMyR9San6haWb4U2Q

**Comment by hemidactylus** [comment]
Hello again,
the trouble you report with the Step 5 is most likely due to Docker not having enough memory to properly start the container (in which DataStax studio would then run). At least ~6 GB are required.
Please check your system specs to confirm this may be the reason, thank you!

**Comment by singh-harmanpreet** [comment]
Hi Stefano,
I tried with 8GB memory allocation in both WLS2 and Hyper-V configurations and still found the same error. System memory is 16GB. Is there any way to debug the issue at my end as I see many have completed part 5 successfully, it's more likely issues at my end.
