### ISSUE TITLE
[HW] <Luigi Francesco Trantino>

### ISSUE THREAD

**Issue by GenPan** [datastaxdevs/workshop-introduction-to-nosql#473]
**Name:** Luigi Francesco Trantino
**Email:** trantino48@gmail.com
**Linkedin Profile:** www.linkedin.com/in/luigi-francesco-trantino

Attach the homework screenshots below:
-----------------------------------------

![Luigi_T_StepIV_Completed](https://user-images.githubusercontent.com/77194190/128732995-dd344dc1-baca-4d8f-8655-b868f3502db9.png)
![Luigi_T_StepV_Completed](https://user-images.githubusercontent.com/77194190/128733012-98000d0c-201e-4804-96cd-6e193e436f38.png)
![Luigi_T_try_it_out_Completed](https://user-images.githubusercontent.com/77194190/128733031-7b670fca-9d0e-4738-81d4-f0951cbe5eef.png)

**Comment by HadesArchitect** [comment]
Hey **Luigi Francesco Trantino**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/srVv-HlIQUOyDzbLn8-eNg
