### ISSUE TITLE
[HW] Rebecca Zee

### ISSUE THREAD

**Issue by rebeccazee** [datastaxdevs/workshop-introduction-to-nosql#474]
**Name:** Rebecca Zee
**Email:** ryz283@gmail.com
**Linkedin Profile**

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
**Part IV**<br>

![step4b-graphql](https://user-images.githubusercontent.com/24459985/128771992-57a09d33-5015-45c0-8a56-dd04c59d2f05.png)
![step4b-cql-console](https://user-images.githubusercontent.com/24459985/128771990-2720b9c6-0ac9-4d95-9b8d-814b2ca9a7c0.png)
![step4c-graphql](https://user-images.githubusercontent.com/24459985/128771995-6f8d3335-f22e-47a5-85c1-702df1dabc30.png)
![step4c-cql-console](https://user-images.githubusercontent.com/24459985/128771993-4358c40a-3405-420e-9ae2-9bde8be92cbc.png)

**try-it-out scenario**<br>
![try-it-out scenario completed](https://user-images.githubusercontent.com/24459985/128771040-dfb6fe81-367b-43a7-95ee-e6e6778fde72.png)

**Comment by HadesArchitect** [comment]
Hey **Rebecca Zee**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/0Da7tnpxSaWA6G4Vgk49Fg
