### ISSUE TITLE
[HW] <Vardhman Banthia>

### ISSUE THREAD

**Issue by Vardhman-Banthia** [datastaxdevs/workshop-introduction-to-nosql#475]
**Name:** Vardhman Banthia
**Email:** vardhmanbanthia015@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/vardhman-banthia-797198194?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BcK8VEAKGQOaUzGM5LP00gg%3D%3D>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![20210810_015217](https://user-images.githubusercontent.com/65674170/128780771-7d695b22-5359-42ce-9d93-15f60d5372a4.jpg)
![20210810_023101](https://user-images.githubusercontent.com/65674170/128780807-c2a99a77-2b2c-458b-aef3-27fe0702a082.jpg)
![20210810_030514](https://user-images.githubusercontent.com/65674170/128780814-fdbc1961-d8f2-428b-a0b7-23ed51092a1b.jpg)
![20210810_030624](https://user-images.githubusercontent.com/65674170/128780836-9d28fd30-df16-4c35-a3ed-eb8ae2a249c7.jpg)
![20210810_031814](https://user-images.githubusercontent.com/65674170/128780845-ee2fef7c-b9c2-4782-b6a9-be7caa062a8e.jpg)

**Comment by SonicDMG** [comment]
Hi there Vardhman, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by sabir98** [comment]
![image](https://user-images.githubusercontent.com/48026931/130091393-cbec78f4-347f-46b4-b105-2206f5d136f0.png)

**Comment by SonicDMG** [comment]
Vardhman dropped me the image from the scenario in Discord. All good!

**Comment by HadesArchitect** [comment]
Hey **Vardhman Banthia**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/sE6ZDCGiRpSqCF3c423ynA
