### ISSUE TITLE
[HW] UDIESHA GAUTAM

### ISSUE THREAD

**Issue by Udiesha** [datastaxdevs/workshop-introduction-to-nosql#476]
Name: Udiesha gautam
Email:1112noni@gmail.com
Linkedin Profile:https://www.linkedin.com/in/udiesha-gautam-988908210

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
SS FROM LAST STEP

![Screenshot (187)](https://user-images.githubusercontent.com/87614825/129003619-e506c369-ec01-4dd8-a1aa-6b9ce9ffbe9a.png)

![Screenshot (179)](https://user-images.githubusercontent.com/87614825/128995946-10c6f938-300a-43f0-ad91-4331ca68a7dc.png)

SS FROM BETWEEN STEPS

![Screenshot (174)](https://user-images.githubusercontent.com/87614825/128995073-b78baaf3-7df6-4c5f-9a87-a42270c2c158.png)
-- image removed by team --
![Screenshot (180)](https://user-images.githubusercontent.com/87614825/128995526-c8dfa962-6bed-49d7-92b1-1c89b2b0487d.png)

**Comment by HadesArchitect** [comment]
Hey **Udiesha gautam**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/9MkYU1SWSfiVaHk0q5RM4A

**Comment by SonicDMG** [comment]
Also, I had to remove one of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.
