### ISSUE TITLE
[HW] HIMANSHU YADAV

### ISSUE THREAD

**Issue by Him-Yadav** [datastaxdevs/workshop-introduction-to-nosql#477]
**Name:** HIMANSHU YADAV
**Email:** himanshu9359@gmail.com
**Linkedin Profile:** https://in.linkedin.com/in/himanshu-yadav-43789153

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/88819995/129150015-3c4dca6c-8d75-4945-bd10-a5af2ff8517c.png)

![image](https://user-images.githubusercontent.com/88819995/129150200-cb837d18-5ff4-4805-a94e-eb97a61a5945.png)

![image](https://user-images.githubusercontent.com/88819995/129150386-bd60fa90-6129-40b1-8c54-57cd364f494a.png)

![image](https://user-images.githubusercontent.com/88819995/129150451-cd7b7a8c-17ed-4a9f-b352-cc3aaf8f425e.png)

![image](https://user-images.githubusercontent.com/88819995/129150516-1deeece5-820b-42e0-b010-198eb1fb6546.png)

![image](https://user-images.githubusercontent.com/88819995/129150617-827660c4-92e4-4a0e-8c58-7fbad9f2360f.png)

![image](https://user-images.githubusercontent.com/88819995/129150801-833bd484-1565-43e0-ba94-3ede09b10910.png)

-- image removed by team --

![image](https://user-images.githubusercontent.com/88819995/129151032-9ece53ac-1d27-48cf-964a-8a4a15220b2f.png)

**Comment by Him-Yadav** [comment]
![image](https://user-images.githubusercontent.com/88819995/129151873-576f3daf-233e-4d60-9d32-f34ec97e60cc.png)

![image](https://user-images.githubusercontent.com/88819995/129151937-734229c9-aa85-4896-ac77-c97baf788ae3.png)

![image](https://user-images.githubusercontent.com/88819995/129152004-17d094a9-dad4-4338-bdf3-e6034237694e.png)

**Comment by SonicDMG** [comment]
Hi there Himanshu, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by SonicDMG** [comment]
Also, I had to remove some of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.

**Comment by Him-Yadav** [comment]
Attaching step 2 screenshots for your reference.
![image](https://user-images.githubusercontent.com/88819995/129309550-4f98de8a-47e0-4f13-ba68-19084f016996.png)
![image](https://user-images.githubusercontent.com/88819995/129309612-f3bf9a65-39ad-455c-8bbf-cf39e2ec424b.png)
![image](https://user-images.githubusercontent.com/88819995/129309658-efda8df5-c038-4656-b203-1372d8798592.png)
![image](https://user-images.githubusercontent.com/88819995/129309694-7d14fee7-a25d-4f28-8fa2-4613366103f5.png)

**Comment by SonicDMG** [comment]
Hi again Himanshu, thank you for the screens. What we are looking for is to complete the scenario at this link https://www.datastax.com/try-it-out

**Comment by Him-Yadav** [comment]
Hi There,
Please find try-it-out screenshots.

![image](https://user-images.githubusercontent.com/88819995/129383970-2e75daf7-7113-40f8-ae18-876b0c4834c7.png)
![image](https://user-images.githubusercontent.com/88819995/129384058-b6975d38-39d2-40dd-9ae5-f36301a2463f.png)
![image](https://user-images.githubusercontent.com/88819995/129384132-3875955c-eb0d-4e79-88db-e9089fbdb032.png)

**Comment by HadesArchitect** [comment]
Hey **HIMANSHU YADAV**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/PyJyqn5bRy2o0u7AdyNk2w
