### ISSUE TITLE
[HW] <Introduction to NotOnly SQL Databases>

### ISSUE THREAD

**Issue by vjadhav13** [datastaxdevs/workshop-introduction-to-nosql#479]
**Name:** Vijay Jadhav
**Email:** viju13677@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/vijay-jadhav-1394347>

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/48402413/129364858-d9d7a825-b129-4c66-9eb7-782387a7b8b8.png)

![image](https://user-images.githubusercontent.com/48402413/129364896-22b08220-50b4-4a5f-9769-d6475c69049b.png)

**Comment by HadesArchitect** [comment]
Hey **Vijay Jadhav**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/T3o6bkKIQQGNkb3j2Yl5tg
