### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by Harish-n1** [datastaxdevs/workshop-introduction-to-nosql#48]
**Name:**  Harish Nakireddy
**Email:**  harishn889@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/harish-nakireddy-82634a202

Attach the homework screenshots below:
-----------------------------------------

<img width="949" alt="8" src="https://user-images.githubusercontent.com/83642774/118871819-90c90400-b905-11eb-917f-2b3782e930c3.png">
<img width="954" alt="9" src="https://user-images.githubusercontent.com/83642774/118871826-91fa3100-b905-11eb-869c-b070cb19608f.png">
<img width="944" alt="10" src="https://user-images.githubusercontent.com/83642774/118871828-9292c780-b905-11eb-9356-7145b2105af4.png">
<img width="957" alt="11" src="https://user-images.githubusercontent.com/83642774/118871834-945c8b00-b905-11eb-9a6c-89ebdac02c3f.png">
<img width="946" alt="12" src="https://user-images.githubusercontent.com/83642774/118871837-94f52180-b905-11eb-9ff6-016d8eaa1b9d.png">
<img width="949" alt="1" src="https://user-images.githubusercontent.com/83642774/118871842-958db800-b905-11eb-8412-4f4cce2b62b7.png">
<img width="938" alt="2" src="https://user-images.githubusercontent.com/83642774/118871847-97577b80-b905-11eb-8ec2-a22207682931.png">
<img width="949" alt="3" src="https://user-images.githubusercontent.com/83642774/118871854-97f01200-b905-11eb-93df-997c1389f091.png">
<img width="956" alt="4" src="https://user-images.githubusercontent.com/83642774/118871855-99213f00-b905-11eb-8d19-9ffb84b8190b.png">
<img width="950" alt="5" src="https://user-images.githubusercontent.com/83642774/118871857-99b9d580-b905-11eb-83b0-0a89665c2ac7.png">
-- images removed by team --

**Comment by SonicDMG** [comment]
Hi there Harish, thank you for your submission. Looks like you completed the repo work, great. Please provide a screenshot from homework step 2 as well.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

**Comment by SonicDMG** [comment]
The other part of Harish's homework is here https://github.com/datastaxdevs/workshop-introduction-to-nosql/issues/77. I also issued his badge there as well.
