### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by jpalbino** [datastaxdevs/workshop-introduction-to-nosql#480]
**Name:** Joao Pedro Albino
**Email:** jp.albino@unesp.br
**Linkedin Profile:** https://www.linkedin.com/in/jo%C3%A3o-pedro-albino-45b196/

Attach the homework screenshots below:
-----------------------------------------

### TRY IT OUT Scenario
![try-it-out-scenario-end](https://user-images.githubusercontent.com/7212697/129415095-5a315005-ed6c-40db-af8e-a3081c90d02f.png)

### Graphql Schema
![graphql-schema-end](https://user-images.githubusercontent.com/7212697/129415333-269bcd6b-a344-40dc-9936-5920a427ac21.png)

### Graphql 
![graphql-end](https://user-images.githubusercontent.com/7212697/129415209-37e73214-93fc-475b-b4d9-14634085fd58.png)

### CQL Console
![cql-console-final](https://user-images.githubusercontent.com/7212697/129415446-ab65c875-72ba-4ece-b25a-b3239bd304cf.png)

**Comment by HadesArchitect** [comment]
Hey **Joao Pedro Albino**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/NmAKvy2gQZ6eqPBus9R-YA
