### ISSUE TITLE
[HW] VIVEK SHARMA

### ISSUE THREAD

**Issue by VS7352** [datastaxdevs/workshop-introduction-to-nosql#481]
Name: VIVEK SHARMA
Email: vivek329182@gmail.com
Linkedin Profile: https://www.linkedin.com/in/vivek-sharma-587282140/

Attach the homework screenshots below:
-----------------------------------------
![Home_Work_1](https://user-images.githubusercontent.com/81165164/129879543-30e8d9f6-b8bc-4efb-a792-d586281a3a79.PNG)

![Screenshot_CQL](https://user-images.githubusercontent.com/81165164/129879558-654ecb22-74d8-47a4-9af6-865845596f5a.PNG)

![Screenshot_Exercise](https://user-images.githubusercontent.com/81165164/129879564-82b604f7-00c4-44e6-9241-061b658da245.PNG)

**Comment by HadesArchitect** [comment]
Hey **VIVEK SHARMA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ncqk3RTPQ2eGwuqg9CKFJw
