### ISSUE TITLE
[HW] <Pramod Byakod>

### ISSUE THREAD

**Issue by byakodpramod** [datastaxdevs/workshop-introduction-to-nosql#482]
**Name:** Pramod Byakod
**Email:** byakodpramod@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/byakodpramod/

Attach the homework screenshots below:
-----------------------------------------

![DataStax1](https://user-images.githubusercontent.com/28912853/129935513-4520dd90-8387-4cda-927d-64ba78d78ad4.jpg)

![DataStax2](https://user-images.githubusercontent.com/28912853/129935564-92db8eeb-9e8d-43fe-a380-25abcee305fa.jpg)

![DataStax3](https://user-images.githubusercontent.com/28912853/129935587-d9895747-4c8f-47c7-9480-139366aef93e.jpg)

-- images removed by team --

**Comment by HadesArchitect** [comment]
Hey **Pramod Byakod**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/T_iW6PJwTC6v2FI_aBtu0g

**Comment by SonicDMG** [comment]
I also had to remove some of your images because they contained your Astra token. Be sure to remove your token from the Astra UI so there are no security issues.
