### ISSUE TITLE
[HW] kevin ND

### ISSUE THREAD

**Issue by kevin1958** [datastaxdevs/workshop-introduction-to-nosql#483]
**Name:** Kevin  ND
**Email:** kevin.nd12@outlook.com
**Linkedin Profile:** <https://www.linkedin.com/in/kevin-n-1b2b75105/>

Attach the homework screenshots below:
-----------------------------------------

![Screenshot 2021-08-18 at 22-44-53 Manage Database — DataStax Astra](https://user-images.githubusercontent.com/20598036/129942833-bc3507f9-7479-43fb-8287-4251f184f9a6.png)

![Screenshot 2021-08-20 at 21-29-02 Try It Out](https://user-images.githubusercontent.com/20598036/130261146-9ec2c010-d1bc-4dc1-8a29-5fc354d018b2.png)

![Screenshot 2021-08-18 at 22-47-17 Swagger UI](https://user-images.githubusercontent.com/20598036/129943075-fef87fc4-4037-4c02-91ec-a30d9612c792.png)

![Screenshot 2021-08-18 at 22-40-45 Playground - https d50a0073-5df7-4b6f-845a-f06b6dc13c0d-asia-south1 apps astra datastax c](https://user-images.githubusercontent.com/20598036/129943204-0ac1e6ff-0d9b-47f7-873c-c41990c17945.png)

![Screenshot 2021-08-18 at 22-19-43 Manage Database — DataStax Astra](https://user-images.githubusercontent.com/20598036/129939327-c5ba867a-7882-486c-b6f0-b0ad06d8fd2b.png)

**Comment by SonicDMG** [comment]
Hi there Kevin, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by kevin1958** [comment]
> 
> 
> **Name:** Kevin ND
> **Email:** [kevin.nd12@outlook.com](mailto:kevin.nd12@outlook.com)
> **Linkedin Profile:** https://www.linkedin.com/in/kevin-n-1b2b75105/
> ## Attach the homework screenshots below:
> 
> ![Screenshot 2021-08-18 at 22-44-53 Manage Database — DataStax Astra](https://user-images.githubusercontent.com/20598036/129942833-bc3507f9-7479-43fb-8287-4251f184f9a6.png)
> 
> ![Screenshot 2021-08-20 at 21-29-02 Try It Out](https://user-images.githubusercontent.com/20598036/130261146-9ec2c010-d1bc-4dc1-8a29-5fc354d018b2.png)
> 
> ![Screenshot 2021-08-18 at 22-47-17 Swagger UI](https://user-images.githubusercontent.com/20598036/129943075-fef87fc4-4037-4c02-91ec-a30d9612c792.png)
> 
> ![Screenshot 2021-08-18 at 22-40-45 Playground - https d50a0073-5df7-4b6f-845a-f06b6dc13c0d-asia-south1 apps astra datastax c](https://user-images.githubusercontent.com/20598036/129943204-0ac1e6ff-0d9b-47f7-873c-c41990c17945.png)
> 
> ![Screenshot 2021-08-18 at 22-19-43 Manage Database — DataStax Astra](https://user-images.githubusercontent.com/20598036/129939327-c5ba867a-7882-486c-b6f0-b0ad06d8fd2b.png)

![Screenshot 2021-08-20 at 21-29-02 Try It Out](https://user-images.githubusercontent.com/20598036/130261254-479cf779-79a8-4a6c-b080-cf3938b10932.png)

**Comment by kevin1958** [comment]
i have comepleted the second strep and added the screenshot

**Comment by HadesArchitect** [comment]
Hey **Kevin  ND**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/nLQmEJNASTuFIrlZOeKxbA
