### ISSUE TITLE
[HW] Hung Fai Leung

### ISSUE THREAD

**Issue by hungfaileung** [datastaxdevs/workshop-introduction-to-nosql#484]
**Name:** Hung Fai Leung
**Email:** hf.leung.gary@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/hfleunggary/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![image](https://user-images.githubusercontent.com/87762948/129939542-9aad379b-2df3-4c65-b456-9b2c1aabacab.png)

![image](https://user-images.githubusercontent.com/87762948/129939581-5418a5e1-1324-44b1-a21e-902131dd6ad2.png)

**Comment by HadesArchitect** [comment]
Hey **Hung Fai Leung**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ffyeF8iGQyuO8ELC7CiLEw
