### ISSUE TITLE
[HW] <NAME>RAJA SHANMUGAN S

### ISSUE THREAD

**Issue by RajaX24** [datastaxdevs/workshop-introduction-to-nosql#485]
**Name:** RAJA SHANMUGAN S
**Email:** g.s.rajashanmugan@gmail.com
**Linkedin Profile:** www.linkedin.com/in/raja-shanmugan

Attach the homework screenshots below:

-----------------------------------------

<SCREENSHOTS>
![SS1](https://user-images.githubusercontent.com/89154635/129942053-82d5a21e-b283-4096-9495-1d4554be085b.png)
![SS](https://user-images.githubusercontent.com/89154635/129942041-89a9dce6-4110-4f25-8889-1b75c75ef135.png)
![SS1](https://user-images.githubusercontent.com/89154635/129942516-1ad93ada-2e99-433e-aaee-f84d01781021.png)
![SS](https://user-images.githubusercontent.com/89154635/129942552-6158db71-e1c4-4a94-965e-2aa2b6afcdc2.png)

**Comment by HadesArchitect** [comment]
Hey **RAJA SHANMUGAN S**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/r5L8B3TJQu6UwR4uKmiPEw
