### ISSUE TITLE
[HW] Jeremias Jimenez Chavarria

### ISSUE THREAD

**Issue by chajere** [datastaxdevs/workshop-introduction-to-nosql#487]
**Name:** Jeremias Jimenez
**Email:** chajere@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/jeremias-jimenez-90319a80/

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/13526144/129939101-37eff19d-e9a3-4843-b6b8-2a2aa0b32791.png)

![image](https://user-images.githubusercontent.com/13526144/129939063-6b6d0a6a-f71e-48ec-9dad-9a62a040d702.png)

![image](https://user-images.githubusercontent.com/13526144/129939643-aa554029-511b-4e17-aa86-04a3e1ca82a6.png)

![image](https://user-images.githubusercontent.com/13526144/129939696-0921eac5-c519-4008-84f3-16ed8fe9052b.png)

**Comment by HadesArchitect** [comment]
Hey **Jeremias Jimenez**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/sQ9_PD8kR9-pJAeS4Vv0cw
