### ISSUE TITLE
[HW] <NAME>RAJA SHANMUGAN S

### ISSUE THREAD

**Issue by RajaX24** [datastaxdevs/workshop-introduction-to-nosql#488]
**Name:** RAJA SHANMUGAN S
**Email:** g.s.rajashanmugan@gmail.com
**Linkedin Profile:** <LINK>www.linkedin.com/in/raja-shanmugan

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![SS1](https://user-images.githubusercontent.com/89154635/129943025-c486c0dc-e822-4018-b082-e15dd721c928.png)
![SS](https://user-images.githubusercontent.com/89154635/129943076-62804cc8-231a-4d3c-9855-396f68feaf03.png)
![SS](https://user-images.githubusercontent.com/89154635/129943233-0c5a64bc-8b2b-4e81-b83a-dcaa27def54c.png)
![SS1](https://user-images.githubusercontent.com/89154635/129943241-7202dbbd-ef2d-43be-9ed6-f217562dc63a.png)

**Comment by HadesArchitect** [comment]
Hey **RAJA SHANMUGAN S**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/P2_1JuL8QGSVuriUZkTRxQ
