### ISSUE TITLE
[HW] <NAME> Nicola Bizzotto

### ISSUE THREAD

**Issue by nicola02nb** [datastaxdevs/workshop-introduction-to-nosql#489]
**Name:** Nicola Bizzotto
**Email:** nicola.02.nb@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/61830443/129944073-6caba456-8897-4ae2-ab8f-74e189b26b28.png)
![image](https://user-images.githubusercontent.com/61830443/129945711-ef4285a4-4340-4685-b771-061b66798a9c.png)
![image](https://user-images.githubusercontent.com/61830443/129945744-f4dfa3fa-c453-4580-98b0-c4e81c309eb4.png)

**Comment by HadesArchitect** [comment]
Hey **Nicola Bizzotto**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/qAClK4IcQXKrX1gO1uh_Bg
