### ISSUE TITLE
[HW] <Lin Yuan>

### ISSUE THREAD

**Issue by lin-05y** [datastaxdevs/workshop-introduction-to-nosql#49]
**Name:** < Lin Yuan >
**Email:** <linayuan2001@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/lin-yuan-26bb57208/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
"scenario completed" screen:

![image](https://user-images.githubusercontent.com/84109485/118872248-5a17cd00-b8b6-11eb-9441-3adc6bdd8be6.png)

STEP I: Astra
![image](https://user-images.githubusercontent.com/84109485/118871968-1624c800-b8b6-11eb-960c-200536e3cfa3.png)

STEP II: Tabular
2c.
![image](https://user-images.githubusercontent.com/84109485/118865924-78c69580-b8af-11eb-8413-40b5968e528f.png)
2d.
![image](https://user-images.githubusercontent.com/84109485/118866143-b4f9f600-b8af-11eb-89c4-dad1ef1fbb0f.png)

STEP III: Document
3a.
![image](https://user-images.githubusercontent.com/84109485/118866447-ff7b7280-b8af-11eb-9606-ae0740abd9d7.png)
-- images removed by team --

STEP IV: KeyValue
4b.
![image](https://user-images.githubusercontent.com/84109485/118871251-65b6c400-b8b5-11eb-8569-ad8e70c51f15.png)
4c.
-- images removed by team --
![image](https://user-images.githubusercontent.com/84109485/118871656-c34b1080-b8b5-11eb-8165-dc4937b3c223.png)
![image](https://user-images.githubusercontent.com/84109485/118871723-d65de080-b8b5-11eb-8f8b-c5cd01e3af94.png)

**Comment by SonicDMG** [comment]
Awesome job Lin, thank you.

**Comment by HadesArchitect** [comment]
Great job! https://api.badgr.io/public/assertions/SXQ_5X1aTeyZJUx_SeDvJw?identity__email=linayuan2001%40gmail.com
