### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by sabir98** [datastaxdevs/workshop-introduction-to-nosql#490]
**Name:** Sabir
**Email:** sabiribrahimov98@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/sabir-ibrahimov-aa8732182/>

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/48026931/129943947-135f703b-74cd-4aad-9f76-a94eb2022a2c.png)
![image](https://user-images.githubusercontent.com/48026931/129944066-94bc193e-f478-4349-b79e-840f9d6efb04.png)
![image](https://user-images.githubusercontent.com/48026931/129944176-42a8d471-e23e-470f-8f99-c513e6a3b832.png)

**Comment by sabir98** [comment]
Here is the snip of completion screen.
Btw. thank you all, guys!

![image](https://user-images.githubusercontent.com/48026931/130091589-0cfb7e36-3831-4f22-bd39-53d58eba1e87.png)

**Comment by HadesArchitect** [comment]
Hey **Sabir**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/y-x-hfbLSZq1KGTYeN-B3g
