### ISSUE TITLE
[HW] <Shivansh>

### ISSUE THREAD

**Issue by Conical-Apollo** [datastaxdevs/workshop-introduction-to-nosql#491]
**Name:** Shivansh
**Email:** shivanshsingh060@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/shivansh-singh-85829740/

Attach the homework screenshots below:
-----------------------------------------
![2](https://user-images.githubusercontent.com/89154077/129944733-b49a071f-e7d8-482c-a02a-542577ae6d0d.png)
![3](https://user-images.githubusercontent.com/89154077/129944738-8099b182-beca-4594-aac3-595e730bdbb3.png)
![4](https://user-images.githubusercontent.com/89154077/129944741-a0b3ce5a-1995-4e53-80c0-e44397bf5084.png)
![5](https://user-images.githubusercontent.com/89154077/129944745-27507e82-7078-4146-b6e7-f31fbe6421f0.png)
![6](https://user-images.githubusercontent.com/89154077/129944748-946dd448-f302-4d25-94c1-7db794965550.png)
-- image removed by team --
![8](https://user-images.githubusercontent.com/89154077/129944755-6bbd0b3c-6b93-477a-97ec-bd8bb1899619.png)
![9](https://user-images.githubusercontent.com/89154077/129944757-1262c444-7320-427b-a818-d3e3c88545d0.png)
![10](https://user-images.githubusercontent.com/89154077/129944758-51862097-e44d-48b4-9436-b954a219a832.png)
![1](https://user-images.githubusercontent.com/89154077/129944762-a9f671a5-8cf2-4a22-9068-6aad24606264.png)
![tryout](https://user-images.githubusercontent.com/89154077/129944764-47bddada-a89d-4372-9405-bb09f85b0e88.png)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Shivansh**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/pNhcbiL6TDK1Vkbdit8WXw

**Comment by SonicDMG** [comment]
Also, I had to remove one of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.
