### ISSUE TITLE
[HW] Ng Wei Xiang

### ISSUE THREAD

**Issue by ngweixiang** [datastaxdevs/workshop-introduction-to-nosql#492]
**Name:** Ng Wei Xiang
**Email:** ngweixiang95@gmail.com
**Linkedin Profile:** -

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Screenshot 2021-08-19 013621](https://user-images.githubusercontent.com/87744159/129945724-c7e60f09-d13b-4e2b-a7f3-232b41516a67.png)

![Screenshot 2021-08-19 013533](https://user-images.githubusercontent.com/87744159/129945456-5020e2a0-5d83-460b-8724-9ca7967ad41d.png)

![Screenshot 2021-08-19 013153](https://user-images.githubusercontent.com/87744159/129945186-561aa2ad-8ce0-4d3e-8ca3-54fd47f56b08.png)

**Comment by HadesArchitect** [comment]
Hey **Ng Wei Xiang**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/uaC6WS7_SZOV87ET021xyw
