### ISSUE TITLE
[HW] <Uttam Kasundara>

### ISSUE THREAD

**Issue by uttamkasundara** [datastaxdevs/workshop-introduction-to-nosql#493]
**Name:** Uttam Kasundara
**Email:** uttam.kasundra6664@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/uttamkasundra

Attach the homework screenshots below:
-----------------------------------------

- Cassandra
![image](https://user-images.githubusercontent.com/35024056/129944600-96731940-7b56-403f-a794-593fc85b7b23.png)

- Swagger
-- image removed by team --

- Graphql
![image](https://user-images.githubusercontent.com/35024056/129945464-13d144a5-d616-4c1b-9994-c2ca9ae50efb.png)

- Graphana for health
![image](https://user-images.githubusercontent.com/35024056/129946102-8f241cf7-e757-4580-b5b2-76cbbbdafecf.png)

**Comment by SonicDMG** [comment]
Hi there Uttam, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by SonicDMG** [comment]
Also, I had to remove one of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.

**Comment by uttamkasundara** [comment]
Here are Step-2 related to CQL 
![image](https://user-images.githubusercontent.com/35024056/130261676-87a8b397-7f0d-4da7-b67e-7801f1b60048.png)
Please review

**Comment by uttamkasundara** [comment]
> Also, I had to remove one of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.

Thank you for removing token image

**Comment by HadesArchitect** [comment]
Hey **Uttam Kasundara**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/2J-0XOB4QNCZszYeGx9vmA
