### ISSUE TITLE
[HW] Yael Estrada

### ISSUE THREAD

**Issue by Yael-Estrada** [datastaxdevs/workshop-introduction-to-nosql#494]
**Name:** Yael Estrada
**Email:** yael_ex2.a97@hotmail.com
**Linkedin Profile:** https://www.linkedin.com/in/yael-estrada-0876501aa/

Attach the homework screenshots below:
-----------------------------------------
Step 4:
![image](https://user-images.githubusercontent.com/23178581/129945374-4b2c9367-ec35-4197-84c1-ce40952f3555.png)

![image](https://user-images.githubusercontent.com/23178581/129945454-ca3261f7-4672-4b45-a3a2-4efd6988f6d5.png)
Scenario:
![image](https://user-images.githubusercontent.com/23178581/129946267-a023e35e-afef-47ca-ba79-7297c0f625b6.png)

**Comment by HadesArchitect** [comment]
Hey **Yael Estrada**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ZrfBCvhOQamsp_dpedjOyw
