### ISSUE TITLE
[HW] Avinash M

### ISSUE THREAD

**Issue by avinash3699** [datastaxdevs/workshop-introduction-to-nosql#495]
**Name:** Avinash M
**Email:** sec19cs005@sairamtap.edu.in
**Linkedin Profile:** https://www.linkedin.com/in/avinash-m-571642119/

Attach the homework screenshots below:
-----------------------------------------
![Screenshot (365)](https://user-images.githubusercontent.com/68368913/129946211-885e2eb1-8211-42f0-a885-9af80f89a484.png)
![Screenshot (366)_LI](https://user-images.githubusercontent.com/68368913/129946230-78104389-e4ed-45bf-963f-d60b1e62e360.jpg)
![Screenshot (367)](https://user-images.githubusercontent.com/68368913/129946237-920402f2-8ecf-41dd-951c-736da51269b7.png)
![Screenshot (368)](https://user-images.githubusercontent.com/68368913/129946239-0bcafa54-1918-4301-a5f1-5a469bd250f1.png)
![Screenshot (369)](https://user-images.githubusercontent.com/68368913/129946241-cf845534-d131-4658-8dfc-6b3f4fb60a51.png)

**Comment by HadesArchitect** [comment]
Hey **Avinash M**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/KXaRcF85Sy-3jYSvyjTUPg

**Comment by avinash3699** [comment]
Thankyou!
