### ISSUE TITLE
[HW] <Michele Atzeni>

### ISSUE THREAD

**Issue by MicheleAtzeni** [datastaxdevs/workshop-introduction-to-nosql#496]
**Name:** Michele Atzeni 
**Email:** michele.atzeni17@gmail.com 
**Linkedin Profile:**  https://www.linkedin.com/in/michele-atzeni-458292153

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

<img width="1439" alt="Schermata 2021-08-18 alle 19 25 20" src="https://user-images.githubusercontent.com/89156889/129946983-2c29491f-d3c3-484b-b0f3-11f13042013a.png">

![image](https://user-images.githubusercontent.com/89156889/129946960-9511774e-016b-43ac-b824-8a230c0c1ffd.png)

**Comment by HadesArchitect** [comment]
Hey **Michele Atzeni**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/z5ELEikJQyGTvqIfEQmnaQ
