### ISSUE TITLE
[HW] Sabarish Guru G

### ISSUE THREAD

**Issue by sabarish404** [datastaxdevs/workshop-introduction-to-nosql#498]
**Name:** Sabarish Guru G
**Email:** sabarish007.g@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sabarish-guru-g-7245b2146

Attach the homework screenshots below:
-----------------------------------------

<SCREENSH
![practice 2](https://user-images.githubusercontent.com/72157710/129949803-6d29c668-f137-41a8-b1c4-0ee7364fe7e0.jpg)
![practice 3](https://user-images.githubusercontent.com/72157710/129949814-e8a07547-66da-42b2-a4dd-1932839c36be.jpg)
![practice 3b](https://user-images.githubusercontent.com/72157710/129949817-44220c8c-a0d3-4c77-a38b-b30d7fad7643.jpg)
![practice 3cdefg](https://user-images.githubusercontent.com/72157710/129949818-3ba1d0f9-bd66-4f0e-ba7a-1c3127064b1e.jpg)
![practice4](https://user-images.githubusercontent.com/72157710/129949822-665861e6-c4ca-410b-af4d-c4cf2f938753.jpg)
![practice4c](https://user-images.githubusercontent.com/72157710/129949826-8ed6f229-e413-46d0-8783-8d69489b9c1c.jpg)
![try out module](https://user-images.githubusercontent.com/72157710/129949831-9f96b5fd-c5a1-448f-b46a-1bdf94355085.jpg)
OTS>

**Comment by HadesArchitect** [comment]
Hey **Sabarish Guru G**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/hyuEFaXXSzGwNp9fOoi5kg
