### ISSUE TITLE
[HW] <CARLOS LOPEZ>

### ISSUE THREAD

**Issue by serialmerol** [datastaxdevs/workshop-introduction-to-nosql#499]
**Name:** Carlos Edmundo Lopez Mateos
**Email:** serialmerol@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/carlos-edmundo-l%C3%B3pez-mateos-051367103/>

Attach the homework screenshots below:
-----------------------------------------

<![scenario complete 1](https://user-images.githubusercontent.com/26726260/129950218-3516037e-bce7-49be-806a-4de0833cd821.png)
![scenario complete](https://user-images.githubusercontent.com/26726260/129950219-9a08d50d-00ff-4540-8f96-34fb04e0cf88.png)
![cap IV console](https://user-images.githubusercontent.com/26726260/129950221-45bdf910-9562-4c05-b4fb-f9d37a34496f.png)
![cap IV graphql](https://user-images.githubusercontent.com/26726260/129950223-7b63cff2-b344-4399-b235-12179ad3807d.png)>

**Comment by HadesArchitect** [comment]
Hey **Carlos Edmundo Lopez Mateos**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/SvzpuiS3TDGCw880fwkzvA
