### ISSUE TITLE
[HW] <kurian mathew>

### ISSUE THREAD

**Issue by kurianmathew7** [datastaxdevs/workshop-introduction-to-nosql#50]
**Name:** kurian
**Email:** <kurianmathew7@gmail.com>
**Linkedin Profile:** www.linkedin.com/in/kurian-mathew-05732024
![Screen Shot 2021-05-19 at 2 25 42 PM](https://user-images.githubusercontent.com/54526158/118872414-8cc1c580-b8b6-11eb-84f9-4d01d7d620e7.png)
-- images removed by team --
![Screen Shot 2021-05-19 at 2 24 53 PM](https://user-images.githubusercontent.com/54526158/118872418-8e8b8900-b8b6-11eb-9d01-dee78b3a8c1f.png)
![Screen Shot 2021-05-19 at 2 29 18 PM](https://user-images.githubusercontent.com/54526158/118872423-8f241f80-b8b6-11eb-9176-7c5ccc9953e1.png)
![Screen Shot 2021-05-19 at 3 21 52 PM](https://user-images.githubusercontent.com/54526158/118872424-8fbcb600-b8b6-11eb-8ca3-65cfa8f1b7fd.png)
![Screen Shot 2021-05-19 at 3 21 11 PM](https://user-images.githubusercontent.com/54526158/118872427-90554c80-b8b6-11eb-8283-65d462f1553a.png)
![Screen Shot 2021-05-19 at 2 22 31 PM](https://user-images.githubusercontent.com/54526158/118872428-90554c80-b8b6-11eb-8147-416541d8ad3e.png)
-- images removed by team --
![Screen Shot 2021-05-19 at 2 26 07 PM](https://user-images.githubusercontent.com/54526158/118872444-92b7a680-b8b6-11eb-8fe3-8a74466a5871.png)

>

Attach the homework screenshots below:
-----------------------------------------
![Screen Shot 2021-05-19 at 2 18 43 PM](https://user-images.githubusercontent.com/54526158/118863829-5df32180-b8ad-11eb-95cb-357a047cc01c.png)

![Screen Shot 2021-05-19 at 2 22 31 PM](https://user-images.githubusercontent.com/54526158/118864279-d22dc500-b8ad-11eb-9f7f-bc20885a42b3.png)
![image](https://user-images.githubusercontent.com/54526158/118864778-52542a80-b8ae-11eb-9d0a-1596ca3720b6.png)
![Screen Shot 2021-05-19 at 2 26 24 PM](https://user-images.githubusercontent.com/54526158/118864806-55e7b180-b8ae-11eb-9e29-ebed3a7e4982.png)
![Screen Shot 2021-05-19 at 2 26 07 PM](https://user-images.githubusercontent.com/54526158/118864810-56804800-b8ae-11eb-86c2-49f878ffecb1.png)
![Screen Shot 2021-05-19 at 2 25 42 PM](https://user-images.githubusercontent.com/54526158/118864846-60a24680-b8ae-11eb-9d90-15f49df8df77.png)
![Screen Shot 2021-05-19 at 2 24 53 PM](https://user-images.githubusercontent.com/54526158/118864851-613add00-b8ae-11eb-8713-bff4cf697861.png)
![Screen Shot 2021-05-19 at 2 22 31 PM](https://user-images.githubusercontent.com/54526158/118864854-61d37380-b8ae-11eb-930e-98a3a24e53ca.png)
![image](https://user-images.githubusercontent.com/54526158/118873801-2c338800-b8b8-11eb-9a88-d8aa2ccadf37.png)

**Comment by kurianmathew7** [comment]
![image](https://user-images.githubusercontent.com/54526158/118873748-1c1ba880-b8b8-11eb-95a7-5649791609ff.png)

**Comment by SonicDMG** [comment]
Looks good Kurian, thank you.

**Comment by HadesArchitect** [comment]
Good job! https://api.badgr.io/public/assertions/YKbcEFFHRPaK_zsKS2jW8Q?identity__email=kurianmathew7%40gmail.com
