### ISSUE TITLE
[HW] Rithesh G

### ISSUE THREAD

**Issue by rithesh-gopal** [datastaxdevs/workshop-introduction-to-nosql#500]
**Name:** Rithesh G
**Email:** rithesh.gopal1@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/rithesh-gopal-3b0015112/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![document2](https://user-images.githubusercontent.com/15688413/129950388-41c6f953-52a0-4a2c-b323-afe8428e78d9.JPG)

![keyvalue1](https://user-images.githubusercontent.com/15688413/129950393-2ce6610d-89e7-4638-8534-1cb229daa822.JPG)
![keyvalue2](https://user-images.githubusercontent.com/15688413/129950394-12fc095b-c9aa-45bb-a55f-96ee812eed0a.JPG)
![keyvalue3](https://user-images.githubusercontent.com/15688413/129950397-f79eb924-ff29-42d5-81c9-e3bb15cab4ec.JPG)
![scenario](https://user-images.githubusercontent.com/15688413/129950398-6ce90e04-20b3-4dd8-83a9-3d3465cce927.JPG)
![tabular](https://user-images.githubusercontent.com/15688413/129950400-8a5dae9f-8994-4f75-815a-e45333667a08.JPG)
![astra_db](https://user-images.githubusercontent.com/15688413/129950403-ca941236-d662-4835-abd1-84bfd8aa7dd5.JPG)
![document1](https://user-images.githubusercontent.com/15688413/129950405-45833ebb-a25f-41e1-8289-bc0f2d31edc1.JPG)

**Comment by HadesArchitect** [comment]
Hey **Rithesh G**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/BEZ2pshoSy2duEruxMFPYA
