### ISSUE TITLE
[HW] Tanmay Kumar Patra

### ISSUE THREAD

**Issue by tkumarpatra** [datastaxdevs/workshop-introduction-to-nosql#501]
**Name:** Tanmay Kumar Patra
**Email:** write2tkpatra@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/tkpatra/

Attach the homework screenshots below:
-----------------------------------------

<img width="1680" alt="Screenshot 2021-08-18 at 10 24 48 PM" src="https://user-images.githubusercontent.com/9041868/129952570-b24c985d-bb41-4a87-ac9d-986ac290ae63.png">
<img width="1680" alt="Screenshot 2021-08-18 at 10 25 00 PM" src="https://user-images.githubusercontent.com/9041868/129952582-92f48f22-8212-4d16-be53-2f7592aa7fa8.png">
<img width="1680" alt="Screenshot 2021-08-18 at 11 41 32 PM" src="https://user-images.githubusercontent.com/9041868/129952588-7a947184-58c8-4484-a247-ef74ca9e8672.png">
-- images removed by team --
<img width="1680" alt="Screenshot 2021-08-18 at 11 51 09 PM" src="https://user-images.githubusercontent.com/9041868/129952624-b2ef687d-e02e-4733-a0b0-e9d25f79d719.png">
<img width="1680" alt="Screenshot 2021-08-18 at 11 54 04 PM" src="https://user-images.githubusercontent.com/9041868/129952625-ce2903b5-b7ba-46c4-a2a3-ec8ce1eab6f2.png">

**Comment by HadesArchitect** [comment]
Hey **Tanmay Kumar Patra**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/3pGkE1CmRCqDyQNz2_95DQ
