### ISSUE TITLE
[HW] <Andrea Maccan>

### ISSUE THREAD

**Issue by acmaccan** [datastaxdevs/workshop-introduction-to-nosql#504]
**Name:** Andrea Maccan
**Email:** acmaccan@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/acmaccan/>

Attach the homework screenshots below:
-----------------------------------------
![01](https://user-images.githubusercontent.com/78446973/129954362-3df64438-5c50-492a-8acd-0284bd671376.png)
![02 a 01](https://user-images.githubusercontent.com/78446973/129954364-c36205ed-7599-4722-96b0-5f1dffa24053.png)
![02 b 01](https://user-images.githubusercontent.com/78446973/129954365-bcccc70a-9c7c-4fa6-b8f0-a06ea5a164f3.png)
![02 b 02](https://user-images.githubusercontent.com/78446973/129954367-dc813905-2a68-44c5-9f91-c4eb8774f41a.png)
![02 c 01](https://user-images.githubusercontent.com/78446973/129954371-99561d31-92b4-45d5-a232-e50873381035.png)
![02 c 02](https://user-images.githubusercontent.com/78446973/129954302-83323f6a-ac21-4bcb-93a7-06021d5118ff.png)
![02 c 03](https://user-images.githubusercontent.com/78446973/129954310-39db35b7-32e0-4ff6-8581-b6deec9895ad.png)
![02 d 01](https://user-images.githubusercontent.com/78446973/129954313-f4210249-ba3d-4c69-b2ac-55e72f57fda4.png)
![02 d 02](https://user-images.githubusercontent.com/78446973/129954316-4da388ff-7c30-4071-943a-4d30bd913aa1.png)
![02 d 03](https://user-images.githubusercontent.com/78446973/129954317-caf5e0af-9de0-419a-9cb3-ca5dfca2142c.png)
![03 a 01](https://user-images.githubusercontent.com/78446973/129954319-cf34de09-9bc7-4483-bee0-8d1945ccb139.png)
![03 a 02](https://user-images.githubusercontent.com/78446973/129954322-5e850846-40fa-4c95-b72f-349144964ecd.png)
![03 b](https://user-images.githubusercontent.com/78446973/129954324-7159e91b-e679-4407-9452-2d44540f18cb.png)
![03 c](https://user-images.githubusercontent.com/78446973/129954327-717c9ba2-81a0-4551-bfc1-7f32d68ae4d2.png)
![03 d](https://user-images.githubusercontent.com/78446973/129954332-e6386bff-c5ee-4977-9930-8d3638227cbe.png)
![03 e](https://user-images.githubusercontent.com/78446973/129954334-b7ecb93e-2e0a-42b7-94fd-8b0a4a9b2f95.png)
![03 f](https://user-images.githubusercontent.com/78446973/129954337-87e37f84-1aaf-4c12-97eb-ed99be6787a0.png)
![03 g](https://user-images.githubusercontent.com/78446973/129954340-bba364b0-05f4-4ce3-802c-e7c26f86623f.png)
![04 b 01](https://user-images.githubusercontent.com/78446973/129954346-ba822e43-f853-4ac3-a0d4-c8e3e38ad6c5.png)
![04 b 02](https://user-images.githubusercontent.com/78446973/129954350-9b9bbc2b-56ec-4bc7-8abc-c6ba5769a1e4.png)
![04 c 01](https://user-images.githubusercontent.com/78446973/129954352-87a8c0d4-09cb-4f80-80bb-7092e9c2cc56.png)
![04 c 02](https://user-images.githubusercontent.com/78446973/129954355-76ec9976-cdc1-4ba2-b3e1-4e97dd711fc0.png)
![04 c 03](https://user-images.githubusercontent.com/78446973/129954357-d5a5e286-f2ab-4c4a-9abf-4b7d605750fe.png)
![04 c 04](https://user-images.githubusercontent.com/78446973/129954360-ab874c26-1e47-4025-8929-f1321df0105f.png)

**Comment by SonicDMG** [comment]
Hi there Andrea, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by acmaccan** [comment]
![Scenario Completed](https://user-images.githubusercontent.com/78446973/130276371-9d71b141-1b06-48f0-9a57-5331c9569478.png)

**Comment by acmaccan** [comment]
Hi! Thanks for the feedback. I attach the screenshot here and I add it to
my homework on Github.

Thanks & regards!
Andrea.

**Comment by HadesArchitect** [comment]
Hey **Andrea Maccan**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/e9p3o_UITWSCLeRdqzmgWg

**Comment by SonicDMG** [comment]
Awesome job, thanks for following up.

**Comment by acmaccan** [comment]
Thank youu!

**Comment by acmaccan** [comment]
Thank youu!
