### ISSUE TITLE
[HW] Bhoumik Bhagat

### ISSUE THREAD

**Issue by Bhoumik** [datastaxdevs/workshop-introduction-to-nosql#505]
**Name:** Bhoumik Bhagat
**Email:** bhoumik_bhagat@yahoo.com
**Linkedin Profile:** https://www.linkedin.com/in/bhoumikbhagat/

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/5413515/129954452-7f7fd786-20a8-4653-9b46-0cedb37b81b7.png)

![image](https://user-images.githubusercontent.com/5413515/129954571-daa58670-e987-4348-ac37-f3f837009260.png)

![image](https://user-images.githubusercontent.com/5413515/129955316-618b8c7f-2482-4def-9624-3e116ae5994a.png)

![image](https://user-images.githubusercontent.com/5413515/129955498-a340b672-bf24-4764-b83f-5b63920be867.png)

**Comment by HadesArchitect** [comment]
Hey **Bhoumik Bhagat**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/j11cI4YLRD2L4dw8Rhy0VQ
