### ISSUE TITLE
[HW] KAPIL VARMANI

### ISSUE THREAD

**Issue by kapexhs** [datastaxdevs/workshop-introduction-to-nosql#506]
**Name:** KAPIL VARMANI
**Email:** kapil190887@gmail.com
**Linkedin Profile:** www.linkedin.com/in/kapil-varmani-9694152a

Attach the homework screenshots below:
-----------------------------------------

![CQL_Scenario](https://user-images.githubusercontent.com/1422778/129955676-e642279f-f5bf-40b3-9aab-92b25118c2e5.jpg)
![CQL_1](https://user-images.githubusercontent.com/1422778/129955680-930d5645-189c-44c1-882a-1d9942ab8920.jpg)

**Comment by HadesArchitect** [comment]
Hey **KAPIL VARMANI**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/UC_pHIAZRTSYyVd0Q0Xycw
