### ISSUE TITLE
[HW] <Dhananjaya B.K.>

### ISSUE THREAD

**Issue by DBbigdata** [datastaxdevs/workshop-introduction-to-nosql#508]
**Name:** Dhananjaya B.K.
**Email:** dhananjaya.bk87@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/dhananjaya-bk-8b103b2a/

Attach the homework screenshots below:
-----------------------------------------

1. Create Astra Db Instance
Initial dashboard before creating DB instance.

<img width="1792" alt="Screenshot 2021-08-19 at 1 00 44 AM" src="https://user-images.githubusercontent.com/59349379/129960841-cb4089f5-39bc-4b0b-9ad8-1d8753e9920f.png">

New Database instance - DB_nosql
<img width="1792" alt="Screenshot 2021-08-19 at 1 02 15 AM" src="https://user-images.githubusercontent.com/59349379/129961018-e3df5834-2631-4d70-a188-af0421197572.png">

DB_nosql DB instance in pending status.
<img width="1792" alt="Screenshot 2021-08-19 at 1 03 25 AM" src="https://user-images.githubusercontent.com/59349379/129961198-8f0c317b-cd08-455b-ada4-f89fe53cb995.png">

DB_nosql DB instance in active status.

<img width="1792" alt="Screenshot 2021-08-19 at 1 04 34 AM" src="https://user-images.githubusercontent.com/59349379/129961357-f8ca6173-6583-4e66-ae93-5861efb2bacf.png">
<img width="1792" alt="Screenshot 2021-08-19 at 1 05 01 AM" src="https://user-images.githubusercontent.com/59349379/129961416-37853316-ee13-429b-93b1-f465f01f8395.png">

----------------------------------------------------------------------------------------------------------------
2. Tabular Databases

Describe keyspaces.

<img width="1792" alt="Screenshot 2021-08-19 at 1 09 35 AM" src="https://user-images.githubusercontent.com/59349379/129962002-aeaece06-2378-42e2-9c1f-4f676c322b8d.png">

nosql4 keysapce is displayed, one which we created during DB instance creation.

<img width="1792" alt="Screenshot 2021-08-19 at 1 08 17 AM" src="https://user-images.githubusercontent.com/59349379/129961818-146fb923-5803-4b2d-b42d-d4a891dd9814.png">

Create table videos

<img width="1792" alt="Screenshot 2021-08-19 at 1 14 48 AM" src="https://user-images.githubusercontent.com/59349379/129962634-0be3a42f-8253-4aff-9ed0-b5710d8d32b9.png">

describe keyspace; To understand keyspace and other objects (tables) inside that.
<img width="1792" alt="Screenshot 2021-08-19 at 1 15 53 AM" src="https://user-images.githubusercontent.com/59349379/129962768-26e336d7-e341-42d9-8712-7c200a7bf115.png">

Insert few records and display them.
<img width="1792" alt="Screenshot 2021-08-19 at 1 16 45 AM" src="https://user-images.githubusercontent.com/59349379/129962871-eb93ba27-2d02-42f2-aa12-914e84579ef1.png">

Read based on key of videos enclosed in small braces.
<img width="1792" alt="Screenshot 2021-08-19 at 1 17 25 AM" src="https://user-images.githubusercontent.com/59349379/129962959-fb1c8d95-1e5d-4636-b567-e975326f83dc.png">

Working on partitions, here city is key, where as lastname and email are clustering columns. These cluster columns are also used in ordering. This is done at creating table, so that data will go and reside in memory orderly. Otherwise while displaying table contents we may need write order by clause. Which is bit costlier.
<img width="1792" alt="Screenshot 2021-08-19 at 1 18 39 AM" src="https://user-images.githubusercontent.com/59349379/129963122-00d26696-432e-42f2-b8d8-d8f011d19cc5.png">

INSERT FEW RECORDS. HERE, WE HAVE 2 RECORDS OF PARIS KEY AND 1 FROM OTHER COUNTRY. When we search a record based on key(city) we will get results in quick time.

<img width="1792" alt="Screenshot 2021-08-19 at 1 21 50 AM" src="https://user-images.githubusercontent.com/59349379/129963566-e4d3d127-0ebc-440a-b659-2a9486b1b9ad.png">

3. Document Databases
We can insert json data (format) into cassandra table. Also, we can read data in json format.
<img width="1792" alt="Screenshot 2021-08-19 at 1 24 55 AM" src="https://user-images.githubusercontent.com/59349379/129963958-06b2686b-60e5-4bf1-8212-aa07bf641359.png">

4. Create application token
<img width="1792" alt="Screenshot 2021-08-19 at 1 27 18 AM" src="https://user-images.githubusercontent.com/59349379/129964233-133ad17e-da34-44d4-aa09-8aa45029a8a4.png">
<img width="1792" alt="Screenshot 2021-08-19 at 1 28 12 AM" src="https://user-images.githubusercontent.com/59349379/129964332-0fdebf22-ffa4-4664-a789-b2c77b470b60.png">

Locate swagger URL:
<img width="1792" alt="Screenshot 2021-08-19 at 1 30 26 AM" src="https://user-images.githubusercontent.com/59349379/129964633-7a0d2f1a-14a2-466e-a07e-77897f69e319.png">

<img width="1792" alt="Screenshot 2021-08-19 at 1 30 36 AM" src="https://user-images.githubusercontent.com/59349379/129964649-005bf2ee-2563-4360-86ad-fd7f6c1b1059.png">

Create a new empty collection 
<img width="1792" alt="Screenshot 2021-08-19 at 1 33 00 AM" src="https://user-images.githubusercontent.com/59349379/129964938-f9c3b057-a4b4-4af7-8946-a2a3d0014b8a.png">

Creating new document
<img width="1792" alt="Screenshot 2021-08-19 at 1 35 38 AM" src="https://user-images.githubusercontent.com/59349379/129965250-28a8abc4-b0a9-4b9b-8363-d034047f01ba.png">

document id created, as we should shared token keys, not sharing screen shots here.

 Find all documents of a collection
<img width="1792" alt="Screenshot 2021-08-19 at 1 45 39 AM" src="https://user-images.githubusercontent.com/59349379/129966451-6a45e5ba-622f-4212-8f94-81cc9235f35c.png">

find document based on auto generated document id.
This is document id created earlier:
{
  "documentId": "e6945521-db00-4f7d-adfe-d82c5860654e"
}
Now use this document_id to get documents
<img width="1792" alt="Screenshot 2021-08-19 at 1 48 12 AM" src="https://user-images.githubusercontent.com/59349379/129966846-7b615cac-d6a0-457c-b082-5585298fa841.png">

Incase, if we don't have document id then use where clause to get the required document.
<img width="1792" alt="Screenshot 2021-08-19 at 1 50 07 AM" src="https://user-images.githubusercontent.com/59349379/129967107-e0f3c10a-c14b-4cad-88fa-59f7c13e0d45.png">

4. KeyValue Databases

Create a table with GraphQL

<img width="1792" alt="Screenshot 2021-08-19 at 1 53 01 AM" src="https://user-images.githubusercontent.com/59349379/129967534-b808acec-8eee-467c-add3-43f4fdc2b922.png">

<img width="1792" alt="Screenshot 2021-08-19 at 1 54 17 AM" src="https://user-images.githubusercontent.com/59349379/129967703-11682b93-f107-41a8-a814-b38db6a87377.png">

we are creating a table we want to use the graphql-schema tab
<img width="1792" alt="Screenshot 2021-08-19 at 1 55 26 AM" src="https://user-images.githubusercontent.com/59349379/129967845-55afb01e-f64b-458d-b1b2-1fae24eb2f21.png">

use key and describe table

<img width="1792" alt="Screenshot 2021-08-19 at 1 57 05 AM" src="https://user-images.githubusercontent.com/59349379/129968077-32a5b10d-16c5-4415-9e6b-c2cf72d6c162.png">

insert data and verify
<img width="1792" alt="Screenshot 2021-08-19 at 1 59 55 AM" src="https://user-images.githubusercontent.com/59349379/129968404-d7e10b54-7fee-43df-8e8d-ae62aae83760.png">

check data inserted in previous step in cqlsh;
<img width="1792" alt="Screenshot 2021-08-19 at 2 01 04 AM" src="https://user-images.githubusercontent.com/59349379/129968559-94ae2bc6-012c-4119-af5f-b29d7f7d8386.png">

Update keys and check in cqlsh:
<img width="1792" alt="Screenshot 2021-08-19 at 2 02 55 AM" src="https://user-images.githubusercontent.com/59349379/129968786-841cf510-c601-4892-9ad8-d6760d0ad42f.png">

<img width="1792" alt="Screenshot 2021-08-19 at 2 03 40 AM" src="https://user-images.githubusercontent.com/59349379/129968867-4bad893f-f51e-47f1-be21-211f1f6de862.png">

Base on the communication, I have shared all the screenshots for topics 1 to 4.

-------2nd assignment-----

1. create keyspace demo
<img width="1792" alt="Screenshot 2021-08-21 at 3 34 11 PM" src="https://user-images.githubusercontent.com/59349379/130318456-9767ee9f-f78a-4ae0-a178-fb7c3d651d22.png">

<img width="1792" alt="Screenshot 2021-08-21 at 3 34 32 PM" src="https://user-images.githubusercontent.com/59349379/130318460-10cc2919-10dc-42e9-8e0b-a53e57db6462.png">
<img width="1792" alt="Screenshot 2021-08-21 at 3 35 45 PM" src="https://user-images.githubusercontent.com/59349379/130318491-b8f3d18a-a366-442b-9579-03b10cb473a9.png">

<img width="1792" alt="Screenshot 2021-08-21 at 3 37 37 PM" src="https://user-images.githubusercontent.com/59349379/130318534-b67f1318-f83f-4306-8aa5-2b76491702d2.png">

Update row:

<img width="1792" alt="Screenshot 2021-08-21 at 3 39 07 PM" src="https://user-images.githubusercontent.com/59349379/130318569-0240fa84-f1e8-4263-978b-8139f81fb4be.png">

delete user

<img width="1792" alt="Screenshot 2021-08-21 at 3 39 29 PM" src="https://user-images.githubusercontent.com/59349379/130318577-9c6c0edb-e275-427f-b383-7164a68c2bf0.png">

Completion evidence:
<img width="1792" alt="Screenshot 2021-08-21 at 3 39 48 PM" src="https://user-images.githubusercontent.com/59349379/130318582-1c7e077b-b970-4f0c-93cd-d7d7a9fed64c.png">

**Comment by SonicDMG** [comment]
Hi there Dhananjaya, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by DBbigdata** [comment]
@SonicDMG Thank you for letting me know. I have completed the try-it-out scenario as communicated earlier.
Please review and let me know if any thing missing here.

Thanks,
Dhananjaya
