### ISSUE TITLE
[HW] Christian Vidal

### ISSUE THREAD

**Issue by ChrisVidal10** [datastaxdevs/workshop-introduction-to-nosql#509]
**Name:** Christian Vidal
**Email:** chris.vidal10@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/vidalchristian/

Attach the homework screenshots below:
-----------------------------------------

<img width="1346" alt="Screen Shot 2021-08-18 at 18 45 35" src="https://user-images.githubusercontent.com/9323867/129976589-6ba8736c-38d6-4dcc-bb2e-8529884ac259.png">
<img width="1144" alt="Screen Shot 2021-08-18 at 18 42 34" src="https://user-images.githubusercontent.com/9323867/129976593-1117843b-28a2-49f6-98e3-2296c6cd7d27.png">
<img width="1316" alt="Screen Shot 2021-08-18 at 18 42 15" src="https://user-images.githubusercontent.com/9323867/129976598-a5bdd747-f960-4acc-8b8d-31a21035ebf3.png">
<img width="1380" alt="Screen Shot 2021-08-18 at 18 42 05" src="https://user-images.githubusercontent.com/9323867/129976600-f6b573af-5ff0-4650-af4f-5c526e065908.png">

**Comment by HadesArchitect** [comment]
Hey **Christian Vidal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/n9VFMiauQBu6SlkyB4FlOA
