### ISSUE TITLE
[HW] Prafull Kotecha

### ISSUE THREAD

**Issue by prafullkotecha** [datastaxdevs/workshop-introduction-to-nosql#51]
**Name:** Prafull Kotecha
**Email:** prafull@direkshan.digital
**Linkedin Profile:** https://www.linkedin.com/in/prafullkotecha

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/563146/118874468-f4791000-b8b8-11eb-8ff9-684cc22dc528.png)

![image](https://user-images.githubusercontent.com/563146/118874490-fa6ef100-b8b8-11eb-872b-c7be69bd61b5.png)

![image](https://user-images.githubusercontent.com/563146/118874499-fcd14b00-b8b8-11eb-9c6f-2f78a86fcabf.png)

![image](https://user-images.githubusercontent.com/563146/118874517-0064d200-b8b9-11eb-965d-f6e15b04c37c.png)

![image](https://user-images.githubusercontent.com/563146/118874530-035fc280-b8b9-11eb-9d73-6acd39243eb8.png)

![image](https://user-images.githubusercontent.com/563146/118874905-6d786780-b8b9-11eb-96ff-203362724ece.png)

![image](https://user-images.githubusercontent.com/563146/118874919-710bee80-b8b9-11eb-9dae-19b44b52ffb3.png)

![image](https://user-images.githubusercontent.com/563146/118874967-808b3780-b8b9-11eb-8150-029d66ebcf21.png)

![image](https://user-images.githubusercontent.com/563146/118875082-a0226000-b8b9-11eb-832f-d89762a5141e.png)

![image](https://user-images.githubusercontent.com/563146/118875098-a3b5e700-b8b9-11eb-9528-d43a1b5a35c1.png)

![image](https://user-images.githubusercontent.com/563146/118875111-a7496e00-b8b9-11eb-833a-a71ca8e5d5b8.png)

**Comment by SonicDMG** [comment]
Nice job Prafull, thank you.

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/Tu7lpyTRTPuUsSCkC6187w?identity__email=prafull%40direkshan.digital

**Comment by prafullkotecha** [comment]
Thank you! This has been a great learning experience. Looking forward to finishing to tik-tok clone soon.
