### ISSUE TITLE
[HW] Manav

### ISSUE THREAD

**Issue by manavjindal** [datastaxdevs/workshop-introduction-to-nosql#510]
**Name:** Manav
**Email:** er.manav.jindal@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/manavjindal/

Attach the homework screenshots below:
-----------------------------------------

![Chapter4](https://user-images.githubusercontent.com/13215135/129982475-4850fec8-c29a-468e-9217-6495e3303b4c.JPG)
![scenarioCompleted](https://user-images.githubusercontent.com/13215135/129982500-0033fe17-1a7f-423f-b685-43ef8dc7d343.JPG)

**Comment by manavjindal** [comment]
Thanks for the very informative session today.

**Comment by HadesArchitect** [comment]
Hey **Manav**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/baDMKDH5QiCEFgwGAGhd_g
