### ISSUE TITLE
[HW] <Omar Jonathan Ramírez Díaz>

### ISSUE THREAD

**Issue by oramirezd92** [datastaxdevs/workshop-introduction-to-nosql#511]
**Name:** Omar Jonathan Ramírez Díaz
**Email:** oramirezd92@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/oramirezd92/>

Attach the homework screenshots below:
-----------------------------------------

![Step I](https://user-images.githubusercontent.com/89171421/129991618-a6eda5de-1e49-425b-99ce-def48b83990d.png)

![Step II](https://user-images.githubusercontent.com/89171421/129991628-1dd91059-f97d-4874-8155-90490c4cfff6.png)

![Step III](https://user-images.githubusercontent.com/89171421/129991641-5e5ad3d5-4aab-45bc-a815-52696775129c.png)

![Step IV (1)](https://user-images.githubusercontent.com/89171421/129991652-3a2620ee-cd5e-4ef4-ace1-c4c61ee24265.png)

![Step IV (2)](https://user-images.githubusercontent.com/89171421/129991661-5d5e1a65-f2d9-47a9-aa3d-da6ffd5e71ba.png)

![Try-out scenario](https://user-images.githubusercontent.com/89171421/129991681-3c97cbfa-e340-48b4-a3e8-724a407ec0b1.JPG)

Greetings!

**Comment by HadesArchitect** [comment]
Hey **Omar Jonathan Ramírez Díaz**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Es6GMCPISkC68k73qm2RVg
