### ISSUE TITLE
[HW] <Introduction to NoSQL Databases>

### ISSUE THREAD

**Issue by LuizPauloMolina** [datastaxdevs/workshop-introduction-to-nosql#512]
**Name:** Luiz Paulo Molina Alvaro
**Email:** paulo.molina1982@gmail.com
**Linkedin Profile:** <www.linkedin.com/in/luizpaulomolina>

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/79719743/130000806-917da768-8c8a-4418-9f27-c3929751cbdb.png)
![image](https://user-images.githubusercontent.com/79719743/130000848-7655d2f0-f435-4a90-81ea-3f2da8ea8529.png)
![image](https://user-images.githubusercontent.com/79719743/130000904-5dccbcf5-efe1-4efa-b211-d2f8f0332bf3.png)
![image](https://user-images.githubusercontent.com/79719743/130000957-62afa733-840b-46e9-bd78-936339a44efc.png)
![image](https://user-images.githubusercontent.com/79719743/130000987-8a90efe4-9de4-40ad-b3cc-aee896e16e87.png)
![image](https://user-images.githubusercontent.com/79719743/130001009-4edc437a-dcaf-4920-ae4a-1d203ad7ed9b.png)
![image](https://user-images.githubusercontent.com/79719743/130001037-a14bd030-1b2c-4321-85fd-578e945fe88f.png)
![image](https://user-images.githubusercontent.com/79719743/130001073-d2ddd122-aee0-4839-bb03-b17dae534ba6.png)
![image](https://user-images.githubusercontent.com/79719743/130001154-23e914ad-07d8-40a4-8daa-48aa6fc76050.png)
![image](https://user-images.githubusercontent.com/79719743/130001185-09ff7a28-d01e-45a9-96b1-81cf68708666.png)
![image](https://user-images.githubusercontent.com/79719743/130001208-9a2cdd4a-c10b-4b10-9027-909d075dd1ee.png)
![image](https://user-images.githubusercontent.com/79719743/130001620-3df655f4-3b4b-4564-9419-07e52fb03664.png)

**Comment by HadesArchitect** [comment]
Hey **Luiz Paulo Molina Alvaro**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ivwOWcXZSB-SQiUvnvH1xw
