### ISSUE TITLE
[HW] CHINMAYA NAIK

### ISSUE THREAD

**Issue by chinmayakain** [datastaxdevs/workshop-introduction-to-nosql#516]
**Name:** Chinmaya Naik
**Email:** chinmaynaik.009@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/chinmaya-naik-20a35b153/>

Attach the homework screenshots below:
-----------------------------------------
![Screenshot (108)](https://user-images.githubusercontent.com/52573685/130030315-f0633c76-7061-4343-807a-25c4cb11cb72.png)
![Screenshot (109)](https://user-images.githubusercontent.com/52573685/130030318-04a59fac-ab63-4cc6-bcfc-334082066ef6.png)
![Screenshot (110)](https://user-images.githubusercontent.com/52573685/130030324-279afc5f-8930-4df9-9823-3ead845ca885.png)
![Screenshot (111)](https://user-images.githubusercontent.com/52573685/130030327-92e44171-db40-4672-bf9d-24820042f838.png)
![Screenshot (112)](https://user-images.githubusercontent.com/52573685/130030339-259e6a38-f033-4683-89c1-9df47eb96942.png)
![Screenshot (113)](https://user-images.githubusercontent.com/52573685/130030351-5e9ead78-2a3b-40a0-9568-efde411cbab0.png)
![Screenshot (114)](https://user-images.githubusercontent.com/52573685/130030368-801ce17e-d981-48a0-92b9-97e0aba81a5d.png)
![Screenshot (115)](https://user-images.githubusercontent.com/52573685/130030371-581be767-75a3-4e02-a2aa-513458b3d426.png)
![Screenshot (116)](https://user-images.githubusercontent.com/52573685/130030374-4771d67d-8db6-4e65-8b49-9bb256f8c52e.png)
![Screenshot (117)](https://user-images.githubusercontent.com/52573685/130030382-d628feb0-7aec-4996-91f0-ce7920187a2d.png)
![Screenshot (118)](https://user-images.githubusercontent.com/52573685/130030386-3f239405-d735-46df-aad7-7d686d471c11.png)
![Screenshot (119)](https://user-images.githubusercontent.com/52573685/130030393-009e9bcf-dde7-4dbf-839a-bf366f4853da.png)
![Screenshot (120)](https://user-images.githubusercontent.com/52573685/130030395-edf6ca1f-80f4-48a4-884b-c39bc617134f.png)
![Screenshot (121)](https://user-images.githubusercontent.com/52573685/130030401-1896cee5-0b74-4a87-99d7-aba9dc060905.png)
![Screenshot (122)](https://user-images.githubusercontent.com/52573685/130030403-599c6995-f422-467f-a1c7-73230e4900e5.png)

**Comment by HadesArchitect** [comment]
Hey **Chinmaya Naik**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/HplZlOxTS5aXH_Jn59Q2xw
