### ISSUE TITLE
[HW] Introduction to NotOnly SQL Databases

### ISSUE THREAD

**Issue by renlips** [datastaxdevs/workshop-introduction-to-nosql#517]
**Name:** Anton Osipov
**Email:** osipov.anton@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/anton-osipov-1ba98764/

Attach the homework screenshots below:
-----------------------------------------
![Screenshot 2021-08-19 at 10 57 25](https://user-images.githubusercontent.com/40640036/130034287-fe747c24-2742-4f42-8f4a-6403b0a2990e.png)
![Screenshot 2021-08-19 at 11 08 20](https://user-images.githubusercontent.com/40640036/130034417-ceebd353-35ef-45d7-a1c7-cca8e89e75b7.png)
![Screenshot 2021-08-19 at 11 13 26](https://user-images.githubusercontent.com/40640036/130034453-e5b97f6c-431b-4449-bce4-53b02bb215ad.png)
![Screenshot 2021-08-19 at 11 17 43](https://user-images.githubusercontent.com/40640036/130034506-ba02c84c-098d-4426-bbbf-fbaaa694315d.png)
![Screenshot 2021-08-19 at 11 18 30](https://user-images.githubusercontent.com/40640036/130034537-f3943129-4428-4db6-8ce1-76d24760b5ce.png)

**Comment by HadesArchitect** [comment]
Hey **Anton Osipov**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/-0JxMqGVSm66dsvTWPCBPQ
