### ISSUE TITLE
[HW: Introduction to NoSQL Database] <ANGELO RIZZO>

### ISSUE THREAD

**Issue by AngeloR94** [datastaxdevs/workshop-introduction-to-nosql#518]
**Name:** ANGELO RIZZO
**Email:** angelor1220@hotmail.it
**Linkedin Profile:** <https://www.linkedin.com/in/angelo-rizzo-a547a1168/>

Attach the homework screenshots below:
-----------------------------------------

![graphqlschema_mod](https://user-images.githubusercontent.com/83451606/130037721-9abc9557-76af-4216-bd6b-c1f29c818bbc.jpg)

![graphql__mod](https://user-images.githubusercontent.com/83451606/130037753-1a1d9332-38fa-4780-8f3f-0de7e090ff9d.jpg)

![nosql_db_console](https://user-images.githubusercontent.com/83451606/130037804-47ec37e2-79fe-4485-9e74-d7f03027c88e.jpg)

![tryout_scenario](https://user-images.githubusercontent.com/83451606/130037834-3d358d82-e9cf-4e92-b2cb-3098de7dc4e6.jpg)

**Comment by HadesArchitect** [comment]
Hey **ANGELO RIZZO**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Xusf5IICQceTigIwS48i_Q
