### ISSUE TITLE
[HW] <HANDE SHRADDHA SURESH>

### ISSUE THREAD

**Issue by Shambo-hub** [datastaxdevs/workshop-introduction-to-nosql#519]
**Name:** HANDE SHRADDHA SURESH
**Email:** hande.shraddha95@gmail.com
**Linkedin Profile:** <linkedin.com/in/hande-shraddha-suresh-98112412b>

Attach the homework screenshots below:
-----------------------------------------

![Excersice_4_Playground](https://user-images.githubusercontent.com/71425578/130056013-4088119a-275a-49eb-b80c-516abeb16eb3.jpg)
![Excersice_4_Output](https://user-images.githubusercontent.com/71425578/130056079-f105ee73-76ab-4149-a6a0-471f7574bf93.jpg)
![Try_it_Out](https://user-images.githubusercontent.com/71425578/130056111-08c47a33-eb6f-4411-9c6e-959ddbb98288.png)

**Comment by HadesArchitect** [comment]
Hey **HANDE SHRADDHA SURESH**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/D3_o3006QwqQ9QigIdmRRg
