### ISSUE TITLE
[HW] <Kumar RS>

### ISSUE THREAD

**Issue by kumarrs30** [datastaxdevs/workshop-introduction-to-nosql#52]
**Name:** Kumar RS
**Email:** kumarrs30@gmail.com

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/65746989/118875987-56ae3100-b90a-11eb-94e4-8e94e18d99ce.png)
![image](https://user-images.githubusercontent.com/65746989/118876004-5ca41200-b90a-11eb-9574-eb51be7fec92.png)
![image](https://user-images.githubusercontent.com/65746989/118876016-6299f300-b90a-11eb-87db-bf5a676944f5.png)
![image](https://user-images.githubusercontent.com/65746989/118876049-6e85b500-b90a-11eb-97a7-cd8943413f7f.png)
![image](https://user-images.githubusercontent.com/65746989/118876077-747b9600-b90a-11eb-8e4a-274c0b188977.png)

**Comment by SonicDMG** [comment]
Awesome Kumar, thank you.

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/TMPDYEgaTG6xIBZCXtPD4g?identity__email=kumarrs30%40gmail.com
