### ISSUE TITLE
[HW] <Mohit Tiwari>

### ISSUE THREAD

**Issue by mohittiwari1925** [datastaxdevs/workshop-introduction-to-nosql#520]
**Name:** Mohit Tiwari
**Email:** MohitTiwari1925@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/mohit-tiwari-7a889510a/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![image][](https://user-images.githubusercontent.com/83041089/130059208-cd94d37d-68f4-423e-904d-cbba6340ed8e.png)
![image][](https://user-images.githubusercontent.com/83041089/130059517-4909051b-d879-4ea3-b355-1ee62e6edead.png)
![image][](https://user-images.githubusercontent.com/83041089/130059968-bdacb362-3f97-4da6-95b9-796aa1ae56e7.png)
![image][](https://user-images.githubusercontent.com/83041089/130058968-8258f14c-8714-4fc4-98b1-e265a21706b8.png)

**Comment by SonicDMG** [comment]
Hi there Mohit, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by mohittiwari1925** [comment]
![image](https://user-images.githubusercontent.com/83041089/130261639-d627dc55-630f-4095-b8ab-f1c4325fae9e.png)
![image](https://user-images.githubusercontent.com/83041089/130261721-280e9ffa-83b7-445a-9b5f-4dd56a67fd09.png)
![image](https://user-images.githubusercontent.com/83041089/130261788-c547e1e4-46a0-479d-aea2-0d124e38315b.png)
**Please check my improved content which was missing.
Thank you**

**Comment by HadesArchitect** [comment]
Hey **Mohit Tiwari**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/HDkalr4DQJGq3qMJEVWBWA
