### ISSUE TITLE
[HW] <Reehana>

### ISSUE THREAD

**Issue by reehana** [datastaxdevs/workshop-introduction-to-nosql#522]
**Name:** Reehana A
**Email:** 786.reehana@gmail.com
**Linkedin Profile:** https://www.linkedin.com/mwlite/in/reehana-reeha-57424312b

Attach the homework screenshots below:
-----------------------------------------

![Capture1](https://user-images.githubusercontent.com/27013952/130067208-fed5169a-7ceb-4ea1-9044-7d6a77709002.PNG)
![Capture2](https://user-images.githubusercontent.com/27013952/130067214-bfcfbcd3-03c7-410d-a93b-d36c7c140548.PNG)
![Capture3](https://user-images.githubusercontent.com/27013952/130067217-a231f6f0-d97e-4923-8579-5b4d5b418d48.PNG)
![nosql_hw](https://user-images.githubusercontent.com/27013952/130067220-b58e3eea-7d21-4104-b0ff-2efc7e495726.PNG)

**Comment by HadesArchitect** [comment]
Hey **Reehana A**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/C5C_5JK-TpyTC4va_HHc1A
