### ISSUE TITLE
[HW] <ARIJIT ADHIKARY>

### ISSUE THREAD

**Issue by ArijitGuru** [datastaxdevs/workshop-introduction-to-nosql#523]
**Name: ** ARIJIT ADHIKARY
**Email:**  arijitadhikary@gmail.com
**LinkedIn Profile:**  https://www.linkedin.com/in/arijit-adhikary-cse/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Try-it-out-completion](https://user-images.githubusercontent.com/38171476/130075985-b55b11e9-927b-464b-bd44-dc05a9de0b2a.png)
![Step IV_1](https://user-images.githubusercontent.com/38171476/130075990-d5e541ee-4987-482b-970f-05bf3ae0a05e.png)
![Step IV_2](https://user-images.githubusercontent.com/38171476/130075991-d5f47f51-e170-48f5-bf76-9669b1caa728.png)
![Step IV_3](https://user-images.githubusercontent.com/38171476/130075992-0a9874cb-ef7a-4144-a093-b2a5f47d159f.png)

**Comment by HadesArchitect** [comment]
Hey **ARIJIT ADHIKARY**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/76AZA7jMSl2zdSDrR5oA-g
