### ISSUE TITLE
[HW] HARSHIT AGARWAL

### ISSUE THREAD

**Issue by harshu0808** [datastaxdevs/workshop-introduction-to-nosql#524]
**Name:** Harshit Agarwal
**Email:** harshit_agarwal08@yahoo.com
**Linkedin Profile:** https://in.linkedin.com/in/harshitagarwal08

Attach the homework screenshots below:
-----------------------------------------
1. Created database 'nosql_db'
![image](https://user-images.githubusercontent.com/46245565/130082976-f2a1458a-5253-4da5-b4cd-a910a138aca9.png)

2. Created tables and data (Tabular DBs)
![image](https://user-images.githubusercontent.com/46245565/130084243-f0e80078-0bba-4242-842e-10bed832342f.png)
![image](https://user-images.githubusercontent.com/46245565/130084345-ab6705bb-a45d-4f64-a043-826fd0a38b08.png)
![image](https://user-images.githubusercontent.com/46245565/130084441-6a32723a-d9a8-4c4b-8f99-a2421319fbb2.png)
![image](https://user-images.githubusercontent.com/46245565/130084605-2576fa73-58f0-4c2c-8c9f-286bb441c9e0.png)
![image](https://user-images.githubusercontent.com/46245565/130084664-203083b7-5698-4875-b511-db3b8e3daa2f.png)

3. Retrieve Data (Tabular DBs)
![image](https://user-images.githubusercontent.com/46245565/130085124-07b83ffa-eb33-461c-987b-66a947ac1b5c.png)
![image](https://user-images.githubusercontent.com/46245565/130085285-959ac05b-78ad-4188-ad5e-4300e50c27e9.png)

4. Retrieve data in JSON format (Document DBs)
![image](https://user-images.githubusercontent.com/46245565/130085710-86d72aae-3802-46b7-8c61-ec1ade82fa84.png)

5. Swagger API:
![image](https://user-images.githubusercontent.com/46245565/130086463-c96555c0-a354-449a-b870-3660b93fce3a.png)

6. Create Document via Swagger:
Input:
![image](https://user-images.githubusercontent.com/46245565/130087096-3386328d-a8e2-4760-aa98-1e664ed5113c.png)

Output:
![image](https://user-images.githubusercontent.com/46245565/130087348-9e256ca4-7273-4704-83f1-7cf758ae99c5.png)

7. Search Document via Swagger:
Input:
![image](https://user-images.githubusercontent.com/46245565/130087763-ae4b1d41-4ace-4628-8511-acd14c13b61e.png)

Output:
![image](https://user-images.githubusercontent.com/46245565/130088120-61c2c05c-cf3e-4e72-958b-5d0eceb7c874.png)

8. Get a document via Swagger:
Input:
![image](https://user-images.githubusercontent.com/46245565/130088386-5c21dc03-d2d8-4e20-9095-1bf8e4afa364.png)

Output:
![image](https://user-images.githubusercontent.com/46245565/130088844-ee8f0e20-9ab6-40cf-92bf-7f166633a27e.png)

9. GraphQL (KeyValue DBs):
Create Table:
![image](https://user-images.githubusercontent.com/46245565/130089993-7f5c6567-e642-474d-8279-ea572d545d8c.png)
![image](https://user-images.githubusercontent.com/46245565/130090439-3543ec65-e6bf-4da7-a65b-0583dd7046c2.png)

Insert Data:
![image](https://user-images.githubusercontent.com/46245565/130090963-582da887-86ee-4df4-b74a-ff701aefd8fd.png)
![image](https://user-images.githubusercontent.com/46245565/130091172-65198b2b-4fdf-4f4c-bb67-7165071e51e8.png)

Update Data:
![image](https://user-images.githubusercontent.com/46245565/130091388-0dd211a3-2271-40d0-a04b-7c669cd1450f.png)
![image](https://user-images.githubusercontent.com/46245565/130091496-66cd9b44-e22a-45a7-bf4f-be511d24e9dc.png)

10. TRY-IT-OUT:
![image](https://user-images.githubusercontent.com/46245565/130092478-ef514644-7c2f-48a1-a53d-e07c0c9160e3.png)

**Comment by HadesArchitect** [comment]
Hey **Harshit Agarwal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/aA5TbHalSRGt0jb6LW5FbQ
