### ISSUE TITLE
[HW] <NOSQL - Rayner Robles J>

### ISSUE THREAD

**Issue by raybro27** [datastaxdevs/workshop-introduction-to-nosql#525]
**Name:** Rayner Robles Jiménez
**Email:** raybro27@hotmail.com
**Linkedin Profile:** <https://cr.linkedin.com/in/rayner-robles

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![noSQL part 4](https://user-images.githubusercontent.com/66093714/130092057-b375786f-30d3-4fb3-bc36-408422d4c309.PNG)
![Casandras Nosql](https://user-images.githubusercontent.com/66093714/130092128-62ef612c-c86f-4b98-9b7e-ac9e7054310c.PNG)
>

**Comment by HadesArchitect** [comment]
Hey **Rayner Robles Jiménez**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/-ZnVMljbSSOGRZ73ijKzSA
