### ISSUE TITLE
[HW] Vishal Gour

### ISSUE THREAD

**Issue by Vishalgour440** [datastaxdevs/workshop-introduction-to-nosql#526]
**Name:** Vishal Gour
**Email:**  vishalgour.440@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/vishal-gour-28711a56/
<img width="689" alt="Step4" src="https://user-images.githubusercontent.com/89213836/130114083-20f455d8-0bca-4f0b-ade0-76f6be86c2ca.PNG">
<img width="674" alt="TryOut" src="https://user-images.githubusercontent.com/89213836/130114112-36205b80-c6bb-4752-8b58-4e5e27d54bfb.PNG">
<img width="664" alt="console" src="https://user-images.githubusercontent.com/89213836/130114186-9edede9b-3802-4fe3-a3a3-35f4e55edaf3.PNG">

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Vishal Gour**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/zz-djG7pQbG72lrzyUljdQ
