### ISSUE TITLE
[HW] <Eleftherios Nikolaou>

### ISSUE THREAD

**Issue by EleftheriosNikolaou** [datastaxdevs/workshop-introduction-to-nosql#527]
**Name:** Eleftherios Nikolaou
**Email:** nikolaou.eleftherios@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/nikolaoueleftherios/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![NoSQL - Eleftherios Nikolaou](https://user-images.githubusercontent.com/38458208/130107367-23bf8837-a16e-487e-867c-435cd4c8afea.jpg)
![NoSQL - Eleftherios Nikolaou 2](https://user-images.githubusercontent.com/38458208/130114251-15191a92-0ed3-43ed-b604-880cf2f9d28a.jpg)

**Comment by HadesArchitect** [comment]
Hey **Eleftherios Nikolaou**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/hnTmfWPiRamEsI6dzb9Xjw
