### ISSUE TITLE
[HW] <NoSQL Workshop>

### ISSUE THREAD

**Issue by giornn0** [datastaxdevs/workshop-introduction-to-nosql#528]
**Name:** Muhammad Ali Rigol
**Email:** shaaamsuu@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/ali-rigol-78906520a>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
-- image removed by team --
![Screenshot from 2021-08-19 14-12-57](https://user-images.githubusercontent.com/79057078/130114321-e71dd92f-79e5-45d9-a9ea-2858082b08d2.png)
![Screenshot from 2021-08-19 14-12-36](https://user-images.githubusercontent.com/79057078/130114322-8a174768-270d-4a5b-bed2-449a604e64fd.png)

**Comment by SonicDMG** [comment]
Hi there Muhammad, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by SonicDMG** [comment]
Also, I had to remove one of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.

**Comment by giornn0** [comment]
Hi, oh i didnt see the token my bad, thanks, i upload the screeshots from the scenario completed. 
![Screenshot from 2021-08-22 15-01-20](https://user-images.githubusercontent.com/79057078/130365357-597fe6c2-d40e-4eee-be1e-fc68f722b7e8.png)
![Screenshot from 2021-08-22 15-00-28](https://user-images.githubusercontent.com/79057078/130365359-492aff98-b824-46ac-97d1-8876ab4d21a5.png)
