### ISSUE TITLE
[HW] Pankaj Pramil Narkhede

### ISSUE THREAD

**Issue by narkhedep11** [datastaxdevs/workshop-introduction-to-nosql#529]
Name : Pankaj Narkhede
Email : narkhedep11@gmail.com
Linkedin Profile : https://www.linkedin.com/in/pankaj-narkhede-8616ba117/

Attach the homework screenshots below:
-----------------------------------------

![try_it_out_CQL](https://user-images.githubusercontent.com/32532538/130114432-04463ee2-bbeb-48ac-9f00-de1f312f7f03.PNG)
![db](https://user-images.githubusercontent.com/32532538/130114504-67ba6f1a-e8de-4d36-a1a0-eedb98b5ce35.PNG)

**Comment by HadesArchitect** [comment]
Hey **Pankaj Narkhede**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/aIQN4H2qREajJgJlcq_nag
