### ISSUE TITLE
[HW] Sivagurunathan Venkatachalapathy

### ISSUE THREAD

**Issue by vsgurunath** [datastaxdevs/workshop-introduction-to-nosql#53]
**Name:** Sivagurunathan Venkatachalapathy
**Email:** v.sivagurunathan@hotmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sivagurunathan-v-32439332/

Attach the homework screenshots below:
-----------------------------------------

![tracing](https://user-images.githubusercontent.com/16850708/118880221-40ef3a80-b90f-11eb-966c-0adb92db13bd.png)
![json](https://user-images.githubusercontent.com/16850708/118880227-42b8fe00-b90f-11eb-974b-c85c1281a4b6.png)
![docker1](https://user-images.githubusercontent.com/16850708/118880258-48164880-b90f-11eb-8b32-55bd4df5c4a9.png)
-- images removed by team --
![docker2](https://user-images.githubusercontent.com/16850708/118880256-477db200-b90f-11eb-9af6-fbd48400afa6.png)
-- images removed by team --
![CQL try it out](https://user-images.githubusercontent.com/16850708/118939580-7591df00-b96d-11eb-9149-0d74a292dd5b.png)

**Comment by SonicDMG** [comment]
Looks good Sivagurunathan, thank you.

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/uk-uzEadQbSk0_HM8NCKzw?identity__email=v.sivagurunathan%40hotmail.com
