### ISSUE TITLE
[HW] Ramesh Krishnamurthy

### ISSUE THREAD

**Issue by rameshk9099** [datastaxdevs/workshop-introduction-to-nosql#530]
**Name:** Ramesh Krishnamurthy
**Email:** rameshk79@gmail.com
**Linkedin Profile:** www.linkedin.com/in/ramesh-krishnamurthy-6600

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![completed](https://user-images.githubusercontent.com/46564866/130114677-268a875f-6511-46ba-ac5e-64fc97d88878.jpg)
![completed_1](https://user-images.githubusercontent.com/46564866/130114689-e082d348-7985-4a6d-acfc-f1a5d7db8672.jpg)

**Comment by SonicDMG** [comment]
Hi there Ramesh, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by rameshk9099** [comment]
Hi David,

I had completed the missing step. Please let me know if this is sufficient.

***@***.***

Thanks & Regards;
Ramesh Krishnamurthy

From: David Jones-Gilardi ***@***.***
Sent: Friday, August 20, 2021 8:51 PM
To: datastaxdevs/workshop-introduction-to-nosql ***@***.***>
Cc: Krishnamurthy, Ramesh ***@***.***>; Author ***@***.***>
Subject: [External] - Re: [datastaxdevs/workshop-introduction-to-nosql] [HW] Ramesh Krishnamurthy (#530)

This email is from an external source.  Use caution responding to it, opening attachments or clicking links.


Hi there Ramesh, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete try-it-out scenario<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.datastax.com%2Ftry-it-out&data=04%7C01%7Cramesh.krishnamurthy%40conduent.com%7C33413918bc1743b9c0c908d963ee2248%7C1aed4588b8ce43a8a775989538fd30d8%7C0%7C0%7C637650697596613528%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lyi8IgrqHGxlT84JIKJqdTvvnKXiJzKpSgHv1AObHzs%3D&reserved=0> and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdatastaxdevs%2Fworkshop-introduction-to-nosql%2Fissues%2F530%23issuecomment-902770153&data=04%7C01%7Cramesh.krishnamurthy%40conduent.com%7C33413918bc1743b9c0c908d963ee2248%7C1aed4588b8ce43a8a775989538fd30d8%7C0%7C0%7C637650697596623483%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=v79uH6rIUeSC2b87LbxjY1IjS%2BcVVgN2Y9mSDqx%2FuNg%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALDIMAVRQ6AYKOE4SSK73ZTT5ZXGBANCNFSM5COVJJ6A&data=04%7C01%7Cramesh.krishnamurthy%40conduent.com%7C33413918bc1743b9c0c908d963ee2248%7C1aed4588b8ce43a8a775989538fd30d8%7C0%7C0%7C637650697596623483%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fIl96dej1LZEdXmr%2F7wQ2GQyZYB581fuLiZfpRQV7Wk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cramesh.krishnamurthy%40conduent.com%7C33413918bc1743b9c0c908d963ee2248%7C1aed4588b8ce43a8a775989538fd30d8%7C0%7C0%7C637650697596633440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=K5YbF18PkkagzmyOLoJb%2FSZqfQ%2FleSpYVMpa%2BVJQUhA%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cramesh.krishnamurthy%40conduent.com%7C33413918bc1743b9c0c908d963ee2248%7C1aed4588b8ce43a8a775989538fd30d8%7C0%7C0%7C637650697596633440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BRpe2BHJtRsE6A%2BD2d1rA%2F0FkabJPC%2FsS1lV8bPCM6w%3D&reserved=0>.

**Comment by SonicDMG** [comment]
It looks like your screenshot didn't attach to the issue properly. Can you try and re-post it?

**Comment by rameshk9099** [comment]
![Step2](https://user-images.githubusercontent.com/46564866/130258011-fa0e0bf2-3355-4ee9-bcbf-c5e90640f964.jpg)

**Comment by HadesArchitect** [comment]
Hey **Ramesh Krishnamurthy**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/uQWyKDWfSd2Pq_W9AroKrA
