### ISSUE TITLE
[HW] Sourabh Girdhar

### ISSUE THREAD

**Issue by girdharsourabh** [datastaxdevs/workshop-introduction-to-nosql#531]
**Name:** Sourabh Girdhar
**Email:**  girdharsourabh@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/girdharsourabh/

Attach the homework screenshots below:
-----------------------------------------

-- image removed by team --

![image](https://user-images.githubusercontent.com/5089894/130114723-df0c0f83-aca2-401b-abd2-91b21c43c42c.png)

![image](https://user-images.githubusercontent.com/5089894/130114898-9dd6c2b9-8b18-4c7c-a05c-cd42d5881a1c.png)

**Comment by SonicDMG** [comment]
Hi there Sourabh, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by SonicDMG** [comment]
Also, I had to remove one of your images because some included your Astra token. Please delete your token from the AstraUI to ensure there are no security issues.

**Comment by girdharsourabh** [comment]
Thanks @SonicDMG . 
I have removed other image with partial token as well. Here is the completion certificate.


![image](https://user-images.githubusercontent.com/5089894/130436131-f94c69cb-1664-4fe3-b265-6609dba588b7.png)
