### ISSUE TITLE
[HW] Jhonny Bonilla

### ISSUE THREAD

**Issue by BonillaJohnny** [datastaxdevs/workshop-introduction-to-nosql#532]
**Name:** Jhonny Bonilla
**Email:** johnnybonilla@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/jhonny-bonilla-alvaran/

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/9422995/130110449-d9c890a8-a067-49dd-bef9-fe6d4b6edf81.png)
![image](https://user-images.githubusercontent.com/9422995/130110566-a02b638a-dfce-4ba0-ac94-1f5e0e7cfb76.png)
![image](https://user-images.githubusercontent.com/9422995/130110651-0820ed0d-9fd2-483f-a8dd-3ef3f974dd02.png)

![image](https://user-images.githubusercontent.com/9422995/130115977-1ddec486-4562-4f3f-b34a-258479fe6b48.png)

**Comment by HadesArchitect** [comment]
Hey **Jhonny Bonilla**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ABnrivKBRqWLIHN2O421QQ
