### ISSUE TITLE
[HW] Jiffin Joachim Gomez

### ISSUE THREAD

**Issue by jiffingomez** [datastaxdevs/workshop-introduction-to-nosql#533]
**Name:** Jiffin Joachim Gomez
**Email:** jiffin.gomez@reflectionsinfos.com
**Linkedin Profile:** https://www.linkedin.com/in/jiffingomez/

Attach the homework screenshots below:
-----------------------------------------

![Playground-https-d7f058a2-497a-4f3d-8ba5-efa996024a9a-ap-southeast-1-apps-astra-datastax-com-api-graphql-yourKeyspace](https://user-images.githubusercontent.com/30854022/130117164-e8230bde-997b-4aa0-8595-07ad16ace0d0.png)
![Try-It-Out-Datastax](https://user-images.githubusercontent.com/30854022/130117172-1ca78f56-8506-4a1e-9bd2-cd31ad021923.png)

**Comment by HadesArchitect** [comment]
Hey **Jiffin Joachim Gomez**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/qQLHfsAQR_CFZwJi0LNf5g
