### ISSUE TITLE
[HW] Nicolas Ochoa

### ISSUE THREAD

**Issue by nicochoa** [datastaxdevs/workshop-introduction-to-nosql#534]
**Name:** Nicolas Ochoa
**Email:** pezkoi1008@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/nicolás-ochoa-891bb479/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
<img width="1343" alt="Captura de Pantalla 2021-08-19 a la(s) 12 30 58 p  m" src="https://user-images.githubusercontent.com/81198928/130117213-d9ceac60-f020-41b5-be0c-07d4ed4c3bd0.png">
<img width="1317" alt="Captura de Pantalla 2021-08-19 a la(s) 12 33 00 p  m" src="https://user-images.githubusercontent.com/81198928/130117221-33733bb8-740c-4642-8eab-5983b01742f2.png">
<img width="1318" alt="Captura de Pantalla 2021-08-19 a la(s) 12 34 19 p  m" src="https://user-images.githubusercontent.com/81198928/130117224-9f3e8d5f-8f60-4c56-8b83-e182a51d1b90.png">
<img width="1319" alt="Captura de Pantalla 2021-08-19 a la(s) 12 34 51 p  m" src="https://user-images.githubusercontent.com/81198928/130117228-bf897f23-24e9-4769-b9c1-d2fd41f38827.png">

**Comment by HadesArchitect** [comment]
Hey **Nicolas Ochoa**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/3HsUbL5rSTup3b8hfi-1cQ
