### ISSUE TITLE
[HW] Introduction to NotOnly SQL Databases

### ISSUE THREAD

**Issue by Stivy1** [datastaxdevs/workshop-introduction-to-nosql#536]
**Name:** Ricardo Steven Porras
**Email:** estivenaudi@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ricardo-steven-porras-romero-476a4317a/

Attach the homework screenshots below:
-----------------------------------------

Step 1:
![image](https://user-images.githubusercontent.com/89215587/130117424-70ad99b7-89ac-4844-95dd-757d9cb9a01c.png)

Step 2a:
![image](https://user-images.githubusercontent.com/89215587/130117834-f98cffcd-dbfc-4f1d-87a1-22236094a51d.png)

Step 2b:
![image](https://user-images.githubusercontent.com/89215587/130118087-42203aea-d2d8-4efd-bfbf-cefa6a8ce77c.png)

Step 2c:
![image](https://user-images.githubusercontent.com/89215587/130118647-d46e90eb-6c10-40cb-aa0a-2dc62e50c80e.png)

Step 2d:
![image](https://user-images.githubusercontent.com/89215587/130118840-5cc8a8eb-e86c-4aec-932a-afcd3674299a.png)

Step 3a:
![image](https://user-images.githubusercontent.com/89215587/130119018-5595c5c0-8bca-4a39-9518-b272154e7822.png)

Step 3b:
![image](https://user-images.githubusercontent.com/89215587/130119209-f1221a50-c4b6-4585-90f9-3ecef86e0db0.png)

Step 3c:
![image](https://user-images.githubusercontent.com/89215587/130120028-65e7b85c-7dd8-4946-9654-43665150b006.png)

Step 3d:
![image](https://user-images.githubusercontent.com/89215587/130120431-c11a1772-d698-4771-af9d-7f1445a51f2d.png)

Step 3e:
![image](https://user-images.githubusercontent.com/89215587/130120682-3c9ceba5-83e9-4276-819a-2c5363ea1068.png)

Step 3f:
![image](https://user-images.githubusercontent.com/89215587/130121310-9772858b-8031-4145-973e-a7aa514e5a80.png)

Step 3g:
![image](https://user-images.githubusercontent.com/89215587/130121555-5173abfd-9e38-4760-ae73-bad9b663e85f.png)

Step 4b:
![image](https://user-images.githubusercontent.com/89215587/130122716-5086c0c8-1c5f-4805-9400-9589b1aa1745.png)

![image](https://user-images.githubusercontent.com/89215587/130122676-649c452f-baaa-4006-9d92-a6de85e4e69b.png)

Step 4c:
![image](https://user-images.githubusercontent.com/89215587/130123183-324edfe6-ddb0-4a43-ae0b-fbce3e94bc20.png)

![image](https://user-images.githubusercontent.com/89215587/130123327-da63879c-7bb9-4e6e-98b5-a206d788202e.png)

Try-it-Out Scenario
![image](https://user-images.githubusercontent.com/89215587/130124566-ad77c277-3590-4aa0-9409-4652e9084601.png)

**Comment by HadesArchitect** [comment]
Hey **Ricardo Steven Porras**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/deUjlilISgeC7L3FiMb-zQ
