### ISSUE TITLE
[HW] <LOKESH LAKHWANI>

### ISSUE THREAD

**Issue by llakhwani17** [datastaxdevs/workshop-introduction-to-nosql#537]
**Name:** LOKESH LAKHWANI
**Email:** llakhwani17@gmail.com
**Linkedin Profile:** <https://my.linkedin.com/in/lokeshlakhwani>

Attach the homework screenshots below:
-----------------------------------------

<CASSANDRA-4
![CASSANDRA-4](https://user-images.githubusercontent.com/77186159/130125528-7c93c2bd-c0ff-4042-af3c-1eccb3eb0a3d.JPG)
>

<
![try-it-out](https://user-images.githubusercontent.com/77186159/130126349-9682f58b-13b0-45c8-8dc1-e8084faa43ba.JPG)
>

**Comment by HadesArchitect** [comment]
Hey **LOKESH LAKHWANI**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/V2zdP7kVSpm64TZOlGpA8A
