### ISSUE TITLE
[HW] <Ramki Senthilnathan>

### ISSUE THREAD

**Issue by ramkisenthilnathan** [datastaxdevs/workshop-introduction-to-nosql#538]
**Name:** Ramki Senthilnathan
**Email:** ramkisenthilnathan@gmail.com
**Linkedin Profile:** <www.linkedin.com/in/ramki-s>

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/89220066/130130454-c57a121e-3b77-4240-9519-27e09855f8ee.png)
![image](https://user-images.githubusercontent.com/89220066/130130519-53f78f4c-1108-492a-8390-74ebc867d8bc.png)
![image](https://user-images.githubusercontent.com/89220066/130130539-a2270f1a-7c0c-4ece-a09b-999adb37133c.png)
![image](https://user-images.githubusercontent.com/89220066/130130548-1d7bd48a-00b8-41c3-8638-1466bb41e84f.png)
![image](https://user-images.githubusercontent.com/89220066/130130554-7a7c0f70-47aa-4fa6-af31-5859da91d70a.png)
![image](https://user-images.githubusercontent.com/89220066/130130592-a7edaf06-f9ac-41b5-8cdc-8dd8b0865861.png)
![image](https://user-images.githubusercontent.com/89220066/130130613-464d58da-7929-4124-937b-cfb5e043fd00.png)
![image](https://user-images.githubusercontent.com/89220066/130130634-5c8b9ee4-14bf-4b3d-a6ff-c161fc3eeb2e.png)
![image](https://user-images.githubusercontent.com/89220066/130130663-aff9cced-4065-40b3-abfc-28ec1724974a.png)
![image](https://user-images.githubusercontent.com/89220066/130130679-bf96af9e-3419-4fbc-9cd6-4911b4edf5a5.png)
![image](https://user-images.githubusercontent.com/89220066/130130694-498e4d50-830c-45dd-a4c7-6c3a0c7ea816.png)

**Comment by ramkisenthilnathan** [comment]
![image](https://user-images.githubusercontent.com/89220066/130131603-34358483-caac-4c0a-ae49-707fa4339b2c.png)

**Comment by HadesArchitect** [comment]
Hey **Ramki Senthilnathan**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/G_udQdTFQ52fbjwey73_yg

**Comment by ramkisenthilnathan** [comment]
Thank you
