### ISSUE TITLE
[HW] Jesus Briceño

### ISSUE THREAD

**Issue by jabriceno** [datastaxdevs/workshop-introduction-to-nosql#539]
**Name:** Jesus Briceño
**Email:** jesusbg71@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/jesusbriceño/

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/45466350/130131866-ce113d34-86f3-4c8d-89e6-f3c31ca98a1c.png)

![image](https://user-images.githubusercontent.com/45466350/130131641-f52656c7-9a32-4ddc-a808-817dfab4ff2d.png)

![image](https://user-images.githubusercontent.com/45466350/130131599-be1c6bc6-086f-4712-984a-d92256315f3e.png)

![image](https://user-images.githubusercontent.com/45466350/130131693-8d6efec6-2327-4222-bb93-a9576cb78846.png)

**Comment by HadesArchitect** [comment]
Hey **Jesus Briceño**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/UDHPdGC4Qtq57DOQyxvwlA
