### ISSUE TITLE
[HW] <Mayra de O Nascimento Sexto>

### ISSUE THREAD

**Issue by MayraSexto** [datastaxdevs/workshop-introduction-to-nosql#54]
**Name:** <Mayra de O Nascimento Sexto>
**Email:** <mayraoln@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/mayrasexto/>

Attach the homework screenshots below:
<img width="1432" alt="Screenshot 2021-05-19 at 21 54 31" src="https://user-images.githubusercontent.com/60547310/118883209-4770b880-b8f5-11eb-967b-8da85e52d283.png">
<img width="1432" alt="Screenshot 2021-05-19 at 21 58 10" src="https://user-images.githubusercontent.com/60547310/118883218-493a7c00-b8f5-11eb-9c54-f94775303354.png">
<img width="1432" alt="Screenshot 2021-05-19 at 21 58 54" src="https://user-images.githubusercontent.com/60547310/118883223-4a6ba900-b8f5-11eb-800b-e2ba2fb391a9.png">
<img width="1432" alt="Screenshot 2021-05-19 at 21 59 03" src="https://user-images.githubusercontent.com/60547310/118883227-4b043f80-b8f5-11eb-9c53-bd532cc68d17.png">
<img width="1432" alt="Screenshot 2021-05-19 at 21 59 26" src="https://user-images.githubusercontent.com/60547310/118883228-4b9cd600-b8f5-11eb-92e4-3376529081a7.png">
<img width="1432" alt="Screenshot 2021-05-19 at 21 59 36" src="https://user-images.githubusercontent.com/60547310/118883232-4b9cd600-b8f5-11eb-851c-a3aa96bdb12d.png">
<img width="1432" alt="Screenshot 2021-05-19 at 21 59 51" src="https://user-images.githubusercontent.com/60547310/118883233-4c356c80-b8f5-11eb-90ea-4e9573ced04d.png">
<img width="1432" alt="Screenshot 2021-05-19 at 22 00 15" src="https://user-images.githubusercontent.com/60547310/118883236-4c356c80-b8f5-11eb-9726-1530b766cc13.png">
<img width="1432" alt="Screenshot 2021-05-19 at 22 00 36" src="https://user-images.githubusercontent.com/60547310/118883238-4cce0300-b8f5-11eb-92d3-10928aaeb69e.png">
<img width="1432" alt="Screenshot 2021-05-19 at 22 02 58" src="https://user-images.githubusercontent.com/60547310/118883239-4d669980-b8f5-11eb-9e39-28fe3b3a8a37.png">
<img width="1432" alt="Screenshot 2021-05-19 at 22 03 02" src="https://user-images.githubusercontent.com/60547310/118883241-4d669980-b8f5-11eb-806e-2032e613f599.png">
<img width="1432" alt="Screenshot 2021-05-19 at 22 03 37" src="https://user-images.githubusercontent.com/60547310/118883244-4dff3000-b8f5-11eb-9ab3-f2d7438919f6.png">
<img width="1432" alt="Screenshot 2021-05-19 at 22 04 22" src="https://user-images.githubusercontent.com/60547310/118883247-4e97c680-b8f5-11eb-9a75-2db1509af5db.png">
<img width="1432" alt="Screenshot 2021-05-19 at 22 04 45" src="https://user-images.githubusercontent.com/60547310/118883250-4e97c680-b8f5-11eb-81de-8012b7e8b0e0.png">
-- images removed by team --
<img width="1432" alt="Screenshot 2021-05-19 at 22 22 47" src="https://user-images.githubusercontent.com/60547310/118883267-5192b700-b8f5-11eb-9e80-6b8d226afa66.png">
<img width="1432" alt="Screenshot 2021-05-19 at 22 32 03" src="https://user-images.githubusercontent.com/60547310/118883268-5192b700-b8f5-11eb-9889-357f65f49c5d.png">
<img width="1432" alt="Screenshot 2021-05-19 at 22 33 21" src="https://user-images.githubusercontent.com/60547310/118883269-522b4d80-b8f5-11eb-93cd-f47c8a6b4073.png">
![Screenshot 2021-05-19 at 22 52 00](https://user-images.githubusercontent.com/60547310/118883274-522b4d80-b8f5-11eb-939b-9dea3d99a9c8.png)

-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Really nice job Mayra, thank you.

**Comment by MayraSexto** [comment]
Hi David,

Is it possible for me to receive the certificate of participation?

BR,

Mayra.

Em qui., 20 de mai. de 2021 às 15:50, David Jones-Gilardi <
***@***.***> escreveu:

**Comment by SonicDMG** [comment]
Hi there Mayra. Yes, of course. These come out weekly and yours will be in the next batch.

**Comment by HadesArchitect** [comment]
Bom trabalho, Mayra!

https://api.badgr.io/public/assertions/uVBpi3xSTKKCCcDn3WRp2g?identity__email=mayraoln%40gmail.com
