### ISSUE TITLE
[HW] <RAHUL BHOJAK>

### ISSUE THREAD

**Issue by Rahulbhojak** [datastaxdevs/workshop-introduction-to-nosql#540]
**Name:** RAHUL BHOJAK
**Email:** rahulbhojak@gmail.com
**Linkedin Profile:** <linkedin.com/in/rahulbhojak>

Attach the homework screenshots below:
-----------------------------------------

<SCREEN
![Final_Email_03](https://user-images.githubusercontent.com/87692451/130139473-ce75c590-d6e6-4a20-9247-c084794d051e.png)
SHOTS>

![Final_Email_01](https://user-images.githubusercontent.com/87692451/130139553-fab1c0b4-8e05-40fb-970b-6ff363487107.png)

![A7A026B7-9A65-42FE-8FA3-B8B2E8233200](https://user-images.githubusercontent.com/87692451/130267787-23685752-2aaa-4ebe-b5bf-5e18f91f3852.png)
![B9EB78FB-A611-45E8-A60A-BA272B43907F](https://user-images.githubusercontent.com/87692451/130267804-69843c8c-3380-44c6-8bd3-e953300ec7c7.png)

**Comment by Rahulbhojak** [comment]
Thanks Team , I submitted my homwwork , plz look for Badge Thanks & Regards

**Comment by SonicDMG** [comment]
Hi there RAHUL, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by Rahulbhojak** [comment]
Dear Team,

Greetings of the day !!!


Plz check I have once run “ try it out scenario “

Is my homework completed


Plz check & revert me appropriate reply

Thanks & Regards
Rahul Bhojak

**Comment by Rahulbhojak** [comment]
Dear Team,

Greetings of the day !!!!

First Of thanks to you for replying mail …..

 I am sending step 2 screenshot plz check


Plz check n revert

Is anything pending from my side?

Thanks & Regards

Rahul Bhojak

**Comment by Rahulbhojak** [comment]
> Hi there RAHUL, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
> 2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen
> 
> Please complete this and provide a screenshot of the completed scenario.


Dear Mam

I completed try it out scenario . Attached screenshot also plz review again and issue badge thanks

**Comment by HadesArchitect** [comment]
Hey **RAHUL BHOJAK**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/VKlKXOyLTdi6jEM1tr8Reg

**Comment by SonicDMG** [comment]
Looks good, thank you.

**Comment by Rahulbhojak** [comment]
Great, thanks!

**Comment by Rahulbhojak** [comment]
Dear Team,

Greetings of the day !!!

I received badge thanks …. Plz once check for voucher also … I filled form
for certification added my database Is but still no voucher mail received
plz check revert . I already filled three times form for reference I am
attaching screenshot

Thanks & regard
