### ISSUE TITLE
[HW] Vitor Ceolin Porfírio Guerra

### ISSUE THREAD

**Issue by vceolin** [datastaxdevs/workshop-introduction-to-nosql#541]
**Name:** Vitor Ceolin Porfírio Guerra
**Email:** vceolinn@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/vceolin/

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/39313422/130145294-a7551ea3-51ec-475c-8b13-1c277037d933.png)
![image](https://user-images.githubusercontent.com/39313422/130145327-04de6322-30ac-4da0-8d10-a525cc9674b4.png)

**Comment by SonicDMG** [comment]
Hi there Vitor, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by HadesArchitect** [comment]
Hey **Vitor Ceolin Porfírio Guerra**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/6L6UM6BSTE6iYC-jrx0ljQ

**Comment by vceolin** [comment]
Ooops my bad @SonicDMG 

Thanks for the workshop everyone!
