### ISSUE TITLE
[HW] <Raj Gupta>

### ISSUE THREAD

**Issue by Jr-Jrts** [datastaxdevs/workshop-introduction-to-nosql#542]
**Name:** Raj Gupta
**Email:** raj.gupta9680@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/raj-gupta-456b28112/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot from 2021-08-20 11-11-43](https://user-images.githubusercontent.com/30189951/130190243-cf58d4a0-6354-4392-8819-01da0a79183e.png)
![Screenshot from 2021-08-20 11-15-27](https://user-images.githubusercontent.com/30189951/130190317-bbfd4015-1110-440b-95cf-248f0c79505e.png)
![Screenshot from 2021-08-20 11-16-19](https://user-images.githubusercontent.com/30189951/130190343-22d752f0-fad2-4950-80a3-021ca625655b.png)
![Screenshot from 2021-08-20 11-16-31](https://user-images.githubusercontent.com/30189951/130190357-db5b544d-6290-4fce-b0a0-c6647b626eec.png)
![Screenshot from 2021-08-20 11-16-50](https://user-images.githubusercontent.com/30189951/130190366-4bdeaab4-6dc4-43bb-ba58-93c5e15c4635.png)
![Screenshot from 2021-08-20 11-17-31](https://user-images.githubusercontent.com/30189951/130190377-24fcd3b2-be13-4255-9f56-27b7a885e88f.png)
![Screenshot from 2021-08-20 11-20-17](https://user-images.githubusercontent.com/30189951/130190383-aa4a52b5-35bf-4fc3-b5a8-cc98f1f2cc7c.png)
![Screenshot from 2021-08-20 11-22-09](https://user-images.githubusercontent.com/30189951/130190389-814c9afb-04dc-45af-b8c6-e8f100bd3cd4.png)
![Screenshot from 2021-08-20 11-22-29](https://user-images.githubusercontent.com/30189951/130190398-dffed2b8-7ce6-431d-ba53-3a91e9d7b534.png)
![Screenshot from 2021-08-20 11-24-12](https://user-images.githubusercontent.com/30189951/130190401-fd6e3883-f9af-42fd-9900-bb79e493fcec.png)
![Screenshot from 2021-08-20 11-24-37](https://user-images.githubusercontent.com/30189951/130190405-8e1b7a3e-86c7-4227-b454-237e00302943.png)
![Screenshot from 2021-08-20 11-24-41](https://user-images.githubusercontent.com/30189951/130190408-9a3de7de-63b5-4d4c-8f72-97f846a87919.png)
![Screenshot from 2021-08-20 11-25-11](https://user-images.githubusercontent.com/30189951/130190416-ceaaad83-5d11-4501-a597-462075c5cb16.png)
![Screenshot from 2021-08-20 11-25-52](https://user-images.githubusercontent.com/30189951/130190423-f09d1a6a-7471-45d0-a763-bdbcdacdf905.png)
![Screenshot from 2021-08-20 11-26-20](https://user-images.githubusercontent.com/30189951/130190430-353bb3d5-1d35-4ec5-a78e-c00b3fcdfa19.png)
![Screenshot from 2021-08-20 11-26-25](https://user-images.githubusercontent.com/30189951/130190435-614a864a-b06d-4fac-820f-d12c82ce6932.png)
![Screenshot from 2021-08-20 11-27-23](https://user-images.githubusercontent.com/30189951/130190443-9d714189-2ce2-4e2b-9ff8-e89a5fbeb057.png)
![Screenshot from 2021-08-20 11-28-04](https://user-images.githubusercontent.com/30189951/130190449-ee798ff6-29e4-41a7-9ffd-1244bb640722.png)
![Screenshot from 2021-08-20 11-29-24](https://user-images.githubusercontent.com/30189951/130190455-7dddeeab-e2df-4463-ad0e-dfd4eb2de2d9.png)
![Screenshot from 2021-08-20 11-31-01](https://user-images.githubusercontent.com/30189951/130190467-919c6cd5-6dcd-4ab9-8700-b189f19416d5.png)
![Screenshot from 2021-08-20 11-31-59](https://user-images.githubusercontent.com/30189951/130190476-b0b398d3-9383-40e1-b556-d6567c18afc8.png)
![Screenshot from 2021-08-20 11-32-45](https://user-images.githubusercontent.com/30189951/130190487-7b6edc0a-aa8e-4124-a4ae-bb5a9fa20983.png)
![Screenshot from 2021-08-20 11-35-40](https://user-images.githubusercontent.com/30189951/130190495-17cf0e88-f321-4a30-b259-665723c8b7f0.png)
![Screenshot from 2021-08-20 11-45-23](https://user-images.githubusercontent.com/30189951/130190498-9ea4dc92-9127-4bd6-8fa5-6a265222e203.png)
![Screenshot from 2021-08-20 11-45-44](https://user-images.githubusercontent.com/30189951/130190503-8aa8db26-793f-4f2f-9abc-e5d47c779e8b.png)
![Screenshot from 2021-08-20 11-46-08](https://user-images.githubusercontent.com/30189951/130190508-a8155a49-991d-49a7-8411-ff23f9d6c6b1.png)
![Screenshot from 2021-08-20 11-46-16](https://user-images.githubusercontent.com/30189951/130190521-8c21f14f-3499-469f-a081-3d2064262f08.png)
![Screenshot from 2021-08-20 11-48-09](https://user-images.githubusercontent.com/30189951/130190525-8ed9997c-210b-4509-8ce9-ad676417b9cf.png)
![Screenshot from 2021-08-20 11-48-23](https://user-images.githubusercontent.com/30189951/130190535-8695905d-44c0-4e04-ab36-e666c49c09cd.png)
![Screenshot from 2021-08-20 11-48-48](https://user-images.githubusercontent.com/30189951/130190545-de3c6878-4a21-4bf9-9f7d-23bc579ae9d0.png)
![Screenshot from 2021-08-20 11-48-55](https://user-images.githubusercontent.com/30189951/130190554-6024c127-5ba6-4d2f-b917-9c6f5befa3fc.png)
![Screenshot from 2021-08-20 11-49-18](https://user-images.githubusercontent.com/30189951/130190567-bd87a944-4af6-4065-aa0e-4d8d8e3dccc9.png)
![Screenshot from 2021-08-20 11-49-37](https://user-images.githubusercontent.com/30189951/130190570-039bfca0-d1ef-4d2d-85aa-51a76bc447b9.png)
![Screenshot from 2021-08-20 11-50-04](https://user-images.githubusercontent.com/30189951/130190575-138be317-2d95-4a9c-a5ec-32f39c98049c.png)

**Comment by Jr-Jrts** [comment]
Hello
As per your instruction I have completed and submitted the home work assignment snapshots .

**Comment by HadesArchitect** [comment]
Hey **Raj Gupta**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/UfxhJ-LqQoasCcLzbgXgyw

**Comment by Jr-Jrts** [comment]
Hello Datastax,

How can I add this badge on my LinkedIn profile?

**Comment by SonicDMG** [comment]
You can add it to the feature section of your LinkedIn profile using the badge URL.

**Comment by Jr-Jrts** [comment]
Hello David,

Thanks for your quick response . I can not find credential Id of this badge.
