### ISSUE TITLE
[HW] <Alex Agueros Dilley>

### ISSUE THREAD

**Issue by agueeros10** [datastaxdevs/workshop-introduction-to-nosql#545]
**Name:** Alex Agueros Dilley
**Email:** alex.agueros@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/alex-agueros-dilley-87998319b/>

Attach the homework screenshots below:
-----------------------------------------

![Exercise IV last step GRAPHQL](https://user-images.githubusercontent.com/47254048/130214663-1b87aabf-dc1d-4a50-af81-1251cc226146.png)
![Exercise IV last step CQL console](https://user-images.githubusercontent.com/47254048/130214664-74e9c9f9-8e3d-438d-b1de-28caacb9fd08.png)
![Cassandra Try-it-out finished](https://user-images.githubusercontent.com/47254048/130214668-1b9b3147-0a0c-4a74-b841-4afccd893446.png)
[](url)

**Comment by HadesArchitect** [comment]
Hey **Alex Agueros Dilley**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ZgbzdqSLSzW8rjSNhLspAg
