### ISSUE TITLE
[HW] Leopoldo Parra

### ISSUE THREAD

**Issue by Leonime** [datastaxdevs/workshop-introduction-to-nosql#546]
**Name:** Leopoldo Parra
**Email:** lparra.dev@gmail.com
**Linkedin Profile:** [link](https://www.linkedin.com/in/devleopoldoparra/)

Attach the homework screenshots below:
-----------------------------------------

1. Create Astra Db Instance
![1  Create Astra Db Instance](https://user-images.githubusercontent.com/616497/130218450-b1892175-4a5f-48e6-9c29-8d3780b74efb.png)

2a. Describe your Keyspace
![2a  Describe your Keyspace](https://user-images.githubusercontent.com/616497/130218961-ee2dd99d-3460-4aee-b1eb-ff4b46ec9ee4.png)

2b. Create tables
![2b  Create tables](https://user-images.githubusercontent.com/616497/130219003-27cd6bf0-3035-48cb-9b1d-6f9a6dd72c6f.png)

2b1  Create tables
![2b1  Create tables](https://user-images.githubusercontent.com/616497/130219036-19c5a638-7236-485e-a9fc-cb3c320f1634.png)

2c  Working with DATA
![2c  Working with DATA](https://user-images.githubusercontent.com/616497/130219046-fb277b7f-f7f2-4660-94cf-6a1ca346e7f7.png)

2c1  Working with DATA
![2c1  Working with DATA](https://user-images.githubusercontent.com/616497/130219048-98763295-5917-49fb-b4f0-c7c40740d297.png)

2c2  Working with DATA
![2c2  Working with DATA](https://user-images.githubusercontent.com/616497/130219049-af324909-d77d-4a99-a25e-bbba746464ce.png)

2d  Working with PARTITIONS
![2d  Working with PARTITIONS](https://user-images.githubusercontent.com/616497/130219050-5fb60271-f57e-4067-b2a6-5574b17710c2.png)

3a  Cassandra knows JSON
![3a  Cassandra knows JSON](https://user-images.githubusercontent.com/616497/130219051-b4202134-d408-47c6-9698-b0169fec060f.png)

3c Create a new empty collection
![3c Create a new empty collection](https://user-images.githubusercontent.com/616497/130219052-184c8002-23f6-478f-b444-aecb02d11ee6.png)

3d  Create a new document
![3d  Create a new document ](https://user-images.githubusercontent.com/616497/130219053-b766fa95-af07-471a-8f8f-d112e5c5a3cb.png)

3e Find all documents of a collection
![3e Find all documents of a collection](https://user-images.githubusercontent.com/616497/130219056-16292849-4bee-422b-bf07-c362191675c6.png)

3f Retrieve a document from its id
![3f Retrieve a document from its id](https://user-images.githubusercontent.com/616497/130219058-3dcf21e8-6c1e-4d3f-a0c9-a47f838bd778.png)

3g Search document from a where clause
![3g Search document from a where clause](https://user-images.githubusercontent.com/616497/130219060-05739470-cf9d-49c5-8ebf-18bc5af1342c.png)

4b  Create a table with GraphQL
![4b  Create a table with GraphQL](https://user-images.githubusercontent.com/616497/130219062-e5a766e2-c1b7-4bd5-b34a-11ca2bdec0bd.png)

4c  Populate the table
![4c  Populate the table](https://user-images.githubusercontent.com/616497/130219063-ea0bb3dc-5f73-426b-927a-d8935b05c5a0.png)

4c1  Populate the table
![4c1  Populate the table](https://user-images.githubusercontent.com/616497/130219065-5029e380-90fa-4e1f-aedb-61b8f654cfbf.png)

5  Graph Databases
![5  Graph Databases](https://user-images.githubusercontent.com/616497/130219066-22ab5c52-1d25-4a45-8998-9a87a5aa0ada.png)

try-it-out scenario
![try-it-out scenario](https://user-images.githubusercontent.com/616497/130219067-6895e900-14ee-40e5-a224-ef6e584ad1f0.png)

**Comment by HadesArchitect** [comment]
Hey **Leopoldo Parra**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/T6EMNvG4QiCu2rAN4BnETQ
