### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by pallav31shrivastava** [datastaxdevs/workshop-introduction-to-nosql#547]
**Name:** PALLAV KUMAR SHRIVASTAVA
**Email:** pallav.shrivastava@outlook.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Capture](https://user-images.githubusercontent.com/89255186/130228171-217102d4-7df6-485f-9858-e6cb17f6dd5a.PNG)

**Comment by SonicDMG** [comment]
Hi there PALLAV, thank you for your submission. I see you got through the workshop content, awesome. We are missing step 2 from the homework though.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please complete this and provide a screenshot of the completed scenario.

**Comment by pallav31shrivastava** [comment]
PFA the requisite for your kind perusal. 
![Capturecas](https://user-images.githubusercontent.com/89255186/130325087-874cdd6a-c30d-4519-b18a-b5e065aeb3f4.PNG)
