### ISSUE TITLE
[HW] Leandro Saavedra

### ISSUE THREAD

**Issue by ldscoullery** [datastaxdevs/workshop-introduction-to-nosql#548]
**Name:** Leandro Saavedra
**Email:** leandro.saavedra19@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/lsaavedra-arg/

Attach the homework screenshots below:
-----------------------------------------
![Captura de pantalla -2021-08-19 13-54-42](https://user-images.githubusercontent.com/18270578/130283582-04d17362-ea7b-4cc8-899c-74734ea553e9.png)
![Captura de pantalla -2021-08-19 13-53-42](https://user-images.githubusercontent.com/18270578/130283587-53a4d8c4-e9f2-4a9c-961f-6915dead2142.png)
![Captura de pantalla -2021-08-20 16-23-52](https://user-images.githubusercontent.com/18270578/130283951-7344bea0-a14b-4622-b61e-fbc9fba8ba41.png)
![Captura de pantalla -2021-08-20 16-24-06](https://user-images.githubusercontent.com/18270578/130283962-a53f8d1e-c216-4496-8d97-e7823f37beb7.png)

**Comment by HadesArchitect** [comment]
Hey **Leandro Saavedra**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/BooketRIRbWzLBqSMzcJxg
