### ISSUE TITLE
[HW] Karla Berenice Arroyo Estrada

### ISSUE THREAD

**Issue by Karla-Arroyo** [datastaxdevs/workshop-introduction-to-nosql#549]
**Name:** Karla Berenice Arroyo Estrada
**Email:** karla.arroyoestb@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/karla-arroyo-estrada-139ba3206/

Attach the homework screenshots below:
-----------------------------------------

<The screenshots of the process be in the pdf file>
[NoSQL.DB.pdf](https://github.com/datastaxdevs/workshop-introduction-to-nosql/files/7024598/NoSQL.DB.pdf)

**Comment by Karla-Arroyo** [comment]
The screenshots of the process be in the pdf file

**Comment by RyanWelford** [comment]
Thanks Karla! Well done! FYI, your Astra DB token should be deleted as these images are public, just a security measure.

**Comment by HadesArchitect** [comment]
Hey **Karla Berenice Arroyo Estrada**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/JgKZFOy9TJ2hEI7l_pnb5w
