### ISSUE TITLE
[HW] Jonnalagadda Venkata Chaitanya Viswanadh

### ISSUE THREAD

**Issue by jvcviswanadh** [datastaxdevs/workshop-introduction-to-nosql#552]
**Name:** Jonnalagadda Venkata Chaitanya Viswanadh
**Email:** jvcviswanadh@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/chaitanya-viswanadh-jonnalagadda-70b26b107/

Attach the homework screenshots below:
-----------------------------------------

![C2](https://user-images.githubusercontent.com/89298821/130318874-efd7fa06-b52d-4064-b0b4-f994e39b95a4.JPG)
![C1](https://user-images.githubusercontent.com/89298821/130318875-161d0628-0686-462a-9950-8476f3f4275e.JPG)
![Cassandra Scenario](https://user-images.githubusercontent.com/89298821/130318876-738ae3e5-8873-44c0-926d-56373cedc361.JPG)
![C4](https://user-images.githubusercontent.com/89298821/130318877-810bcfaf-111f-427c-9701-b743f9e6936c.JPG)
![C3](https://user-images.githubusercontent.com/89298821/130318878-cf4d71f1-fad4-413e-b90c-77ae2c3b741e.JPG)

**Comment by jvcviswanadh** [comment]
Attached the screenshots after completion  of the assignment

**Comment by RyanWelford** [comment]
Looks good, thanks Jonnalagadda!

**Comment by HadesArchitect** [comment]
Hey **Jonnalagadda Venkata Chaitanya Viswanadh**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/QyOq17j7S-ieT2UH8nPBVA

**Comment by jvcviswanadh** [comment]
Thank you
