### ISSUE TITLE
[HW] Ben Golfin

### ISSUE THREAD

**Issue by bennygolfin** [datastaxdevs/workshop-introduction-to-nosql#554]
**Name:** Benny Golfin
**Email:** contact.b.golfin@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/bengolfin/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![NoSQL Workshop Homework - BenGolfin](https://user-images.githubusercontent.com/77009609/130330180-38d09a0b-94c1-4b87-b345-42eb43e99ba7.png)
![Try CQL Complete - BenGolfin](https://user-images.githubusercontent.com/77009609/130330940-37390cc3-7541-464b-8626-6d79cbce1d5f.png)

I'd like to say a huge thank you to both Cedrick and Ryan for the awesome workshop!
The only thing I couldn't do was step 5 - for some reason I couldn't make sense of how it should work fully unfortunately.

**Comment by bennygolfin** [comment]
Apologies, here are the images:

![Try CQL Complete - BenGolfin](https://user-images.githubusercontent.com/77009609/130458847-f4eca8e6-ea82-467c-84a7-831f667dbb28.png)
![NoSQL Workshop Homework - BenGolfin](https://user-images.githubusercontent.com/77009609/130458855-4cd40310-a749-4416-ad8b-cb9e6d471286.png)

**Comment by RyanWelford** [comment]
Thanks! Glad you had a good time at the workshop!
