### ISSUE TITLE
[HW] Anil Kumar Chittajallu

### ISSUE THREAD

**Issue by anil4mic** [datastaxdevs/workshop-introduction-to-nosql#555]
**Name:** Anil Kumar Chittajallu
**Email:** anil4mic@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/anil-kumar-chittajallu-1793b037/

Attach the homework screenshots below:
-----------------------------------------
Introduction to NotOnly SQL Databases

![input](https://user-images.githubusercontent.com/23282128/130333030-dbcac8a3-4e4f-4827-9418-f8f091316720.jpg)
![output](https://user-images.githubusercontent.com/23282128/130332904-4050a3ed-4511-4086-adb3-2c63bb31b8d4.jpg)
![scenario](https://user-images.githubusercontent.com/23282128/130332949-ce168b0b-de66-48e0-a1a2-e7c105e1765e.JPG)

**Comment by RyanWelford** [comment]
Well done Anil! I will assume you also completed parts 2 & 3 with us in the workshop.

**Comment by HadesArchitect** [comment]
Hey **Anil Kumar Chittajallu**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Mmzv7ogaQfKCr-JARvXC_w

**Comment by anil4mic** [comment]
@RyanWelford Yes, during the workshop I completed the parts 2 & 3.
