### ISSUE TITLE
[HW] Sooraj Shajahan

### ISSUE THREAD

**Issue by sooraj19** [datastaxdevs/workshop-introduction-to-nosql#556]
**Name:** Sooraj Shajahan
**Email:** soorajshajahan@ymail.com
**Linkedin Profile:** https://www.linkedin.com/in/sooraj-shajahan-8a853984/

Attach the homework screenshots below:
-----------------------------------------

![AstraDB Last Step](https://user-images.githubusercontent.com/38080672/130336272-a8659f08-f919-4a4d-8417-e8eeab24474a.JPG)

![try-it-out-completion](https://user-images.githubusercontent.com/38080672/130336275-a4c46015-55ff-4a52-afd3-e200668deff7.JPG)

Thanks & Regards,
Sooraj Shajahan

**Comment by RyanWelford** [comment]
Well done Sooraj! Thanks for participating!

**Comment by HadesArchitect** [comment]
Hey **Sooraj Shajahan**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/xkTX4dUbQyCPNTCECYJv0A

**Comment by sooraj19** [comment]
Thank you very much @RyanWelford  and @HadesArchitect 👍
