### ISSUE TITLE
[HW] Varshini

### ISSUE THREAD

**Issue by varshini39** [datastaxdevs/workshop-introduction-to-nosql#56]
**Name:** Varshini
**Email:** sweetyrv@yahoo.co.in
**Linkedin Profile:** https://www.linkedin.com/in/ragavarshini1812/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Screenshot from 2021-05-20 12-37-54](https://user-images.githubusercontent.com/14819986/118957609-4c2d7f00-b97e-11eb-9bda-9ce57d1b846a.png)
![Screenshot from 2021-05-20 12-39-19](https://user-images.githubusercontent.com/14819986/118957621-4e8fd900-b97e-11eb-8d5c-bb8ff2a4c3d6.png)
![Screenshot from 2021-05-20 12-48-31](https://user-images.githubusercontent.com/14819986/118957634-4fc10600-b97e-11eb-9a7f-5547cbce7336.png)
![Screenshot from 2021-05-20 12-49-35](https://user-images.githubusercontent.com/14819986/118957642-50f23300-b97e-11eb-8924-1ff8e708c27a.png)
![Screenshot from 2021-05-20 12-50-15](https://user-images.githubusercontent.com/14819986/118957645-52236000-b97e-11eb-9cbc-1747c754acd6.png)
![Screenshot from 2021-05-20 12-50-59](https://user-images.githubusercontent.com/14819986/118957653-53548d00-b97e-11eb-8934-bdd1d888e0af.png)
-- images removed by team --
![Screenshot from 2021-05-20 15-09-19](https://user-images.githubusercontent.com/14819986/118957702-5b143180-b97e-11eb-8475-d09abff4d910.png)
-- images removed by team --
![Screenshot from 2021-05-20 15-09-57](https://user-images.githubusercontent.com/14819986/118957707-5cddf500-b97e-11eb-9afe-452867f052fc.png)
![Screenshot from 2021-05-20 15-13-57](https://user-images.githubusercontent.com/14819986/118957715-5e0f2200-b97e-11eb-9fdf-19bc24fbff4a.png)

**Comment by SonicDMG** [comment]
Nice job Varshini, thank you.

**Comment by HadesArchitect** [comment]
Well done! https://api.badgr.io/public/assertions/oejr9CZzTpWyR0Aw1Q2Maw?identity__email=sweetyrv%40yahoo.co.in
