### ISSUE TITLE
[HW] Veronica Smigielski

### ISSUE THREAD

**Issue by VSmigielski** [datastaxdevs/workshop-introduction-to-nosql#561]
**Name:** Veronica Smigielski
**Email:** veronicasmigielski@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/veronica-smigielski-b85025174/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
Step 4
-- image removed by team --
![image](https://user-images.githubusercontent.com/66082052/131248475-42304c55-ec5b-4a00-b552-72db2d6b005c.png)
![image](https://user-images.githubusercontent.com/66082052/131248554-2e793762-3922-48c0-8f1f-93b02c6927ee.png)
![image](https://user-images.githubusercontent.com/66082052/131248671-7178f7b1-8288-4899-8d78-09b2912e3a19.png)
![image](https://user-images.githubusercontent.com/66082052/131248719-e2406bc3-bc29-427f-bd3a-92af18b2d502.png)
![image](https://user-images.githubusercontent.com/66082052/131248834-942c9e48-635b-40bd-8c35-7e2ec2e312ca.png)
![image](https://user-images.githubusercontent.com/66082052/131248870-d44dc365-e68e-47b0-b0ff-7177eb7b2e5e.png)
![image](https://user-images.githubusercontent.com/66082052/131248900-0c59b16e-2ddb-435f-a2a8-ecb148fabcd1.png)

Step 5
(On a windows this process was a bit rough to get through until kind was finally linked/installed properly)
![image](https://user-images.githubusercontent.com/66082052/131259585-6623b6a9-1ce1-4380-b610-28d0c27b3901.png)

![image](https://user-images.githubusercontent.com/66082052/131260619-853e4945-7eb6-4460-969c-872a9014fd18.png)
![image](https://user-images.githubusercontent.com/66082052/131260634-f5522302-d5df-4292-b719-9f024940ee20.png)

Step 2 of HW:
![image](https://user-images.githubusercontent.com/66082052/131387267-9f128c84-b78d-41cf-80de-924be70b1343.png)
![image](https://user-images.githubusercontent.com/66082052/131387371-07ea85df-81ef-4a14-b2f1-6ea93bbd76fa.png)
![image](https://user-images.githubusercontent.com/66082052/131387399-b65930f0-a3a0-4f51-a091-5ebabcb24a77.png)
![image](https://user-images.githubusercontent.com/66082052/131387457-07b45bbd-9a9a-4ff6-b975-1ee7e4953937.png)

**Comment by SonicDMG** [comment]
Great job getting through the graph database piece. The only thing we are missing is step 2 from the homework.
2. Complete [try-it-out scenario ](https://www.datastax.com/try-it-out)and make a screenshot of the "scenario completed" screen

It should only take about 10 minutes.

**Comment by VSmigielski** [comment]
Hello,
I just finished up the missing try-it-out scenario. I think at some point
the screenshots disappeared from the github (I was restarting my computer a
lot during the use of docker).

**Comment by SonicDMG** [comment]
^Oh no! Well thank you for following up and uploading them again.

**Comment by HadesArchitect** [comment]
Hey **Veronica Smigielski**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/dKzx8BWaSwuB47YK8Voonw
