### ISSUE TITLE
[HW] BHASKAR PAL

### ISSUE THREAD

**Issue by pal-bhaskar** [datastaxdevs/workshop-introduction-to-nosql#565]
**Name:** Bhaskar Pal
**Email:** bhaskarpaal@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/bhaskar-pal-3364758a/

Attach the homework screenshots below:
-----------------------------------------

![Screenshot 2021-09-02 at 3 08 29 PM](https://user-images.githubusercontent.com/69039695/131825238-329b4980-5eb9-478d-b638-e6bf9a8fb535.png)
![Screenshot 2021-09-02 at 3 07 51 PM](https://user-images.githubusercontent.com/69039695/131825261-9b808261-871b-42b8-815b-263dd21ce028.png)
![Screenshot 2021-09-02 at 3 07 36 PM](https://user-images.githubusercontent.com/69039695/131825266-13a90f96-4bfb-49d0-b89a-5fe5a235e4ab.png)
![Screenshot 2021-09-02 at 3 04 34 PM](https://user-images.githubusercontent.com/69039695/131825267-a782a3c6-549d-4be1-9a2c-23deb3dbda05.png)
![Screenshot 2021-09-02 at 3 03 34 PM](https://user-images.githubusercontent.com/69039695/131825270-d73a204f-f142-4023-ae61-dcb4ecd3a454.png)
![Screenshot 2021-09-02 at 3 32 22 PM](https://user-images.githubusercontent.com/69039695/131825311-037331ea-cdaf-427b-a161-bf0c02622643.png)

**Comment by HadesArchitect** [comment]
Hey **Bhaskar Pal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Fvze8pk9Qc-2CAPOfwMZqw

**Comment by pal-bhaskar** [comment]
Thank you @HadesArchitect.
It's an awesome learning experience!
