### ISSUE TITLE
[HW] ABHIJEET MUKHERJEE

### ISSUE THREAD

**Issue by Abhijeet007-coder** [datastaxdevs/workshop-introduction-to-nosql#567]
**Name:** Abhijeet Mukherjee
**Email:** abhijeetmukherji007@gmail.com
**Linkedin Profile:** www.linkedin.com/in/abhijeet-mukherjee-580616145

Attach the homework screenshots below:
-----------------------------------------

![Screenshot (108)](https://user-images.githubusercontent.com/80517732/132100787-f38532dd-ef12-496a-b382-f6827f83ee92.png)
![Screenshot (109)](https://user-images.githubusercontent.com/80517732/132100792-e74d3327-ccb8-4a22-ad0a-96d6b9d624b0.png)
![Screenshot (111)](https://user-images.githubusercontent.com/80517732/132100800-b1d33d5f-2988-4717-b9fe-9f21a478344b.png)
![Screenshot (110)](https://user-images.githubusercontent.com/80517732/132100809-9253d7e4-6377-4271-a29d-3bd5aad9b174.png)
![Screenshot (107)](https://user-images.githubusercontent.com/80517732/132100815-b31e38a6-ffad-4c5f-b664-c90d03f2562f.png)
![Screenshot (112)](https://user-images.githubusercontent.com/80517732/132100830-bfd2c509-1cfa-4de8-a988-644287a96bb5.png)

**Comment by Abhijeet007-coder** [comment]
Hello I haven't received feedback. Waiting for the response

**Comment by HadesArchitect** [comment]
Hey **Abhijeet Mukherjee**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/lePUPJkKRmqcfNmcI8If7Q
