### ISSUE TITLE
[HW] Sabyasachi Dutta

### ISSUE THREAD

**Issue by sabydutta** [datastaxdevs/workshop-introduction-to-nosql#568]
**Name:** Sabyasachi Dutta
**Email:** orderviasaby@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sabydutta/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![image](https://user-images.githubusercontent.com/60998317/133611919-a761ef37-e7b4-44d6-8005-31cda1c33541.png)
![image](https://user-images.githubusercontent.com/60998317/133611981-5bf5e3ad-a3d5-4def-b5fd-f7bfcbcdd0b9.png)
![image](https://user-images.githubusercontent.com/60998317/133612043-3b5ccd06-54ff-4ad8-b106-f4b70b1f6656.png)

**Comment by HadesArchitect** [comment]
Hey **Sabyasachi Dutta**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/wNPbm-hPSCyKtIt9FTITOg
