### ISSUE TITLE
[HW] Niraj Chaurasia

### ISSUE THREAD

**Issue by nirajch** [datastaxdevs/workshop-introduction-to-nosql#569]
**Name:** Niraj Chaurasia
**Email:** niraj.chrs@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/niraj-chaurasia/

Attach the homework screenshots below:
-----------------------------------------

<img width="1427" alt="Screen Shot 2021-09-16 at 10 22 34 AM" src="https://user-images.githubusercontent.com/35894898/133629619-6c2aaaa7-4cc9-4323-b113-68861172d514.png">

**Comment by SonicDMG** [comment]
Hey there Niraj, thank you for your submission. Nice job getting Through the workshop materials. The only thing we are missing is step 2 of the homework.
2. [Complete try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please post an image of the "completed" screen once finished.

**Comment by nirajch** [comment]
Hi David, thanks for the link, as suggested, I have attached the scenario completed screenshot.
<img width="1440" alt="Screen Shot 2021-09-20 at 3 52 11 PM" src="https://user-images.githubusercontent.com/35894898/134066215-099a99b4-c7a5-42d5-8458-f5bad1d7efb7.png">

**Comment by HadesArchitect** [comment]
Hey **Niraj Chaurasia**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/gtd4ypyZQL-C7olrAHWqKw

**Comment by nirajch** [comment]
Thanks! Appreciate the quick turnaround.
