### ISSUE TITLE
[HW] <ASHUTOSH KUMAR>

### ISSUE THREAD

**Issue by letusashutosh** [datastaxdevs/workshop-introduction-to-nosql#57]
**Name:** <ASHUTOSH KUMAR>
**Email:** <letusashutosh@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/ashutosh-kumar-05b66416/>

Attach the homework screenshots below:
----------------
-- images removed by team --
-------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
I see that. What browser are you using? If you are using something like Brave you may need to disable shields or turn off any security blockers. I had the same thing happen in Brave, disabled shields, and the site loaded up as expected.

**Comment by SonicDMG** [comment]
Btw, really nice job with the homework. I appreciated the way you organized the images in your document. Thank you Ashutosh. I'll go ahead and approve this because you obviously did the work and only got stuck in the scenario because your browser might be blocking it. I would love to know if by disabling any popup blockers or whatnot if the scenario works for you.

**Comment by letusashutosh** [comment]
> I see that. What browser are you using? If you are using something like Brave you may need to disable shields or turn off any security blockers. I had the same thing happen in Brave, disabled shields, and the site loaded up as expected.

I am using chrome and also tried in Firefox but no luck , I also tried incognito mode . I will try by clearing cache and will let you know if that works. Thank you for you feedback!

**Comment by SonicDMG** [comment]
Thank you for saying so and glad this was useful for you. We have a lot more and more coming. Always feel free to reach out if you need anything or have any questions. See you at the next one. Take care.

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/ySTYrLKoQX-_sW6N2wONkg?identity__email=letusashutosh%40gmail.com Congrats!
