### ISSUE TITLE
[HW] <Alodia Yusuf>

### ISSUE THREAD

**Issue by blackcatt1217** [datastaxdevs/workshop-introduction-to-nosql#570]
**Name**: Alodia Yusuf
**Email**: alodiaysf@gmail.com
**Linkedin Profile**: https://www.linkedin.com/in/alodia-yusuf/

**Attach the homework screenshots below:**
-----------------------------------------

**1.** 
![image](https://user-images.githubusercontent.com/90201518/133642344-ecde7b40-60d2-426b-a007-e17900c879d6.png)

**2.** 
![image](https://user-images.githubusercontent.com/90201518/133642407-5890c632-fc96-40e1-9bf0-d7316d411245.png)

**Comment by HadesArchitect** [comment]
Hey **Alodia Yusuf**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/UmJUIoKtRS2JRd-zAcq8cQ
