### ISSUE TITLE
[HW] <Vitalii Chernushenko>

### ISSUE THREAD

**Issue by ChernushenkoVitalii** [datastaxdevs/workshop-introduction-to-nosql#571]
**Name:** Vitalii Chernushenko
**Email:** v.chernushenko@triangu.com
**Linkedin Profile:** <https://www.linkedin.com/in/vitaliy-chernushenko-29685aa0>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS
-- images removed by team --
![HW-4  KeyValue Databases-4c1](https://user-images.githubusercontent.com/90852786/133648804-9c210d75-4dbe-44a5-b52b-e29a82764dad.jpg)
![HW-4  KeyValue Databases-4c2](https://user-images.githubusercontent.com/90852786/133648806-8f0b8423-2810-4be6-a4cb-72e1891ca8c5.jpg)
![HW-4  KeyValue Databases-4c3](https://user-images.githubusercontent.com/90852786/133648811-0e8f51ca-9e51-49e5-88af-060b0d520147.jpg)
>

**Comment by SonicDMG** [comment]
Hey there Vitalii, thank you for your submission. Nice job getting Through the workshop materials. The only thing we are missing is step 2 of the homework.
2. [Complete try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please post an image of the "completed" screen once finished.

**Comment by SonicDMG** [comment]
Also, I had to remove a set of your images because they contained your Astra token. Please delete your token from the Astra UI and create another one to use. Thank you.

**Comment by ChernushenkoVitalii** [comment]
![HW s2-2](https://user-images.githubusercontent.com/90852786/134013632-da438bae-433f-4fd5-b680-6a1782427b2a.jpg)

**Comment by ChernushenkoVitalii** [comment]
![Uploading HW s2-2.jpg…]()

**Comment by ChernushenkoVitalii** [comment]
Thank you.

**Comment by HadesArchitect** [comment]
Hey **Vitalii Chernushenko**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/T3qfmeM5SjWlbnSbQfES8Q
