### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by MelendezIvelis** [datastaxdevs/workshop-introduction-to-nosql#572]
**Name:** Ivelis Melendez
**Email:** MelendezIvelis@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ivelis-melendez/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![image](https://user-images.githubusercontent.com/81835592/133809593-e27f1113-3ad3-416d-bb33-a251ddfc78bf.png)

![image](https://user-images.githubusercontent.com/81835592/133810027-ab2c99e6-208a-4b8b-9cea-857cab1db955.png)

**Comment by SonicDMG** [comment]
Hi there Ivelis. This looks good, nice job, but we'll need a complete email in order to give you your badge. Can you please update your email to the correct address?

**Comment by MelendezIvelis** [comment]
So sorry about that! I have updated my commit with my email address.

**Comment by HadesArchitect** [comment]
Hey **Ivelis Melendez**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ZEAa4cAZRG2dLb5L9xEYsA

**Comment by SonicDMG** [comment]
> So sorry about that! I have updated my commit with my email address.

No worries, just wanted to ensure you got your badge for your work. :)
