### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by Data-Lady** [datastaxdevs/workshop-introduction-to-nosql#573]
**Name:** Sapna Parkash
**Email:** sp24610@yahoo.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/84138450/133977193-06182f92-1e67-4183-aeda-087c481d0b46.png)
![image](https://user-images.githubusercontent.com/84138450/133977714-45554fa4-e571-4410-978c-dd6ff4af0bb3.png)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Sapna Parkash**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ZktqLpu7Qs66Unst7-js6Q

**Comment by Data-Lady** [comment]
Hi Aleks
Thank you so much - my 1st badge!
I was hoping that you would also be providing a certification voucher for exams? I intend to study for the exams if possible. 
Did I misunderstand - was that the prize for the top 3 in the quiz?
Anyway, it would be great if I am eligible for the voucher.
Thanks again for a great workshop - I really appreciate these opportunities.
Sapna Parkash
    On Monday, 20 September 2021, 14:04:48 BST, Aleks Volochnev ***@***.***> wrote:  
 
 


Hey Sapna Parkash, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ZktqLpu7Qs66Unst7-js6Q

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SonicDMG** [comment]
Hi there Sapna. Sounds like you may have missed the voucher form when we dropped it at the end of the session. With that, here you go -> https://dtsx.io/workshop-voucher. Just go to the link and fill it out. If you were one of the top 3 from the quiz did you email jack.fryer@datastax.com? If not, be sure to do that with an image of your win to get your swag.

**Comment by SonicDMG** [comment]
> I have just completed the voucher form.

Excellent. FYI, those are batch processed each week, usually on Friday's so expect some delay before you get a voucher.

**Comment by Data-Lady** [comment]
Thanks for the update.
    On Monday, 20 September 2021, 15:40:25 BST, David Jones-Gilardi ***@***.***> wrote:  
 
 



I have just completed the voucher form.


Excellent. FYI, those are batch processed each week, usually on Friday's so expect some delay before you get a voucher.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
