### ISSUE TITLE
[HW] <Solomon Yu>

### ISSUE THREAD

**Issue by sqr00t** [datastaxdevs/workshop-introduction-to-nosql#574]
**Name:** Solomon Yu
**Email:** solomon.sj.yu@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/solomonsjyu/>

Attach the homework screenshots below:
-----------------------------------------

![screenshotlaststep4](https://user-images.githubusercontent.com/797346/134192953-e9cdba13-5cbc-41f0-befa-1c5566c21fc0.png)
![scenariocompleted](https://user-images.githubusercontent.com/797346/134194291-65940b68-0509-46ce-8be9-64b2c643497e.png)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Solomon Yu**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/F7brRK5eRsudYmMVQ47lTQ
