### ISSUE TITLE
[HW] SHANTANU KASHYAP

### ISSUE THREAD

**Issue by shantanukash** [datastaxdevs/workshop-introduction-to-nosql#575]
**Name:** Shantanu Kashyap
**Email:** shantanukashyap@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/shantanukashyap/

Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------

### **Step 4**
![Step 4 - Last step Screenshot](https://user-images.githubusercontent.com/91284815/135356571-96f4dc64-20bf-48d8-b315-cb60773986be.JPG)

### The **try-it-yourself** scenario is also done
![Try_it-Yourself-Scenario](https://user-images.githubusercontent.com/91284815/135356636-7d1c22e0-e6d6-4ba3-b04d-67c386f7b626.JPG)

**Comment by HadesArchitect** [comment]
Hey **Shantanu Kashyap**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/HEPFau55TFmQGZCN1zPiNA

**Comment by shantanukash** [comment]
Thank you so much
