### ISSUE TITLE
[HW] Kyle MacDonald

### ISSUE THREAD

**Issue by kajankow42** [datastaxdevs/workshop-introduction-to-nosql#576]
**Name:** Kyle MacDonald
**Email:** kyle.macdonald@outlook.com
**Linkedin Profile:** https://www.linkedin.com/in/kylemacdonald25/

Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------

![Step 4](https://user-images.githubusercontent.com/80118823/135357375-1398b4e8-ed45-4103-847b-b04351c5f22b.png)

**Comment by SonicDMG** [comment]
Hey there Kyle, thank you for your submission. Nice job getting Through the workshop materials. The only thing we are missing is step 2 of the homework.
2. [Complete try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please post an image of the "completed" screen once finished.

**Comment by kajankow42** [comment]
Hey Sonic. 

Here is the additional screenshot that I missed. 

![image](https://user-images.githubusercontent.com/80118823/135485711-3ea11737-9f2a-46d0-8a07-d8f269ce1795.png)

**Comment by HadesArchitect** [comment]
Hey **Kyle MacDonald**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/otHsOT7pTfWyt2X4VXPBQA
