### ISSUE TITLE
[HW] Goudham Raj Rajasekar

### ISSUE THREAD

**Issue by GauthamRajasekar** [datastaxdevs/workshop-introduction-to-nosql#577]
**Name:** Goudham Raj Rajasekar
**Email:** gauthamr776@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/gautham-raj/

![Screenshot](https://user-images.githubusercontent.com/37381531/135363586-7595758f-50eb-4fd2-af95-735e9c11d278.PNG)
![Screenshot2](https://user-images.githubusercontent.com/37381531/135363588-aaf2959d-2b4b-4937-9ee5-05f75afce32f.PNG)
Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------

**Comment by HadesArchitect** [comment]
Hey **Goudham Raj Rajasekar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/2uRDHdu7Re-bZM7y2dPr2g
