### ISSUE TITLE
[HW] Arman Haghanifar

### ISSUE THREAD

**Issue by armiro** [datastaxdevs/workshop-introduction-to-nosql#578]
**Name:** Arman Haghanifar
**Email:** arman.haghanifar@gmail.com
**Linkedin Profile:** https://linkedin.com/in/armanhgh

Attach the homework screenshot below:
-----------------------------------------
<img width="954" alt="ex5_snapshot" src="https://user-images.githubusercontent.com/20238267/135364676-6128223f-9a7a-4f67-97d1-ddbb19841298.PNG">
<img width="957" alt="completed_scenario" src="https://user-images.githubusercontent.com/20238267/135364690-93b48a5a-10bc-4716-a0e7-5f578e069d65.PNG">

**Comment by HadesArchitect** [comment]
Hey **Arman Haghanifar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/sGTC6xOBSneUMVH52qUkkg

**Comment by SonicDMG** [comment]
Excellent job doing the graph section. We hope that was informational.

**Comment by armiro** [comment]
@SonicDMG Thanks! I do really need to learn Docker and Kubernetes as part of my career path.

**Comment by SonicDMG** [comment]
This, might be useful https://www.youtube.com/playlist?list=PL2g2h-wyI4Sq_6MQEVn4fFmjSJ10IwVrU BTW, K8ssandra is a full fledged control plane and tools for Cassandra on k8s, if fully open source, and is what Astra runs on. Might be worth checking out per your k8s journey.
