### ISSUE TITLE
[HW] workshop-introduction-to-sql

### ISSUE THREAD

**Issue by oain-mait** [datastaxdevs/workshop-introduction-to-nosql#579]
**Name:** Ojaswin Jain
**Email:** ojaswinjain@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/14894848/135388709-6bb7e29c-610f-4180-b4ae-fba58ee30406.png)
-- images removed by team --
![image](https://user-images.githubusercontent.com/14894848/135388950-e52774b8-af57-4aa5-9512-3c3956fdd35c.png)
![image](https://user-images.githubusercontent.com/14894848/135388989-9210c96d-4a60-4739-b0a1-06c66c9a2493.png)
-- images removed by team --

**Comment by HadesArchitect** [comment]
Hey **Ojaswin Jain**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/XIsSTxoUQ0KEVj1OHK1Qyw
