### ISSUE TITLE
[HW] Chris Raile

### ISSUE THREAD

**Issue by craile** [datastaxdevs/workshop-introduction-to-nosql#58]
**Name:** Chris Raile
**Email:** datastax@raile.org
**Linkedin Profile:** n/a

Attach the homework screenshots below:
-----------------------------------------

![Step 1-1](https://user-images.githubusercontent.com/56035927/118999404-db6f6e00-b94f-11eb-8351-5717c69ee2b1.png)
![Step 2-1](https://user-images.githubusercontent.com/56035927/118999428-e0342200-b94f-11eb-9544-251c9050df39.png)
![Step 2-2](https://user-images.githubusercontent.com/56035927/118999439-e2967c00-b94f-11eb-87da-f46661b51a49.png)
![Step 3-1](https://user-images.githubusercontent.com/56035927/118999449-e4f8d600-b94f-11eb-908e-b11d11afc59e.png)
-- images removed by team --
![Step 4-1](https://user-images.githubusercontent.com/56035927/118999475-e924f380-b94f-11eb-87ef-fae3ac27e059.png)
-- images removed by team --
![TryItOut](https://user-images.githubusercontent.com/56035927/118999490-ed511100-b94f-11eb-9536-474b84d6e59a.png)

**Comment by RyanWelford** [comment]
Great job Chris! Thank you!

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/AWw-EVu3TIWvrCCB5vvY4w?identity__email=datastax%40raile.org
