### ISSUE TITLE
[HW] Henry Naftulin

### ISSUE THREAD

**Issue by writencode** [datastaxdevs/workshop-introduction-to-nosql#581]
**Name:** Henry Naftulin
**Email:** mail2henry@yahoo.com
**Linkedin Profile:** https://www.linkedin.com/in/naftulin/

Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------

<SCREENSHOT
![1_Screenshot 2021-09-30 141015](https://user-images.githubusercontent.com/15383242/135508534-15dd5448-05e8-4dac-bd7f-fdf71fc7ab33.png)
>

**Comment by SonicDMG** [comment]
Hey there Henry, thank you for your submission. Nice job getting Through the workshop materials. The only thing we are missing is step 2 of the homework.
2. [Complete try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please post an image of the "completed" screen once finished.
