### ISSUE TITLE
[HW] Max Submission of Step 4

### ISSUE THREAD

**Issue by mbding98** [datastaxdevs/workshop-introduction-to-nosql#583]
**Name:** Maxwell Ding
**Email:** mbding@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/mbding98/

Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------
![final step graphql playground](https://user-images.githubusercontent.com/48102042/135573404-b024b0e8-3b35-4dd2-ba7f-a64d4dad558e.PNG)
![final step cql console](https://user-images.githubusercontent.com/48102042/135573406-00bd1b9a-163c-4718-a1bf-fb0e5e876374.PNG)

<SCREENSHOT>

**Comment by poornimaa** [comment]
Hi,

I'm unable to create the mutation.. Here is the output of my error..

[image: image.png]

Can someone help me out?

Thanks,
Poornima

**Comment by SonicDMG** [comment]
Hey there Maxwell, looks like your mutation issue image wasn't uploaded. Can you reup please?

**Comment by mbding98** [comment]
Sorry about that! Here is the one with the mutation!

![final step graphql playground](https://user-images.githubusercontent.com/48102042/135698219-6582d2b3-9b5e-45a4-8167-735c58f1dc3d.PNG)

**Comment by SonicDMG** [comment]
Ok, that all looks good. The only thing left is to complete step 2 of the homework.
2. Complete [try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

It shouldn't take very long. :)

**Comment by mbding98** [comment]
Hello! 
Sorry for the delay! Here it is!

![scenario](https://user-images.githubusercontent.com/48102042/136598938-42a979a7-bd6e-4e89-9d4b-05a6cf9bb32d.PNG)
