### ISSUE TITLE
[HW] <ArtiJ>

### ISSUE THREAD

**Issue by ArtiJ** [datastaxdevs/workshop-introduction-to-nosql#586]
**Name:** Arti Johri
**Email:** rti.srivastava@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/arti-johri-a8b45b9/

Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------

![AJ-CQL](https://user-images.githubusercontent.com/16674071/135714223-ecbcdd63-edac-4b5f-b2be-274efdd3abbc.png)

![AJ](https://user-images.githubusercontent.com/16674071/135713828-aa4295a9-398a-4018-a92a-6ceedf2c4816.PNG)

**Comment by ArtiJ** [comment]
![AJ-CQL](https://user-images.githubusercontent.com/16674071/135714246-eb84fc7a-6e6a-4605-9586-ab4315a47a16.png)

**Comment by HadesArchitect** [comment]
Hey **Arti Johri**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ORQoci0vTd-Hdl49SYOB5A
