### ISSUE TITLE
[HW] <Manthan Vishen>

### ISSUE THREAD

**Issue by Themanthanvishen** [datastaxdevs/workshop-introduction-to-nosql#587]
Name: Manthan Vishen
Email: rajputmanthan98@gmail.com
https://www.linkedin.com/in/manthanvishen/

I have successfully completed the workshop and the homework too! 

Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------
![Screenshot (1)](https://user-images.githubusercontent.com/90868958/135728536-f3e627b1-ecdb-4b02-a1f9-2542480c9cb5.png)
![Screenshot (2)_LI](https://user-images.githubusercontent.com/90868958/135728548-c7596715-f02e-4723-8212-4ecc74e63c1e.jpg)

![Screenshot (1)](https://user-images.githubusercontent.com/90868958/135728560-be555ff9-8ead-4615-b64a-74dcbe854b65.png)
![Screenshot (2)_LI](https://user-images.githubusercontent.com/90868958/135728561-46baea74-25ef-46e6-8864-45395a8ace0a.jpg)

**Comment by Themanthanvishen** [comment]
Here I Manthan Vishen is attaching my tryitout scenario.
please have a check.

**Comment by SonicDMG** [comment]
Ok, I saw it. Looks good, thank you.

**Comment by HadesArchitect** [comment]
Hey **Manthan Vishen**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/mUA2W1InSduUFXp8uAn_4Q
