### ISSUE TITLE
[HW] <workshop-introduction-to-nosql>

### ISSUE THREAD

**Issue by iamindika** [datastaxdevs/workshop-introduction-to-nosql#588]
**Name:** Indika Kolamba Tantrege
**Email:** ikolamba2@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/indika-kolamba-tantrege-b2ba3b201/>

Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------

![Screen Shot 2021-10-02 at 5 18 07 PM](https://user-images.githubusercontent.com/31863947/135732191-ee182258-d9d1-438b-91bf-d6e9d8a84f12.png)

![Screen Shot 2021-10-02 at 12 10 12 PM](https://user-images.githubusercontent.com/31863947/135732197-35bf49d3-76ab-47f3-bfee-26913896bc18.png)

**Comment by HadesArchitect** [comment]
Hey **Indika Kolamba Tantrege**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/pNt6LdknSRS8e9U9R0bSKQ
