### ISSUE TITLE
[HW Introduction to NoSQL Databases] <Gregory John Carberry>

### ISSUE THREAD

**Issue by Carbs-78** [datastaxdevs/workshop-introduction-to-nosql#589]
**Name:** Gregory John Carberry
**Email:** gjc01@hotmail.co.uk
**Linkedin Profile:** https://www.linkedin.com/in/gregory-carberry/
![Screenshot Task4(1)](https://user-images.githubusercontent.com/83065502/135734931-0b3ec1c7-43d8-40b6-a469-216bec1f30e6.png)
![Screenshot Task4(2)](https://user-images.githubusercontent.com/83065502/135734935-c2d762be-8a3e-4cc0-9e4f-f47c76582146.png)
![Screenshot Try It Out scenario(1)](https://user-images.githubusercontent.com/83065502/135734938-9fad35a4-7ae1-4ec1-976c-ed60ddede502.png)
![Screenshot Try It Out scenario(2)](https://user-images.githubusercontent.com/83065502/135734939-911cb973-7d4d-4186-8778-c98f8f72fd8a.png)

Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------

<SCREENSHOT>

**Comment by HadesArchitect** [comment]
Hey **Gregory John Carberry**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/v9t1nrLrSo6_6U63FOpu9g
