### ISSUE TITLE
[HW] <Pramod Gajre>

### ISSUE THREAD

**Issue by pramodgajre-gh** [datastaxdevs/workshop-introduction-to-nosql#590]
**Name:** Pramod Gajre
**Email:** pramodgajre@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------
Thank you for hands on try out options, good to build primary level understanding.

![Astradb-PramodG-Homework-2Oct2021](https://user-images.githubusercontent.com/91812096/135735959-cb73972e-419b-43a0-a32a-0302cc34f11b.png)
![Astradb-PramodG-Homework1-2Oct2021](https://user-images.githubusercontent.com/91812096/135735960-bf3106e9-6054-419b-8450-e9f3ea6ea489.png)

<SCREENSHOT>

**Comment by HadesArchitect** [comment]
Hey **Pramod Gajre**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/0w75eWlhRpGyyR2Z0ReeHg

**Comment by pramodgajre-gh** [comment]
Thanks Aleks! @HadesArchitect
