### ISSUE TITLE
[HW] Joseph

### ISSUE THREAD

**Issue by jchen76** [datastaxdevs/workshop-introduction-to-nosql#591]
**Name:** Joseph Chen
**Email:** josephchen817@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/joseph-chen-1590811/

Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------

![image](https://user-images.githubusercontent.com/28128065/135746409-55cf3cdc-ed3f-4e31-a2af-cf8212198814.png)

**Comment by SonicDMG** [comment]
Hey there Joseph, thank you for your submission. Nice job getting Through the workshop materials. The only thing we are missing is step 2 of the homework.
2. [Complete try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please post an image of the "completed" screen once finished.

**Comment by jchen76** [comment]
Here are the screenshots.
![image](https://user-images.githubusercontent.com/28128065/135861380-b50dd8dc-217b-4158-8a2d-11842f9211a5.png)
![image](https://user-images.githubusercontent.com/28128065/135861519-b136d3f2-862f-4744-a3c5-d11bc3bb663f.png)

**Comment by HadesArchitect** [comment]
Hey **Joseph Chen**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/SCpUKbGlTh60R--R1VLGHg
