### ISSUE TITLE
[HW] <Mostafa Fadaeefath Abadi>

### ISSUE THREAD

**Issue by mostafaf1987** [datastaxdevs/workshop-introduction-to-nosql#592]
**Name:** Mostafa_Fadaeefath_Abadi
**Email:** mostafa.fadaee@concordia.ca
**Linkedin Profile:** <https://www.linkedin.com/in/mostafa-fadaee/>

Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------
![4c  Populate the table - 3](https://user-images.githubusercontent.com/45298522/135888595-fd9c2f57-098f-4438-ba1c-c0358046dfeb.jpg)

![4c  Check with CQL Console - 2](https://user-images.githubusercontent.com/45298522/135888606-93d1aae1-2c4e-4324-a882-363e2289ff22.jpg)

![Try It Out - Cassandra Query Language (CQL) - Step 7](https://user-images.githubusercontent.com/45298522/135888626-e4030d03-962f-4263-997c-faf275df6294.jpg)

![Complete try-it-out scenario](https://user-images.githubusercontent.com/45298522/135888642-327b4549-ed2c-42f4-9e96-8b2810ad7056.jpg)

**Comment by mostafaf1987** [comment]
Hello and thank you very much!

**Comment by mostafaf1987** [comment]
@RyanWelford @HadesArchitect @SonicDMG Hello, please review my homework.
I have sent it 13 hours ago.
Thank you very much.

**Comment by HadesArchitect** [comment]
Hey **Mostafa_Fadaeefath_Abadi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ow4_k-W9QPeh0sPWWhklog

**Comment by mostafaf1987** [comment]
> Hey **Mostafa_Fadaeefath_Abadi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ow4_k-W9QPeh0sPWWhklog

Hello@HadesArchitect Thank you very much for the valuable workshop!
