### ISSUE TITLE
[HW] <Tsycz >Nosql workshop homework

### ISSUE THREAD

**Issue by Tsycz** [datastaxdevs/workshop-introduction-to-nosql#595]
**Name:** T Sycz
**Email:** tsycz@southingtonschools.org
**Linkedin Profile:** 
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/tsycz/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/tsycz/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/tsycz/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

http://linkedin.com/in/tamatha-s-a92ab850
--

</html>

Attach the homework screenshot below: Remember, you only need the last screen of the step you have completed, step IV or V
-----------------------------------------
![image](https://user-images.githubusercontent.com/79209796/136097990-c1acf95c-6bb3-4925-883c-f41c357daf1d.png)
![image](https://user-images.githubusercontent.com/79209796/136098026-af7b1431-20d0-4d13-af37-02ddf5b3d033.png)
![image](https://user-images.githubusercontent.com/79209796/136098039-41ad2556-ea9a-4347-9147-1e82c81a9970.png)
-- images removed by team --

**Comment by SonicDMG** [comment]
Hey there Tammy, thank you for your submission. Nice job getting Through the workshop materials. The only thing we are missing is step 2 of the homework.
2. [Complete try-it-out scenario](https://www.datastax.com/try-it-out) and make a screenshot of the "scenario completed" screen

Please post an image of the "completed" screen once finished.

**Comment by SonicDMG** [comment]
I also removed a set of your images because they contained your Astra token. Please delete your token via the Astra UI to ensure there are no security issues.
