### ISSUE TITLE
[HW] Dhinesh Sundararaj

### ISSUE THREAD

**Issue by dhineshdurai** [datastaxdevs/workshop-introduction-to-nosql#6]
Hi Datastax team/ @HadesArchitect ,
I followed the steps in workshop for the docker exercise. I am new to docker/containers and I have installed docker, cloned the repo, did a docker-compose, I could see the container is created and running. But I am not able to see the page when I access localhost:9091. I am currently running it in Linux Mint. Could you please help me with what I am missing.

![image](https://user-images.githubusercontent.com/60195378/113330136-0a983480-933c-11eb-8f5f-f14f36ca53f8.png)

Regards
Dhinesh

**Comment by kennethheung** [comment]
try to do a `docker logs workshopintroductiontonosql_studio_1` and see why. the most common issue is the container does not have write access to the host folder. A quick and dirty **but not recommended** workaround is to do chmod

**Comment by dhineshdurai** [comment]
Hi @kennethheung , Yes. You're correct. I checked the logs was due to permission issue. I have completed the setting up docker and I have completed the docker task. Thanks for the help. Kindly have a look at the screenshots below.

![1](https://user-images.githubusercontent.com/60195378/114152418-e93ad800-993b-11eb-8dea-84ec17e95b88.jpg)
![2](https://user-images.githubusercontent.com/60195378/114152422-ecce5f00-993b-11eb-8d14-7ae873aa29c5.jpg)
![3](https://user-images.githubusercontent.com/60195378/114152429-ee982280-993b-11eb-8faf-72c5dca80fc5.jpg)
![4_namespace_creation](https://user-images.githubusercontent.com/60195378/114152439-f0fa7c80-993b-11eb-8e65-5761560b487e.jpg)
![5_namespace_showall](https://user-images.githubusercontent.com/60195378/114152448-f35cd680-993b-11eb-8dbd-1fdb1f66a6f7.jpg)
![6_namespace_creation](https://user-images.githubusercontent.com/60195378/114152466-f788f400-993b-11eb-9e7c-e58a4f0593b1.jpg)
![7_document_creation](https://user-images.githubusercontent.com/60195378/114152473-f9eb4e00-993b-11eb-9c48-3bfe3d11bc69.jpg)
![8_graphql_login](https://user-images.githubusercontent.com/60195378/114152483-fce63e80-993b-11eb-8513-9c2b8ac0202f.jpg)
![9_check_K_V](https://user-images.githubusercontent.com/60195378/114152486-fe176b80-993b-11eb-98e0-530b1e6a17a2.jpg)
![10_Docker_network_create](https://user-images.githubusercontent.com/60195378/114152542-0a032d80-993c-11eb-9bfc-27f6c0836b78.jpg)
![11_docker_composer](https://user-images.githubusercontent.com/60195378/114152504-02dc1f80-993c-11eb-8c0b-0fa9fe065435.jpg)
![12 docker1](https://user-images.githubusercontent.com/60195378/114152513-04a5e300-993c-11eb-96ab-c152f9ce11da.png)
![13 docker2](https://user-images.githubusercontent.com/60195378/114152516-053e7980-993c-11eb-8250-b65236ac29eb.png)
![14 docker3](https://user-images.githubusercontent.com/60195378/114152518-05d71000-993c-11eb-852c-5b821a8759de.png)
![15 docker4](https://user-images.githubusercontent.com/60195378/114152521-07083d00-993c-11eb-804a-5d92174c5e28.png)
![16 docker5](https://user-images.githubusercontent.com/60195378/114152529-07a0d380-993c-11eb-864b-07f4955676f6.png)
![17 docker6](https://user-images.githubusercontent.com/60195378/114152531-08396a00-993c-11eb-924e-5ac361b615d6.png)
![18 docker7](https://user-images.githubusercontent.com/60195378/114152539-096a9700-993c-11eb-9af7-218276ec0f3d.png)

**Comment by dhineshdurai** [comment]
Name: Dhinesh Sundararaj
Email: dhineshdurai@gmail.com
Linkedin Profile: https://www.linkedin.com/in/dhinesh-sundararaj-00a18b24/

**Comment by dhineshdurai** [comment]
++ @HadesArchitect

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/xh2OreTGRVio6GL8oxRzsQ
