### ISSUE TITLE
[HW] <Nitin Lal Chandani>

### ISSUE THREAD

**Issue by NitinLalChandani** [datastaxdevs/workshop-introduction-to-nosql#60]
**Name:** <Nitin Lal Chandani>
**Email:** <nitin.iphone29@gmail.com>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
-- images removed by team --

**Comment by SonicDMG** [comment]
Great job Nitin, thank you.

**Comment by NitinLalChandani** [comment]
Thank you so much for the acceptance and approval.

**Comment by HadesArchitect** [comment]
Badge issued! Great job, Nitin! https://api.badgr.io/public/assertions/FlTqV3gbQR6F039d1BHNmw?identity__email=nitin.iphone29%40gmail.com
