### ISSUE TITLE
[HW] Partha Sarathi Chowdhury

### ISSUE THREAD

**Issue by pcpschow1** [datastaxdevs/workshop-introduction-to-nosql#64]
**Name:**  Partha Sarathi Chowdhury
**Email:**  pcpschow1@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/partha-sarathi-chowdhury-72535459/

Attach the homework screenshots below:
-----------------------------------------
![Screenshot_1](https://user-images.githubusercontent.com/84148929/119098946-092de300-ba34-11eb-8ad6-61b36ae74f97.png)
![Screenshot_2](https://user-images.githubusercontent.com/84148929/119098960-0b903d00-ba34-11eb-89d6-a93473f7c14d.png)
![Screenshot_3](https://user-images.githubusercontent.com/84148929/119098963-0c28d380-ba34-11eb-80dc-99515b8c7428.png)
![Screenshot_4](https://user-images.githubusercontent.com/84148929/119098964-0cc16a00-ba34-11eb-9e5d-4626ee146e0d.png)
![Screenshot_5](https://user-images.githubusercontent.com/84148929/119098965-0cc16a00-ba34-11eb-9fe2-7ad5aecdf7c2.png)
![Screenshot_6](https://user-images.githubusercontent.com/84148929/119098966-0d5a0080-ba34-11eb-8667-c9ee4baeb2ea.png)
![Screenshot_7](https://user-images.githubusercontent.com/84148929/119098970-0d5a0080-ba34-11eb-9044-1834ee2e8f1a.png)
![Screenshot_8](https://user-images.githubusercontent.com/84148929/119098971-0df29700-ba34-11eb-8a44-ddeab9a2d045.png)
![Screenshot_9](https://user-images.githubusercontent.com/84148929/119098974-0e8b2d80-ba34-11eb-91b4-5ba0b0c6695a.png)
![Screenshot_10](https://user-images.githubusercontent.com/84148929/119098976-0f23c400-ba34-11eb-85fc-70239f8970a4.png)
![Screenshot_11](https://user-images.githubusercontent.com/84148929/119098978-0f23c400-ba34-11eb-92ab-1f0a9ab8f027.png)
![Screenshot_12](https://user-images.githubusercontent.com/84148929/119098982-0fbc5a80-ba34-11eb-8893-a55323bd3d4f.png)
![Screenshot_13](https://user-images.githubusercontent.com/84148929/119098984-1054f100-ba34-11eb-910c-25859855e83c.png)
![Screenshot_14](https://user-images.githubusercontent.com/84148929/119098988-10ed8780-ba34-11eb-8173-a201062861d5.png)
![Screenshot_15](https://user-images.githubusercontent.com/84148929/119098989-10ed8780-ba34-11eb-9956-46e4fb9ac0f2.png)
![Screenshot_16](https://user-images.githubusercontent.com/84148929/119098995-11861e00-ba34-11eb-9c38-f0447ac0efce.png)
-- images removed by team --
![Screenshot_29](https://user-images.githubusercontent.com/84148929/119099019-15b23b80-ba34-11eb-9a2b-8ea230484b98.png)
-- images removed by team --
![Screenshot_31](https://user-images.githubusercontent.com/84148929/119099023-164ad200-ba34-11eb-9ea0-b03afd3d6b1e.png)
![Screenshot_32](https://user-images.githubusercontent.com/84148929/119099024-16e36880-ba34-11eb-871a-c1bbf00d95e2.png)

**Comment by SonicDMG** [comment]
Really nice job Partha, thank you.

**Comment by HadesArchitect** [comment]
Great job! https://api.badgr.io/public/assertions/xfiMpXbrS-ienLoz1s44fg?identity__email=pcpschow1%40gmail.com
