### ISSUE TITLE
[HW] <Manish Kumar>

### ISSUE THREAD

**Issue by manishkumarsinha-001** [datastaxdevs/workshop-introduction-to-nosql#66]
**Name:** <Manish Kumar>
**Email:** <Manish.kumar01982@gmail.com>
**Linkedin Profile:** <www.linkedin.com/in/manish-kumar-b3a4b513>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
-- images removed by team --
<img width="1305" alt="Screenshot 2021-05-21 at 7 31 49 PM" src="https://user-images.githubusercontent.com/84192822/119149560-4366a700-ba6b-11eb-9a47-01aff032b01b.png">
-- images removed by team --
<img width="1287" alt="Screenshot 2021-05-21 at 7 36 16 PM" src="https://user-images.githubusercontent.com/84192822/119150202-d7d10980-ba6b-11eb-9e3f-6cd49a0295d4.png">
<img width="1302" alt="Screenshot 2021-05-21 at 7 35 33 PM" src="https://user-images.githubusercontent.com/84192822/119150236-df90ae00-ba6b-11eb-843e-f21dfabe09dd.png">

**Comment by RyanWelford** [comment]
Excellent! Thanks Manish!

**Comment by manishkumarsinha-001** [comment]
How to get the badge?? I suppose u will issue it right?

**Comment by HadesArchitect** [comment]
Here we go! https://api.badgr.io/public/assertions/f1pa9BQ2SdGhaMtQkvW_tQ?identity__email=manish.kumar01982%40gmail.com
