### ISSUE TITLE
[HW] <Shubham Prakash>

### ISSUE THREAD

**Issue by Shubham041** [datastaxdevs/workshop-introduction-to-nosql#67]
**Name:** <Shubham Prakash>
**Email:** <shubham041@hotmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/shubhamthecoder/>

Attach the homework screenshots below:
-----------------------------------------
                                                  
![image](https://user-images.githubusercontent.com/62212139/119219868-4ada8e80-bb05-11eb-8dc2-90de53b7db9e.png)
![image](https://user-images.githubusercontent.com/62212139/119219874-5037d900-bb05-11eb-9e19-1e191a5631a9.png)
![image](https://user-images.githubusercontent.com/62212139/119219894-6d6ca780-bb05-11eb-836c-cddf1b1b5dcd.png)
![image](https://user-images.githubusercontent.com/62212139/119219902-70679800-bb05-11eb-9f01-dc45edc57327.png)
![image](https://user-images.githubusercontent.com/62212139/119219908-73628880-bb05-11eb-949c-a6aa6f24c73d.png)
![image](https://user-images.githubusercontent.com/62212139/119219910-752c4c00-bb05-11eb-8663-e3286d5e5094.png)
![image](https://user-images.githubusercontent.com/62212139/119219913-778ea600-bb05-11eb-909e-156285fe4d34.png)
![image](https://user-images.githubusercontent.com/62212139/119219915-7a899680-bb05-11eb-8bfe-539f81be1721.png)
![image](https://user-images.githubusercontent.com/62212139/119219917-7cebf080-bb05-11eb-835c-1540c3dafb79.png)
![image](https://user-images.githubusercontent.com/62212139/119219920-7eb5b400-bb05-11eb-85e2-55f5be191fdf.png)
![image](https://user-images.githubusercontent.com/62212139/119219924-81b0a480-bb05-11eb-9801-98305c7a9af5.png)
![image](https://user-images.githubusercontent.com/62212139/119219928-8412fe80-bb05-11eb-949c-20c6f1024b33.png)
-- images removed by team --
![image](https://user-images.githubusercontent.com/62212139/119219949-9ab95580-bb05-11eb-9779-59a90440cf08.png)
-- images removed by team --
![image](https://user-images.githubusercontent.com/62212139/119219958-9f7e0980-bb05-11eb-9bb6-a48a4e505f78.png)
![image](https://user-images.githubusercontent.com/62212139/119219960-a278fa00-bb05-11eb-9a5b-7cde514b6fa7.png)
![image](https://user-images.githubusercontent.com/62212139/119219961-a4db5400-bb05-11eb-8f16-dbd42fdee118.png)

**Comment by HadesArchitect** [comment]
👍👍👍

**Comment by Shubham041** [comment]
> 👍👍👍

Sir I didn't able to find the badge... Thanks

**Comment by SonicDMG** [comment]
Here you go Shubham -> https://api.badgr.io/public/assertions/HnzUIcN3TDSnNDW81J9kLg?identity__email=shubham041%40hotmail.com

**Comment by Shubham041** [comment]
Thanks!!!

________________________________
