### ISSUE TITLE
[HW] Pushkar Singh

### ISSUE THREAD

**Issue by pushkar-singh-cse** [datastaxdevs/workshop-introduction-to-nosql#68]
**Name:** Pushkar Singh
**Email:** puskarsingh0@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/pushkar-s/

Attach the homework screenshots below:
-----------------------------------------
![Step1](https://user-images.githubusercontent.com/52779762/119226880-f0ebc000-bb28-11eb-93b0-1dc53ad5f55f.JPG)
![Step2_1](https://user-images.githubusercontent.com/52779762/119226883-f2b58380-bb28-11eb-8836-649ccd606929.JPG)
![Step2_2](https://user-images.githubusercontent.com/52779762/119226885-f47f4700-bb28-11eb-97ce-c8ccfde5ccbd.JPG)
![Step2_3](https://user-images.githubusercontent.com/52779762/119226889-fc3eeb80-bb28-11eb-8310-713c3875daa1.JPG)
![Step2_4](https://user-images.githubusercontent.com/52779762/119226912-1d9fd780-bb29-11eb-9bf8-996604ed9955.JPG)
![Step3a](https://user-images.githubusercontent.com/52779762/119226920-285a6c80-bb29-11eb-941e-22f3bced61ec.JPG)
![Step3b](https://user-images.githubusercontent.com/52779762/119226924-2a243000-bb29-11eb-8798-4a5969a31db7.JPG)
![Step3b_1](https://user-images.githubusercontent.com/52779762/119226926-2b555d00-bb29-11eb-8f0c-c6d37f36bb84.JPG)
-- images removed by team --
![Step4b_1](https://user-images.githubusercontent.com/52779762/119226939-36a88880-bb29-11eb-9d40-2c96f8372bc2.JPG)
![Step4c](https://user-images.githubusercontent.com/52779762/119226943-3b6d3c80-bb29-11eb-9a6c-523c30bb1ede.JPG)
![Step5b](https://user-images.githubusercontent.com/52779762/119226952-4cb64900-bb29-11eb-87c0-a8b6d310f1a2.JPG)
![try_it_out](https://user-images.githubusercontent.com/52779762/119226968-5cce2880-bb29-11eb-977c-5e4c9db23cde.JPG)

**Comment by HadesArchitect** [comment]
Great job!

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/qW5XABy6S1GO8S0k4qiNtA?identity__email=puskarsingh0%40gmail.com
