### ISSUE TITLE
[HW] SRI

### ISSUE THREAD

**Issue by Shadow-002** [datastaxdevs/workshop-introduction-to-nosql#69]
**Name:** SRI
**Email:** sri05@protonmail.com
**Linkedin Profile:** none

Attach the homework screenshots below:
-----------------------------------------
![Step-1_1](https://user-images.githubusercontent.com/53784459/119230985-441b3e00-bb3c-11eb-898c-7e861b81bf05.png)
![Step-1_2](https://user-images.githubusercontent.com/53784459/119230986-454c6b00-bb3c-11eb-83f8-2fedcce7b85d.png)

![Step-2_1](https://user-images.githubusercontent.com/53784459/119231030-6c0aa180-bb3c-11eb-976a-06dce2dface1.png)
![Step-2_2](https://user-images.githubusercontent.com/53784459/119231032-6d3bce80-bb3c-11eb-886d-9adff77dc060.png)

![Step-3_1](https://user-images.githubusercontent.com/53784459/119231065-93fa0500-bb3c-11eb-84ac-899c20b412f2.png)
![Step-3_2](https://user-images.githubusercontent.com/53784459/119231066-94929b80-bb3c-11eb-96b4-569692d944b7.png)

![Step-4_1](https://user-images.githubusercontent.com/53784459/119231106-c277e000-bb3c-11eb-912b-864d5ff03643.png)
![Step-4_2](https://user-images.githubusercontent.com/53784459/119231108-c3a90d00-bb3c-11eb-9b97-13df7b510a69.png)

![Scenario Completed](https://user-images.githubusercontent.com/53784459/119231131-d9b6cd80-bb3c-11eb-8c83-354ce29578b4.png)

**Comment by HadesArchitect** [comment]
Well done! To issue the badge, I need your full name (official full name).

**Comment by Shadow-002** [comment]
My full name is : SRINIVAS B A

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Shadow-002** [comment]
My full name is : SRI

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/jbvp9NctRDugsdi_1cr40A?identity__email=sri05%40protonmail.com
