### ISSUE TITLE
[HW] Kenneth Heung

### ISSUE THREAD

**Issue by kennethheung** [datastaxdevs/workshop-introduction-to-nosql#7]
**Name:** Kenneth Heung
**Email:** kenneth.heung@gmail.com
**Linkedin Profile:** [NIL]

Attach the homework screenshots below:
-----------------------------------------

<img width="1310" alt="Screenshot 2021-04-02 at 10 30 59 AM" src="https://user-images.githubusercontent.com/9417297/113374078-d9048500-939e-11eb-9aac-21fcc07ea27d.png">

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/giPjoXeQTBO0enL2Ly_hpw
