### ISSUE TITLE
[HW]  Nikhil T M

### ISSUE THREAD

**Issue by Nikhil0321** [datastaxdevs/workshop-introduction-to-nosql#71]
**Name:** Nikhil T M
**Email:** nikhil0321@protonmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Capture](https://user-images.githubusercontent.com/77892100/119232880-6913af00-bb44-11eb-900b-7d43c9908c27.JPG)
![Capture1](https://user-images.githubusercontent.com/77892100/119232883-6a44dc00-bb44-11eb-8859-2f798b69d74e.JPG)
![Capture2](https://user-images.githubusercontent.com/77892100/119232886-6e70f980-bb44-11eb-9485-c0ad37a4bcbb.JPG)
![Capture3](https://user-images.githubusercontent.com/77892100/119232888-703abd00-bb44-11eb-822e-304bf3bc9224.JPG)
![Capture4](https://user-images.githubusercontent.com/77892100/119232899-7335ad80-bb44-11eb-9496-487664aa6c50.JPG)
![Capture5](https://user-images.githubusercontent.com/77892100/119232905-74ff7100-bb44-11eb-8ab9-040cc2c2e588.JPG)
![Capture6](https://user-images.githubusercontent.com/77892100/119232915-7761cb00-bb44-11eb-8fa6-66db20e8addc.JPG)
![Capture7](https://user-images.githubusercontent.com/77892100/119232919-7892f800-bb44-11eb-97f3-0ec857e75721.JPG)
![Capture8](https://user-images.githubusercontent.com/77892100/119232921-7a5cbb80-bb44-11eb-8cc0-647715fdb85c.JPG)
![Capture9](https://user-images.githubusercontent.com/77892100/119232926-7b8de880-bb44-11eb-9a33-eb29139432ee.JPG)
![Capture10](https://user-images.githubusercontent.com/77892100/119232931-7d57ac00-bb44-11eb-938a-acd04c76d3ff.JPG)
![Capture11](https://user-images.githubusercontent.com/77892100/119232938-7f216f80-bb44-11eb-950b-858db889f784.JPG)
![Capture12](https://user-images.githubusercontent.com/77892100/119232947-80529c80-bb44-11eb-8842-bfbaf21ea390.JPG)
-- images removed by team --
![Capture21](https://user-images.githubusercontent.com/77892100/119232984-8fd1e580-bb44-11eb-838f-4bb9193a21d4.JPG)
-- images removed by team --
![Capture23](https://user-images.githubusercontent.com/77892100/119232988-92343f80-bb44-11eb-8aa6-dc7a9a7fb894.JPG)
![Capture24](https://user-images.githubusercontent.com/77892100/119232990-93fe0300-bb44-11eb-9d2e-37c0a691a1ab.JPG)

**Comment by Nikhil0321** [comment]
good

**Comment by HadesArchitect** [comment]
Great job!

**Comment by HadesArchitect** [comment]
To issue the badge, I need a full name, an "official" one

**Comment by Nikhil0321** [comment]
> To issue the badge, I need a full name, an "official" one

"Nikhil T M"

**Comment by SonicDMG** [comment]
Ok, Nikhil, here you go. https://api.badgr.io/public/assertions/Md34Ujc8Rva1fXlSxQ65eQ?identity__email=nikhil0321%40protonmail.com
