### ISSUE TITLE
[Introduction to NotOnly SQL Databases] Akhilesh Chafale

### ISSUE THREAD

**Issue by akhileshc** [datastaxdevs/workshop-introduction-to-nosql#73]
**Name:** Akhilesh Chafale
**Email:** akhileshchafale@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/akhilesh-chafale-6064a645/

Attach the homework screenshots below:
-----------------------------------------

Step 1: Create Astra Instance
![image](https://user-images.githubusercontent.com/25613531/119262520-32e43700-bbf9-11eb-94b4-2ae78d32e6af.png)
 
Step 2: Tabular Databases
![image](https://user-images.githubusercontent.com/25613531/119262531-3b3c7200-bbf9-11eb-9f1f-da3fc72c92e8.png)
![image](https://user-images.githubusercontent.com/25613531/119262536-3e376280-bbf9-11eb-899c-9e02b6492622.png)
![image](https://user-images.githubusercontent.com/25613531/119262544-4099bc80-bbf9-11eb-82e6-2e153a131c3a.png)

Step 3: Document Databases
![image](https://user-images.githubusercontent.com/25613531/119262557-4a232480-bbf9-11eb-9917-282c4248dea1.png)

 Swagger Create a new empty collection in a namespace
-- images removed by team --

Swagger : Create a new Document
-- images removed by team --
 
Swagger: Fetch Created Col1 Document
-- images removed by team --

Step 4: KeyValue Databases
-- images removed by team --

Try It Out Scenario:
![image](https://user-images.githubusercontent.com/25613531/119262605-6a52e380-bbf9-11eb-8667-2ee26172ed0f.png)

**Comment by akhileshc** [comment]
**Could not Complete step5: Graph databases;**
I installed docker and pulled the datastax image. 
As per the steps, it did not start automatically, I had to run the docker un command to run datastax_studio container and then the dse started.
But studio did not start on localhost:9091. I tried different ports, but no success.

**Comment by HadesArchitect** [comment]
Sorry you've experienced the issue with the step V! It's optional, so the work is accepted!

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/SeLcvHADTr6Kg-OjNG9xNg?identity__email=akhileshchafale%40gmail.com
