### ISSUE TITLE
[HW] Mohammed Yunus Shariff

### ISSUE THREAD

**Issue by yunus-shariff** [datastaxdevs/workshop-introduction-to-nosql#74]
**Name:** Mohammed Yunus Shariff
**Email:** shariff.yunus96@gmail.com
**Linkedin Profile:** www.linkedin.com/in/yunus-shariff

Attach the homework screenshots below:
-----------------------------------------
![step 1-1](https://user-images.githubusercontent.com/76933994/119271782-8901ac00-bbf2-11eb-90e9-49497de47c93.png)
![step 1-2](https://user-images.githubusercontent.com/76933994/119271785-8bfc9c80-bbf2-11eb-995f-c0a2a0415eb5.png)
![step 2-1](https://user-images.githubusercontent.com/76933994/119271787-8d2dc980-bbf2-11eb-84d6-d78e3cd3b0e1.png)
![step 2-2](https://user-images.githubusercontent.com/76933994/119271789-8ef78d00-bbf2-11eb-8ec6-273dc81502fc.png)
![step 3-1](https://user-images.githubusercontent.com/76933994/119271793-90c15080-bbf2-11eb-85a6-7a9238bc88b8.png)
![step 3-5](https://user-images.githubusercontent.com/76933994/119271795-91f27d80-bbf2-11eb-9eaf-9d6e51451acc.png)
![Try-It-Out](https://user-images.githubusercontent.com/76933994/119271798-94ed6e00-bbf2-11eb-836a-1abb8f8e67a9.png)

**Comment by HadesArchitect** [comment]
Great job!

**Comment by HadesArchitect** [comment]
Here we go! https://api.badgr.io/public/assertions/3HGyN6sFQOGkOzWvWYGvqw?identity__email=shariff.yunus96%40gmail.com

**Comment by yunus-shariff** [comment]
### Thank you Aleks, David and Ryan! 
Struggled quite a bit around the API section - the recording made it much more easier to follow.
Appreciate the subject matter + hands-on condensed into the workshop!

Thanks again to the team that made it possible!

Cheers,
Yunus
