### ISSUE TITLE
[HW] <DEEPAK PATIL>

### ISSUE THREAD

**Issue by Deepzoid** [datastaxdevs/workshop-introduction-to-nosql#75]
**Name:** 
DEEPAK S. PATIL
**Email:** 
dspatil26701@gmail.com

**Linkedin Profile:** 
https://www.linkedin.com/in/deepak-patil-440881201/

-- images removed by team --

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by clun** [comment]
Hi there DEEPAK, thank you for your submission. 

Looks like you completed the repo work, great. Please provide a screenshot from homework step 2 as well.
2. Complete [try-it-out](https://www.datastax.com/try-it-out) scenario and make a screenshot of the "scenario completed" screen

**Comment by deepak-04** [comment]
![18](https://user-images.githubusercontent.com/72160764/119511867-7624de00-bd90-11eb-8c69-0cf316f71915.png)
![19](https://user-images.githubusercontent.com/72160764/119511882-77eea180-bd90-11eb-8a4a-7c9fcb97097d.png)

**Comment by SonicDMG** [comment]
Ok, looks good Deepak, thank you.
