### ISSUE TITLE
Workshop Introduction to NoSQL- Nikhil Jain

### ISSUE THREAD

**Issue by NikhilJainNJ** [datastaxdevs/workshop-introduction-to-nosql#78]
**Name:** NIKHIL JAIN
**Email:** jain1999.nikhil@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nikhil-jain1999

Attach the homework screenshots below:
-----------------------------------------
-- images removed by team --

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks good Nikhil, thank you.

Here's your badge, nice job. https://api.badgr.io/public/assertions/dpEb1NnMQ461zB7ookVhRQ?identity__email=jain1999.nikhil%40gmail.com
