### ISSUE TITLE
[HW] <SaiRamaKrishna>

### ISSUE THREAD

**Issue by myselfsrk** [datastaxdevs/workshop-introduction-to-nosql#79]
**Name:** <SaiRamaKrishna>
**Email:** <sairamakrishna.srk96@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/sai-rama-krishna-srk96/>

Attach the homework screenshots below:
-----------------------------------------

-- images removed by team --

**Comment by SonicDMG** [comment]
Looks good Sai, thank you.

Here's your badge, good job. https://api.badgr.io/public/assertions/G3RBKej5RTe6QkHiHh2avw?identity__email=sairamakrishna.srk96%40gmail.com
