### ISSUE TITLE
[HW] <Gordon Moore> - Introduction to NotOnly SQL Databases

### ISSUE THREAD

**Issue by gordonmoore-dev** [datastaxdevs/workshop-introduction-to-nosql#80]
**Name:** <Gordon Moore>
**Email:** <gordon........>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

-- images removed by team --

**Comment by SonicDMG** [comment]
Looks like you worked through the Docker issue on Windows using Ubuntu. Nice job on that. Sorry the windows version caused you issues. Also, really nice job getting through the graph portion. Very cool. Here you go -> https://api.badgr.io/public/assertions/zD9-YLiGTn-urLP67qlzxA?identity__email=gordon.moore%40cardinal-it.co.uk
