### ISSUE TITLE
Workshop Introduction to NoSQL- Akanksha Tripathi

### ISSUE THREAD

**Issue by akankshatripathi24** [datastaxdevs/workshop-introduction-to-nosql#83]
**Name:** Akanksha Tripathi
**Email:** akankshatripathi291@gmail.com
**Linkedin Profile:** 
-- images removed by team --

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by akankshatripathi24** [comment]
Hi All,

Let me know your reviews.

Thanks

**Comment by SonicDMG** [comment]
Looks great Akanksha, nice job. I've removed the images because some included your Astra tokens. Please ensure to delete the token you used within Astra. Here's your badge -> https://api.badgr.io/public/assertions/VtadHJ_CR_2yd13pZVw8Cw?identity__email=akankshatripathi291%40gmail.com
