### ISSUE TITLE
[HW] <Narahari Krishna Galla>

### ISSUE THREAD

**Issue by Narahari7RK** [datastaxdevs/workshop-introduction-to-nosql#85]
**Name:** Narahari Krishna Galla
**Email:** naraharikrishna17@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/narahari-krishna-galla-44a8571a/

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/66745531/120524157-c01b4e80-c3a4-11eb-84ac-9df6d652aa1a.png)

![image](https://user-images.githubusercontent.com/66745531/120524811-75e69d00-c3a5-11eb-9ceb-6e88011a8221.png)

![image](https://user-images.githubusercontent.com/66745531/120524892-8dbe2100-c3a5-11eb-9cd5-646de65bd89a.png)

![image](https://user-images.githubusercontent.com/66745531/120525057-b6461b00-c3a5-11eb-9ed9-82db929f6fe8.png)

**Comment by SonicDMG** [comment]
Perfect Narahari, nice job. Here's your badge -> https://api.badgr.io/public/assertions/xqrer9nyS9KXF36-hhqs2Q?identity__email=naraharikrishna17%40gmail.com
