### ISSUE TITLE
[NOSQL HW] <Jessica Nyon>

### ISSUE THREAD

**Issue by jess-ny** [datastaxdevs/workshop-introduction-to-nosql#86]
**Name:** Jessica Nyon
**Email:** nyon.jessica@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/jessica-nyon/

Attach the homework screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/85250809/120528391-411c1b00-c390-11eb-8e35-9417ac768a67.png)
![image](https://user-images.githubusercontent.com/85250809/120529030-e8994d80-c390-11eb-86b2-a8db7a996426.png)

**Comment by SonicDMG** [comment]
Looks great Jessica, thank you. Here's your badge -> https://api.badgr.io/public/assertions/fhJEW16TS2SqMYsETZCBBA?identity__email=nyon.jessica%40gmail.com
