### ISSUE TITLE
[HW] Adam Siemaszkiewicz

### ISSUE THREAD

**Issue by adamsiemaszkiewicz** [datastaxdevs/workshop-introduction-to-nosql#87]
**Name:** Adam Siemaszkiewicz
**Email:** siemaszkiewiczadam@gmail.com and/or adamsiemaszkiewicz@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/adamsiemaszkiewicz/

Attach the homework screenshots below:
-----------------------------------------

![Zrzut ekranu 2021-06-02 200728](https://user-images.githubusercontent.com/39764360/120532750-4dc85f80-c3e0-11eb-9880-2e3e2c85ba30.jpg)
![Zrzut ekranu 2021-06-02 200753](https://user-images.githubusercontent.com/39764360/120532756-4ef98c80-c3e0-11eb-8525-7758dcd50d06.jpg)
![Zrzut ekranu 2021-06-02 201551](https://user-images.githubusercontent.com/39764360/120532757-4ef98c80-c3e0-11eb-8524-1ba75f5bfc48.jpg)
![Zrzut ekranu 2021-06-02 201800](https://user-images.githubusercontent.com/39764360/120532759-4f922300-c3e0-11eb-8a92-e05ae431a641.jpg)
![Zrzut ekranu 2021-06-02 202155](https://user-images.githubusercontent.com/39764360/120532761-4f922300-c3e0-11eb-9685-4c1cab2322af.jpg)

**Comment by SonicDMG** [comment]
Awesome job Adam, thank you. Here's your badge -> https://api.badgr.io/public/assertions/tq-of9RtTsqF9hgBnZGgRw?identity__email=siemaszkiewiczadam%40gmail.com. 

BTW, I noticed you submitted your quiz win here. Did you also send an email to Jack?

**Comment by adamsiemaszkiewicz** [comment]
Hi David,

Thank you for the link. Is there a particular way how I add it to my
LinkedIn profile or just use the data shown and the code from the link?

As for the quiz - I didn't send it anywhere else. Should I? If so where
exactly to?

Thanks
Adam

**Comment by SonicDMG** [comment]
Oh yea, for your quiz send it to jack.fryer@datastax.com. For LinkedIn, you can add it directly to your profiles "Featured" section per the badge URL. Let me know how that goes.
