### ISSUE TITLE
[HW] Introduction to NoSQL Databases

### ISSUE THREAD

**Issue by nfelicio1976** [datastaxdevs/workshop-introduction-to-nosql#88]
**Name:** Nuno Felicio
**Email:** nfelicio@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nuno-felicio-a8b4356/

Attach the homework screenshots below:
-----------------------------------------
![Screenshot 2021-06-02 18 45 12](https://user-images.githubusercontent.com/72761634/120533008-31c0c000-c3d8-11eb-9a67-19f0f0ebe053.png)
-- images removed by team --
![Screenshot 2021-06-02 18 48 13](https://user-images.githubusercontent.com/72761634/120533018-338a8380-c3d8-11eb-8751-d4aba8b8ec03.png)
-- images removed by team --
![Screenshot 2021-06-02 18 49 20](https://user-images.githubusercontent.com/72761634/120533021-34231a00-c3d8-11eb-9930-8082279fbb7e.png)

<SCREENSHOTS>

Try It Out: Cassandra Query Language (CQL):

![Screenshot 2021-06-02 19 23 02](https://user-images.githubusercontent.com/72761634/120533111-4e5cf800-c3d8-11eb-9d4a-bc0a4fc2b104.png)
![Screenshot 2021-06-02 19 23 18](https://user-images.githubusercontent.com/72761634/120533114-4ef58e80-c3d8-11eb-8135-032b818e1baa.png)

**Comment by SonicDMG** [comment]
This looks really good Nuno, thank you. Here's your badge -> https://api.badgr.io/public/assertions/J_2_-2-WQYqNeNT9rLDsHg?identity__email=nfelicio%40gmail.com. I've removed some of your screenshots because they included your Astra key.

**Comment by nfelicio1976** [comment]
Thank you

Cumprimentos,
Nuno Felício.


David Jones-Gilardi ***@***.***> escreveu no dia quinta,
3/06/2021 à(s) 15:30:
