### ISSUE TITLE
NoSQL COding - Gowtham

### ISSUE THREAD

**Issue by gowtham0710** [datastaxdevs/workshop-introduction-to-nosql#89]
**Name:** Gowtham Babu M R
**Email:** mrgowtham93@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![image](https://user-images.githubusercontent.com/85252553/120533544-75c6bb80-c3fe-11eb-8748-e69b152c36c3.png)

![image](https://user-images.githubusercontent.com/85252553/120533619-8c6d1280-c3fe-11eb-864e-9585ba24333c.png)

**Comment by gowtham0710** [comment]
![image](https://user-images.githubusercontent.com/85252553/120534067-0a311e00-c3ff-11eb-83d5-5f095e3738f9.png)

**Comment by SonicDMG** [comment]
Looks great Gowtham, nice job. Here's your badge -> https://api.badgr.io/public/assertions/Miy6HJCOTtu6n52Oc3ylew?identity__email=mrgowtham93%40gmail.com
