### ISSUE TITLE
[HW] Arvind

### ISSUE THREAD

**Issue by arvindvijayarooban** [datastaxdevs/workshop-introduction-to-nosql#9]
**Name:** Arvind 
**Email:** arvindvijayarooban@gmail.com
**Linkedin Profile:** https://my.linkedin.com/in/arvindvijayarooban

Attach the homework screenshots below:
-----------------------------------------

Unable to do step 5,  providing completion till step 4

![try-it-out-screenshot](https://user-images.githubusercontent.com/34472833/117190638-45e1c380-ae12-11eb-8fdc-9b943c41451c.PNG)
![step4-graphql-final](https://user-images.githubusercontent.com/34472833/117190642-4712f080-ae12-11eb-9779-bf36939fd886.PNG)
![step4-final](https://user-images.githubusercontent.com/34472833/117190644-47ab8700-ae12-11eb-94e7-ceb2b42ea3de.PNG)

**Comment by SonicDMG** [comment]
Looks good Arvind, thank you.

**Comment by HadesArchitect** [comment]
https://api.badgr.io/public/assertions/i3CfckDVTAK7v3NFuo1XKQ?identity__email=arvindvijayarooban%40gmail.com
