### ISSUE TITLE
[HW] <introduction to nosql database>

### ISSUE THREAD

**Issue by vikas613** [datastaxdevs/workshop-introduction-to-nosql#92]
**Name:** vikas anand
**Email:** <va65656565@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/vikas-anand-93380620b
-- image remove by team --
![2](https://user-images.githubusercontent.com/84899454/120534915-02be4480-c400-11eb-9fd1-b6bfac28a767.jpg)
![3](https://user-images.githubusercontent.com/84899454/120534921-03ef7180-c400-11eb-9134-56498b9467e4.jpg)
![6](https://user-images.githubusercontent.com/84899454/120534930-05b93500-c400-11eb-9389-1ac8c54e934e.jpg)

>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Awesome Vikas, looks good. Here's your badge -> https://api.badgr.io/public/assertions/lpYd5N5ASEyM_mAVAaAKyA?identity__email=va65656565%40gmail.com. I removed one of your screenshots because it included your Astra key.
