### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by NicolasContrerasGit** [datastaxdevs/workshop-introduction-to-nosql#93]
**Name:** Nicolas Contreras Aso
**Email:** nikolasin.00@gmail.com
**Linkedin Profile:** [https://www.linkedin.com/in/nicolas-contreras-aso/](url Linkedin)

Attach the homework screenshots below:
-----------------------------------------

**Aditional homework**

![create a new empty collection](https://user-images.githubusercontent.com/84481529/120535161-f2e43780-c3e2-11eb-9d6a-9cb937bb794b.png)

![Search document](https://user-images.githubusercontent.com/84481529/120535126-ec55c000-c3e2-11eb-9d83-29e3feaf94ef.png)

![create a new empty collection](https://user-images.githubusercontent.com/84481529/120535134-ecee5680-c3e2-11eb-98d2-e2b1a49b2308.png)

![Get a document](https://user-images.githubusercontent.com/84481529/120535203-fecff980-c3e2-11eb-9728-133ec31afcc1.png)

**Datastax:**

![datastax](https://user-images.githubusercontent.com/84481529/120534862-9da82600-c3e2-11eb-80cc-1a5372fef205.png)

**Last section IV:** 

![Last-Section4](https://user-images.githubusercontent.com/84481529/120534980-bd3f4e80-c3e2-11eb-8578-eae7ad884d1f.png)

**Comment by SonicDMG** [comment]
Awesome job Nicolas, thank you. Here's your badge -> https://api.badgr.io/public/assertions/gS7eGiVwTBWIcz2vkGVNsQ?identity__email=nikolasin.00%40gmail.com
