### ISSUE TITLE
[HW] Neelanjan Ghatak

### ISSUE THREAD

**Issue by Neelanjan1** [datastaxdevs/workshop-introduction-to-nosql#94]
**Name:** Neelanjan Ghatak
**Email:** ngjoy71@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/neelanjanghatak

Attach the homework screenshots below:
-----------------------------------------

<img width="201" alt="Step 1 - Exercise 4" src="https://user-images.githubusercontent.com/42545864/120535924-2c2ba000-c401-11eb-8f86-47fb103a8f5b.png">
<img width="602" alt="step 2 Try-it-out" src="https://user-images.githubusercontent.com/42545864/120536273-8e84a080-c401-11eb-8435-37a41db73e05.png">

**Comment by SonicDMG** [comment]
Nice job Neelanjan, thank you. Here's your badge -> https://api.badgr.io/public/assertions/qh03Xhs0Shq-OE5jwxvHPw?identity__email=ngjoy71%40gmail.com
