### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by vikasraiexp** [datastaxdevs/workshop-introduction-to-nosql#96]
**Name:*Vikas Kumar Rai* 
**Email:** <ccm@abbzorb.com>
**Linkedin Profile:** <https://www.linkedin.com/in/vikasraiexp/>

<![Uploading screen4.png…](
-- images removed by team --
![screen4](https://user-images.githubusercontent.com/85254718/120540203-081e8d80-c406-11eb-9c1b-982e27f0478d.png)

>

Attach the homework screenshots below:
-----------------------------------------

-- images removed by team --

**Comment by SonicDMG** [comment]
I also removed some images that included your Astra key. You should delete your current key from the Astra UI to be safe.

**Comment by vikasraiexp** [comment]
`Connected as ccm@abbzorb.com.
Connected to cndb at cassandra.ingress:9042.
[cqlsh 6.8.0 | DSE DB 4.0.0.6813 | CQL spec 3.4.5 | Native protocol v4]
Use HELP for help.
token@cqlsh> describe keyspaces;

system_virtual_schema  system_auth   system        data_endpoint_auth  nosql1
system_schema          system_views  datastax_sla  system_traces     

token@cqlsh> use nosql1;
token@cqlsh:nosql1> CREATE TABLE IF NOT EXISTS videos (
          ...  videoid   uuid,
          ...  email     text,
          ...  title     text,
          ...  upload    timestamp,
          ...  url       text,
          ...  tags      set <text>,
          ...  frames    list<int>,
          ...  PRIMARY KEY (videoid)
          ... );
token@cqlsh:nosql1> describe keyspace nosql1;

CREATE KEYSPACE nosql1 WITH replication = {'class': 'NetworkTopologyStrategy', 'westus2': '3'}  AND durable_writes = true;

CREATE TABLE nosql1.key_value (
    key text PRIMARY KEY,
    value text
) WITH additional_write_policy = '99PERCENTILE'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.UnifiedCompactionStrategy', 'log_all': 'true', 'num_shards': '128'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99PERCENTILE';

CREATE TABLE nosql1.users_by_city (
    city text,
    lastname text,
    email text,
    firstname text,
    PRIMARY KEY (city, lastname, email)
) WITH CLUSTERING ORDER BY (lastname ASC, email ASC)
    AND additional_write_policy = '99PERCENTILE'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.UnifiedCompactionStrategy', 'log_all': 'true', 'num_shards': '128'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99PERCENTILE';

CREATE TABLE nosql1.videos (
    videoid uuid PRIMARY KEY,
    email text,
    frames list<int>,
    tags set<text>,
    title text,
    upload timestamp,
    url text
) WITH additional_write_policy = '99PERCENTILE'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.UnifiedCompactionStrategy', 'log_all': 'true', 'num_shards': '128'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99PERCENTILE';

CREATE TABLE nosql1.col1 (
    key text,
    p0 text,
    p1 text,
    p2 text,
    p3 text,
    p4 text,
    p5 text,
    p6 text,
    p7 text,
    p8 text,
    p9 text,
    p10 text,
    p11 text,
    p12 text,
    p13 text,
    p14 text,
    p15 text,
    p16 text,
    p17 text,
    p18 text,
    p19 text,
    p20 text,
    p21 text,
    p22 text,
    p23 text,
    p24 text,
    p25 text,
    p26 text,
    p27 text,
    p28 text,
    p29 text,
    p30 text,
    p31 text,
    p32 text,
    p33 text,
    p34 text,
    p35 text,
    p36 text,
    p37 text,
    p38 text,
    p39 text,
    p40 text,
    p41 text,
    p42 text,
    p43 text,
    p44 text,
    bool_value tinyint,
    dbl_value double,
    leaf text,
    text_value text,
    PRIMARY KEY (key, p0, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21, p22, p23, p24, p25, p26, p27, p28, p29, p30, p31, p32, p33, p34, p35, p36, p37, p38, p39, p40, p41, p42, p43, p44)
) WITH CLUSTERING ORDER BY (p0 ASC, p1 ASC, p2 ASC, p3 ASC, p4 ASC, p5 ASC, p6 ASC, p7 ASC, p8 ASC, p9 ASC, p10 ASC, p11 ASC, p12 ASC, p13 ASC, p14 ASC, p15 ASC, p16 ASC, p17 ASC, p18 ASC, p19 ASC, p20 ASC, p21 ASC, p22 ASC, p23 ASC, p24 ASC, p25 ASC, p26 ASC, p27 ASC, p28 ASC, p29 ASC, p30 ASC, p31 ASC, p32 ASC, p33 ASC, p34 ASC, p35 ASC, p36 ASC, p37 ASC, p38 ASC, p39 ASC, p40 ASC, p41 ASC, p42 ASC, p43 ASC, p44 ASC)
    AND additional_write_policy = '99PERCENTILE'
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.UnifiedCompactionStrategy', 'log_all': 'true', 'num_shards': '128'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair = 'BLOCKING'
    AND speculative_retry = '99PERCENTILE';
CREATE CUSTOM INDEX col1_leaf_idx ON nosql1.col1 (leaf) USING 'StorageAttachedIndex';
CREATE CUSTOM INDEX col1_text_value_idx ON nosql1.col1 (text_value) USING 'StorageAttachedIndex';
CREATE CUSTOM INDEX col1_bool_value_idx ON nosql1.col1 (bool_value) USING 'StorageAttachedIndex';
CREATE CUSTOM INDEX col1_dbl_value_idx ON nosql1.col1 (dbl_value) USING 'StorageAttachedIndex';

token@cqlsh:nosql1> INSERT INTO videos(videoid, email, title, upload, url, tags, frames)          ... VALUES(uuid(), 
          ...      'clu@sample.com', 
          ...      'Introduction to Nosql Databases', 
          ...      toTimeStamp(now()), 
          ...      'https://www.youtube.com/watch?v=cMDHxsGbmC8',
          ...      { 'nosql','workshop','2021'}, 
          ...      [ 1, 2, 3, 4]);
token@cqlsh:nosql1>      
token@cqlsh:nosql1> INSERT INTO videos(videoid, email, title, upload, url)
          ... VALUES(uuid(), 
          ...       'clu@sample.com', 
          ...       'Demo video Y', 
          ...       toTimeStamp(now()), 
          ...       'https://www.youtube.com/watch?v=XXXX');
token@cqlsh:nosql1> 
token@cqlsh:nosql1> INSERT INTO videos(videoid, email, title, upload, url)
          ... VALUES(e466f561-4ea4-4eb7-8dcc-126e0fbfd573, 
          ...       'clu@sample.com', 
          ...       'Yet another video', 
          ...       toTimeStamp(now()), 
          ...       'https://www.youtube.com/watch?v=ABCDE');
token@cqlsh:nosql1> select * from videos;

 videoid                              | email              | frames       | tags                                | title                           | upload                          | url
--------------------------------------+--------------------+--------------+-------------------------------------+---------------------------------+---------------------------------+---------------------------------------------
 aef24087-6610-4464-8ecc-1bcd905590a0 |     clu@sample.com |         null |                                null |                    Demo video Y | 2021-06-02 17:00:54.639000+0000 |        https://www.youtube.com/watch?v=XXXX
 4bd9a8a5-e55d-4f3e-8241-a809cfeaae1c |     clu@sample.com |         null |                                null |                    Demo video Y | 2021-06-08 03:19:03.232000+0000 |        https://www.youtube.com/watch?v=XXXX
 20c5968a-2fec-414d-8887-9a3749cb79b0 |     clu@sample.com | [1, 2, 3, 4] |       {'2021', 'nosql', 'workshop'} | Introduction to Nosql Databases | 2021-06-02 17:01:02.889000+0000 | https://www.youtube.com/watch?v=cMDHxsGbmC8
 e466f561-4ea4-4eb7-8dcc-126e0fbfd578 | clunven@sample.com | [1, 2, 3, 4] | {'2020', 'accelerate', 'cassandra'} |                   A JSON videos | 2020-02-26 15:09:22.000000+0000 |                            http://google.fr
 e466f561-4ea4-4eb7-8dcc-126e0fbfd573 |     clu@sample.com |         null |                                null |               Yet another video | 2021-06-08 03:19:08.596000+0000 |       https://www.youtube.com/watch?v=ABCDE
 c07f43e5-1e57-4efc-9ccf-2cb97e64a347 |     clu@sample.com |         null |                                null |                    Demo video Y | 2021-06-02 17:01:02.894000+0000 |        https://www.youtube.com/watch?v=XXXX
 938e22e2-f786-42a6-8cb8-ac73bc6ccbe3 |     clu@sample.com |         null |                                null |                    Demo video Y | 2021-06-02 17:00:42.492000+0000 |        https://www.youtube.com/watch?v=XXXX
 69baab01-d506-44c3-9203-2adf75ee8c9f |     clu@sample.com | [1, 2, 3, 4] |       {'2021', 'nosql', 'workshop'} | Introduction to Nosql Databases | 2021-06-02 17:00:42.481000+0000 | https://www.youtube.com/watch?v=cMDHxsGbmC8
 b675e0a5-90eb-4a49-819c-f82f8d3dcb26 |     clu@sample.com | [1, 2, 3, 4] |       {'2021', 'nosql', 'workshop'} | Introduction to Nosql Databases | 2021-06-08 03:19:03.218000+0000 | https://www.youtube.com/watch?v=cMDHxsGbmC8
 20116a39-6597-47b8-9289-610f13a1dae8 |     clu@sample.com | [1, 2, 3, 4] |       {'2021', 'nosql', 'workshop'} | Introduction to Nosql Databases | 2021-06-02 17:00:54.634000+0000 | https://www.youtube.com/watch?v=cMDHxsGbmC8

(10 rows)
token@cqlsh:nosql1> select * from videos 
          ... where videoid=e466f561-4ea4-4eb7-8dcc-126e0fbfd573;

 videoid                              | email          | frames | tags | title             | upload                          | url
--------------------------------------+----------------+--------+------+-------------------+---------------------------------+---------------------------------------
 e466f561-4ea4-4eb7-8dcc-126e0fbfd573 | clu@sample.com |   null | null | Yet another video | 2021-06-08 03:19:08.596000+0000 | https://www.youtube.com/watch?v=ABCDE

(1 rows)
token@cqlsh:nosql1> CREATE TABLE IF NOT EXISTS users_by_city (
          ...  city      text,
          ...  firstname text,
          ...  lastname  text,
          ...  email     text,
          ...  PRIMARY KEY ((city), lastname, email)
          ... ) WITH CLUSTERING ORDER BY(lastname ASC, email ASC);
token@cqlsh:nosql1> 
token@cqlsh:nosql1> INSERT INTO users_by_city(city, firstname, lastname, email) 
          ... VALUES('PARIS', 'Lunven', 'Cedrick', 'clu@sample.com');
token@cqlsh:nosql1> 
token@cqlsh:nosql1> INSERT INTO users_by_city(city, firstname, lastname, email) 
          ... VALUES('PARIS', 'Yellow', 'Jackets', 'yj@sample.com');
token@cqlsh:nosql1> 
token@cqlsh:nosql1> INSERT INTO users_by_city(city, firstname, lastname, email) 
          ... VALUES('ORLANDO', 'David', 'Gilardi', 'dgi@sample.com');
token@cqlsh:nosql1> SELECT * from users_by_city WHERE city='PARIS';

 city  | lastname | email          | firstname
-------+----------+----------------+-----------
 PARIS |  Cedrick | clu@sample.com |    Lunven
 PARIS |  Jackets |  yj@sample.com |    Yellow

(2 rows)
token@cqlsh:nosql1> SELECT * from users_by_city WHERE lastname='Gilardi';
InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING"
token@cqlsh:nosql1> tracing on;
Now Tracing is enabled
token@cqlsh:nosql1> SELECT * from users_by_city WHERE city='PARIS';

 city  | lastname | email          | firstname
-------+----------+----------------+-----------
 PARIS |  Cedrick | clu@sample.com |    Lunven
 PARIS |  Jackets |  yj@sample.com |    Yellow

(2 rows)

Tracing session: 96613a60-c808-11eb-a9ec-ddf5b6c70419

 activity                                                                                                                | timestamp                  | source       | source_elapsed | client
-------------------------------------------------------------------------------------------------------------------------+----------------------------+--------------+----------------+----------------------------------------
                                                                                                      Execute CQL3 query | 2021-06-08 03:21:17.320000 |   172.23.5.7 |              0 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                  Parsing SELECT * from users_by_city WHERE city='PARIS'; [CoreThread-4] | 2021-06-08 03:21:17.321000 |   172.23.5.7 |           1496 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                                      Preparing statement [CoreThread-4] | 2021-06-08 03:21:17.322000 |   172.23.5.7 |           2623 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                        Reading data from [/172.23.3.149] [CoreThread-4] | 2021-06-08 03:21:17.322000 |   172.23.5.7 |           3207 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                     Reading digests from [/172.23.0.222] [CoreThread-4] | 2021-06-08 03:21:17.322000 |   172.23.5.7 |           3546 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                       Sending READS.SINGLE_READ message to /172.23.3.149, size=173 bytes [CoreThread-5] | 2021-06-08 03:21:17.322001 |   172.23.5.7 |           3546 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                       Sending READS.SINGLE_READ message to /172.23.0.222, size=174 bytes [CoreThread-1] | 2021-06-08 03:21:17.324000 |   172.23.5.7 |           3895 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                      READS.SINGLE_READ message received from /172.23.5.7 [CoreThread-5] | 2021-06-08 03:21:17.324000 | 172.23.0.222 |             58 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                Skipped 0/3 non-slice-intersecting sstables, included 0 due to tombstones [CoreThread-5] | 2021-06-08 03:21:17.324000 | 172.23.0.222 |            290 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
 Merged data from memtables and 3 sstables during single-partition query on users_by_city for key 'PARIS' [CoreThread-5] | 2021-06-08 03:21:17.324000 | 172.23.0.222 |            641 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                      READS.SINGLE_READ message received from /172.23.5.7 [CoreThread-3] | 2021-06-08 03:21:17.325000 | 172.23.3.149 |             57 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                    Read 2 live rows and 0 tombstone ones [CoreThread-5] | 2021-06-08 03:21:17.325000 | 172.23.0.222 |            699 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                Skipped 0/3 non-slice-intersecting sstables, included 0 due to tombstones [CoreThread-3] | 2021-06-08 03:21:17.325000 | 172.23.3.149 |            365 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                    Enqueuing READS.SINGLE_READ response to /172.23.0.222 [CoreThread-5] | 2021-06-08 03:21:17.325000 | 172.23.0.222 |            757 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                         Sending READS.SINGLE_READ message to /172.23.5.7, size=128 bytes [CoreThread-3] | 2021-06-08 03:21:17.325000 | 172.23.0.222 |            885 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                    READS.SINGLE_READ message received from /172.23.0.222 [CoreThread-0] | 2021-06-08 03:21:17.326000 |   172.23.5.7 |           7139 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                   Processing response from /172.23.0.222 [CoreThread-4] | 2021-06-08 03:21:17.329000 |   172.23.5.7 |           8801 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                    READS.SINGLE_READ message received from /172.23.3.149 [CoreThread-6] | 2021-06-08 03:21:17.350000 |   172.23.5.7 |          31055 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                   Processing response from /172.23.3.149 [CoreThread-4] | 2021-06-08 03:21:17.350000 |   172.23.5.7 |          31205 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
 Merged data from memtables and 3 sstables during single-partition query on users_by_city for key 'PARIS' [CoreThread-3] | 2021-06-08 03:21:17.351000 | 172.23.3.149 |          26252 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                    Read 2 live rows and 0 tombstone ones [CoreThread-3] | 2021-06-08 03:21:17.351000 | 172.23.3.149 |          26314 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                    Enqueuing READS.SINGLE_READ response to /172.23.3.149 [CoreThread-3] | 2021-06-08 03:21:17.351000 | 172.23.3.149 |          26377 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                         Sending READS.SINGLE_READ message to /172.23.5.7, size=211 bytes [CoreThread-2] | 2021-06-08 03:21:17.351000 | 172.23.3.149 |          26506 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                                                        Request complete | 2021-06-08 03:21:17.352460 |   172.23.5.7 |          32460 | 6025:705:d0f7:43ae:945a:984d:142d:80b1


token@cqlsh:nosql1> SELECT * from users_by_city WHERE lastname='Gilardi' ALLOW FILTERING;

 city    | lastname | email          | firstname
---------+----------+----------------+-----------
 ORLANDO |  Gilardi | dgi@sample.com |     David

(1 rows)

Tracing session: 9dbaf120-c808-11eb-a9ec-ddf5b6c70419

 activity                                                                                                                    | timestamp                  | source       | source_elapsed | client
-----------------------------------------------------------------------------------------------------------------------------+----------------------------+--------------+----------------+----------------------------------------
                                                                                                          Execute CQL3 query | 2021-06-08 03:21:29.650000 |   172.23.5.7 |              0 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                Parsing SELECT * from users_by_city WHERE lastname='Gilardi' ALLOW FILTERING; [CoreThread-4] | 2021-06-08 03:21:29.651000 |   172.23.5.7 |            362 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                                          Preparing statement [CoreThread-4] | 2021-06-08 03:21:29.651000 |   172.23.5.7 |            537 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                                 Computing ranges to query... [CoreThread-4] | 2021-06-08 03:21:29.651000 |   172.23.5.7 |            927 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                 Submitting range requests on 25 ranges with a concurrency of 1 (0.0 rows per range expected) [CoreThread-4] | 2021-06-08 03:21:29.651000 |   172.23.5.7 |           1043 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                        Submitted 1 concurrent range requests [CoreThread-4] | 2021-06-08 03:21:29.652000 |   172.23.5.7 |           1278 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                           READS.RANGE_READ message received from /172.23.5.7 [CoreThread-5] | 2021-06-08 03:21:29.652000 | 172.23.0.222 |             59 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                            Sending READS.RANGE_READ message to /172.23.0.222, size=213 bytes [CoreThread-1] | 2021-06-08 03:21:29.652000 |   172.23.5.7 |           1354 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
              Executing seq scan across 3 sstables for (min(-9223372036854775808), min(-9223372036854775808)] [CoreThread-5] | 2021-06-08 03:21:29.652000 | 172.23.0.222 |            370 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                            Sending READS.RANGE_READ message to /172.23.3.222, size=213 bytes [CoreThread-3] | 2021-06-08 03:21:29.652000 |   172.23.5.7 |           1417 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                         READS.RANGE_READ message received from /172.23.0.222 [CoreThread-0] | 2021-06-08 03:21:29.653000 |   172.23.5.7 |           3258 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                           READS.RANGE_READ message received from /172.23.5.7 [CoreThread-5] | 2021-06-08 03:21:29.653000 | 172.23.3.222 |             93 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                        Read 1 live rows and 0 tombstone ones [CoreThread-5] | 2021-06-08 03:21:29.653000 | 172.23.0.222 |           1203 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
              Executing seq scan across 3 sstables for (min(-9223372036854775808), min(-9223372036854775808)] [CoreThread-5] | 2021-06-08 03:21:29.653000 | 172.23.3.222 |            648 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                         Enqueuing READS.RANGE_READ response to /172.23.0.222 [CoreThread-5] | 2021-06-08 03:21:29.653000 | 172.23.0.222 |           1203 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                              Sending READS.RANGE_READ message to /172.23.5.7, size=193 bytes [CoreThread-3] | 2021-06-08 03:21:29.653000 | 172.23.0.222 |           1281 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                       Processing response from /172.23.0.222 [CoreThread-4] | 2021-06-08 03:21:29.654000 |   172.23.5.7 |           3410 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                        Read 1 live rows and 0 tombstone ones [CoreThread-5] | 2021-06-08 03:21:29.654000 | 172.23.3.222 |           1549 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                         READS.RANGE_READ message received from /172.23.3.222 [CoreThread-3] | 2021-06-08 03:21:29.654000 |   172.23.5.7 |           4083 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                         Enqueuing READS.RANGE_READ response to /172.23.3.222 [CoreThread-5] | 2021-06-08 03:21:29.654000 | 172.23.3.222 |           1620 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                       Processing response from /172.23.3.222 [CoreThread-4] | 2021-06-08 03:21:29.654000 |   172.23.5.7 |           4162 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                              Sending READS.RANGE_READ message to /172.23.5.7, size=193 bytes [CoreThread-5] | 2021-06-08 03:21:29.654000 | 172.23.3.222 |           1745 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
 Didn't get enough response rows; actual rows per range: 0.04; remaining rows: 99, new concurrent requests: 1 [CoreThread-4] | 2021-06-08 03:21:29.655000 |   172.23.5.7 |           4937 | 6025:705:d0f7:43ae:945a:984d:142d:80b1
                                                                                                            Request complete | 2021-06-08 03:21:29.655176 |   172.23.5.7 |           5176 | 6025:705:d0f7:43ae:945a:984d:142d:80b1


token@cqlsh:nosql1> tracing off;
Disabled Tracing.
token@cqlsh:nosql1> `

**Comment by vikasraiexp** [comment]
Hi Team,
Awaiting your revert

**Comment by vikasraiexp** [comment]
PLease let me know How i can download the certificate

**Comment by SonicDMG** [comment]
Hey there Vikas. Unfortunately what you attached was not the completed screen from the scenario. Let me know if you are still interested in getting a badge and I'll keep this open.
