### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by nithinkumar1993** [datastaxdevs/workshop-introduction-to-nosql#97]
**Name:** Nithin Kumar Nukala
**Email:** nithin.sunny007@gmail.com
**Linkedin Profile:** http://www.linkedin.com/in/nithin-kumar-nukala 

Attach the homework screenshots below:
-----------------------------------------
![Capture](https://user-images.githubusercontent.com/10800342/120548651-7f462880-c3ea-11eb-9992-155ac5b22151.PNG)
![Scenario](https://user-images.githubusercontent.com/10800342/120548655-80775580-c3ea-11eb-971e-62bc11d4dd4b.PNG)

**Comment by SonicDMG** [comment]
Nice job getting through step V Nithin, looks great. Here's your badge -> https://api.badgr.io/public/assertions/CO8ezlqyQ7SES3kmD97KqQ?identity__email=nithin.sunny007%40gmail.com
