### ISSUE TITLE
[HW] Dhruv Patel

### ISSUE THREAD

**Issue by dhruvp1997** [datastaxdevs/workshop-introduction-to-nosql#98]
**Name:** Dhruv Patel
**Email:** dhruvp1997@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/dhruvp1997/

Attach the homework screenshots below:
-----------------------------------------

![bandicam 2021-06-02 17-30-12-049](https://user-images.githubusercontent.com/30743023/120554975-688eda00-c3c8-11eb-92b5-5a385cc1c349.jpg)
![bandicam 2021-06-02 13-44-40-494](https://user-images.githubusercontent.com/30743023/120554976-69277080-c3c8-11eb-99e2-f61a11e09b51.jpg)
![bandicam 2021-06-02 13-45-44-779](https://user-images.githubusercontent.com/30743023/120554977-69277080-c3c8-11eb-9577-58887ea50b99.jpg)
![bandicam 2021-06-02 13-46-54-864](https://user-images.githubusercontent.com/30743023/120554979-69277080-c3c8-11eb-9d6d-3dcc0969c82c.jpg)
![bandicam 2021-06-02 13-50-10-269](https://user-images.githubusercontent.com/30743023/120554982-69c00700-c3c8-11eb-97c9-2d561fcbedda.jpg)
![bandicam 2021-06-02 13-55-30-922](https://user-images.githubusercontent.com/30743023/120554983-69c00700-c3c8-11eb-8d56-4c3e7ead6d8b.jpg)
![bandicam 2021-06-02 13-55-50-577](https://user-images.githubusercontent.com/30743023/120554986-69c00700-c3c8-11eb-9d64-c7af15e4792b.jpg)
![bandicam 2021-06-02 17-20-39-005](https://user-images.githubusercontent.com/30743023/120554988-69c00700-c3c8-11eb-863d-021ac17bf32e.jpg)
![bandicam 2021-06-02 17-21-52-672](https://user-images.githubusercontent.com/30743023/120554990-6a589d80-c3c8-11eb-9849-5d64aef04b71.jpg)

**Comment by SonicDMG** [comment]
Really nice job getting through everything including step V Dhruv, awesome. Here's your badge -> https://api.badgr.io/public/assertions/0gg2Xz5LSzqZSiLlyxDz2A?identity__email=dhruvp1997%40gmail.com
