### ISSUE TITLE
[HW] <sha>

### ISSUE THREAD

**Issue by usharajam** [datastaxdevs/workshop-introduction-to-nosql#99]
<img width="1440" alt="Screen Shot 2021-06-02 at 5 36 43 PM" src="https://user-images.githubusercontent.com/7246032/120555802-99234380-c3c9-11eb-9234-d98faef15e13.png">
<img width="1440" alt="Screen Shot 2021-06-02 at 5 27 56 PM" src="https://user-images.githubusercontent.com/7246032/120555824-a0e2e800-c3c9-11eb-8296-5961789499e5.png">
-- image removed by team --

**Ayyammal Govindaraj** <NAME>
**sharmithewriter@gmail.com** <email>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks great Ayyammal, thank you. I removed one of your images because it included your Astra token. I would suggest you delete this token from your Astra UI to be safe.

**Comment by SonicDMG** [comment]
Here's your badge -> https://api.badgr.io/public/assertions/mpfYfIieSbmyU4Bc4evEyg?identity__email=sharmithewriter%40gmail.com
